### ISSUE TITLE
No shema found for Eufy RoboVac

### ISSUE THREAD

**Issue by azanke** [Apollon77/ioBroker.tuya#107]
Hi Apollon77,

I connected my vacuum (Eufy RoboVac) successfully with your adapter. But it does not response to any state change... I run the adapter in debug mode and found that now shema was found.
Could you implement the shema to the adapter or explain how to do so....

I have a list with all states and the log which I took from ioBroker:

Key/Values for status / commands:

    1 = unknown, bool
    2 = play/pause, bool
    3 = direction, string, one of:
        left
        right
        forward
        backward
    5 = work mode, one of:
        Nosweep
        auto
        SmallRoom
        Edge
        Spot
    15 = work status, string, one of:
        Charging
        standby
        Sleeping
        Recharge
    101 = go home, bool, true = going home
    102 = clean speed, string, one of:
        No_suction
        Standard
        Boost_IQ
        Max
    103 = find robot status, bool, true = on
    104 = battery level, int 0-100
    106 = error code, string, one of:
        no_error
        Wheel_stuck
        R_brush_stuck
        Crash_bar_stuck
        sensor_dirty
        N_enough_pow
        Stuck_5_min
        Fan_stuck
        S_brush_stuck

tuya.0 | 2020-01-17 02:29:33.877 | debug | (15133) connected set to true
-- | -- | -- | --
tuya.0 | 2020-01-17 02:29:33.867 | info | (15133) 73531780807d3a570afb: No schema exists, init basic states ...
tuya.0 | 2020-01-17 02:29:33.866 | debug | (15133) 73531780807d3a570afb: Received data:  {"1":true,"2":false,"3":"forward","5":"Nosweep","15":"completed","101":false,"102":"No_suction","103":false,"104":100,"106":"no_error"}
tuya.0 | 2020-01-17 02:29:33.841 | debug | (15133) 73531780807d3a570afb: Connected to device
tuya.0 | 2020-01-17 02:29:33.810 | info | (15133) Listen for encrypted local Tuya devices on port 6667
tuya.0 | 2020-01-17 02:29:33.809 | info | (15133) Listen for local Tuya devices on port 6666
tuya.0 | 2020-01-17 02:29:33.796 | info | (15133) Existing devices initialized
tuya.0 | 2020-01-17 02:29:33.790 | info | (15133) 73531780807d3a570afb Init with IP=192.168.178.21, Key=1cbe9a4359433bba, Version=3.1
tuya.0 | 2020-01-17 02:29:33.688 | debug | (15133) 73531780807d3a570afb: Create device objects if not exist
tuya.0 | 2020-01-17 02:29:33.685 | debug | (15133) 73531780807d3a570afb: Schema found for Yhtig6DeVgGXKt2W: null
tuya.0 | 2020-01-17 02:29:33.681 | debug | (15133) init 1 known devices
tuya.0 | 2020-01-17 02:29:33.675 | debug | (15133) connected set to false
tuya.0 | 2020-01-17 02:29:33.525 | info | (15133) starting. Version 3.1.16 in /opt/iobroker/node_modules/iobroker.tuya, node: v10.18.1

Thank you so much....

Cheers

André

**Comment by Apollon77** [comment]
You need to do the Proxy Sync with the tuya app (only older versions like 3.12.x work, 3.14+ DO NOT work anymore att the moment!) ... then the schema ist retrieved from the app ...
