### ISSUE TITLE
New Version Firmware not found

### ISSUE THREAD

**Issue by maestroat** [Apollon77/ioBroker.tuya#114]
Hello, i have 8x
https://www.amazon.de/gp/product/B07B911Y6V/ref=ppx_yo_dt_b_asin_title_o07_s00?ie=UTF8&psc=1
Gosund W-Lan 
in Smart life App all works, 
on iobroker and tuya i found only 4
the vor have wi-fi modul 1.0.5
mcu-modul; 1.0.5
check update - newest version is 
the 4 moduls i not found
have
WIFI und MCU Modul version 1.0.6, here also say newest version is installed.

**Comment by Apollon77** [comment]
Did you done the proxy sync? The 1.06 firmware devices are encrypted devices which are only discoverable after the proxy sync
