### ISSUE TITLE
Correct State

### ISSUE THREAD

**Issue by maestroat** [Apollon77/ioBroker.tuya#115]
hi,
![image](https://user-images.githubusercontent.com/50575712/73657776-4893bd00-4693-11ea-97b6-e8d2d574f096.png)
you se 19 -   24, thats not correct, thats 2,4 watt in real on in smart life app. can you pls change it that i see correcty watt in tuya iobroker!

**Comment by Apollon77** [comment]
Please sync using the proxy. Without the schema fetched by this sync the adapter do not know anything about unis and "exponents used" and can only show the raw data.
