### ISSUE TITLE
Where are my 2 issus from yesterday

### ISSUE THREAD

**Issue by maestroat** [Apollon77/ioBroker.tuya#119]
hi, is this a service only delete no infos?

**Comment by Apollon77** [comment]
They are commented and closed. Please see comments in them and check your mails ... normally GitHub sends notifications on answers

Her the links to your issues:
https://github.com/Apollon77/ioBroker.tuya/issues/115
https://github.com/Apollon77/ioBroker.tuya/issues/114

If you have questions you still can answer on the closed issues.

And I also close this one. :-)
