### ISSUE TITLE
Empfang von Daten eines Gerätes, das offline war?

### ISSUE THREAD

**Issue by riridi** [Apollon77/ioBroker.tuya#124]
Hallo,

ich habe eine Frage zum Tuya Adapter. Aber erstmal eine kleine Problembeschreibung.
Ich will mithilfe der Luminea WLAN-Steckdosen den Stromverbrauch mehrerer elektrischer Geräte messen. Dafür habe ich auf einem Raspberry Pi den IoBroker zusammen mit den Tuya Adapter laufen. Wenn die Steckdose immer Strom hat und Online ist funktioniert das auch problemlos. Bei einer Waschmaschiene habe ich aber jetzt das Problem, dass vor der WLAN-Steckdose ein Münzautomat geschalten ist, der den Stromfluss zur Waschmaschiene kontrolliert. Unterbricht dieser Münzautomat nun den Stomfluss, schaltet sich die Steckdose natürlich ab und der Tuya Adapter bekommt keine Daten mehr von diesem Gerät. Schaltet sich die Steckdose nach einer nur kurzzeitigen Stromunterbrechungn (bis zu 15 min) wieder ein, kann der Tuya Adabter die aktuellen Daten wieder empfangen und es funktioniert immer noch alles. Schaltet sich die Steckdose erst nach einer längeren Unterbrechung des Stromflusses wieder ein, empfängt der Tuya Adapter keine Daten mehr von diesem Stecker und es bedarf eine erneute Synchronisation zwischen der Tuya Smart Home App und dem Tuya Adapter.

Jetzt zur Frage: ist es möglich, dass der Tuya Adapter die Daten der Steckdose, die für eine längere Zeit offline war, wieder empfangen kann, ohne das eine erneute Synchronisation notwendig ist?

Mit freundlichen Grüßen

**Comment by Apollon77** [comment]
Das sollte im Normalfall kein Thema sein. Wenn Die Tuya App das gerät noch kennt und Daten nach dem wieder einschalten bekommt dann geht das auch beim Adapter. Der Versucht sogar,  wenn er die Verbindung verliert regelmässig neu zu verbinden.

Hier wäre das Log mal super

**Comment by riridi** [comment]
Danke für die schnelle Antwort! Habe es gerade nochmal getestet, aber im IoBroker Log sehe ich keine hilfreichen Einträge. Habe beim Test mal alle Stecker angesteckt (4 Geräte) und synchronisiert. Wenig später habe ich dann einen Stecker ausgesteckt und nach ca. 30 min wieder eingesteckt. Der Adapter baut aber zu diesem Stecker keine Verbindung mehr auf, der "Device online status" ist nun auch auf false gesetzt. Hier mal die Einträge des IoBroker Logs die wärend dieses Testes entstanden sind:

from | Time | debug | Message
-- | -- | -- | --
info.0 | 2020-02-13 21:52:43.743 | info | (840) Popup news was read...
admin.0 | 2020-02-13 21:50:51.421 | info | (8086) Repository received successfully.
host.raspberrypi | 2020-02-13 21:50:50.460 | info | Update repository "default" under "http://download.iobroker.net/sources-dist.json"
admin.0 | 2020-02-13 21:50:50.398 | info | (8086) Request actual repository...
tuya.0 | 2020-02-13 21:38:13.076 | info | (1339) 62384361cc50e344cceb Init with IP=xx.xx.xx.xx, Key=xxxxxxxx, Version=3.1
tuya.0 | 2020-02-13 21:38:13.074 | info | (1339) 388750602cf43220de8e Init with IP=xx.xx.xx.xx, Key=xxxxxxxx, Version=3.3
tuya.0 | 2020-02-13 21:38:13.049 | info | (1339) 388750602cf43220dd3f Init with IP=xx.xx.xx.xx, Key=xxxxxxxx, Version=3.3
tuya.0 | 2020-02-13 21:38:13.046 | info | (1339) 388750602cf43220d1b6 Init with IP=xx.xx.xx.xx, Key=xxxxxxxx, Version=3.3
tuya.0 | 2020-02-13 21:38:10.861 | info | (1339) SSL-Proxy ready to receive requests

Gibt es noch andere Logs wo hilfreichere Informationen drinnen stehen?

**Comment by Apollon77** [comment]
Bitte mal ein Debug Log .. Instanzen - Expertenmodus - Spalte Logstufe.

**Comment by riridi** [comment]
Okay hier mal die Debug Log-Einträge, die für den eine Stecker (hier Stecker1 genannt) entstanden sind.
1) Verbindung funktioniert noch, Daten von Stecker1 werden übertragen:

from | Time | debug | Message
-- | -- | -- | --
tuya.0 | 2020-02-14 10:20:07.217 | debug | (26559) stateChange tuya.0.ID-Stecker1.5 {"val":0,"ack":true,"ts":1581672007205,"q":0,"from":"system.adapter.tuya.0","user":"system.user.admin","lc":1581672007205}
tuya.0 | 2020-02-14 10:20:07.211 | debug | (26559) stateChange tuya.0.ID-Stecker1.4 {"val":0,"ack":true,"ts":1581672007204,"q":0,"from":"system.adapter.tuya.0","user":"system.user.admin","lc":1581672007204}
tuya.0 | 2020-02-14 10:20:07.201 | debug | (26559) ID-Stecker1: Received data: {"4":0,"5":0}

2) Stecker1 wird ausgesteckt um 10:26, Fehlermeldung nach ca. 16 min:

from | Time | debug | Message
-- | -- | -- | --
tuya.0 | 2020-02-14 10:42:18.128 | debug | (26559) stateChange tuya.0.ID-Stecker1.online {"val":false,"ack":true,"ts":1581673338125,"q":0,"from":"system.adapter.tuya.0","user":"system.user.admin","lc":1581673338125}
tuya.0 | 2020-02-14 10:42:18.119 | debug | (26559) ID-Stecker1: Disconnected from device
tuya.0 | 2020-02-14 10:42:18.118 | debug | (26559) ID-Stecker1: Error from device (0): App still open on your mobile phone? Error: Error from socket

3) Fehlermeldung nach ca. 17 min:

from | Time | debug | Message
-- | -- | -- | --
tuya.0 | 2020-02-14 10:43:21.249 | debug | (26559) stateChange tuya.0.ID-Stecker1.online {"val":false,"ack":true,"ts":1581673401244,"q":0,"from":"system.adapter.tuya.0","user":"system.user.admin","lc":1581673338125}
tuya.0 | 2020-02-14 10:43:21.240 | debug | (26559) ID-Stecker1: Disconnected from device
tuya.0 | 2020-02-14 10:43:21.238 | debug | (26559) ID-Stecker1: Error from device (1): App still open on your mobile phone? Error: Error from socket

4) Fehlermeldung nach ca. 18 min:

from | Time | debug | Message
-- | -- | -- | --
tuya.0 | 2020-02-14 10:44:24.371 | debug | (26559) stateChange tuya.0.ID-Stecker1.online {"val":false,"ack":true,"ts":1581673464366,"q":0,"from":"system.adapter.tuya.0","user":"system.user.admin","lc":1581673338125}
tuya.0 | 2020-02-14 10:44:24.360 | debug | (26559) ID-Stecker1: Disconnected from device
tuya.0 | 2020-02-14 10:44:24.358 | debug | (26559) ID-Stecker1: Error from device (2): App still open on your mobile phone? Error: Error from socket

5) Fehlermeldung nach ca. 19 min:

from | Time | debug | Message
-- | -- | -- | --
tuya.0 | 2020-02-14 10:45:27.489 | debug | (26559) stateChange tuya.0.ID-Stecker1.online {"val":false,"ack":true,"ts":1581673527485,"q":0,"from":"system.adapter.tuya.0","user":"system.user.admin","lc":1581673338125}
tuya.0 | 2020-02-14 10:45:27.481 | debug | (26559) ID-Stecker1: Disconnected from device
tuya.0 | 2020-02-14 10:45:27.478 | debug | (26559) ID-Stecker1: Error from device (3): App still open on your mobile phone? Error: Error from socket

6) Stecker1 wird wieder eingesteckt um 10:46, Meldung:

from | Time | debug | Message
-- | -- | -- | --
tuya.0 | 2020-02-14 10:46:37.071 | debug | (26559) Discovered encrypted device and store for later usage: IP-Adresse-Stecker1 - U��{c4���.p�������$G�$ cm[�����)��l��IH�]B�dGhF�\���R�E>E'�Y$����^�|�@��!p�!��f��8�_ޅ

Danach gibt es keine Einträge mehr zu Stecker1.

**Comment by Apollon77** [comment]
Bitte die 3.2.2 vom GitHub versuchen!

**Comment by riridi** [comment]
Danke für das Update! Jetzt verbindet sich der Stecker meistens automatisch mit dem Adapter. Eine Ausnahme ist, wenn der Stecker bei aktiven Stromfluss vom Netz genommen wird. Dann stehen im ioBroker noch die alten Werte drin (Stromstärke, Leistung > 0). Im Log finden sich dann die regelmäßigen "Disconnected from Device" Fehlermeldungen wieder. Wird dann der Stecker wieder angesteckt bzw. bekommt wieder Strom, verbindet er sich nicht mehr mit dem Tuya Adapter. Es tauchen dann auch keine Einträge mehr im Log auf. Keine "Discovered encrypted device" als auch keine "Disconnected from Device" Nachricht. Ich weis nicht ob das Problem am Stecker oder am Tuya Adapter liegt. Vielleicht kann das Problem auch durch ein ioBroker-Skript behoben werden, das die entsprechenden Werte auf 0 zurücksetzt, falls der Stecker offline ist (müsste ja möglich sein oder?).

**Comment by Apollon77** [comment]
Der Status ist beim reconnect handling irrelevant. Der Adapter versucht bis zu 3mal von sich aus zu reconnecten. Das siehst du im log. Dann hört er damit auf und geht davon aus das das Gerät offline ist. 

Er versucht es dann wieder sobald dich das Gerät mit einem Udp Paket zurückmeldet. Das sind die Meldungen mit encrypted device und so. Wenn die aber vom Gerät nicht kommen kann der Adapter Nichts tun.

**Comment by riridi** [comment]
Danke für die Antwort. Ich habe herausgefunden, dass das Problem am Stecker liegt. Adapter tut das was er soll. :+1:
