### ISSUE TITLE
can't control. SSL-Proxy ERROR.

### ISSUE THREAD

**Issue by Anzic23** [Apollon77/ioBroker.tuya#126]
v. 3.2.0
Smartlife app - 3.12.6
I have 4 BHT-002GBLW thermostats. Previously, they were all managed normally, only you had to convert values #33 . Now I had to reset one, and now I can't control it. It was possible to add via proxy, but there is no way to manage it. Adapter writes: Status: 4 detected in the network, connected devices are connected, 4 with a known scheme, 3 initialized for real-time updates and for management. When I try to update the device through a proxy an error appears in the log :

```
error: tuya.0 (18677) SSL-Proxy ERROR: Error: 139729338554176:error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert number 46
--
error: tuya.0 (18677) Error: 139729338554176:error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert number 46

```

**Comment by Apollon77** [comment]
it seems that the custom SWL certificate is not activated on your mobile device correctly ... Please check that and do proxy sync again
