### ISSUE TITLE
Handy oder ein Adapterfehler ?

### ISSUE THREAD

**Issue by daxemann** [Apollon77/ioBroker.tuya#138]
hab 2 Defuser aber im Handy kommt Fehlermeldung " Das Netzwerk hat Verbindungsfehler,Bitte überprüfen Sie das Netzwerk"
und unten das Log denke hab irgend ein Fehler in einem Adapter oder ?

tuya.0	2020-03-09 16:44:51.567	error	at TCP._handle.close (net.js:607:12)
tuya.0	2020-03-09 16:44:51.567	error	at Socket.EventEmitter.emit (domain.js:448:20)
tuya.0	2020-03-09 16:44:51.567	error	at Socket.emit (events.js:198:13)
tuya.0	2020-03-09 16:44:51.567	error	at Object.onceWrapper (events.js:286:20)
tuya.0	2020-03-09 16:44:51.567	error	at Socket.done (_tls_wrap.js:388:7)
tuya.0	2020-03-09 16:44:51.567	error	at _handle.close (net.js:607:12)
tuya.0	2020-03-09 16:44:51.567	error	at TLSSocket.EventEmitter.emit (domain.js:448:20)
tuya.0	2020-03-09 16:44:51.567	error	at TLSSocket.emit (events.js:203:15)
tuya.0	2020-03-09 16:44:51.567	error	at TLSSocket.onSocketClose (_tls_wrap.js:764:23)
tuya.0	2020-03-09 16:44:51.567	error	(20173) Error: socket hang up
tuya.0	2020-03-09 16:44:51.566	error	(20173) SSL-Proxy ERROR: Error: socket hang up

---

**System data:**

Model: ARMv7 Processor rev 3 (v7l)
RAM: 3.81 GB
Node.js: v10.19.0
NPM: 6.13.4
Platform: linux
Distribution: Raspbian GNU/Linux
Architecture: arm
JS-Controller (1): 2.2.9
Admin: 4.0.5
Tuya: 3.2.3

> *created by ioBroker.info*

**Comment by Apollon77** [comment]
Wenn Du proxy an hast und eingerichtet hast ... kannst Du browsen auf https seiten? https://heise.de oder so? Wenn nein dann ist der Proxy nicht korrekt eingetragen oder nicht erreichbar vom Handy aus,

**Comment by daxemann** [comment]
also meine ip vom iobroker ist 192.168.178.54 das steht auch im Proxy am Handy port dann 8888
im Proxy adapter hab ich mit http://localhost:8888 probiert und mi http://192.168.178.54:8888

wo soll oder kann ich noch was eintragen ?

**Comment by Apollon77** [comment]
proxy Adapter? Der hat damit nichts zu tun!!
Du startest den tuya Adapter proxy, dann trägst Du die IPbroker IP und den Port in deinem Handy als zu nutzender Proxy ein

**Comment by Apollon77** [comment]
Anleitung: https://github.com/Apollon77/ioBroker.tuya/blob/master/PROXY.md

**Comment by daxemann** [comment]
jup so gemacht , geht nicht . das LOG im iobroker wird immer länger und handy hat keine verbindung

**Comment by Apollon77** [comment]
Wenn handy auch im browser keine verbindung hat dann stimmt was nicht mit dem setup. Was steht denn im iobroker log? Irgendwas mit ungültigem zertifikat? Dann ist was falsch aufgesetzt oder das Zertifikat nicht korrekt aktiviert

**Comment by daxemann** [comment]
hab adapter nochmal gelöscht neu installiert und alles von anfang an , zertifikat runter installiert aktiviert, proxy eingestellt auf mein iobroker auf 8888 , am handy kommt Das Netzwerk hat Verbindungsfehler,Bitte überprüfen Sie das Netzwerk"Das Netzwerk hat Verbindungsfehler,Bitte überprüfen Sie das Netzwerk"

**Comment by daxemann** [comment]
tuya.0 | 2020-03-11 18:37:57.150 | info | (23153) SSL-Proxy ready to receive requests
-- | -- | -- | --
tuya.0 | 2020-03-11 18:37:51.812 | info | (23153) Listen for encrypted local Tuya devices on port 6667
tuya.0 | 2020-03-11 18:37:51.811 | info | (23153) Listen for local Tuya devices on port 6666
tuya.0 | 2020-03-11 18:37:51.802 | info | (23153) Existing devices initialized
tuya.0 | 2020-03-11 18:37:51.556 | info | (23153) starting. Version 3.2.3 in /opt/iobroker/node_modules/iobroker.tuya, node: v10.19.0

das LOG - hab aber auch Port 6666 und port 6667 probiert :( kein erfolg

**Comment by daxemann** [comment]
tuya.0 | 2020-03-11 18:50:57.741 | error | (23453) Error: socket hang up at TLSSocket.onSocketClose (_tls_wrap.js:764:23) at TLSSocket.emit (events.js:203:15) at TLSSocket.EventEmitter.emit (domain.js:448:20) at _handle.close (
-- | -- | -- | --
tuya.0 | 2020-03-11 18:50:57.734 | error | (23453) SSL-Proxy ERROR: Error: socket hang up

**Comment by Apollon77** [comment]
socket hangup mostly means that the adapter can not get data from the internet  ... I assume ...

I only know that it works for most users, so it needs to be something on your system ... I think it is better to switch to forum to get better support.
