### ISSUE TITLE
New Shema for W7KCgml5Qn2x5T9v

### ISSUE THREAD

**Issue by DocYester** [Apollon77/ioBroker.tuya#14]
tuya.0 | 2019-01-07 17:34:53.672 | info | {"schema":"[{\"mode\":\"rw\",\"code\":\"led_switch\",\"name\":\"开关\",\"property\":{\"type\":\"bool\"},\"iconname\":\"icon-dp_power2\",\"id\":1,\"type\":\"obj\",\"desc\":\"\"},{\"mode\":\"rw\",\"code\
-- | -- | -- | --
tuya.0 | 2019-01-07 17:34:53.671 | info | new Shema added for product type W7KCgml5Qn2x5T9v. Please send next line from logfile on disk to developer!

-> Luminea Home Control LAV-100.rgbw

**Comment by Apollon77** [comment]
Bräuchte es bitte nicht abgeschnitten von dem Logfile auf Platte unter /opt/iobroker/log/... Danke!

**Comment by Apollon77** [comment]
will be in next version
