### ISSUE TITLE
Schalten nicht möglich

### ISSUE THREAD

**Issue by DerAndy77** [Apollon77/ioBroker.tuya#176]
Hallo,

ich habe meine 4 LED Stripes eingebunden, soweit alles gut. Im Adapter habe ich auch den korrekten Status:
Status: 4 Geräte im Netzwerk gefunden, 4 Geräte verbunden, 4 mit bekanntem Schema, 4 initialisiert für Echtzeit-Updates und zur Steuerung

Allerdings kann ich die Geräte nicht über ioBroker steuern. Ich habe im Log immer die gleiche Meldung bei allen 4 devices:
Value from device not defined in Schema: null
Auch wird der Status nicht aktualisiert wenn ich die Stripes mit der Fernbedienung schalte. 

```
tuya.0 | 2020-05-18 13:46:55.910 | warn | (25124) bf78fdbfedda34e30efsun.2: Value from device not defined in Schema: null
tuya.0 | 2020-05-18 13:46:55.849 | warn | (25124) bfcfad3aaa67650291pb9y.2: Value from device not defined in Schema: null
tuya.0 | 2020-05-18 13:46:55.846 | warn | (25124) bfe22d0646d6ab6de2qise.2: Value from device not defined in Schema: null
tuya.0 | 2020-05-18 13:46:55.842 | warn | (25124) bfb7cddbf45b73551bel7w.2: Value from device not defined in Schema: null
tuya.0 | 2020-05-18 13:46:55.617 | info | (25124) Listen for encrypted local Tuya devices on port 6667
tuya.0 | 2020-05-18 13:46:55.616 | info | (25124) Listen for local Tuya devices on port 6666
tuya.0 | 2020-05-18 13:46:55.610 | info | (25124) Existing devices initialized
tuya.0 | 2020-05-18 13:46:55.608 | info | (25124) bf78fdbfedda34e30efsun Init with IP=192.168.188.23, Key=9826eebaf9bdffa3, Version=3.2
tuya.0 | 2020-05-18 13:46:55.561 | info | (25124) bfb7cddbf45b73551bel7w Init with IP=192.168.188.25, Key=eeefa3385af3fdae, Version=3.2
tuya.0 | 2020-05-18 13:46:55.558 | info | (25124) bfe22d0646d6ab6de2qise Init with IP=192.168.188.27, Key=a47f2d3ddba16773, Version=3.2
tuya.0 | 2020-05-18 13:46:55.552 | info | (25124) bfcfad3aaa67650291pb9y Init with IP=192.168.188.29, Key=1cde0bb4f04edef8, Version=3.2
tuya.0 | 2020-05-18 13:46:55.218 | info | (25124) starting. Version 3.2.3 in /opt/iobroker/node_modules/iobroker.tuya, node: v12.16.3, js-controller: 3.1.4
```

Kann mir hier jemand einen Tip geben?

**Comment by Apollon77** [comment]
Bitte nochmal neu den Proxy Sync machen. Und debug logging aktivieren (Instanzen - expertenmodus - Spalte logstufe. 

Dann Proxy Sync und dann einmal eine relevante schaltaktion versuchen. Dann das gesamte relevante  log von der Platte unser /opt/iobroker/log/... hier einstellen.

**Comment by DerAndy77** [comment]
Hi Apollon,

erstmal danke für die schnelle Rückmeldung.
Habe den Adapter gerade nochmal komplett neu installiert, Smart Life App habe ich die 3,12 verwendet, ebenfalls neu installiert. Den Sync Prozess habe ich auch 2 mal durchlaufen lassen. Anbei das Log.

Vielen Dank in Voraus und beste Grüße
Andy


[iobroker.2020-05-19.log](https://github.com/Apollon77/ioBroker.tuya/files/4649105/iobroker.2020-05-19.log)

**Comment by Apollon77** [comment]
Um welche Geräte der 4 geht es denn? Bitte mit 3.3.5 neu versuchen und neues Log senden

**Comment by Jockelflo** [comment]
Hallo,
seit dem vorletztem oder vorvorletzem Update speichert Tuya im iobroker unter Objekte den Status nicht mehr. Wenn ich die Steckdose einschalte steht kurz true genauso wie beim ausschalten false steht aber immer nur für 2-3 Sekunden, dann ist das Feld leer. Dadurch funktioniert meine Vis nicht mehr. Gibt es da eine Lösung?

**Comment by Apollon77** [comment]
Bitte 3.3.8 versuchen, ist ab morgen im Latest repo
