### ISSUE TITLE
Synchronisation 

### ISSUE THREAD

**Issue by Schmusekater76** [Apollon77/ioBroker.tuya#181]
Synchronisation ist mit Android nicht mehr möglich, bei Eingabe des Proxy (Manual) kommt nur eine Fehlermeldung 50505, das wurde getestet auf mehreren Geräten.

Der Tuya Adapter sowie die App sind auf aktuellen stand.

**Comment by Apollon77** [comment]
>  sowie die App sind auf aktuellen stand.

Und das ist der Fehler!
Sowohl hier auf der Readme wie auch beim Adapter auf der Konfigseite genau da wo der Proxy aktiviert wird steht FETT geschrieben die App Version die es sein muss.
