### ISSUE TITLE
Keine Syncronisation möglich, SmartLife App Version 3.12

### ISSUE THREAD

**Issue by ich77** [Apollon77/ioBroker.tuya#183]
Hallo,

habe seit ein paar Tagen, das Problem, dass ich nicht mehr die neuen Geräte Synchronisieren kann. Starte den Proxy, stelle den Proxy im Handy ein, installiere die "alte" 3.12er Version, habe Verbindung zum Internet. Nach dem Starten der SmartLife App geht die Internetverbindung verloren und er synchronisiert nicht. 

Habe das letzte Woche noch auf dem gleichen Weg gemacht, da hat es Problemlos funktioniert. 

Anbei noch das Log aus iobroker, vielleicht kann man da was erkennen...

Danke

Markus

`tuya.0 | 2020-06-19 08:59:20.243 | info | (13492) Terminated (NO_ERROR): Without reason
-- | -- | -- | --
tuya.0 | 2020-06-19 08:59:20.241 | info | (13492) terminating
tuya.0 | 2020-06-19 08:59:20.213 | error | at Proxy._onResponseEnd (/opt/iobroker/node_modules/http-mitm-proxy/lib/proxy.js:1072:9)
tuya.0 | 2020-06-19 08:59:20.213 | error | at Object.eachLimit (/opt/iobroker/node_modules/async/dist/async.js:3172:5)
tuya.0 | 2020-06-19 08:59:20.213 | error | at eachOf (/opt/iobroker/node_modules/async/dist/async.js:1117:5)
tuya.0 | 2020-06-19 08:59:20.213 | error | at eachOfArrayLike (/opt/iobroker/node_modules/async/dist/async.js:1069:9)
tuya.0 | 2020-06-19 08:59:20.213 | error | at /opt/iobroker/node_modules/async/dist/async.js:3110:16
tuya.0 | 2020-06-19 08:59:20.213 | error | at /opt/iobroker/node_modules/http-mitm-proxy/lib/proxy.js:1073:12
tuya.0 | 2020-06-19 08:59:20.213 | error | at /opt/iobroker/node_modules/iobroker.tuya/main.js:680:25
tuya.0 | 2020-06-19 08:59:20.213 | error | at catchProxyInfo (/opt/iobroker/node_modules/iobroker.tuya/main.js:827:21)
tuya.0 | 2020-06-19 08:59:20.213 | error | at Array.forEach (<anonymous>)
tuya.0 | 2020-06-19 08:59:20.213 | error | at deviceInfos.forEach (/opt/iobroker/node_modules/iobroker.tuya/main.js:831:24)
tuya.0 | 2020-06-19 08:59:20.213 | error | (13492) TypeError: Cannot read property 'withScope' of undefined
tuya.0 | 2020-06-19 08:59:20.213 | error | (13492) uncaught exception: Cannot read property 'withScope' of undefined
tuya.0 | 2020-06-19 08:59:20.207 | warn | (13492) Exception: TypeError: Cannot read property 'withScope' of undefined
tuya.0 | 2020-06-19 08:59:20.194 | info | (13492)  {"schemaExt":"[]","schema":"[{\"mode\":\"ro\",\"code\":\"upward\",\"name\":\"上行通道\",\"id\":101,\"type\":\"raw\",\"desc\":\"\"},{\"mode\":\"wr\",\"code\":\"down\",\"name\":\"下行通道\",\"id\":102,
tuya.0 | 2020-06-19 08:59:20.194 | info | (13492) new Schema added for product type ddy7a81zb1a9otk1. Please send next line from logfile on disk to developer!
tuya.0 | 2020-06-19 08:59:18.377 | error | (13492) Error: 3069950416:error:14094416:SSL  routines:ssl3_read_bytes:sslv3 alert certificate  unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1550:SSL alert  number 46
tuya.0 | 2020-06-19 08:59:18.377 | error | (13492) SSL-Proxy ERROR: Error: 3069950416:error:14094416:SSL  routines:ssl3_read_bytes:sslv3 alert certificate  unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1550:SSL alert  number 46
tuya.0 | 2020-06-19 08:58:47.443 | error | (13492) Error: 3069950416:error:14094416:SSL  routines:ssl3_read_bytes:sslv3 alert certificate  unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1550:SSL alert  number 46
tuya.0 | 2020-06-19 08:58:47.442 | error | (13492) SSL-Proxy ERROR: Error: 3069950416:error:14094416:SSL  routines:ssl3_read_bytes:sslv3 alert certificate  unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1550:SSL alert  number 46
tuya.0 | 2020-06-19 08:58:44.170 | error | (13492) Error: 3069950416:error:14094416:SSL  routines:ssl3_read_bytes:sslv3 alert certificate  unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1550:SSL alert  number 46
tuya.0 | 2020-06-19 08:58:44.170 | error | (13492) SSL-Proxy ERROR: Error: 3069950416:error:14094416:SSL  routines:ssl3_read_bytes:sslv3 alert certificate  unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1550:SSL alert  number 46
tuya.0 | 2020-06-19 08:58:37.313 | error | (13492) Error: 3069950416:error:14094416:SSL  routines:ssl3_read_bytes:sslv3 alert certificate  unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1550:SSL alert  number 46
tuya.0 | 2020-06-19 08:58:37.312 | error | (13492) SSL-Proxy ERROR: Error: 3069950416:error:14094416:SSL  routines:ssl3_read_bytes:sslv3 alert certificate  unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1550:SSL alert  number 46
tuya.0 | 2020-06-19 08:58:35.302 | error | (13492) Error: 3069950416:error:14094416:SSL  routines:ssl3_read_bytes:sslv3 alert certificate  unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1550:SSL alert  number 46
tuya.0 | 2020-06-19 08:58:35.301 | error | (13492) SSL-Proxy ERROR: Error: 3069950416:error:14094416:SSL  routines:ssl3_read_bytes:sslv3 alert certificate  unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1550:SSL alert  number 46
tuya.0 | 2020-06-19 08:58:30.967 | error | (13492) Error: 3069950416:error:14094416:SSL  routines:ssl3_read_bytes:sslv3 alert certificate  unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1550:SSL alert  number 46
tuya.0 | 2020-06-19 08:58:30.967 | error | (13492) SSL-Proxy ERROR: Error: 3069950416:error:14094416:SSL  routines:ssl3_read_bytes:sslv3 alert certificate  unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1550:SSL alert  number 46
tuya.0 | 2020-06-19 08:58:29.314 | error | (13492) Error: 3069950416:error:14094416:SSL  routines:ssl3_read_bytes:sslv3 alert certificate  unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1550:SSL alert  number 46
tuya.0 | 2020-06-19 08:58:29.313 | error | (13492) SSL-Proxy ERROR: Error: 3069950416:error:14094416:SSL  routines:ssl3_read_bytes:sslv3 alert certificate  unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1550:SSL alert  number 46
tuya.0 | 2020-06-19 08:58:29.124 | error | (13492) Error: 3069950416:error:14094416:SSL  routines:ssl3_read_bytes:sslv3 alert certificate  unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1550:SSL alert  number 46
tuya.0 | 2020-06-19 08:58:29.123 | error | (13492) SSL-Proxy ERROR: Error: 3069950416:error:14094416:SSL  routines:ssl3_read_bytes:sslv3 alert certificate  unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1550:SSL alert  number 46
tuya.0 | 2020-06-19 08:58:27.709 | error | (13492) Error: 3069950416:error:14209102:SSL  routines:tls_early_post_process_client_hello:unsupported  protocol:../deps/openssl/openssl/ssl/statem/statem_srvr.c:1686:
tuya.0 | 2020-06-19 08:58:27.708 | error | (13492) SSL-Proxy ERROR: Error: 3069950416:error:14209102:SSL  routines:tls_early_post_process_client_hello:unsupported  protocol:../deps/openssl/openssl/ssl/statem/statem_srvr.c:1686:
tuya.0 | 2020-06-19 08:58:26.663 | error | at Socket.EventEmitter.emit (domain.js:448:20)
tuya.0 | 2020-06-19 08:58:26.663 | error | at Socket.emit (events.js:198:13)
tuya.0 | 2020-06-19 08:58:26.663 | error | at Socket.ondata (_stream_readable.js:710:20)
tuya.0 | 2020-06-19 08:58:26.663 | error | at Socket.Writable.write (_stream_writable.js:299:11)
tuya.0 | 2020-06-19 08:58:26.663 | error | at writeOrBuffer (_stream_writable.js:399:5)
tuya.0 | 2020-06-19 08:58:26.663 | error | at doWrite (_stream_writable.js:415:12)
tuya.0 | 2020-06-19 08:58:26.663 | error | at Socket._write (net.js:726:8)
tuya.0 | 2020-06-19 08:58:26.663 | error | at Socket._writeGeneric (net.js:714:5)
tuya.0 | 2020-06-19 08:58:26.663 | error | at writeGeneric (internal/stream_base_commons.js:73:3)
tuya.0 | 2020-06-19 08:58:26.663 | error | at afterWriteDispatched (internal/stream_base_commons.js:78:25)
tuya.0 | 2020-06-19 08:58:26.663 | error | (13492) Error: write EPIPE
tuya.0 | 2020-06-19 08:58:26.661 | error | (13492) SSL-Proxy ERROR: Error: write EPIPE
tuya.0 | 2020-06-19 08:58:26.652 | error | (13492) Error: 3069950416:error:14209102:SSL  routines:tls_early_post_process_client_hello:unsupported  protocol:../deps/openssl/openssl/ssl/statem/statem_srvr.c:1686:
tuya.0 | 2020-06-19 08:58:26.651 | error | (13492) SSL-Proxy ERROR: Error: 3069950416:error:14209102:SSL  routines:tls_early_post_process_client_hello:unsupported  protocol:../deps/openssl/openssl/ssl/statem/statem_srvr.c:1686:
tuya.0 | 2020-06-19 08:57:56.247 | error | (13492) Error: 3069950416:error:14209102:SSL  routines:tls_early_post_process_client_hello:unsupported  protocol:../deps/openssl/openssl/ssl/statem/statem_srvr.c:1686:
tuya.0 | 2020-06-19 08:57:56.246 | error | (13492) SSL-Proxy ERROR: Error: 3069950416:error:14209102:SSL  routines:tls_early_post_process_client_hello:unsupported  protocol:../deps/openssl/openssl/ssl/statem/statem_srvr.c:1686:
tuya.0 | 2020-06-19 08:57:54.060 | error | (13492) Error: 3069950416:error:14094416:SSL  routines:ssl3_read_bytes:sslv3 alert certificate  unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1550:SSL alert  number 46
tuya.0 | 2020-06-19 08:57:54.059 | error | (13492) SSL-Proxy ERROR: Error: 3069950416:error:14094416:SSL  routines:ssl3_read_bytes:sslv3 alert certificate  unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1550:SSL alert  number 46
tuya.0 | 2020-06-19 08:57:52.887 | error | (13492) Error: 3069950416:error:14094416:SSL  routines:ssl3_read_bytes:sslv3 alert certificate  unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1550:SSL alert  number 46
tuya.0 | 2020-06-19 08:57:52.886 | error | (13492) SSL-Proxy ERROR: Error: 3069950416:error:14094416:SSL  routines:ssl3_read_bytes:sslv3 alert certificate  unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1550

`

**Comment by Apollon77** [comment]
Dann scheint das SSL Zertifikat vom proxy nicht korrekt im handy hinterlegt bzw aktiviert zu sein

**Comment by Apollon77** [comment]
Und bitte neueste "LatesT" Version des Adapters versuchen. Der hier gezeigte Fehler ist dort bereits gefixt
