### ISSUE TITLE
Adapter synchronisieren 

### ISSUE THREAD

**Issue by Reuli61** [Apollon77/ioBroker.tuya#198]
Habe das ganze schon gefühlt 100 mal versucht. Es funktioniert nicht mehr. Einmal am Anfang. Ich weiß nicht wieso. Alles gemacht wie beschrieben. Werde die Tuya Sachen langsam austauschen. Alleine mit dem Proxy habe ich es so gemacht wie beschrieben. Das ist aber der Knackpunkt nehme ich an. Es ist auch der neuere.

**Comment by Apollon77** [comment]
Und du hast auch die korrekte alte App Version genommen und nicht die aktuelle App???

**Comment by Reuli61** [comment]
Welche Version soll ich denn nehmen?

**Comment by Apollon77** [comment]
Die die in Admin und auch hier imGithub in der readme steht? 
https://github.com/Apollon77/ioBroker.tuya#iobrokertuya

> The Adapter only works with Tuya and compatible apps as long as their version is <3.14 (!!)
