### ISSUE TITLE
thermostat not correct temperature

### ISSUE THREAD

**Issue by di3t0** [Apollon77/ioBroker.tuya#211]
I have integrated a thermostat. but it does not show the correct temperature in the adapter.
Instead of showing 27 ° C, there are only 4 and a few signs.
![2020_09_04_11_37_43_objects_ioBroker](https://user-images.githubusercontent.com/40027237/92225403-721ffb80-eea3-11ea-933c-5d247e4aeee1.jpg)

**Comment by Apollon77** [comment]
The "few signs" is the "unit" wehich is delivered in the schema from Tuya for that ... so data come so from them ... So I have no idea, sorry ... but when it is coming that way it is provided that way from Tuya. The adapter can not do anything
