### ISSUE TITLE
LSC Action Tuya Steckdose wird gefunden ist aber nicht online

### ISSUE THREAD

**Issue by soeni** [Apollon77/ioBroker.tuya#218]
Hi,

ich habe den Tuya Adapter im IO broker installiert. Per Proxy habe ich mich mit der älteren App version verbunden. Nun Steht im Adapter folgendes:

"Status: 2 Geräte im Netzwerk gefunden, 0 Geräte verbunden, 2 mit bekanntem Schema, 2 initialisiert für Echtzeit-Updates und zur Steuerung"

Die zwei Geräte sind richtig. Entsprechende Objekte sind auch unter Objekte angelegt wirden. nur bedienen kann ich die nicht und den Status bekomme ich auch nicht aktualisiert.

Gab es wieder ein Firmwarewechsel, sodass die Steckdosen nicht mehr funktionieren? 
Kann ich unterstützen, damit sie wieder funktionieren?

Ich habe gelesen, dass die Geräte UDP Pakete zur Identifikation und IP Adressübermittlung versenden. Wenn diese nicht oder in einem anderen Format kommen, könne der Fehler auftreten. Kann man sonst auch irgendwo manuell eine Verbindung herstellen? Die IP Adresse kann ich ja aus der Fritzbox holen. Auf Pings antworten die Dosen auch.

**Comment by Apollon77** [comment]
Was steht im Adapter log? Ist die Tuya APp aus (und gekillt)?

**Comment by soeni** [comment]
Ja die Tuya App ist komplett gekillt. ich habe sie probehalber auch deinstalliert. Pi ist ausch schon neu gestartet.

Hier die Logeinträge beim Neustart des Tuya Adapters:


tuya.0 | 2020-09-23 22:38:28.452 | info | (2048) Listen for encrypted local Tuya devices on port 6667
-- | -- | -- | --
tuya.0 | 2020-09-23 22:38:28.449 | info | (2048) Listen for local Tuya devices on port 6666
tuya.0 | 2020-09-23 22:38:28.424 | info | (2048) Existing devices initialized
tuya.0 | 2020-09-23 22:38:28.421 | info | (2048) bf2c97caa0c59f9fd1yjaj: None of the discovered devices matches :-(
tuya.0 | 2020-09-23 22:38:28.360 | info | (2048) bfa1ea1eb1f65c3fabvrpj: None of the discovered devices matches :-(
tuya.0 | 2020-09-23 22:38:27.925 | info | (2048) starting. Version 3.3.12 in /opt/iobroker/node_modules/iobroker.tuya, node: v12.18.3, js-controller: 3.1.6
tuya.0 | 2020-09-23 22:38:17.599 | info | (1555) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
tuya.0 | 2020-09-23 22:38:17.589 | info | (1555) terminating
tuya.0 | 2020-09-23 22:38:14.580 | info | (1555) Got terminate signal TERMINATE_YOURSELF

**Comment by soeni** [comment]
Habe den Adapter ncoh mal auf Debug gestelt. Lustigerweise wird dort angezeigt, dass er die Geräte gefunden hat:


tuya.0 | 2020-09-23 22:44:33.628 | debug | (2183) Discovered encrypted device and store for later usage: 192.168.178.50:49153 - U��Зfgo3i����2��* �(���\|)��m�����M-*hg����_�Rr�BΕJ���S\|�Y�Y�&Օ������7�@��m��Eo?~(�ԓ+�a���
-- | -- | -- | --
tuya.0 | 2020-09-23 22:44:30.459 | debug | (2183)  Discovered encrypted device and store for later usage:  192.168.178.49:49153 -  U��Зfgo3i����2��*9wvF�<skv�a�I����I/L���z(�a�,DA}mc`}{��Y�Y�&Օ������7�@��m��Eo?~(�ԓ+�a�
tuya.0 | 2020-09-23 22:44:29.540 | info | (2183) Listen for encrypted local Tuya devices on port 6667

Die IP adressen scheinen mit denen aus der Fritzbox überein zu stimmen

**Comment by Castlehub** [comment]
Hallöchen
Seit kurzem habe ich die selben Probleme. Gibt es schon einen Lösungsansatz?

**Comment by GustavR** [comment]
Ich habe dasselbe Problem. Eigentlich lief alles prima, aber ich wollte eine neue Steckdose zum iobroker hinzufügen. Diese hat er auch erkannt, aber sie war immer offline (indicator.reachable false).
Dann mal tuya komplett runtergehauen, alles gelöscht und wieder installiert, Proxy-Sync (mit altem Handy und alter APK) hat auch scheinbar erfolgreich geklappt, jetzt sind allerdings alle Geräte offline. :( Nix geht mehr.

Für jedes der sieben Geräte kommt das folgende im Log: "None of the discovered devices matches :-("

tuya.0 | 2020-09-27 13:55:14.853 | debug | (1784) Discovered encrypted device and store for later usage: 192.168.88.12:49154 - U����o���C�\|�sj��`>���h���!�@c�}����ܢ�F�#��!��dn����xk�L��l A;�э/��ي �̆>S$���^�1"�����X�
-- | -- | -- | --
tuya.0 | 2020-09-27 13:55:13.999 | debug | (1784) Discovered encrypted device and store for later usage: 192.168.88.16:49154 - U����o���C�\|�sj���8*[ml:�B�2u� �!=C ��鯍R���O7oH�}DB[+{��L��l A;�э/��ي �̆>S$���^�1"�����X�
tuya.0 | 2020-09-27 13:55:13.948 | debug | (1784) Discovered encrypted device and store for later usage: 192.168.88.10:49154 - U����o���C�\|�sj������Q`� p�ʇ1-������N? �$�+���)�~�O���AL��l A;�э/��ي �̆>S$���^�1"�����X
tuya.0 | 2020-09-27 13:55:13.789 | debug | (1784) Discovered encrypted device and store for later usage: 192.168.88.19:49154 - U����o���C�\|�sj�����rm���熯���T�@{�j�8~Kj�XvK <��U� ќ��?L��l A;�э/��ي �̆>S$���^�1"�����X�
tuya.0 | 2020-09-27 13:55:13.628 | debug | (1784) Discovered encrypted device and store for later usage: 192.168.88.11:49154 - U����o���C�\|�sj��s�����,�ׁ 6 h����e��Ivd���p�<�Pvn�ڵl�L��l A;�э/��ي �̆>S$���^�1"�����X�
tuya.0 | 2020-09-27 13:55:11.877 | debug | (1784) Discovered encrypted device and store for later usage: 192.168.88.40:49154 - U����o���C�\|�sj�b�f�dQ�ף�L`Bx���y0B��\�7?���MVE8?���F��OL��l A;�э/��ي �̆>S$���^�1"�����
tuya.0 | 2020-09-27 13:55:11.490 | debug | (1784) Discovered encrypted device and store for later usage: 192.168.88.13:49154 - U����o���C�\|�sj��<�'V�F��\|^e���D�FUJ�%0�� Y�RwH�����"�5��5L��l A;�э/��ي �̆>S$���^�1"����
tuya.0 | 2020-09-27 13:55:10.896 | info | (1784) Listen for encrypted local Tuya devices on port 6667
tuya.0 | 2020-09-27 13:55:10.896 | info | (1784) Listen for local Tuya devices on port 6666
tuya.0 | 2020-09-27 13:55:10.888 | info | (1784) Existing devices initialized
tuya.0 | 2020-09-27 13:55:10.887 | info | (1784) 880216662cf432264793: None of the discovered devices matches :-(
tuya.0 | 2020-09-27 13:55:10.887 | debug | (1784) 880216662cf432264793: Try to initialize encrypted device with received UDP messages (#IPs: 0): version=undefined, key=1f9e5e46b6027a68
tuya.0 | 2020-09-27 13:55:10.885 | info | (1784) 880216662cf432264e80: None of the discovered devices matches :-(
tuya.0 | 2020-09-27 13:55:10.884 | debug | (1784) 880216662cf432264e80: Try to initialize encrypted device with received UDP messages (#IPs: 0): version=undefined, key=642e992b90b51edc
tuya.0 | 2020-09-27 13:55:10.882 | info | (1784) 431883812cf432dbdc9c: None of the discovered devices matches :-(
tuya.0 | 2020-09-27 13:55:10.881 | debug | (1784) 431883812cf432dbdc9c: Try to initialize encrypted device with received UDP messages (#IPs: 0): version=undefined, key=bfab3e62288d524f
tuya.0 | 2020-09-27 13:55:10.880 | info | (1784) 880216662cf432264f8d: None of the discovered devices matches :-(
tuya.0 | 2020-09-27 13:55:10.878 | debug | (1784) 880216662cf432264f8d: Try to initialize encrypted device with received UDP messages (#IPs: 0): version=undefined, key=f9e7902c0559c892
tuya.0 | 2020-09-27 13:55:10.871 | info | (1784) 10438000d8f15ba4de5c: None of the discovered devices matches :-(
tuya.0 | 2020-09-27 13:55:10.870 | debug | (1784) 10438000d8f15ba4de5c: Try to initialize encrypted device with received UDP messages (#IPs: 0): version=undefined, key=05f306268211dd07
tuya.0 | 2020-09-27 13:55:10.869 | info | (1784) 880216662cf4322645fb: None of the discovered devices matches :-(
tuya.0 | 2020-09-27 13:55:10.869 | debug | (1784) 880216662cf4322645fb: Try to initialize encrypted device with received UDP messages (#IPs: 0): version=undefined, key=898dbe3051f6c0f7
tuya.0 | 2020-09-27 13:55:10.868 | info | (1784) 431883812cf432db4075: None of the discovered devices matches :-(
tuya.0 | 2020-09-27 13:55:10.866 | debug | (1784) 431883812cf432db4075: Try to initialize encrypted device with received UDP messages (#IPs: 0): version=undefined, key=2d8d3702cacdac56
tuya.0 | 2020-09-27 13:55:10.700 | debug | (1784) 880216662cf432264e80 Register onChange for 7
tuya.0 | 2020-09-27 13:55:10.699 | debug | (1784) 880216662cf432264e80 Register onChange for 2
tuya.0 | 2020-09-27 13:55:10.699 | debug | (1784) 880216662cf432264e80 Register onChange for 1
tuya.0 | 2020-09-27 13:55:10.698 | debug | (1784) 880216662cf432264e80: Objects [{"type":"boolean","read":true,"write":true,"name":"switch_on","id":1,"role":"switch"},{"type":"number","unit":"ç§’","max":86400,"read":true,"write":true,"name":"c
tuya.0 | 2020-09-27 13:55:10.697 | debug | (1784) 880216662cf432264e80: Create device objects if not exist
tuya.0 | 2020-09-27 13:55:10.696 | debug | (1784) 10438000d8f15ba4de5c Register onChange for 2
tuya.0 | 2020-09-27 13:55:10.696 | debug | (1784) 10438000d8f15ba4de5c Register onChange for 1
tuya.0 | 2020-09-27 13:55:10.695 | debug | (1784) 10438000d8f15ba4de5c: Objects [{"type":"boolean","read":true,"write":true,"name":"switch_on","id":1,"role":"switch"},{"type":"number","unit":"秒","max":86400,"read":true,"write":true,"name":"cou
tuya.0 | 2020-09-27 13:55:10.694 | debug | (1784) 10438000d8f15ba4de5c: Create device objects if not exist
tuya.0 | 2020-09-27 13:55:10.693 | debug | (1784) 880216662cf4322645fb Register onChange for 7
tuya.0 | 2020-09-27 13:55:10.693 | debug | (1784) 880216662cf4322645fb Register onChange for 2
tuya.0 | 2020-09-27 13:55:10.692 | debug | (1784) 880216662cf4322645fb Register onChange for 1
tuya.0 | 2020-09-27 13:55:10.692 | debug | (1784) 880216662cf4322645fb: Objects [{"type":"boolean","read":true,"write":true,"name":"switch_on","id":1,"role":"switch"},{"type":"number","unit":"ç§’","max":86400,"read":true,"write":true,"name":"c
tuya.0 | 2020-09-27 13:55:10.691 | debug | (1784) 880216662cf4322645fb: Create device objects if not exist
tuya.0 | 2020-09-27 13:55:10.689 | debug | (1784) 431883812cf432db4075 Register onChange for 2
tuya.0 | 2020-09-27 13:55:10.689 | debug | (1784) 431883812cf432db4075 Register onChange for 1
tuya.0 | 2020-09-27 13:55:10.688 | debug | (1784) 431883812cf432db4075: Objects [{"type":"boolean","read":true,"write":true,"name":"switch_on","id":1,"role":"switch"},{"type":"number","unit":"秒","max":86400,"read":true,"write":true,"name":"cou
tuya.0 | 2020-09-27 13:55:10.687 | debug | (1784) 431883812cf432db4075: Create device objects if not exist
tuya.0 | 2020-09-27 13:55:10.686 | debug | (1784) 880216662cf432264793 Register onChange for 7
tuya.0 | 2020-09-27 13:55:10.685 | debug | (1784) 880216662cf432264793 Register onChange for 2
tuya.0 | 2020-09-27 13:55:10.685 | debug | (1784) 880216662cf432264793 Register onChange for 1
tuya.0 | 2020-09-27 13:55:10.685 | debug | (1784) 880216662cf432264793: Objects [{"type":"boolean","read":true,"write":true,"name":"switch_on","id":1,"role":"switch"},{"type":"number","unit":"ç§’","max":86400,"read":true,"write":true,"name":"c
tuya.0 | 2020-09-27 13:55:10.684 | debug | (1784) 880216662cf432264793: Create device objects if not exist
tuya.0 | 2020-09-27 13:55:10.682 | debug | (1784) 880216662cf432264f8d Register onChange for 7
tuya.0 | 2020-09-27 13:55:10.682 | debug | (1784) 880216662cf432264f8d Register onChange for 2
tuya.0 | 2020-09-27 13:55:10.681 | debug | (1784) 880216662cf432264f8d Register onChange for 1
tuya.0 | 2020-09-27 13:55:10.681 | debug | (1784) 880216662cf432264f8d: Objects [{"type":"boolean","read":true,"write":true,"name":"switch_on","id":1,"role":"switch"},{"type":"number","unit":"ç§’","max":86400,"read":true,"write":true,"name":"c
tuya.0 | 2020-09-27 13:55:10.679 | debug | (1784) 880216662cf432264f8d: Create device objects if not exist
tuya.0 | 2020-09-27 13:55:10.677 | debug | (1784) 431883812cf432dbdc9c Register onChange for 2
tuya.0 | 2020-09-27 13:55:10.676 | debug | (1784) 431883812cf432dbdc9c Register onChange for 1
tuya.0 | 2020-09-27 13:55:10.675 | debug | (1784) 431883812cf432dbdc9c: Objects [{"type":"boolean","read":true,"write":true,"name":"switch_on","id":1,"role":"switch"},{"type":"number","unit":"秒","max":86400,"read":true,"write":true,"name":"cou
tuya.0 | 2020-09-27 13:55:10.672 | debug | (1784) 431883812cf432dbdc9c: Create device objects if not exist
tuya.0 | 2020-09-27 13:55:10.669 | debug | (1784) init 7 known devices
tuya.0 | 2020-09-27 13:55:10.649 | debug | (1784) connected set to false
tuya.0 | 2020-09-27 13:55:10.591 | info | (1784) starting. Version 3.3.14 in /opt/iobroker/node_modules/iobroker.tuya, node: v14.12.0, js-controller: 3.1.6
tuya.0 | 2020-09-27 13:55:10.409 | debug | (1784) Plugin sentry Initialize Plugin (enabled=true)
host.pi | 2020-09-27 13:55:09.113 | info | instance system.adapter.tuya.0 started with pid 1784

**Comment by Blade1987** [comment]
Hatte das gleiche Problem, habe es mit dem Ansatz aus dem anderen Thread und der manuellen "version" und "ip" Eingabe zum laufen bekommen. Als Hint. Der Adapter bleibt gelb solange beim Neustart noch eine App verbunden bzw. geöffnet ist, schließt man diese läuft der Adapter in den grünen Status.
Allerdings läuft er instabil und verliert auch gerne mal die Verbindung.
Vor 2 Monaten hat alles noch super funktioniert.
PS: Bekomme beim Sync in der Log auch einen Proxy fehler.
Devices werden alle erkannt auch angelegt nur ohne version und IP.
PPS: Auch mit älteren Versionen läuft es nicht mehr reibungslos.

Viele Grüße

**Comment by Apollon77** [comment]
Bitte 3.4.1 versuchen
