### ISSUE TITLE
LSC Door Sensor 

### ISSUE THREAD

**Issue by B4unty** [Apollon77/ioBroker.tuya#219]
Hallo meine LSC Smart Door Sensoren werden nur mit dem einlese State angezeigt beim öffnen und schließen wird der Status nicht geändert im Iobroker

**Comment by Apollon77** [comment]
Batteriebetrieben? Dann zitiere ichdie Readme:

> The adapter is proofed to work very well with all devices that are "always in wifi". Devices that only come online when there is an event, send their data and go offline again are not supported. This means that battery powered devices usually DO NOT work!

**Comment by elzershark** [comment]
Bei offline Geräte wird "im Moment?" die IP nicht mit übermittelt. Heute... 3.11. über github  den Tuya Adapter installieren (über die Katze) . Dann das Rot eingetragene zusätzlich eintragen. Dann funktionieren Sie wieder. --> https://github.com/Apollon77/ioBroker.tuya/issues/221#issuecomment-702392636

**Comment by Apollon77** [comment]
Es geht ja genau das rum das dieses manuelle editoeren NICHT mehr nötig sein soll ... !!! :-)

Also geht es nurn "out of the box" oder nucht mit manuellen Änderungen?

**Comment by elzershark** [comment]
> Hallo meine LSC Smart Door Sensoren werden nur mit dem einlese State angezeigt beim öffnen und schließen wird der Status nicht geändert im Iobroker

Kann sein das es bald gelöst wird.
Wenn das Gerät neu gekauft wurde... 
Es ist ein Batterie betriebenes Gerät. Da ändern sich keine States. Die States werden einfach nur aktualisiert, wenn der Melder sich "meldet". Da durch erkennt man, das etwas passiert ist. Es wird aber nichts von true/false geschaltet. Das ist normal.

**Comment by B4unty** [comment]
> > Hallo meine LSC Smart Door Sensoren werden nur mit dem einlese State angezeigt beim öffnen und schließen wird der Status nicht geändert im Iobroker
> 
> Kann sein das es bald gelöst wird.
> Wenn das Gerät neu gekauft wurde...
> Es ist ein Batterie betriebenes Gerät. Da ändern sich keine States. Die States werden einfach nur aktualisiert, wenn der Melder sich "meldet". Da durch erkennt man, das etwas passiert ist. Es wird aber nichts von true/false geschaltet. Das ist normal.

Schön wehre es wen das gehen würde den die sind so günstig und lokal zu bekommen

**Comment by Apollon77** [comment]
Ja geht aber nicht. die sind so kurz online - den exakten zeitpuntk zu erwischen ist der 6er im Lotto

**Comment by elzershark** [comment]
Für Batteriebetriebene Geräte würde ich Zigbee nehmen. W-Lan dauert auch viel zu lange, bis die reagieren.
Ansonsten geht es nur manuell die IP und die Versionsnummer einzutragen.
Aber irgend was muss sich geändert haben. Diese Geräte gingen vorher.
