### ISSUE TITLE
Willkürliches schalten von Steckdosen

### ISSUE THREAD

**Issue by Jastroger** [Apollon77/ioBroker.tuya#22]
Hi Ingo,
ich bin ungern der Issue Schreiberling allerdings dieser hier hält mich von der Nutzung des Tuya Adapters ab.

Das Problem besteht darin, dass meine Steckdosen willkürlich ein und aus schalten. Das ist besonders bei Steckdosen mir Nachttisch Lampen nervtötend....Um drei Uhr morgens.  😉 

Tuya Adapter ausschalten behebt das Problem. Zusätzlich ist noch der Alexa Skill aktiv sowie die Smart Life App aktiv. Diese sind nicht die Ursache. 

Vermutlich geht es in Richtung Status Abfragen. Any Ideas?

Bezüglich meines Supports zu den minor issues deiner anderen Projekte - ich bin gerade etwas unter Wasser bei meinen anderen Projekten. Sobald ich die in der Reihe hab komme ich mit Pull-Requests unterstützend dazu. 

Gruß Jan

**Comment by lug-gh** [comment]
Kann es bestätigen, habe das selbe Problem! Aber den Alexa Skill habe ich nicht

**Comment by Apollon77** [comment]
Dann bitte mal tuya auf debug log setzen und dann log senden wenn das passiert.

**Comment by Apollon77** [comment]
Der Adapter schaltet and ich von sich aus nur wenn ein State auch als Kommando gesetzt wird.

**Comment by lug-gh** [comment]
Habe jetzt einfach Tasmota drauf geflasht, dann hab ich auch den Stress mit der Smart Life App nicht mehr..
https://github.com/ct-Open-Source/tuya-convert
https://blakadder.github.io/templates/nx-sm200.html

Danke Trotzdem ;)

**Comment by Apollon77** [comment]
Ok, plesse reopen with more debug data. Without infos I can not do anything
