### ISSUE TITLE
Allow overriding Tuya Proxy IP

### ISSUE THREAD

**Issue by Subtixx** [Apollon77/ioBroker.tuya#226]
Implement overwriting the ip because if it is running in a docker container it takes the container ip

**Comment by Apollon77** [comment]
Please provide more detaisl on what you need? In fact you need to make sure that the UDP packages are available in the container

**Comment by Subtixx** [comment]
A field to override the IP of the proxy like alexa 2.0

![https://i.imgur.com/3fGTvhs.png](https://i.imgur.com/3fGTvhs.png)

**Comment by Apollon77** [comment]
Aahhhh ... the proxy ...

**Comment by Apollon77** [comment]
I'm not sure if this will work, we have same issues in shelly too and here the advice is 

> If you use ioBroker in a docker container, the container has to run in host or macvlan modus

**Comment by Apollon77** [comment]
I thought again about that and honestly ... I do not see any need. The adapter will listen on the configured port as proxy or for the certificate. SO yopu just need to forward these configured ports to be reachable from outside. The only thing that you then need to do manually is getting the URl for the certificate ... which will be "http://<external IP>:webPort/ca.pem" ... so the QR code from admin will not work - this is all!!

**Comment by felge1965** [comment]
My iobroker has 3 network interfaces. (ens32, ens33 and ens35). Ens32 is the admin interface with 192.168.x.y. ens33 is a smart home LAN interface with 172.16.x.y. ens35 is a smart home WLAN interface with 172.20.x.y. The Tuya devices are on the ens35 interface. The proxy always starts with the ens32's IP. Can I enter my IP for the proxy somewhere in main.js?

**Comment by Apollon77** [comment]
As said the only benefit such a field would bring is for the "certificate download QR Code/URL ... simply replace it there manually. The proxy way will be deprecated soon, so I will close this here as "won't do"
