### ISSUE TITLE
Device can not be controlled

### ISSUE THREAD

**Issue by olipanis** [Apollon77/ioBroker.tuya#227]
The device was added via the proxy, this works.
Tried to set the switch to true, nothing happens.

State: 2 Geräte im Netzwerk gefunden, 0 Geräte verbunden, 2 mit bekanntem Schema, 2 initialisiert für Echtzeit-Updates und zur Steuerung

see the log attached

`

tuya.0 | 2020-10-21 21:49:23.619 | info | (1742) 13807035d8bfc0029576: None of the discovered devices matches :-(
-- | -- | -- | --
tuya.0 | 2020-10-21 21:49:23.613 | info | (1742) bf8315d72f1edf0699zzjo: None of the discovered devices matches :-(
tuya.0 | 2020-10-21 21:49:23.160 | info | (1742) {"schemaExt":"[{\"complexType\":\"\",\"id\":1,\"inputStyle\":\"\",\"inputType\":\"plain\"},{\"complexType\":\"\",\"id\":9,\"inputStyle\":\"\",\"inputType\":\"plain\"}]","schema":"[{\"mode\":\"
tuya.0 | 2020-10-21 21:49:23.159 | info | (1742) new Schema added for product type gbm9ata1zrzaez4a. Please send next line from logfile on disk to developer!
tuya.0 | 2020-10-21 21:49:23.089 | info | (1742) {"schemaExt":"[{\"complexType\":\"\",\"id\":1,\"inputStyle\":\"\",\"inputType\":\"\"},{\"complexType\":\"\",\"id\":9,\"inputStyle\":\"\",\"inputType\":\"countdown\"},{\"complexType\":\"\",\"id
tuya.0 | 2020-10-21 21:49:23.088 | info | (1742) new Schema added for product type fbvia0apnlnattcy. Please send next line from logfile on disk to developer!

`

**Comment by necotec** [comment]
In Issue #218 gibt es einen Workaround 😉

**Comment by olipanis** [comment]
Es hat bei mir leider noch nie funktioniert, deswegen habe ich leider kein backup das helfen würde.
Aber danke fürs verlinken.

**Comment by necotec** [comment]
Scrolle etwas weiter nach unten. Da habe ich ein Bild verlinkt. Da siehst du was du ändern musst, damit die Geräte erkannt werden. Und beachte, dass du eine Spezielle Version der App benötigst.

**Comment by olipanis** [comment]
danke, funktioniert noch immer nicht bei mir leider. oder mache ich etwas falsch?
![io](https://user-images.githubusercontent.com/4749824/96994112-8049da00-152c-11eb-90e3-07561837e857.PNG)

**Comment by Apollon77** [comment]
Ja du editierst das falschw object! Du musst quasi den "Folder" editieren (ohne ".ip")

**Comment by olipanis** [comment]
Danke! Funktioniert jetzt
