### ISSUE TITLE
Neues Schema

### ISSUE THREAD

**Issue by olli1986** [Apollon77/ioBroker.tuya#228]
Hi,

follgende Meldung habe ich in dem Log vom iobroker.
Hier bei geht es um eine Splitklimaanlage.
 
```
tuya.0 | 2020-10-27 19:30:54.041 | info | (31079) 33051602e0980600312e: None of the discovered devices matches :-(
tuya.0 | 2020-10-27 19:30:53.040 | info | (31079) {"schemaExt":"[]","schema":"[{\"mode\":\"rw\",\"code\":\"Power\",\"name\":\"开关\",\"property\":{\"type\":\"bool\"},\"iconname\":\"icon-dp_power\",\"id\":1,\"type\":\"obj\"},{\"mode\":\"rw\",\"
tuya.0 | 2020-10-27 19:30:53.038 | info | (31079) new Schema added for product type hw50w7qvxluhslkk. Please send next line from logfile on disk to developer!
```

Gruß Olli

**Comment by necotec** [comment]
Hallo,

hast du bereits Issue #221 befolgt?

**Comment by olli1986** [comment]
Hi necotec,

jetzt ja ;-)

Hatte es mir zwar angeschaut, aber völlig auf dem Schlauch gestanden, jetzt noch mal in Ruhe mir das alles übersetzt mit Google und jetzt läuft es, manchmal kann es so einfach sein.
Danke für den Tipp.

Gruß Olli

**Comment by Apollon77** [comment]
device will be in next update
