### ISSUE TITLE
Also allow "Alternative Linking way"?

### ISSUE THREAD

**Issue by Apollon77** [Apollon77/ioBroker.tuya#229]
Should the adapter also support the alternative way?

https://github.com/codetheweb/tuyapi/blob/master/docs/SETUP.md#listing-tuya-devices-from-the-tuya-smart-or-smart-life-apps-highly-recommended

**Comment by SchneJoe23** [comment]
I followed this instruction and received name, id and key from tuya cli. So far so good. What do I have to do with this information? How do I add the device to iobroker tuya adapter?

**Comment by Apollon77** [comment]
Noone said that you need to do it that way ... The adapter only supports the official apps old versions right now

**Comment by SchneJoe23** [comment]
Ok, maybe I misunderstood. I have a similar problem like issue #221. I connected the Device (Gosund LED bulb WB4) with the described proxy method. It was found, but not connected. I will try the workaround in issue #221 again. Do you recommend to use 3.3.15 from iobroker or 3.4.0 from github?

**Comment by Apollon77** [comment]
try 3.4.x of adapter please

**Comment by necotec** [comment]
@Apollon77 I think, tomorrow I have a little bit of time. Then I test the latest Version of theadapter.

Do you need anything like LOGs?

**Comment by Apollon77** [comment]
only if it does not work. update and pot make new proxy sync

**Comment by Apollon77** [comment]
Also: https://github.com/tuya/tuya-homebridge

**Comment by Apollon77** [comment]
So, here wo go ... https://forum.iobroker.net/topic/59663/test-adapter-tuya-3-8-0

**Comment by Apollon77** [comment]
3.8.1
