### ISSUE TITLE
Problem mit Proyx Einstellung

### ISSUE THREAD

**Issue by newcompuhelp** [Apollon77/ioBroker.tuya#23]
Problem mit dem Tuya Adapter!
Seit heute Nacht sind alle Geräte aus dem Tuya Adapter verschwunden. Der Tuya Adapter läßt sich nicht mehr starten. Die Proxy Einstellungen können nicht gestartet werden. Wie kann man das Problem lösen. P.S ich verfüge über ein Andoid Smartphone.

**Comment by Apollon77** [comment]
Was ist denn heute Nacht so passiert? Was steht im Log?

**Comment by newcompuhelp** [comment]
Wie kann ich das Log denn auf den Zeitpunkt selektieren ?

**Comment by newcompuhelp** [comment]
Kann man da was mit anfangen ?
http://192.168.178.71:8089/log/file1/iobroker.2019-02-12.log

**Comment by newcompuhelp** [comment]
Ein erneutes starten der Proxy ist auch nach Neuinstallation des Adapters
nicht mehr möglich. Auch ein wechsel der Browser hat zu keinem Erfolg geführt.

**Comment by Apollon77** [comment]
Naja mit einem lokale Logfile Link kann ich nichts anfangen ...Auf der Platte unter /opt/iobroker/log/... findest Du das auch

**Comment by newcompuhelp** [comment]
Unabhänig vom Absturz des Adapters, aber warum kann man den Proxy nicht mehr starten????

**Comment by Apollon77** [comment]
Schon mal den ganzen rechner rebootet?

**Comment by newcompuhelp** [comment]
Ja alles gemacht - aber ich glaube jetzt worann es liegt - einer der letzten App Updats hat wohl die Lücke geschlossen die es dem Tuya Adapter ermöglichte dauf die Geräte zu zu greifen so jedenfall die Meinung
von einem anderen Nutzer !

**Comment by Apollon77** [comment]
Meinung oder gesichert und getestet? Glaube ich nämlich nicht. Der Adapter nutzt keine "Lücke" sonder geht ganz anders.

Wenn bei dir noch nicht mal der Proxy startet dann hast Du auch ein anderes Problem.

Kurz: Ich brauche Debug Log um irgendwas zu sagen

**Comment by Apollon77** [comment]
Any news here? Please reopen if you still have the problem
