### ISSUE TITLE
Keine Verbindung möglich - Probleme mit SmartLife v.3.21.5

### ISSUE THREAD

**Issue by MrJur1** [Apollon77/ioBroker.tuya#237]
Hallo, ich bin noch recht neu was das Thema ioBroker angeht. Habe nun versucht der Adapter zum laufen zu bringen - leider ohne erfolg. Habe alles entsprechend der Anleitung befolgt.

App Version: SmartLife App (iOS) v.3.21.5

Log:
> tuya.0 | 2020-12-04 00:09:40.815 | warn | (7967) It seems that you use an unsupported App version of Tuya App! Please see Admin Infos and GitHub Readme for details!
-- | -- | -- | --
tuya.0 | 2020-12-04 00:09:40.460 | warn | (7967) It seems that you use an unsupported App version of Tuya App! Please see Admin Infos and GitHub Readme for details!
tuya.0 | 2020-12-04 00:09:25.236 | error | (7967) Error: socket hang up at TLSSocket.onSocketClose (_tls_wrap.js:794:23) at TLSSocket.emit (events.js:203:15) at TLSSocket.EventEmitter.emit (domain.js:448:20) at _handle.close (n
tuya.0 | 2020-12-04 00:09:25.233 | error | (7967) SSL-Proxy ERROR: Error: socket hang up
tuya.0 | 2020-12-04 00:09:25.158 | error | (7967) Error: socket hang up at TLSSocket.onSocketClose (_tls_wrap.js:794:23) at TLSSocket.emit (events.js:203:15) at TLSSocket.EventEmitter.emit (domain.js:448:20) at _handle.close (n
tuya.0 | 2020-12-04 00:09:25.142 | error | (7967) SSL-Proxy ERROR: Error: socket hang up
tuya.0 | 2020-12-04 00:09:20.146 | error | (7967) Error: socket hang up at TLSSocket.onSocketClose (_tls_wrap.js:794:23) at TLSSocket.emit (events.js:203:15) at TLSSocket.EventEmitter.emit (domain.js:448:20) at _handle.close (n
tuya.0 | 2020-12-04 00:09:20.144 | error | (7967) SSL-Proxy ERROR: Error: socket hang up
tuya.0 | 2020-12-04 00:09:20.067 | error | (7967) Error: socket hang up at TLSSocket.onSocketClose (_tls_wrap.js:794:23) at TLSSocket.emit (events.js:203:15) at TLSSocket.EventEmitter.emit (domain.js:448:20) at _handle.close (n
tuya.0 | 2020-12-04 00:09:20.063 | error | (7967) SSL-Proxy ERROR: Error: socket hang up
tuya.0 | 2020-12-04 00:09:15.052 | error | (7967) Error: socket hang up at TLSSocket.onSocketClose (_tls_wrap.js:794:23) at TLSSocket.emit (events.js:203:15) at TLSSocket.EventEmitter.emit (domain.js:448:20) at _handle.close (n
tuya.0 | 2020-12-04 00:09:15.050 | error | (7967) SSL-Proxy ERROR: Error: socket hang up
tuya.0 | 2020-12-04 00:09:12.930 | warn | (7967) It seems that you use an unsupported App version of Tuya App! Please see Admin Infos and GitHub Readme for details!
tuya.0 | 2020-12-04 00:09:12.905 | warn | (7967) It seems that you use an unsupported App version of Tuya App! Please see Admin Infos and GitHub Readme for details!
tuya.0 | 2020-12-04 00:09:11.510 | warn | (7967) It seems that you use an unsupported App version of Tuya App! Please see Admin Infos and GitHub Readme for details!
tuya.0 | 2020-12-04 00:09:10.834 | warn | (7967) It seems that you use an unsupported App version of Tuya App! Please see Admin Infos and GitHub Readme for details!
tuya.0 | 2020-12-04 00:09:10.812 | error | (7967) Error: socket hang up at TLSSocket.onSocketClose (_tls_wrap.js:794:23) at TLSSocket.emit (events.js:203:15) at TLSSocket.EventEmitter.emit (domain.js:448:20) at _handle.close (n
tuya.0 | 2020-12-04 00:09:10.809 | error | (7967) SSL-Proxy ERROR: Error: socket hang up
tuya.0 | 2020-12-04 00:09:10.793 | warn | (7967) It seems that you use an unsupported App version of Tuya App! Please see Admin Infos and GitHub Readme for details!
tuya.0 | 2020-12-04 00:09:10.773 | warn | (7967) It seems that you use an unsupported App version of Tuya App! Please see Admin Infos and GitHub Readme for details!
>

**Comment by Apollon77** [comment]
Read readme, check the Big bold note in admin beside the warning symbol:

The Adapter only works with Tuya and compatible apps as long as their version is <3.14 (!!)
