### ISSUE TITLE
tuya updater ioBroker lampe indicator.reachable = false

### ISSUE THREAD

**Issue by Sportsmen78** [Apollon77/ioBroker.tuya#239]
Hallo zusammen!

Ich hoffe, ihr könnt mir weiterhelfen. Bin neu im "Smart-Sektor". Ich habe den einen Raspberry Pi 4, ioBroker, viele HMIP-Geräte und 3 Teckin (2 Steckdose und eine Glühampe - farbe verstellbar). Alles läuft bei mir mittels Homekit in der Home-App. Das Meiste funktioniert auch. Aber die Glühlampe von Teckin bekomme ich nicht an. Die Geräte habe ich mittels dem Tuya Adapter über die Proxy Funktion eingebunden. Wenn ich das Gerät über die home app einschaltet steht auch im ioBroker  der Status "switch_led" auf true und ändert sich, wenn ich es wieder aus schalte folgerichtig auf false. Jedoch passiert an der Lampe nix. Der Wert Device online Status (Indikator.reachable) steht auf false. Das ist wohl der Knackpunkt, bekomme es aber nicht auf true. Die beiden Steckdosen stehen bei diesem Wert auf true und da funktioniert auch alles. Hat jemand eine Idee, wie ich die Lampe zum Laufen bekomme? Vielen Dank vorab und viele Grüße
Sebastian

**Comment by Apollon77** [comment]
Alles ist erfolgreich mit der App und Proxy gesynct? Was steht auf der Adapter-Admin Seite? Was steht im Log wenn der Adapter startet?

**Comment by Sportsmen78** [comment]
Ich habe die "STL Smart Home" App, damit funktioniert alles ohne Probleme. (Habe nicht die Standard App "Smart Home", weil die neuere Version wohl nicht mit dem Tuya-Adapter kompatibel ist). In der Adapterkonfiguration von Tuya stand beim syncen Status: 3 Geräte im Netzwerk gefunden, 3 Geräte verbunden, 3 mit bekanntem Schema, 3 Initialisiert für Echtzeit-Updates. Dann gehe ich zB auf Objekte, steuere mit dem Handy die Lampe, switch-status schaltet korrekt auf true(device online Status weiterhin false). Wenn ich zurück auf die Adapterkonfiguration von Tuya gehe, steht: 3 Geräte im Netzwerk gefunden, **2 Geräte verbunden**, 3 mit bekanntem Schema, 3 Initialisiert für Echtzeit-Updates. Der Switch Status kann aber weiterhin auf true und false mittels handy (oder direkt im ioBroker) geschaltet werden.

Unter Info-Meine Adapter-Tuya steht: "Es sind keine Fehler, Probleme oder Anforderungen für den ausgewählten Adapter bekannt." Ich habe Version 3.4.3. installiert.

Ich kenne mich wirklich noch nicht so gut aus, ich habe jetzt den Tuya - Adapter neu gestartet und das Log schreibt folgendes:

tuya.0 | 2020-12-13 15:11:08.974 | info | (1788) Listen for encrypted local Tuya devices on port 6667
-- | -- | -- | --
tuya.0 | 2020-12-13 15:11:08.973 | info | (1788) Listen for local Tuya devices on port 6666
tuya.0 | 2020-12-13 15:11:08.965 | info | (1788) Existing devices initialized
tuya.0 | 2020-12-13 15:11:08.964 | info | (1788) bf6abb2ba6e182db3esntn Init with IP=192.168.178.49, Key=41ad673759c43aef, Version=3.3
tuya.0 | 2020-12-13 15:11:08.917 | info | (1788) bfa7276f10fe435583obhk Init with IP=192.168.178.48, Key=5a47c5bec722c081, Version=3.3
tuya.0 | 2020-12-13 15:11:08.907 | info | (1788) 2615658084cca8900b3e Init with IP=192.168.178.59, Key=152ad034031e1206, Version=3.3
tuya.0 | 2020-12-13 15:11:08.675 | info | (1788) starting. Version 3.4.3 in /opt/iobroker/node_modules/iobroker.tuya, node: v10.23.0, js-controller: 3.1.6



tuya.0 | 2020-12-13 15:11:08.974 | info | (1788) Listen for encrypted local Tuya devices on port 6667
-- | -- | -- | --
tuya.0 | 2020-12-13 15:11:08.973 | info | (1788) Listen for local Tuya devices on port 6666
tuya.0 | 2020-12-13 15:11:08.965 | info | (1788) Existing devices initialized
tuya.0 | 2020-12-13 15:11:08.964 | info | (1788) bf6abb2ba6e182db3esntn Init with IP=192.168.178.49, Key=41ad673759c43aef, Version=3.3
tuya.0 | 2020-12-13 15:11:08.917 | info | (1788) bfa7276f10fe435583obhk Init with IP=192.168.178.48, Key=5a47c5bec722c081, Version=3.3
tuya.0 | 2020-12-13 15:11:08.907 | info | (1788) 2615658084cca8900b3e Init with IP=192.168.178.59, Key=152ad034031e1206, Version=3.3
tuya.0 | 2020-12-13 15:11:08.675 | info | (1788) starting. Version 3.4.3 in /opt/iobroker/node_modules/iobroker.tuya, node: v10.23.0, js-controller: 3.1.6

Danke für eure Hilfe!
Gruß 
Sebastian

**Comment by Apollon77** [comment]
Ist das Log echt alles? Schalt doch mal Loging auf Debug (Admin - Instanzen - Expertenmodus - Spalte Logstufe). Was steht denn dann so - vor allem beim start und wenn du schalten willst
ABer bevor beim gerät nicht ein connected true steht brauchst du schalten gar nicht erst versuchen :-)

**Comment by Sportsmen78** [comment]
Hier das Log-Ergebnis im "Debug-Modus". Habe nach der Meldung mal die App aufm Handy geschlossen und versucht, dass Gerät über die HomeApp zu starten...


tuya.0 | 2020-12-15 21:52:06.654 | debug | (32083) 2615658084cca8900b3eDevice communication not initialized ...
-- | -- | -- | --
tuya.0 | 2020-12-15 21:52:06.653 | debug | (32083) 2615658084cca8900b3e onChange triggered for 20 and value false
tuya.0 | 2020-12-15 21:52:06.652 | debug | (32083) stateChange tuya.0.2615658084cca8900b3e.20 {"val":false,"ack":false,"ts":1608065526648,"q":0,"from":"system.adapter.yahka.0","user":"system.user.admin","lc":1608065526648}
tuya.0 | 2020-12-15 21:51:58.263 | debug | (32083) 2615658084cca8900b3eDevice communication not initialized ...
tuya.0 | 2020-12-15 21:51:58.262 | debug | (32083) 2615658084cca8900b3e onChange triggered for 20 and value true
tuya.0 | 2020-12-15 21:51:58.260 | debug | (32083) stateChange tuya.0.2615658084cca8900b3e.20 {"val":true,"ack":false,"ts":1608065518256,"q":0,"from":"system.adapter.yahka.0","user":"system.user.admin","lc":1608065518256}
tuya.0 | 2020-12-15 21:51:38.337 | debug | (32083) stateChange tuya.0.2615658084cca8900b3e.online {"val":false,"ack":true,"ts":1608065498333,"q":0,"from":"system.adapter.tuya.0","user":"system.user.admin","lc":1607292540485}
tuya.0 | 2020-12-15 21:51:38.327 | debug | (32083) 2615658084cca8900b3e: Disconnected from device
tuya.0 | 2020-12-15 21:51:38.324 | debug | (32083) 2615658084cca8900b3e: Error from device (3): App still open on your mobile phone? Error: Error from socket
tuya.0 | 2020-12-15 21:50:35.215 | debug | (32083) stateChange tuya.0.2615658084cca8900b3e.online {"val":false,"ack":true,"ts":1608065435209,"q":0,"from":"system.adapter.tuya.0","user":"system.user.admin","lc":1607292540485}
tuya.0 | 2020-12-15 21:50:35.206 | debug | (32083) 2615658084cca8900b3e: Disconnected from device
tuya.0 | 2020-12-15 21:50:35.204 | debug | (32083) 2615658084cca8900b3e: Error from device (2): App still open on your mobile phone? Error: Error from socket
tuya.0 | 2020-12-15 21:49:32.098 | debug | (32083) stateChange tuya.0.2615658084cca8900b3e.online {"val":false,"ack":true,"ts":1608065372093,"q":0,"from":"system.adapter.tuya.0","user":"system.user.admin","lc":1607292540485}
tuya.0 | 2020-12-15 21:49:32.086 | debug | (32083) 2615658084cca8900b3e: Disconnected from device
tuya.0 | 2020-12-15 21:49:32.084 | debug | (32083) 2615658084cca8900b3e: Error from device (1): App still open on your mobile phone? Error: Error from socket
tuya.0 | 2020-12-15 21:48:28.980 | debug | (32083) stateChange tuya.0.2615658084cca8900b3e.online {"val":false,"ack":true,"ts":1608065308973,"q":0,"from":"system.adapter.tuya.0","user":"system.user.admin","lc":1607292540485}
tuya.0 | 2020-12-15 21:48:28.969 | debug | (32083) 2615658084cca8900b3e: Disconnected from device
tuya.0 | 2020-12-15 21:48:28.966 | debug | (32083) 2615658084cca8900b3e: Error from device (0): App still open on your mobile phone? Error: Error from socket
tuya.0 | 2020-12-15 21:48:28.611 | debug | (32083) Discovered encrypted device and store for later usage: 192.168.178.48:49153 - 000055aa00000000000000130000009c00000000d09766676f3369eb10b5e9f132fd802a3073a79bd60de093a5b0f959d23b16005ec1b4b5e
tuya.0 | 2020-12-15 21:48:28.542 | debug | (32083) Discovered encrypted device and store for later usage: 192.168.178.49:49153 - 000055aa00000000000000130000009c00000000d09766676f3369eb10b5e9f132fd802a39777646e73c1504736b0876a41661e54f4a0c2c6
tuya.0 | 2020-12-15 21:48:26.309 | debug | (32083) bfa7276f10fe435583obhk: Ignore invalid data (Counter: 1)
tuya.0 | 2020-12-15 21:48:26.308 | debug | (32083) bfa7276f10fe435583obhk: Received data: {"1":null,"2":null,"3":null,"101":null,"102":null,"103":null}
tuya.0 | 2020-12-15 21:48:26.307 | debug | (32083) bfa7276f10fe435583obhk: Error from device (0): App still open on your mobile phone? json obj data unvalid
tuya.0 | 2020-12-15 21:48:25.925 | debug | (32083) stateChange tuya.0.bf6abb2ba6e182db3esntn.online {"val":true,"ack":true,"ts":1608065305908,"q":0,"from":"system.adapter.tuya.0","user":"system.user.admin","lc":1608065305908}
tuya.0 | 2020-12-15 21:48:25.923 | debug | (32083) stateChange tuya.0.info.connection {"val":true,"ack":true,"ts":1608065305908,"q":0,"from":"system.adapter.tuya.0","user":"system.user.admin","lc":1608065305908}
tuya.0 | 2020-12-15 21:48:25.922 | debug | (32083) bf6abb2ba6e182db3esntn: Ignore invalid data (Counter: 1)
tuya.0 | 2020-12-15 21:48:25.922 | debug | (32083) bf6abb2ba6e182db3esntn: Received data: {"1":null,"2":null,"3":null,"101":null,"102":null,"103":null}
tuya.0 | 2020-12-15 21:48:25.920 | debug | (32083) bf6abb2ba6e182db3esntn: Error from device (0): App still open on your mobile phone? json obj data unvalid
tuya.0 | 2020-12-15 21:48:25.914 | debug | (32083) connected set to true
tuya.0 | 2020-12-15 21:48:25.912 | debug | (32083) stateChange tuya.0.bfa7276f10fe435583obhk.online {"val":true,"ack":true,"ts":1608065305907,"q":0,"from":"system.adapter.tuya.0","user":"system.user.admin","lc":1608065305907}
tuya.0 | 2020-12-15 21:48:25.905 | debug | (32083) bf6abb2ba6e182db3esntn: Connected to device
tuya.0 | 2020-12-15 21:48:25.897 | debug | (32083) bfa7276f10fe435583obhk: Connected to device

**Comment by derherrgraf** [comment]
Ich habe glaub ich ein ähnliches/das gleiche Problem. Ich habe schon vor längerem einen Türsensor eingebunden. Allerdings gibt es mir keine Werte aus wegen `indicator.reachable = false`. In der Smart-Life App und auch in der Alexa App funktioniert der Sensor wie er soll. Wenn ich den Adapter neu starte bekomme ich das Log voll mit `(1409) 13600724840d8eae8870: None of the discovered devices matches :-(` (bestimmt 20 Mal). Das gerät ist aber sicher online.

Außerdem habe ich vor ca. 1 Woche ein 'rescan' aller Geräte gemacht, da ist es wieder rein gekommen aber eben unerreichbar.

**Comment by Apollon77** [comment]
Ssttoooop ... nicht jetzt Dinge mischen
@Sportsmen78 Hm ... log sagt das er keine Daten vom Gerät bekommt ... Das wird auch hier https://github.com/codetheweb/tuyapi/issues/389 diskutiert ... von daher kann ich da gerade nicht viel tun. Scheinbar ist (absichtlich ode runabsichtlich) das lokale Protokoll des Geräts kaputt ... :-( Die App fällt dann quasi auf die Could daten zurück, daher tuts dort. Der Adapter kann aber nur lokal verbinden.

@derherrgraf Gleiche Frage wie oben: Batteriedevice? Dann bitte Readme schauen .., sonst bitte Log posten. Bei vielen "None of the discovered devices matches" bitte den Proxy Sync wiederholen und in jedem Fall aktuellste Adapter Version nutzen!

**Comment by derherrgraf** [comment]
@Apollon77 Das mit der Batterie hab ich ganz überlesen :o Damit hat sich meine Frage geklärt.

**Comment by Apollon77** [comment]
@Sportsmen78 Mal noch eine Frage: Kannst DU bitte mal das object json posten von dem gerät ws immer diesen "json unvalid" fehler hatte (bfa7276f10fe435583obhk) ich will mal was schauen ...

Objekt posten geht: gehe unter objekte. Wähle den tuya.0.bfa7276f10fe435583obhk "ordner" aus ... hinten rechts auf den stuft klicken, dort Tab "Raw" und das json posten

**Comment by ali86x** [comment]
Ich habe ein ähnliches Problem wie @derherrgraf.
Mein Log wird alle paar Minuten von der Meldung "None of the discovered Devices matches" überflutet. 
Und es sind keine Batterie-Geräte (u.a. Rolladen Schalter etc.).
Online Status steht auf falsch, ist aber schaltbar. 
Neu mit Proxy synchronisiert, aber keine Verbesserung. 
@Apollon77 hast du ne Idee?
Log kann ich gerne nachreichen.

**Comment by ali86x** [comment]
[192.168.178.128_8081_log_iobroker-pi_file1_iobroker.current.log](https://github.com/Apollon77/ioBroker.tuya/files/8021479/192.168.178.128_8081_log_iobroker-pi_file1_iobroker.current.log)
