### ISSUE TITLE
Smart Wall Switch Unterstützung

### ISSUE THREAD

**Issue by DocGame69** [Apollon77/ioBroker.tuya#241]
Meinst du, das eine Unterstützung dieses Gerätes mäglich wäre?
Den Schalter nur für die Aservatenkammer zu bestellen wäre mir zu schade.
[https://de.aliexpress.com/item/1005001669799084.html?spm=a2g0o.productlist.0.0.177e3da2MecGmO&algo_pvid=783145ea-ff40-4878-96c2-658370dca857&algo_expid=783145ea-ff40-4878-96c2-658370dca857-0&btsid=2100bddd16092332193841731e3c74&ws_ab_test=searchweb0_0,searchweb201602_,searchweb201603_](url)

![SmartWallSwitch](https://user-images.githubusercontent.com/43096454/103305353-33dab900-4a0b-11eb-8edc-a5d28511d37d.JPG)

**Comment by Apollon77** [comment]
Der Adapter funktioniert vollständig generisch ... Es werden die Schemadaten aus der Tuya App ausgelesen und dann geht es an sich ... von daher sehe ich da spontan keine Probleme ... 100% sicherstellen kann ich es natürlich nicht.

**Comment by Apollon77** [comment]
BTW: Naja  ich habe mal überflogen und leider nicht erlesen können ob das überhaupt Tuya ist und welche App genutzt wird ...
