### ISSUE TITLE
cur_current and cur_power not updated anymore - add device Polling mechanism

### ISSUE THREAD

**Issue by Koalabaer** [Apollon77/ioBroker.tuya#242]
**Describe the bug**  
Proxy-sync done with step by step description. status (switch_1) of the plugs are shown and working in ioBroker. objects are constantly updated, but if it turn on or off the plugs, the cur_current and cur_power are not updated (stay on the last cosumption). Turned adapter to debug and nothing to see in the logs...

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.
![Screenshot](https://user-images.githubusercontent.com/14127529/103478704-cf33ab80-4dc8-11eb-9664-8d1c11c9fe88.PNG)

**Versions:**  
 - Adapter version: 3.5.2
 - JS-Controller version: 3.16
 - Node version: 12.13.0
 - Operating system: raspi 3b+ with ioBroker

**Comment by Koalabaer** [comment]
Used plugs: (https://www.amazon.de/gp/product/B07FTDG4B2/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1)
And done the proxy sync with MeMu on Windows - ioBroker show success and the cur_power etc. of the plugs seems working for a while... but not sure when it interrupts.

**Comment by Koalabaer** [comment]
Just redone the sync and the cur_current and cur_power are still having values and not turning to 0 when the plug is off...

![Screenshot2](https://user-images.githubusercontent.com/14127529/103478952-6c431400-4dca-11eb-9172-c9d9c05a6e43.PNG)

**Comment by Apollon77** [comment]
Values are updated when the device reports a change ... so if in this case the values "stay old" then the device is not updating them ... If you restart the adapter when it is turned off - are the values reset to 0 then?

**Comment by Koalabaer** [comment]
yes the will be set on 0 - works as designed? i thought they will be set on 0, if the device is turned off...

**Comment by Apollon77** [comment]
On start the adapter queries the initail values, afte rthat it gets push updates from the device on changes. It seems that exactly that push is not working when it is turned off. SO only option would be to introduce a "Polling interval" and request updates in a defined interval - but this still will come later as the change.

The adapter works generic, so a device specific handling is no option in my eyes

**Comment by Koalabaer** [comment]
hi Apollon, today i detected, that i got the updates only when the smart life app is running... 
(i synced it with MeMu and then it works for a time (dont know how long exactly) - when its not working anymore i open the smart life app on my iPhone or Android Tablet open the switch, which isn't working and suddenly i got the updates in ioBroker again. I not completly got it - can I never open the Smart Life App on my iPhone or Tablet when i have synced the app with Memu to get live updates?

**Comment by Apollon77** [comment]
thats strange ... but no idea how that device works. normally having app open occupies the local connection port and so adapter is not getting values. if adapter is connected then the app should use the cloud ...

**Comment by balzreber** [comment]
I have the exact same problem with this adapter: https://de.aliexpress.com/item/4001345668180.html?spm=a2g0s.9042311.0.0.27424c4d47px1z. I was able to connect it with the adapter without problems. Switching works fine. But I only get the meter values updated when I have the app open.

<img width="2356" alt="Screenshot 2021-01-20 at 04 01 41" src="https://user-images.githubusercontent.com/9654244/105121510-9720ae00-5ad4-11eb-82e4-b042b091d62a.png">

Versions:
Adapter version: 3.5.2
JS-Controller version: 3.2.0
Node version: 12.20.0
System: Raspi 3b+

**Comment by Apollon77** [comment]
Then sorry but I need to propose an adjustment of your phrasing ... you have this problem with YOUR SPECIFIC DEVICE.

The adapter can not do anything when the device do not send the data, so as said above we only could add something like a "Polling interval" (but we also know that devices tend to get unstable when queried too often ...

**Comment by balzreber** [comment]
@Apollon77 Sorry, you are right. With "this adapter" I meant the device I have, not your adapter.

Do you know how the App (Smart Life in my case) does that? Do they have another connection to the device you don't have in the adapter? Or do they just do polling?

**Comment by Koalabaer** [comment]
Hi together, my current situation is, that i get all updates of the cur_current and cur_power when i turn on the  devices, which is plugged in (e.g. Washing machine) - so i got every 5 seconds updates... but when the wasching machine is done and the cur_current and cur_power should be 0, it not update this value in the adapter. The adapter updates it, when i open the smart Life App on my phone - then imidiatly the iobroker adapter gets the update to 0 too. @Apollon77  Do you have a clue what this could be? do you still think it is due to my used hardware?

**Comment by Apollon77** [comment]
As said above I think it is simply how the device is doing it. In fact the only way could be to add a polling mechanism that triggers getting values if no event came in since time X ... still far away from accurate but could work roughly.
I think as soon as the app via clould requests a value then it is also "triggered locally"

**Comment by balzreber** [comment]
+1 fot the adapter polling mechanism

**Comment by RedStar1973** [comment]
I have a similar  Problem, but with my tyua water heater, it stopps getting any reading after a while, would like to See a reading polling Option.

**Comment by stevoh6** [comment]
Hi, there is couple of details why only "local" power statistics doesn't work and also possible solution with command 18.
codetheweb/tuyapi#417
jasonacox/tinytuya#8

**Comment by Apollon77** [comment]
Thank you!
We also rely on tuyapi ... so if then command 18 needs support in there ...

**Comment by mcbirne** [comment]
I have the same problem. Since a few days I don't get any update of the cur_power value.

**Comment by Apollon77** [comment]
In general please try GitHub version ... are values coming again?

**Comment by Apollon77** [comment]
Please try GitHub version

**Comment by Apollon77** [comment]
Can anyone please give the github version a try ?

**Comment by mcbirne** [comment]
I can test it on Tuesday. I will give you a feedback

**Comment by bierking** [comment]
Hello, frustrating, 2 data sets were synchronised after proxy refresh and then nothing more. Switch worked. a look at github worth ! 
I am currently testing github version, it looks great. Adapter Sync works consistently as before.  Great work. thx

**Comment by Apollon77** [comment]
@bierking this issue is not about sync in general it is about power values in specifics

I release new version as 3.6.0

**Comment by mcbirne** [comment]
With the 3.6 I have the same problem. The cur_power values doesn't refresh. My workaround is to reboot the adapter every minute.

**Comment by Apollon77** [comment]
Can you please let the adapter run. The polling interval is at 30 or 60s by default ... so could it be that you just not wait long enoght? Alternatively change the polling interval (but not too low!). Please provide a debug log

**Comment by mcbirne** [comment]
Sorry, it was my fault. Maybe I don't wait enough. I install it completely new and also sync it again with the app and now it works.

**Comment by mcbirne** [comment]
Thank you very much

**Comment by Klugschieter** [comment]
Sorry, damned old thread ...
But the same problem, except that I have to striktly open the "Energy" Tab of the switch in the SmartLife App, before any actual cur_current and cur_power data is shown in ioBroker. 
Are there any changes made meanwhile or am I just too stupid for it?
