### ISSUE TITLE
Control Wake Up Light

### ISSUE THREAD

**Issue by Koalabaer** [Apollon77/ioBroker.tuya#243]
**Is your feature request related to a problem? Please describe.**
Tuya-Adapter shows all values of the wake up light (see screenshot) and instantly updates them if I push a button directly at the wake up light. But if i change a object value (e.g. led on true) the light dont turn on. 

Would it be possible to control the wake up light with the tuya adapter? Also to set the clock1? 
(I tried everything but nothting is working - see log-screenshot)

![WakeUpLight](https://user-images.githubusercontent.com/14127529/103579424-93880700-4ed8-11eb-9536-6a6c6a5cc924.png)

Log:
![log](https://user-images.githubusercontent.com/14127529/103579654-f5e10780-4ed8-11eb-9a01-ef779fb671e8.PNG)

Used Wake Up Light
[https://www.amazon.de/gp/product/B07SDD7SPF/ref=ppx_yo_dt_b_asin_title_o01_s01?ie=UTF8&psc=1](https://www.amazon.de/gp/product/B07SDD7SPF/ref=ppx_yo_dt_b_asin_title_o01_s01?ie=UTF8&psc=1)

**Comment by Koalabaer** [comment]
Used wake up light:
[](https://www.amazon.de/gp/product/B07SDD7SPF/ref=ppx_yo_dt_b_asin_title_o01_s01?ie=UTF8&psc=1)

**Comment by Apollon77** [comment]
The log tells that the device disconnects ... so sorry, no idea whats up there. tried to restart (power off(on) the device?

**Comment by Koalabaer** [comment]
Hi Apollon,
it is working now - it is updating the status and i can control it for the simple values - just restarted the device. 

Would it be possible to "translate" the values as shown on the screenshot from the chinese symbols to readable?

**Comment by Koalabaer** [comment]
Or could you help me to translate the symbols? I just found out, that i can read the set sleep time and also can set it, but it only showing me symbols and i dont know how to translate it:

It is looking like this:
����

Notepad++ shows this (see screenshot)
![setTime](https://user-images.githubusercontent.com/14127529/104018657-77c38000-51ba-11eb-8c73-657bc6c6037a.PNG)

If I read the given text by different set times to wake up and paste them to set the alarm it sets the alarm like 34:07 o'clock... 

Could you give me a hint what to do?

BR and thanks

Koala

**Comment by Apollon77** [comment]
the chinese text is JUST the "Unit", so do not take care. The other field seems to have a "binary" content ... no idea how to parse that. try to read the state and see what it brings you here
