### ISSUE TITLE
Sync funktioniert nicht mehr

### ISSUE THREAD

**Issue by deepminds83** [Apollon77/ioBroker.tuya#245]
In der aktuellen Adapterversion (3.5.2) funktioniert der Sync mit Start Life (v3.12.6) nicht mehr.
In SmartLife kommt die Meldung tuya incorrect local timer,please correct it,50502

Im iobroker Log stehen folgende fehler:
`
4537)  Error: 3065149904:error:14094416:SSL routines:ssl3_read_bytes:sslv3  alert certificate  unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert  number 46
--
tuya.0 | 2021-01-11 18:30:37.521 | error | (4537) SSL-Proxy ERROR: Error: 3065149904:error:14094416:SSL  routines:ssl3_read_bytes:sslv3 alert certificate  unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert  number 46
tuya.0 | 2021-01-11 18:30:36.554 | error | (4537) Error: 3065149904:error:14094416:SSL  routines:ssl3_read_bytes:sslv3 alert certificate  unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert  number 46
tuya.0 | 2021-01-11 18:30:36.554 | error | (4537) SSL-Proxy ERROR: Error: 3065149904:error:14094416:SSL  routines:ssl3_read_bytes:sslv3 alert certificate  unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert  number 46
tuya.0 | 2021-01-11 18:30:36.543 | error | (4537) Error: 3065149904:error:14094416:SSL  routines:ssl3_read_bytes:sslv3 alert certificate  unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert  number 46
tuya.0 | 2021-01-11 18:30:36.543 | error | (4537) SSL-Proxy ERROR: Error: 3065149904:error:14094416:SSL  routines:ssl3_read_bytes:sslv3 alert certificate  unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert  number 46
tuya.0 | 2021-01-11 18:30:36.487 | error | (4537) Error: 3065149904:error:14094416:SSL  routines:ssl3_read_bytes:sslv3 alert certificate  unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert  number 46
tuya.0 | 2021-01-11 18:30:36.486 | error | (4537) SSL-Proxy ERROR: Error: 3065149904:error:14094416:SSL  routines:ssl3_read_bytes:sslv3 alert certificate  unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert  number 46
tuya.0 | 2021-01-11 18:30:36.267 | error | (4537) Error: 3065149904:error:14094416:SSL  routines:ssl3_read_bytes:sslv3 alert certificate  unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert  number 46
tuya.0 | 2021-01-11 18:30:36.267 | error | (4537) SSL-Proxy ERROR: Error: 3065149904:error:14094416:SSL  routines:ssl3_read_bytes:sslv3 alert certificate  unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert  number 46
tuya.0 | 2021-01-11 18:30:36.078 | error | (4537) Error: 3065149904:error:14094416:SSL  routines:ssl3_read_bytes:sslv3 alert certificate  unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert  number 46
tuya.0 | 2021-01-11 18:30:36.077 | error | (4537) SSL-Proxy ERROR: Error: 3065149904:error:14094416:SSL  routines:ssl3_read_bytes:sslv3 alert certificate  unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert  number 46
tuya.0 | 2021-01-11 18:30:36.073 | error | (4537) Error: 3065149904:error:14094416:SSL  routines:ssl3_read_bytes:sslv3 alert certificate  unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert  number 46
tuya.0 | 2021-01-11 18:30:36.072 | error | (4537) SSL-Proxy ERROR: Error: 3065149904:error:14094416:SSL  routines:ssl3_read_bytes:sslv3 alert certificate  unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert  number 46
tuya.0 | 2021-01-11 18:30:36.071 | error | (4537) Error: 3065149904:error:14094416:SSL  routines:ssl3_read_bytes:sslv3 alert certificate  unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert  number 46
tuya.0 | 2021-01-11 18:30:36.070 | error | (4537) SSL-Proxy ERROR: Error: 3065149904:error:14094416:SSL  routines:ssl3_read_bytes:sslv3 alert certificate  unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert  number 46
tuya.0 | 2021-01-11 18:30:36.061 | error | (4537) Error: 3065149904:error:14094416:SSL  routines:ssl3_read_bytes:sslv3 alert certificate  unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert  number 46
tuya.0 | 2021-01-11 18:30:36.060 | error | (4537) SSL-Proxy ERROR: Error: 3065149904:error:14094416:SSL  routines:ssl3_read_bytes:sslv3 alert certificate  unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert  number 46
tuya.0 | 2021-01-11 18:30:35.885 | error | (4537) Error: 3065149904:error:14094416:SSL  routines:ssl3_read_bytes:sslv3 alert certificate  unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert  number 46
tuya.0 | 2021-01-11 18:30:35.884 | error | (4537) SSL-Proxy ERROR: Error: 3065149904:error:14094416:SSL  routines:ssl3_read_bytes:sslv3 alert certificate  unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert  number 46
tuya.0 | 2021-01-11 18:30:35.876 | error | (4537) Error: 3065149904:error:14094416:SSL  routines:ssl3_read_bytes:sslv3 alert certificate  unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert  number 46
tuya.0 | 2021-01-11 18:30:35.875 | error | (4537) SSL-Proxy ERROR: Error: 3065149904:error:14094416:SSL  routines:ssl3_read_bytes:sslv3 alert certificate  unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert  number 46
tuya.0 | 2021-01-11 18:30:35.852 | error | (4537) Error: 3065149904:error:14094416:SSL  routines:ssl3_read_bytes:sslv3 alert certificate  unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert  number 46
tuya.0 | 2021-01-11 18:30:35.852 | error | (4537) SSL-Proxy ERROR: Error: 3065149904:error:14094416:SSL  routines:ssl3_read_bytes:sslv3 alert certificate  unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert  number 46
tuya.0 | 2021-01-11 18:30:35.848 | error | (4537) Error: 3065149904:error:14094416:SSL  routines:ssl3_read_bytes:sslv3 alert certificate  unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert  number 46
tuya.0 | 2021-01-11 18:30:35.847 | error | (4537) SSL-Proxy ERROR: Error: 3065149904:error:14094416:SSL  routines:ssl3_read_bytes:sslv3 alert certificate  unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert  number 46
tuya.0 | 2021-01-11 18:30:35.783 | error | (4537) Error: 3065149904:error:14094416:SSL  routines:ssl3_read_bytes:sslv3 alert certificate  unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert  number 46
tuya.0 | 2021-01-11 18:30:35.782 | error | (4537) SSL-Proxy ERROR: Error: 3065149904:error:14094416:SSL  routines:ssl3_read_bytes:sslv3 alert certificate  unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert  number 46
tuya.0 | 2021-01-11 18:30:35.776 | error | (4537) Error: 3065149904:error:14094416:SSL  routines:ssl3_read_bytes:sslv3 alert certificate  unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert  number 46
tuya.0 | 2021-01-11 18:30:35.776 | error | (4537) SSL-Proxy ERROR: Error: 3065149904:error:14094416:SSL  routines:ssl3_read_bytes:sslv3 alert certificate  unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert  number 46
tuya.0 | 2021-01-11 18:30:35.768 | error | (4537) Error: 3065149904:error:14094416:SSL  routines:ssl3_read_bytes:sslv3 alert certificate  unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert  number 46
tuya.0 | 2021-01-11 18:30:35.767 | error | (4537) SSL-Proxy ERROR: Error: 3065149904:error:14094416:SSL  routines:ssl3_read_bytes:sslv3 alert certificate  unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert  number 46
tuya.0 | 2021-01-11 18:30:35.637 | error | (4537) Error: 3065149904:error:14094416:SSL  routines:ssl3_read_bytes:sslv3 alert certificate  unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert  number 46
tuya.0 | 2021-01-11 18:30:35.636 | error | (4537) SSL-Proxy ERROR: Error: 3065149904:error:14094416:SSL  routines:ssl3_read_bytes:sslv3 alert certificate  unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert  number 46
tuya.0 | 2021-01-11 18:30:35.451 | error | (4537) Error: 3065149904:error:14094416:SSL  routines:ssl3_read_bytes:sslv3 alert certificate  unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert  number 46
tuya.0 | 2021-01-11 18:30:35.451 | error | (4537) SSL-Proxy ERROR: Error: 3065149904:error:14094416:SSL  routines:ssl3_read_bytes:sslv3 alert certificate  unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert  number 46
tuya.0 | 2021-01-11 18:30:35.428 | error | (4537) Error: 3065149904:error:14094416:SSL  routines:ssl3_read_bytes:sslv3 alert certificate  unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert  number 46
tuya.0 | 2021-01-11 18:30:35.428 | error | (4537) SSL-Proxy ERROR: Error: 3065149904:error:14094416:SSL  routines:ssl3_read_bytes:sslv3 alert certificate  unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert  number 46
tuya.0 | 2021-01-11 18:30:35.407 | error | (4537) Error: 3065149904:error:14094416:SSL  routines:ssl3_read_bytes:sslv3 alert certificate  unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert  number 46
tuya.0 | 2021-01-11 18:30:35.407 | error | (4537) SSL-Proxy ERROR: Error: 3065149904:error:14094416:SSL  routines:ssl3_read_bytes:sslv3 alert certificate  unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert  number 46
tuya.0 | 2021-01-11 18:30:35.398 | error | (4537) Error: 3065149904:error:14094416:SSL  routines:ssl3_read_bytes:sslv3 alert certificate  unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert  number 46
tuya.0 | 2021-01-11 18:30:35.397 | error | (4537) SSL-Proxy ERROR: Error: 3065149904:error:14094416:SSL  routines:ssl3_read_bytes:sslv3 alert certificate  unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert  number 46
tuya.0 | 2021-01-11 18:30:34.512 | error | (4537) Error: 3065149904:error:14094416:SSL  routines:ssl3_read_bytes:sslv3 alert certificate  unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert  number 46
tuya.0 | 2021-01-11 18:30:34.511 | error | (4537) SSL-Proxy ERROR: Error: 3065149904:error:14094416:SSL  routines:ssl3_read_bytes:sslv3 alert certificate  unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert  number 46
tuya.0 | 2021-01-11 18:30:34.486 | error | (4537) Error: 3065149904:error:14094416:SSL  routines:ssl3_read_bytes:sslv3 alert certificate  unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert  number 46
tuya.0 | 2021-01-11 18:30:34.486 | error | (4537) SSL-Proxy ERROR: Error: 3065149904:error:14094416:SSL  routines:ssl3_read_bytes:sslv3 alert certificate  unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert  number 46
tuya.0 | 2021-01-11 18:30:34.370 | error | (4537) Error: 3065149904:error:14094416:SSL  routines:ssl3_read_bytes:sslv3 alert certificate  unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert  number 46
tuya.0 | 2021-01-11 18:30:34.369 | error | (4537) SSL-Proxy ERROR: Error: 3065149904:error:14094416:SSL  routines:ssl3_read_bytes:sslv3 alert certificate  unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert  number 46
tuya.0 | 2021-01-11 18:30:34.168 | error | (4537) Error: 3065149904:error:14094416:SSL  routines:ssl3_read_bytes:sslv3 alert certificate  unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert  number 46
tuya.0 | 2021-01-11 18:30:34.168 | error | (4537) SSL-Proxy ERROR: Error: 3065149904:error:14094416:SSL  routines:ssl3_read_bytes:sslv3 alert certificate  unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert  number 46
tuya.0 | 2021-01-11 18:30:33.952 | error | (4537) Error: 3065149904:error:14094416:SSL  routines:ssl3_read_bytes:sslv3 alert certificate  unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert  number 46
tuya.0 | 2021-01-11 18:30:33.951 | error | (4537) SSL-Proxy ERROR: Error: 3065149904:error:14094416:SSL  routines:ssl3_read_bytes:sslv3 alert certificate  unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert  number 46
tuya.0 | 2021-01-11 18:30:29.543 | info | (4537) SSL-Proxy ready to receive requests
`
Neuinstallation vom Adapter und der App brachten keine Besserung.

Hat da jemand ne Idee?

**Comment by Apollon77** [comment]
Diese Fehlermeldung bedeutet das das SSL Zertifikat irgendwie nicht korrekt eingerichtet ist ... es gibt inzwischen wohl auch einige Android versionen die diese art Zertifikate gar nicht mehr erlauben ... sorry hier musst Du leider einen Weg finden ... ggf mal Android emulator (siehe readme) versuchen?
