### ISSUE TITLE
Tuya | WiFi switch-4CH | cannot set Datapoint jg_time by script

### ISSUE THREAD

**Issue by RVE1** [Apollon77/ioBroker.tuya#250]
Hallo zusammen,

ich hoffe, dass ich hier nicht einen Fehler beschreibe, der zuvor schon gelöst wurde.
Evtl. handelt es sich bei meinem Problem auch um ein fehlerhaftes Handling von ioBroker. Ich habe keinen Lösungsansatz oder eine andere Diskussion zu diesem Thema finden können, weshalb ich diesen Bug report eröffne.

Ich betreibe seit einigen Jahren eine ioBroker Instanz, auf der diverse Aktoren eingebunden sind.
Am letzten Wochenende ist ein weiteres Tuya Gerät (WiFi switch-4CH) hinzugekommen.
Mit der grundsätzlichen Funktion bin ich soweit zufrieden, lediglich ein Wert lässt sich nicht per Skript verändern.
![grafik](https://user-images.githubusercontent.com/77974107/105714185-5386d380-5f1c-11eb-80ae-3228c01eab0a.png)
Es handelt sich um einen Wert, der die Anschaltzeit eines Relais bis zum selbstständigen Ausschalten in Sekunden angibt.
Seitens Tuya sind Werte von 0.5 bis 60 Sekunden vorgesehen.

Jetzt zu dem eigentlichen Problem:
Sofern ich den Wert des Datenpunktes jg_time manuell im Bereich Objekte und der Spalte Wert ändere, funktioniert alles perfekt. Der Wert wird gesetzt, seitens des Gerätes verwendet und bleibt auch nach dem Schalten von Relais dauerhaft gesetzt.
Sofern ich diesen Wert allerdings per Skript setze, erscheint er kurz, wird aber bei der nächsten Schaltaktion zurückgesetzt.
Ich gehe davon aus, dass keine Übertragung an das Gerät stattgefunden hat. Dies führt dann dazu, dass der im Gerät bekannte Wert wieder herangezogen wird.

Hier mein Skript blockly -> JS:
![grafik](https://user-images.githubusercontent.com/77974107/105716357-fdfff600-5f1e-11eb-9a78-27beb9405520.png)

Die Zugriffsrechte auf den Datenpunkt habe ich mir bereits angeschaut. Auch wenn ich hier alles erlaube, ändert sich das verhalten nicht. Zu dem habe diverse Varianten in blockly getestet. Leider führt bisher keiner meiner Ansätze dazu, dass der Wert auch per Skript gesetzt werden kann.

Hier die RAW Werte meines Datenpunktes:
![grafik](https://user-images.githubusercontent.com/77974107/105716685-78307a80-5f1f-11eb-80aa-ee4546c18969.png)

**Versions:**  
 - Adapter version: Tuya Adapter 3.5.2
 - JS-Controller version: Javascript/Blockly Skriptausführung für ioBroker 4.8.4
 - Node version: 12.20.1
 - Operating system: raspbian buster

Kann hier jemand Licht ins Dunkle bringen?
Vielen Dank vorab!

**Comment by Apollon77** [comment]
Also sdin deinem Code beispiel setzt du ack auf true (dritter parameter) ... das ist der Fehler.

ack = true bedeutet "Dies ist ein Wert vom gerät, KEIN KOMMANDO"
ack = false ist ein KOMMANDO buitte an das Gerät weitersenden.
