### ISSUE TITLE
Indicator Reachable switching true/false

### ISSUE THREAD

**Issue by KoEnix** [Apollon77/ioBroker.tuya#255]
Hello, first of all, nice work!
But I got a strange problem right now, my three Tuya Devices, two of them are switchable sockets, are constantly switching between beeing reachable and not reachable. 

Logs says following:

`

tuya.0 | 2021-02-08 19:12:33.577 | debug | (26376) 6003468550029110afc2: Error from device (20): App still open on your mobile phone? Error: Error from socket
-- | -- | -- | --
tuya.0 | 2021-02-08 19:12:28.698 | debug | (26376)  stateChange tuya.0.6003468550029110afcd.7  {"val":false,"ack":true,"ts":1612807948667,"q":0,"from":"system.adapter.tuya.0","user":"system.user.admin","lc":1612807301709}
tuya.0 | 2021-02-08 19:12:28.690 | debug | (26376)  stateChange tuya.0.6003468550029110afcd.6  {"val":0,"ack":true,"ts":1612807948628,"q":0,"from":"system.adapter.tuya.0","user":"system.user.admin","lc":1612807301693}
tuya.0 | 2021-02-08 19:12:28.663 | debug | (26376)  stateChange tuya.0.6003468550029110afcd.5  {"val":0,"ack":true,"ts":1612807948628,"q":0,"from":"system.adapter.tuya.0","user":"system.user.admin","lc":1612807301636}
tuya.0 | 2021-02-08 19:12:28.661 | debug | (26376)  stateChange tuya.0.6003468550029110afcd.4  {"val":0,"ack":true,"ts":1612807948627,"q":0,"from":"system.adapter.tuya.0","user":"system.user.admin","lc":1612807301615}
tuya.0 | 2021-02-08 19:12:28.658 | debug | (26376)  stateChange tuya.0.6003468550029110afcd.2  {"val":0,"ack":true,"ts":1612807948626,"q":0,"from":"system.adapter.tuya.0","user":"system.user.admin","lc":1612807301593}
tuya.0 | 2021-02-08 19:12:28.653 | debug | (26376)  stateChange tuya.0.6003468550029110afcd.1  {"val":false,"ack":true,"ts":1612807948625,"q":0,"from":"system.adapter.tuya.0","user":"system.user.admin","lc":1612807826107}
tuya.0 | 2021-02-08 19:12:28.612 | debug | (26376) 6003468550029110afcd: Received data: {"1":false,"2":0,"4":0,"5":0,"6":0,"7":false}
tuya.0 | 2021-02-08 19:12:23.582 | debug | (26376) 6003468550029110afc2: Error from device (19): App still open on your mobile phone? Error: Error from socket
tuya.0 | 2021-02-08 19:12:13.576 | debug | (26376) 6003468550029110afc2: Error from device (18): App still open on your mobile phone? Error: Error from socket
tuya.0 | 2021-02-08 19:12:03.578 | debug | (26376) 6003468550029110afc2: Error from device (17): App still open on your mobile phone? Error: Error from socket
tuya.0 | 2021-02-08 19:11:53.573 | debug | (26376) 6003468550029110afc2: Error from device (16): App still open on your mobile phone? Error: Error from socket
tuya.0 | 2021-02-08 19:11:52.172 | debug | (26376)  stateChange tuya.0.bf04470fb911f9c88ansmu.online  {"val":false,"ack":true,"ts":1612807912161,"q":0,"from":"system.adapter.tuya.0","user":"system.user.admin","lc":1612807912161}
tuya.0 | 2021-02-08 19:11:52.155 | debug | (26376) bf04470fb911f9c88ansmu: Disconnected from device
tuya.0 | 2021-02-08 19:11:43.592 | debug | (26376) 6003468550029110afc2: Error from device (15): App still open on your mobile phone? Error: Error from socket
tuya.0 | 2021-02-08 19:11:40.264 | debug | (26376)  stateChange tuya.0.bf04470fb911f9c88ansmu.26  {"val":0,"ack":true,"ts":1612807900192,"q":0,"from":"system.adapter.tuya.0","user":"system.user.admin","lc":1612807301040}
tuya.0 | 2021-02-08 19:11:40.262 | debug | (26376)  stateChange tuya.0.bf04470fb911f9c88ansmu.25  {"val":"000d0d00000003e803e800000000","ack":true,"ts":1612807900190,"q":0,"from":"system.adapter.tuya.0","user":"system.user.admin","lc":1612807301
tuya.0 | 2021-02-08 19:11:40.259 | debug | (26376)  stateChange tuya.0.bf04470fb911f9c88ansmu.24  {"val":"001c03e803e8","ack":true,"ts":1612807900189,"q":0,"from":"system.adapter.tuya.0","user":"system.user.admin","lc":1612807300938}
tuya.0 | 2021-02-08 19:11:40.242 | debug | (26376)  stateChange tuya.0.bf04470fb911f9c88ansmu.23  {"val":1000,"ack":true,"ts":1612807900183,"q":0,"from":"system.adapter.tuya.0","user":"system.user.admin","lc":1612807300849}
tuya.0 | 2021-02-08 19:11:40.218 | debug | (26376)  stateChange tuya.0.bf04470fb911f9c88ansmu.22  {"val":1000,"ack":true,"ts":1612807900182,"q":0,"from":"system.adapter.tuya.0","user":"system.user.admin","lc":1612807300684}
tuya.0 | 2021-02-08 19:11:40.215 | debug | (26376)  stateChange tuya.0.bf04470fb911f9c88ansmu.21  {"val":"1","ack":true,"ts":1612807900181,"q":0,"from":"system.adapter.tuya.0","user":"system.user.admin","lc":1612807300641}
tuya.0 | 2021-02-08 19:11:40.212 | debug | (26376)  stateChange tuya.0.bf04470fb911f9c88ansmu.20  {"val":false,"ack":true,"ts":1612807900180,"q":0,"from":"system.adapter.tuya.0","user":"system.user.admin","lc":1612807300573}
tuya.0 | 2021-02-08 19:11:40.193 | debug | (26376)  stateChange tuya.0.bf04470fb911f9c88ansmu.online  {"val":true,"ack":true,"ts":1612807900159,"q":0,"from":"system.adapter.tuya.0","user":"system.user.admin","lc":1612807900159}
tuya.0 | 2021-02-08 19:11:40.166 | debug | (26376)  bf04470fb911f9c88ansmu: Received data:  {"20":false,"21":"colour","22":1000,"23":1000,"24":"001c03e803e8","25":"000d0d00000003e803e800000000","26":0}

`

**Comment by Apollon77** [comment]
seems that the device is ending the socket ... or there is a wlan reachability issue ... try to remove power from device and try again. or check wlan quality
