### ISSUE TITLE
Tuya Adapter dauerhaft Gelb

### ISSUE THREAD

**Issue by PhilippBrandt** [Apollon77/ioBroker.tuya#256]
@Apollon77 
Seit einigen Tagen bleibt der Tuya Adapter dauerhaft Gelb und auch nach mehrmaligem neustarten des adapters sowie des raspberry pi funktioniert er nicht.Bevor er noch ging funktionierten die Geräte auch nur im selben Zimmer wo sich auch der raspberry pi mit dem iobroker befand und eine steckdose in einem anderen stockwerk funktionierte nicht.

![FireShot Capture 006 - instances - ioBroker - 192 168 178 38](https://user-images.githubusercontent.com/58659313/108565921-d0338480-7305-11eb-8b40-e5a814ac0a65.png)
![FireShot Capture 009 - instances - ioBroker - 192 168 178 38](https://user-images.githubusercontent.com/58659313/108565922-d0cc1b00-7305-11eb-9986-84f997d74bc7.png)
![FireShot Capture 003 -  - 192 168 178 38](https://user-images.githubusercontent.com/58659313/108565494-0de3dd80-7305-11eb-82ac-29c4ae3308c9.png)

**Comment by Apollon77** [comment]
"timed out" heisst Geräte nicht erreichbar oder antworten nicht. grund unbekannt. Da kann ich nichts tun.
WLAN ist ok?
Mit den Etagen ... ggf andere WLAN router und UDP Pakete nicht geroutet?

**Comment by PhilippBrandt** [comment]
Das wlan ist in Ordnung und wird mit netgear Orbi verteilt.Ich finde einfach keine Lösung dafür liegt es daran das das wlan nicht über die FRITZ!Box läuft sondern über die orbis?

**Comment by Apollon77** [comment]
Du musst sicherstellen das UDP geroutet wird für die erkennenung und rausfinden warum netzwerk timeouts sind. Keine AHnung zum Rest sorry

**Comment by PhilippBrandt** [comment]
@Apollon77 
Auf welchem Port müssen denn die Udp Pakete geroutet werden?6666 oder 6665 oder nen komplett anderen?

**Comment by Apollon77** [comment]
Ja, 6666 und 6667
