### ISSUE TITLE
Can not start because IP unknown

### ISSUE THREAD

**Issue by lug-gh** [Apollon77/ioBroker.tuya#26]
Moin,

ich habe iobroker mal auf meinem orangepi unter armbian installiert und da funktioniert der tuya adapter aus irgendeinem grund nicht...

tuya adapter installiert, proxy gestartet, cert installiert, proxy gesetzt und app gestartet, der proxy hat dann auch alles lesen können, außer die IP des Geräts.

Muss man noch irgendwas installieren, was auf einem raspbian ist, aber unter armbian nicht?

**Comment by Apollon77** [comment]
Die IP kommt nicht vom Sync, sonder die IP wird über UDP Pakete gefunden. Also bitte sicherstellen das die Geräte und ioBroker-Host im gleichen netzwerk sind und auch UDP Pakete durchgereicht werden.

**Comment by lug-gh** [comment]
Ja sind im gleichen netz und die Paket werden auch durchgereicht, zumindest wird laut Firewall nichts geblockt. Die hätte das beim Raspberry dann ja auch blockiert..

**Comment by Apollon77** [comment]
Und sicherstellen das die App zu ist auf dem Handy. Im log solltest du sehen (im zweifel im debug log) wenn er die IPs bekommt. Ansonsten kannst du manuell im device Objekt die IP eintragen. Unter Objekte auf den Ordner gehen der das Gerät ist und da auf dem Stift rechts. Da unter raw ist ein json und da sollte dann ein leeres IP feld sein. 

Solcher Support bitte im Forum.
