### ISSUE TITLE
Device online but switch 1 and 2 always false

### ISSUE THREAD

**Issue by mcbirne** [Apollon77/ioBroker.tuya#265]
Hello,
I have a switch. Since a few weeks It doesn't work with the tuya adapter. If I switch is on the light goes on, in the Smartlife app it is green but in the adapter the state is false. 
![image](https://user-images.githubusercontent.com/38691204/111977433-02055a00-8b03-11eb-987e-ad4aafe758b5.png)

**Comment by Apollon77** [comment]
What does the log say?

**Comment by mcbirne** [comment]
If I switch the first switch, I get this log:
![image](https://user-images.githubusercontent.com/38691204/112123968-1f4d2d80-8bc2-11eb-8797-029989eaf17b.png)
If I switch the second switch I get nothing in the log.
But If I press "all on", I get this information in the log:
![image](https://user-images.githubusercontent.com/38691204/112124281-78b55c80-8bc2-11eb-8710-18b1aaadbf5c.png)

**Comment by Apollon77** [comment]
Ok, so in fact when device sends something it is also set in iobroker. Why the second switch alone do not do anything I have no idea, but also if no data comes from the device it is not fault of adapter ...

Ok, what should I do now? The log shows that the state is set to true

**Comment by mcbirne** [comment]
I don't know. I thought maybe it is a bug in the adapter because it works until before some weeks. But I also test some older versions an they also don't work. Maybe they change some other thinks in the tuya api, because there was no update for the switch.

**Comment by Apollon77** [comment]
Maybe downgrade and update adapter again please. There was a tuyaapi depenedncy update some days ago that had an issue and after that got a fixed version after some hours ... I plan to update adapter the next days also after some other stuff ...

**Comment by mcbirne** [comment]
I also try that. But I have the same problem.

**Comment by Apollon77** [comment]
Please check Github version

**Comment by mcbirne** [comment]
I try it with the new version but it doesn't work. I have the same problem.

**Comment by Apollon77** [comment]
Ok, the it is the device

**Comment by mcbirne** [comment]
Or the interface, because in the app I can see the correct state in real-time.

**Comment by Apollon77** [comment]
App uses cloud ... so it might be that status there is updated, but not provided locally ... then honestly ... no chance. sorry

**Comment by mcbirne** [comment]
With the new Version 3.6 it works
