### ISSUE TITLE
Seit Update des Adapters keine aktuellen Werte von meinem Tuya-Lichtsensor mehr

### ISSUE THREAD

**Issue by Diet1976** [Apollon77/ioBroker.tuya#268]
Hallo Apollon77,
ich nutze den Tuya-Adapter bisher ohne größere Probleme mit meinen WLAN-Steckdosen und einem WLAN-Lichtsensor.
Seit den letzten beiden Updates des Adapters werden die Datenpunkte für die Lux-Werte des Sensors nicht mehr aktualisiert, lediglich beim Neustart des Adapters. Haben Sie eine Idee, was sich im Adapterverhalten geändert haben könnte?

Viele Grüße,
Dietmar H.

**Comment by Apollon77** [comment]
Welche version ird genutzt? Am Ende gab es ein Update der tuyaapi

**Comment by Apollon77** [comment]
Bitte GitHub version versuchen (Versionsnummer gleich, also nach Github install bitte adapter manuell neu starten)

**Comment by Diet1976** [comment]
Vielen Dank,
nach Installation der github-Version klappt es wieder! Sollte man nach Ihrer Empfehlung für ein einmal stabil laufendes System besser keine Updates einfach so einspielen, wenn keine Features vermisst werden oder ist es wichtig, den IOBroker up to date zu halten?

Viele Grüße,
Dietmar H.

**Comment by Diet1976** [comment]
Vielen Dank,
nach Installation der github-Version klappt es wieder! Sollte man nach Ihrer Empfehlung für ein einmal stabil laufendes System besser keine Updates einfach so einspielen, wenn keine Features vermisst werden oder ist es wichtig, den IOBroker up to date zu halten?

Viele Grüße,
Dietmar H.

**Comment by Apollon77** [comment]
AN sich sollten updates unkritisch sein wenn nicht die erste Versionszahl geändert wurde. In dem Fall war es eine unerwartete Önderung in einer genutzten Library die indirekt wohl bei denen breaking war, aber nicht als solches gekennzeichnet ... von daher schwierig zu erkennen.
