### ISSUE TITLE
Geräte lassen sich wie nicht von tuya vorgesehen schalten

### ISSUE THREAD

**Issue by lug-gh** [Apollon77/ioBroker.tuya#27]
Moin,

in der Tuya-App 'Smart Life' ist es ja nicht vorgesehen Attribute von den Geräten zu ändern, wenn diese ausgeschaltet sind, beispielsweise die Helligkeit einer Lampe, die Slider werden ausgeblendet wenn das Gerät ausgeschaltet ist. (switch = false)

Dank dieser iobrroker Erweiterung, lassen sich solche Werte auch ändern, wenn das Gerät ausgeschaltet ist.
Das führt allerdings dazu, dass sich das Gerät auch einschaltet, der switch aber trotzdem auf false bleibt. Es war ja von den Entwicklern bei tuya auch nie vorgesehen, dass man in dieser Art und weise schalten kann.

Nun die Frage, wäre es dir möglich so einen Steuerbefehl abzufangen, und dann entweder den Switch auf true zu setzen oder eine solche Steuerung zu verwehren?

Man kann das ja auch als Skript in iobroker einbinden, das allerdings für jedes Gerät zu machen ist ja unnötiger Aufwand, wenn dies einmal Zentral im Adapter eingepflegt werden könnte :)

**Comment by lug-gh** [comment]
Mein jetziger Workaround:
![image](https://user-images.githubusercontent.com/24546639/53592158-fbab8a80-3b95-11e9-9677-9c9d205fe43a.png)

wenn helligkeit oder farbtemperatur geändert werden, obwohl die lampe aus ist, dann setze den schalter auf 'lampe ist an'

**Comment by Apollon77** [comment]
"Schaltbefehl abfangen" ist so eine Sache. Es gibt so viele Geräte. Der Adapter kann nicht die Verhaltensweisen aller Gerät erahnen bzw. der weiss auch nicht mal was davon der Switch ist. Sorry

**Comment by lug-gh** [comment]
Hmm schade, dann heißt es wohl den ibroker mit skripten zumüllen :)
