### ISSUE TITLE
Scene - Support for simple switch 'scene'

### ISSUE THREAD

**Issue by elzershark** [Apollon77/ioBroker.tuya#271]
https://www.npmjs.com/package/@fratton/homebridge-tuya-web
Scene - Support for simple switch 'scene'

Geräte die als Untergruppe gehören können ja nicht bedient werden.
Vieleicht kann man in dem Adapter die Scenen integrieren. 
Damit lassen sich alle Geräte von Tuya bedienen. Auch die, die nicht integrierbar sind.

**Comment by Apollon77** [comment]
--> https://forum.iobroker.net/topic/59899/test-adapter-tuya-3-9-x-alpha-github

**Comment by Apollon77** [comment]
3.9.1 released
