### ISSUE TITLE
Wifi Deckenleuchte

### ISSUE THREAD

**Issue by Dorich1990** [Apollon77/ioBroker.tuya#273]
Hallo,

habe mir eine Smarte Wifi Deckenleuchte bei Amazon gekauft [(Link)](https://www.amazon.de/gp/product/B08BFC2SM4/ref=ppx_yo_dt_b_asin_title_o06_s00?ie=UTF8&psc=1).

Die Deckenleuchte funktioniert mit der Smartlife App und der Tuya Adapter hat sie auch mit erkannt.

Ich kann an der Deckenleuchte aber keine Farbe steuern, da mir der Tuya Adapter eine Colordata Code mit 3 Viererblöcken aus gibt.
![tuya](https://user-images.githubusercontent.com/82087740/113841021-9a513f00-9791-11eb-979c-ca74aa88068a.JPG)

Hab mal code mal auseinander genommen, weiß aber nichts mit den Hex anzufangen.

Die Deckenleuchte soll so, per VIS gesteuert werden 
![vis](https://user-images.githubusercontent.com/82087740/113841501-0fbd0f80-9792-11eb-9193-525902d12575.JPG)

MFG Dorich

**Comment by Apollon77** [comment]
The adapter can not decode that for you, you need extra own logic for it (also because we have no idea which kind of color encoding a certain device uses.

see https://github.com/Apollon77/ioBroker.tuya/issues/254 for more infos maybe

**Comment by Apollon77** [comment]
Please check out --> https://forum.iobroker.net/topic/59899/test-adapter-tuya-3-9-x-alpha-github
