### ISSUE TITLE
Manually adding a device if local key is known?

### ISSUE THREAD

**Issue by kopierschnitte** [Apollon77/ioBroker.tuya#274]
I'm currently running tuya-mqtt and gone through the entire process of registering fake apps, cloud access, ... in order to get the required IDs/key using tuya-cli wizard.

As far as I know, the ioBroker-adapter is using a similar approach and I'm wondering if it could be possible to skip the "man in the middle" task of the adapter as I already know the Local ID/Key.

**Comment by Apollon77** [comment]
This is a feature request ... Currently there is no way to provide a list of such device infos.... would need to this about how to do that

**Comment by Apollon77** [comment]
problem is from where to get all meta and schema information ... I will more implement the "tuyapi wizard cliud sync" way, so using this we can get the details
