### ISSUE TITLE
Werte cur_power, cur_current und cur_voltage werden nicht aktualisiert

### ISSUE THREAD

**Issue by paulinchen14** [Apollon77/ioBroker.tuya#285]
Da das Problem eigentlich mit der Version 3.6.0 behoben sein sollte, habe ich im ioBroker den Adapter und die DP gelöscht und die aktuelle Version 3.6.1 von GitHub neu installiert.

Leider besteht das Problem immer noch.

Der Switch-State (true/false) funktioniert und wird unmittelbar aktualisiert.

Die Werte von cur_power, cur_current und cur_voltage bleiben allerdings unverändert. Meist werden diese Werte erst nach 8 Minuten geupdatet, mitunter allerdings auch gar nicht.

Wenn ich die App "Smart Live" starte und auf die Seite "Electric" gehe, werden die Daten im ioBroker sofort aktualisiert.

**Comment by Apollon77** [comment]
Was ist als "polling Interval" eingestellt? Was sagt ein Debug log?

**Comment by paulinchen14** [comment]
"polling intervall" steht auf 20 Sekunden.
Die DP blinken auch aller 20 Sek. grün auf und der Zeitstempel wird aktualisiert.

Die Debug Log ist auch unauffällig, aller 20 Sek. werden alle Werte abgerufen:

tuya.0 | 2021-05-07 11:46:42.404 | debug | (5042) stateChange tuya.0.605385842462ab174303.19 {"val":0,"ack":true,"ts":1620380802382,"q":0,"from":"system.adapter.tuya.0","user":"system.user.admin","lc":1620378606855}
...
tuya.0 | 2021-05-07 11:46:42.388 | debug | (5042) stateChange tuya.0.605385842462ab174303.1 {"val":true,"ack":true,"ts":1620380802380,"q":0,"from":"system.adapter.tuya.0","user":"system.user.admin","lc":1620380760064}
tuya.0 | 2021-05-07 11:46:42.367 | debug | (5042) 605385842462ab174303: Received data: {"1":true,"9":0,"18":0,"19":0,"20":2354,"21":1,"22":626,"23":30848,"24":17408,"25":1196}
tuya.0 | 2021-05-07 11:46:42.256 | debug | (5042) 605385842462ab174303 request data via get ...

**Comment by Apollon77** [comment]
Welche IDs haben denndie fehlenden Werte? Also welche Zahlen?

**Comment by Apollon77** [comment]
PS: Und wenn Werte abgerufen werden sind die relevanten Fehler/Ids dabei?

**Comment by Apollon77** [comment]
Aber der Wert von 19 ist im obigen beispiel bei den get werten dabei? Oder fehlt er bei anderen get requests??? ggf bitte vollständiges Log posten

**Comment by paulinchen14** [comment]
Ich hatte es ja schon geschrieben, im Log sind alle DP als "stateChange" enthalten.
Hier noch mal ein Auszug, welcher sich aller 20 Sekunden wiederholt:

<html>
<body>


tuya.0 | 2021-05-08 12:04:46.298 | debug | (25214) stateChange tuya.0.60538584807d3a03dfea.25 {"val":1248,"ack":true,"ts":1620468286233,"q":0,"from":"system.adapter.tuya.0","user":"system.user.admin","lc":1620062613449}
-- | -- | -- | --
tuya.0 | 2021-05-08 12:04:46.296 | debug | (25214) stateChange tuya.0.60538584807d3a03dfea.24 {"val":16716,"ack":true,"ts":1620468286233,"q":0,"from":"system.adapter.tuya.0","user":"system.user.admin","lc":1620062613445}
tuya.0 | 2021-05-08 12:04:46.295 | debug | (25214) stateChange tuya.0.60538584807d3a03dfea.23 {"val":29142,"ack":true,"ts":1620468286233,"q":0,"from":"system.adapter.tuya.0","user":"system.user.admin","lc":1620062613401}
tuya.0 | 2021-05-08 12:04:46.292 | debug | (25214) stateChange tuya.0.60538584807d3a03dfea.22 {"val":613,"ack":true,"ts":1620468286232,"q":0,"from":"system.adapter.tuya.0","user":"system.user.admin","lc":1620062613221}
tuya.0 | 2021-05-08 12:04:46.285 | debug | (25214) stateChange tuya.0.60538584807d3a03dfea.21 {"val":1,"ack":true,"ts":1620468286231,"q":0,"from":"system.adapter.tuya.0","user":"system.user.admin","lc":1620062613156}
tuya.0 | 2021-05-08 12:04:46.281 | debug | (25214) stateChange tuya.0.60538584807d3a03dfea.20 {"val":243.4,"ack":true,"ts":1620468286231,"q":0,"from":"system.adapter.tuya.0","user":"system.user.admin","lc":1620468026648}
tuya.0 | 2021-05-08 12:04:46.271 | debug | (25214) stateChange tuya.0.60538584807d3a03dfea.19 {"val":34.4,"ack":true,"ts":1620468286230,"q":0,"from":"system.adapter.tuya.0","user":"system.user.admin","lc":1620468026648}
tuya.0 | 2021-05-08 12:04:46.266 | debug | (25214) stateChange tuya.0.60538584807d3a03dfea.18 {"val":354,"ack":true,"ts":1620468286229,"q":0,"from":"system.adapter.tuya.0","user":"system.user.admin","lc":1620468026647}
tuya.0 | 2021-05-08 12:04:46.262 | debug | (25214) stateChange tuya.0.60538584807d3a03dfea.9 {"val":0,"ack":true,"ts":1620468286229,"q":0,"from":"system.adapter.tuya.0","user":"system.user.admin","lc":1620062613110}
tuya.0 | 2021-05-08 12:04:46.237 | debug | (25214) stateChange tuya.0.60538584807d3a03dfea.1 {"val":false,"ack":true,"ts":1620468286228,"q":0,"from":"system.adapter.tuya.0","user":"system.user.admin","lc":1620468123628}
tuya.0 | 2021-05-08 12:04:46.216 | debug | (25214) 60538584807d3a03dfea: Received data: {"1":false,"9":0,"18":354,"19":344,"20":2434,"21":1,"22":613,"23":29142,"24":16716,"25":1248}
tuya.0 | 2021-05-08 12:04:46.146 | debug | (25214) 60538584807d3a03dfea request data via get ...


</body>
</html>

Der DP "1" ist korrekt auf false, die Steckdose ist ausgeschaltet.
Der DP "19" zeigt aber weiterhin 34,4 W an ?

Was halt auffällig ist: Oft (aber nicht immer!) wird genau 8 Minuten zu Spät der korrekte Wert in den DP übernommen:

<html>
<body>


tuya.0 | 2021-05-08 12:10:47.061 | debug | (25214) stateChange tuya.0.60538584807d3a03dfea.25 {"val":1248,"ack":true,"ts":1620468647031,"q":0,"from":"system.adapter.tuya.0","user":"system.user.admin","lc":1620062613449}
-- | -- | -- | --
tuya.0 | 2021-05-08 12:10:47.057 | debug | (25214) stateChange tuya.0.60538584807d3a03dfea.24 {"val":16716,"ack":true,"ts":1620468647031,"q":0,"from":"system.adapter.tuya.0","user":"system.user.admin","lc":1620062613445}
tuya.0 | 2021-05-08 12:10:47.055 | debug | (25214) stateChange tuya.0.60538584807d3a03dfea.23 {"val":29142,"ack":true,"ts":1620468647031,"q":0,"from":"system.adapter.tuya.0","user":"system.user.admin","lc":1620062613401}
tuya.0 | 2021-05-08 12:10:47.051 | debug | (25214) stateChange tuya.0.60538584807d3a03dfea.22 {"val":613,"ack":true,"ts":1620468647030,"q":0,"from":"system.adapter.tuya.0","user":"system.user.admin","lc":1620062613221}
tuya.0 | 2021-05-08 12:10:47.048 | debug | (25214) stateChange tuya.0.60538584807d3a03dfea.21 {"val":1,"ack":true,"ts":1620468647030,"q":0,"from":"system.adapter.tuya.0","user":"system.user.admin","lc":1620062613156}
tuya.0 | 2021-05-08 12:10:47.040 | debug | (25214) stateChange tuya.0.60538584807d3a03dfea.20 {"val":236.5,"ack":true,"ts":1620468647029,"q":0,"from":"system.adapter.tuya.0","user":"system.user.admin","lc":1620468626941}
tuya.0 | 2021-05-08 12:10:47.037 | debug | (25214) stateChange tuya.0.60538584807d3a03dfea.19 {"val":0,"ack":true,"ts":1620468647029,"q":0,"from":"system.adapter.tuya.0","user":"system.user.admin","lc":1620468626940}
tuya.0 | 2021-05-08 12:10:47.034 | debug | (25214) stateChange tuya.0.60538584807d3a03dfea.18 {"val":0,"ack":true,"ts":1620468647028,"q":0,"from":"system.adapter.tuya.0","user":"system.user.admin","lc":1620468626939}
tuya.0 | 2021-05-08 12:10:46.991 | debug | (25214) stateChange tuya.0.60538584807d3a03dfea.9 {"val":0,"ack":true,"ts":1620468646983,"q":0,"from":"system.adapter.tuya.0","user":"system.user.admin","lc":1620062613110}
tuya.0 | 2021-05-08 12:10:46.987 | debug | (25214) stateChange tuya.0.60538584807d3a03dfea.1 {"val":false,"ack":true,"ts":1620468646983,"q":0,"from":"system.adapter.tuya.0","user":"system.user.admin","lc":1620468123628}
tuya.0 | 2021-05-08 12:10:46.972 | debug | (25214) 60538584807d3a03dfea: Received data: {"1":false,"9":0,"18":0,"19":0,"20":2365,"21":1,"22":613,"23":29142,"24":16716,"25":1248}
tuya.0 | 2021-05-08 12:10:46.936 | debug | (25214) 60538584807d3a03dfea request data via get ...


</body>
</html>

**Comment by Apollon77** [comment]
Also dann liegts jetzt aber wirklich am Device ... Der Adapter kann nix raten. Du siehst im Log genau was das Gerät liefert und das ist alles verfügbar. Mehr als Anfragen kann man nicht
