### ISSUE TITLE
iobroker Tuya-Adapter und Lichtschalter ohne N-Leiter

### ISSUE THREAD

**Issue by nobtuk** [Apollon77/ioBroker.tuya#289]
Hallo, 
Du schreibst in der Anleitung zum Tuya-Adapter "The adapter is proofed to work very well with all devices that are "always in wifi". Devices that only come online when there is an event, send their data and go offline again are not supported. This means that battery powered devices usually DO NOT work!", was ist mit Lichtschaltern die keinen Neutralleiter (Nullleiter) anschluss benötigen.
Ich habe das Problem das die im iobroker nicht immer online = true angezeigt werden. Sie schalten zwar wenn ich manuell in den jeweiligen Objekten den "Switch" betätige aber mit Blockly oder am Schalter funktioniert das dann nicht. Ich habe Schalter mit 3 Tastern, Ausgang 1 und 2 sind mit Lampen verbunden und mit dem 3ten möchte ich zb. eine Steckdose schalten. Manchmal geht es aber die meiste Zeit nicht.
![Screenshot_2021-05-18 objects - ioBroker](https://user-images.githubusercontent.com/80999840/118617956-54a28000-b7ed-11eb-91ad-bfeb4e03da3d.png)
So wie das Verhalten der Schalter und Steckdosen jetzt ist kann ich keine verlässliche Steuerung mit dem iobroker realisieren. Ich hoffe es gibt eine Lösung, ansonsten waren die Wifi Wandschalter für die Tonne und ich muß mir die Schalter in der Zigbee Variante kaufen und dann damit testen.

**Comment by nobtuk** [comment]
Eine Frage hätte ich da noch zum Tuya-Adapter.
Die Wifi Einstellung im Handy kann ich nach der Syncronisierung zwischen Tuya-App und Tuya iobroker-Adapter wieder auf "ohne Proxy" zurückstellen, oder benötige ich die Einstellung mit "proxy manuel" im Dauerbetrieb. Schalte ich dann immer noch über China?
Vielen Dank schonmal im voraus

**Comment by nobtuk** [comment]
Ich muß nochmal stören, das Schalten der Steckdose mit dem 3ten Schalter hat jetzt mal gklappt, allerdings mit Zeitverzögerung. Wenn ich am Lichtschalter ein oder ausschalte dauert es eine Zeit bis der Schalter im iobroker aktuallisiert wird und die Steckdose geschaltet wird. Woran liegt das und kann ich da eine Änderung auf fast sofort herbeiführen?

**Comment by nobtuk** [comment]
ich habe gerade den Tuya Adapter von 3.5.9 auf 3.6.2 upgedatet. Erstmal reagiert die Steckdose sofort. Mal sehen wie es mit dem Problem "Online" geht.

**Comment by Apollon77** [comment]
Proxy wird nur einmalig benötigt um Daten zu holen, danach ist alles lokal. Für mehr brauche ich ein Debug Log

**Comment by nobtuk** [comment]
ich brauche den Proxy also nur nochmal wenn ich neue Geräte hinzufügen möchte, oder liege ich da falsch?
Die Probleme mit Online true oder false haben sich mit der Adapterversion 3.6.2 erledigt. Danke für deine Arbeit.

**Comment by Apollon77** [comment]
> ich brauche den Proxy also nur nochmal wenn ich neue Geräte hinzufügen möchte, oder liege ich da falsch?

Korrekt
