### ISSUE TITLE
Question: Autoconnect after electrical cut

### ISSUE THREAD

**Issue by necotec** [Apollon77/ioBroker.tuya#298]
Is it normal, that after a cut of a device from the electrical network (and a following reconnect to the electrical network), the device is connected to Wifi, but not connected to the Tuya-Adaptor? If I restart the adaptor, then the device is reconnected. Is there any way, how I can automate or fix this?

**Comment by Apollon77** [comment]
Normally the adapter tries to reconnect and after some tries wait for a new UDP package ... so it should work.

Please use most current version of adapter,set loglevel to debug and check/provide log from such a reconnect case where it do not work

**Comment by necotec** [comment]
Ok, thank you, I try it

**Comment by necotec** [comment]
So, I've installed the newest version and activated debug. There are some lines in the log. But I don't know, how i can fix it -_-
The first 5 lines confuse me... The App isn't running... And the adaptor is still in yellow state

`

&nbsp; | &nbsp; | &nbsp; | &nbsp;
-- | -- | -- | --
tuya.0 | 2021-06-03 19:49:00.327 | debug | (1258) bffcdbee23b647a511dspj: Error from device (7): App still open on your mobile phone? Error: Error from socket: connect EHOSTUNREACH 192.168.11.125:6668
tuya.0 | 2021-06-03 19:48:57.251 | debug | (1258) bffcdbee23b647a511dspj: Error from device (6): App still open on your mobile phone? Error: Error from socket: connect EHOSTUNREACH 192.168.11.125:6668
tuya.0 | 2021-06-03 19:48:54.180 | debug | (1258) bffcdbee23b647a511dspj: Error from device (5): App still open on your mobile phone? Error: Error from socket: connect EHOSTUNREACH 192.168.11.125:6668
tuya.0 | 2021-06-03 19:48:54.180 | debug | (1258) bffcdbee23b647a511dspj: Error from device (4): App still open on your mobile phone? Error: Error from socket: connect EHOSTUNREACH 192.168.11.125:6668
tuya.0 | 2021-06-03 19:48:54.179 | debug | (1258) bffcdbee23b647a511dspj: Error from device (3): App still open on your mobile phone? Error: Error from socket: connect EHOSTUNREACH 192.168.11.125:6668
tuya.0 | 2021-06-03 19:48:53.101 | debug | (1258) bffcdbee23b647a511dspj.1: set value false via bffcdbee23b647a511dspj
tuya.0 | 2021-06-03 19:48:53.100 | debug | (1258) bffcdbee23b647a511dspj: Error from device (2): App still open on your mobile phone? Timeout waiting for status response from device id: bffcdbee23b647a511dspj
tuya.0 | 2021-06-03 19:48:50.102 | debug | (1258) bffcdbee23b647a511dspj request data via refresh for [4,5,6]
tuya.0 | 2021-06-03 19:48:48.100 | debug | (1258) bffcdbee23b647a511dspj.3: set value 255 via bffcdbee23b647a511dspj
tuya.0 | 2021-06-03 19:48:48.100 | debug | (1258) bffcdbee23b647a511dspj: Error from device (1): App still open on your mobile phone? Timeout waiting for status response from device id: bffcdbee23b647a511dspj
tuya.0 | 2021-06-03 17:48:45.100 | debug | (1258) bffcdbee23b647a511dspj request data via refresh for [4,5,6]
tuya.0 | 2021-06-03 17:48:43.099 | debug | (1258) bffcdbee23b647a511dspj.5: set value 255,255,255 via bffcdbee23b647a511dspj
tuya.0 | 2021-06-03 17:48:43.099 | debug | (1258) bffcdbee23b647a511dspj: Error from device (0): App still open on your mobile phone? Timeout waiting for status response from device id: bffcdbee23b647a511dspj
tuya.0 | 2021-06-03 17:48:41.803 | debug | (1258) Discovered encrypted device and store for later usage: 192.168.10.118:49153 - 000055aa00000000000000130000009c00000000d09766676f3369eb10b5e9f132fd802a04e2038d6ab326dc40d8d953857e01e0a1abf314af
tuya.0 | 2021-06-03 17:48:38.101 | debug | (1258) bffcdbee23b647a511dspj onChange triggered for 1 and value false
tuya.0 | 2021-06-03 17:48:38.100 | debug | (1258) stateChange tuya.0.bffcdbee23b647a511dspj.1 {"val":false,"ack":false,"ts":1622742518096,"q":0,"c":"script.js.Rooms.EG.Bathroom-EG.MainLight","from":"system.adapter.javascript.0","user":"system
tuya.0 | 2021-06-03 17:48:38.099 | debug | (1258) bffcdbee23b647a511dspj onChange triggered for 3 and value 255
tuya.0 | 2021-06-03 17:48:38.099 | debug | (1258) stateChange tuya.0.bffcdbee23b647a511dspj.3 {"val":255,"ack":false,"ts":1622742518096,"q":0,"c":"script.js.Rooms.EG.Bathroom-EG.MainLight","from":"system.adapter.javascript.0","user":"system.u
tuya.0 | 2021-06-03 17:48:38.097 | debug | (1258) bffcdbee23b647a511dspj onChange triggered for 5 and value "255,255,255"
tuya.0 | 2021-06-03 17:48:38.097 | debug | (1258) stateChange tuya.0.bffcdbee23b647a511dspj.5 {"val":"255,255,255","ack":false,"ts":1622742518096,"q":0,"c":"script.js.Rooms.EG.Bathroom-EG.MainLight","from":"system.adapter.javascript.0","user"
tuya.0 | 2021-06-03 17:48:38.094 | debug | (1258) connected set to false
tuya.0 | 2021-06-03 17:48:38.094 | debug | (1258) stateChange tuya.0.info.connection {"val":false,"ack":true,"ts":1622742518092,"q":0,"from":"system.adapter.tuya.0","user":"system.user.admin","lc":1622742518092}
tuya.0 | 2021-06-03 17:48:38.093 | debug | (1258) stateChange tuya.0.bffcdbee23b647a511dspj.online {"val":false,"ack":true,"ts":1622742518092,"q":0,"from":"system.adapter.tuya.0","user":"system.user.admin","lc":1622742518092}
tuya.0 | 2021-06-03 17:48:38.090 | debug | (1258) bffcdbee23b647a511dspj: Disconnected from device
tuya.0 | 2021-06-03 17:46:41.086 | debug | (1258) sendTo "getDeviceInfo" to system.adapter.admin.0 from system.adapter.tuya.0
tuya.0 | 2021-06-03 17:46:41.086 | debug | (1258) Message: {"command":"getDeviceInfo","message":null,"from":"system.adapter.admin.0","callback":{"message":null,"id":26,"ack":false,"time":1622742401084},"_id":92906313}

`

**Comment by Apollon77** [comment]
EHOSTUNREACH means that the iobroker host can not fnd any route to the given IP ... this means the device s offline or not reachable via WLAN.

Even before you sended the commands the device was offline again (see the "Disconnected from device" logline ...

SO check the connectivity first

**Comment by necotec** [comment]
I don't know what I've done.... but with latest version it's working now.

After a cut of the device from the electrical network, the device reconnects to WiFi and the Tuya adaptor find it automatically... so, issue closed
