### ISSUE TITLE
Falscher Typ bei Rolladenaktor

### ISSUE THREAD

**Issue by sunshower2** [Apollon77/ioBroker.tuya#300]
Hallo, 
seit dem neuen Admin bekomme ich folgende Infomeldungen im log:
State value to set for "tuya.0.bf1b50435c7b13cc5f1234.1" has to be type "number" but received type "string" 
State value to set for "tuya.0.bf1b50435c7b13cc5f1234.8" has to be type "number" but received type "string" 
[log.txt](https://github.com/Apollon77/ioBroker.tuya/files/6602823/log.txt)

**Comment by Apollon77** [comment]
Plesse try GitHub version. Working there?

**Comment by sunshower2** [comment]
Same lines in log with 3.6.3 from GitHub.

**Comment by Apollon77** [comment]
stil in 3.6.5? Please provide new log

**Comment by sunshower2** [comment]
Solved with 3.6.5, thanks
