### ISSUE TITLE
Door Sensor SDT-100-Tuya

### ISSUE THREAD

**Issue by paveltsytovich** [Apollon77/ioBroker.tuya#302]
Door sensor states not reflect into object state. 

**To Reproduce**  

1. Add to Smart Life Door Sensor with wi-fi via mobile application in your android device
2. Sync with iobroker tuya adapter via MEmu
3. Go to object tree and see door sensor object
4. In tree not reflect all state - online status, ip address, open/close state

**Expected behavior**  

Automate sync state between iobroker and this device

**Versions:**  
 - Adapter version: 3.6.3
 - JS-Controller version: 3.3.12
 - Node version: V14.17.0
 - Operating system: Rapsberrian 32bit

**Comment by Apollon77** [comment]
Door sensor === Battery powered device??? --> Readme!!
