### ISSUE TITLE
Tuya Adapter startet ständig neu ohne erkennbaren Grund

### ISSUE THREAD

**Issue by Diet1976** [Apollon77/ioBroker.tuya#311]
Hallo Apollon77,

nachdem der Adapter eine ganze Zeit lang ohne Probleme lief, habe ich zur Zeit das Problem, dass der Adapter ständig neu startet (ca. jede Minute). Im Log steht nur:
**Got terminate signal TERMINATE_YOURSELF
terminating
Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason**

Gibts da irgendwas, wonach IOBroker entscheidet, den Adapter neu zu starten? Vielleicht komme ich so weiter?

LG, Dietmar Hermann

**Comment by Apollon77** [comment]
Im Log steht bestimmt noch mehr ...  Welche Adapter Version? Sorry aber in dem Issue fehlen jegliche Infos m´die mir helfen Die zu helfen.

Mit dem Log: Bitte mal in den Settings schauen ob du aus versehen einen restart schedule gesetzt hast weil es sieht so aus als ob er absichtlich regelmässig neu startet

**Comment by Diet1976** [comment]
Hallo! Ja, war mein Fehler, sorry about. Da ist was in meinem Skript zum Neustart des Adapters quer gelaufen. Hatte ich schon vor längerer Zeit geändert, ist aber durch Urlaub vergessen worden.

In diesem Zusammenhang hätte ich mal eine Frage, die mein Skript ggf. obsolet macht:
Ich habe einen Tuya-Lichtsensor (hängt am Strom), den ich regelmäßig abfrage. Leider ist der Tuya-Adapter öfters der Meinung, dass der online-Status des Gerätes offline wäre und dann aktualisiert er keine Werte mehr. Ich habe mir ein Skript geschrieben, was über die FritzBox abfragt ob der Lichtsensor tatsächlich offline ist und falls nicht, den online-Status im Tuya-Adapter manuell auf true setzt und anschließend den Adapter resettet. Danach funktioniert alles wieder super für eine gewisse Zeit.
Kann man am Verhalten des Adapters etwas einstellen, dass er das Gerät nicht immer selbstständig auf offline setzt und keine Werte mehr entgegen nimmt? Das würde mir sehr helfen!

Gruß, Dietmar

**Comment by Apollon77** [comment]
Versuch mal die neuesten Versionen. Ich habe die Tage - weil es selbst passiert ist - bisll was am reconnect handling geändert. Es gab Fälle wo er "stecken" geblieben ist ... vllt löst das schon dein Problem. sonst Debug log von so einem Fall wo er offline bleibt
