### ISSUE TITLE
tuya Instanz stoppt bei Timeout

### ISSUE THREAD

**Issue by ArnoD15** [Apollon77/ioBroker.tuya#326]
Ich hatte heute keine W-LAN Verbindung zu meiner Wärmepumpe und folgende Fehler im LOG:

![Fehler tuya](https://user-images.githubusercontent.com/52088254/132245885-13c9ada8-e17c-4d36-868d-b4fbc4d0fd61.png)

Das Problem ist, das die tuya Instanz gestoppt wird und nur manuell wieder gestartet werden kann.
Ist hier ein Error handling möglich?

**Versions:**  
 - Adapter version: 3.6.9
 - JS-Controller version: 3.3.15
 - Node version: 12.22.4
 - Operating system: Linux

**Comment by Apollon77** [comment]
Bitte 3.6.11 versuchen ... vor allem in 10 wurde noch was an dem Thema gefixt. Falls immer noch bitte neues Issue mit neuem Log öffnenv  (und bitte Log als Text und kein Screenshot)

**Comment by ArnoD15** [comment]
Ok, mach und werde es Morgen dann testen. Danke.
