### ISSUE TITLE
Min-Max value TempSet

### ISSUE THREAD

**Issue by Anzic23** [Apollon77/ioBroker.tuya#33]
in continuation of conversation issues #21 
I added a thermostat to the Smart life app. and added in IoBroker. I can control it now. But the problem with the wrong values remained. I wanted to send values through the script, but the driver creates restrictions for object TempSet 10-70 after reboot, which is unacceptable for me. I need to be able to change the values from 0, can fix it? This thermostat for some reason sends values divided by 5. I. e. if the object is 5 then the thermostat will be 25. Perhaps you can somehow track that the thermostat returns "small" values, and by default multiply them by 5? But now I would like at least what would the driver do not set the value interval, and allowed me to store values which are less than 10..

**Comment by Apollon77** [comment]
Please send
1.) the object definition for the relevant state you want to modify (Objects - in the line of the state klick the pencil icon, select "raw" tab and copy json here
2.) Object devinition of the "device" (the folder) object. same as above
3.) Debug log from start of adapter and when trying to change that value including some time after that. Set tuya instance to debug (Instances, exportmode,columsn "Log stufe"/Loeg level" change to debug). Take the log from disk (/opt/iobroker/log/...) and not from Admin

**Comment by Anzic23** [comment]
1)
{
  "from": "system.adapter.tuya.0",
  "user": "system.user.admin",
  "ts": 1552906932522,
  "common": {
    "name": "TempSet",
    "type": "number",
    "role": "level",
    "unit": "â„ƒ",
    "min": 10,
    "max": 70,
    "scale": 1,
    "read": true,
    "write": true,
    "custom": {
      "sql.0": {
        "enabled": true,
        "changesOnly": false,
        "debounce": "1000",
        "retention": "31536000",
        "changesRelogInterval": 0,
        "changesMinDelta": 0,
        "storageType": "",
        "aliasId": ""
      }
    }
  },
  "native": {},
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator",
    "state": 1636
  },
  "_id": "tuya.0.30801624bcddc28daee6.2",
  "type": "state"
}
2)
{
  "type": "device",
  "common": {
    "name": "Kuhnya",
    "read": true,
    "write": false
  },
  "native": {
    "ip": "192.168.1.28",
    "gwId": "30801624bcddc28daee6",
    "active": 2,
    "ability": 0,
    "mode": 0,
    "encrypt": true,
    "productKey": "modify",
    "version": "3.1",
    "schema": [
      {
        "mode": "rw",
        "code": "Power",
        "name": "å¼€å…³",
        "property": {
          "type": "bool"
        },
        "iconname": "icon-dp_power",
        "id": 1,
        "type": "obj",
        "desc": ""
      },
      {
        "mode": "rw",
        "code": "TempSet",
        "name": "ç›®æ ‡æ¸©åº¦",
        "property": {
          "unit": "â„ƒ",
          "min": 10,
          "max": 70,
          "scale": 1,
          "step": 5,
          "type": "value"
        },
        "iconname": "icon-dp_temp",
        "id": 2,
        "type": "obj",
        "desc": ""
      },
      {
        "mode": "ro",
        "code": "TempCurrent",
        "name": "å½“å‰æ¸©åº¦",
        "property": {
          "unit": "â„ƒ",
          "min": 0,
          "max": 100,
          "scale": 1,
          "step": 5,
          "type": "value"
        },
        "iconname": "icon-dp_sun",
        "id": 3,
        "type": "obj",
        "desc": ""
      },
      {
        "mode": "rw",
        "code": "Mode",
        "name": "æ¨¡å¼",
        "property": {
          "range": [
            "0",
            "1"
          ],
          "type": "enum"
        },
        "iconname": "icon-dp_mode",
        "id": 4,
        "type": "obj",
        "desc": ""
      },
      {
        "mode": "rw",
        "code": "ECO",
        "name": "ECOæ¨¡å¼",
        "property": {
          "type": "bool"
        },
        "iconname": "icon-eco",
        "id": 5,
        "type": "obj",
        "desc": ""
      },
      {
        "mode": "rw",
        "code": "ChildLock",
        "name": "ç«¥é”",
        "property": {
          "type": "bool"
        },
        "iconname": "icon-dp_lock",
        "id": 6,
        "type": "obj",
        "desc": ""
      },
      {
        "mode": "rw",
        "code": "program",
        "name": "å‘¨ç¨‹åº",
        "id": 101,
        "type": "raw",
        "desc": "å¯¹åº”æ˜ŸæœŸä¸€~æ˜ŸæœŸäº”ã€æ˜ŸæœŸå…­ã€æ˜ŸæœŸæ—¥ï¼Œæ¯å¤©å…­æ®µï¼Œå¯è®¾ç½®æ¯å°æ—¶çš„æ¸©åº¦èŒƒå›´ã€‚æ¸©åº¦èŒƒå›´ä¸º5-35æ‘„æ°åº¦ã€‚"
      },
      {
        "mode": "ro",
        "code": "floorTemp",
        "name": "åœ°æ¿æ¸©åº¦",
        "property": {
          "unit": "â„ƒ",
          "min": 0,
          "max": 198,
          "scale": 1,
          "step": 5,
          "type": "value"
        },
        "id": 102,
        "type": "obj",
        "desc": ""
      },
      {
        "mode": "rw",
        "code": "tempSwitch",
        "name": "æ¸©åº¦åˆ‡æ¢",
        "property": {
          "range": [
            "0",
            "1"
          ],
          "type": "enum"
        },
        "id": 103,
        "type": "obj",
        "desc": ""
      },
      {
        "mode": "ro",
        "code": "floortempFunction",
        "name": "åœ°æš–æ¸©åº¦åŠŸèƒ½",
        "property": {
          "type": "bool"
        },
        "id": 104,
        "type": "obj",
        "desc": ""
      }
    ],
    "schemaExt": [],
    "localKey": "09989b348ec0a361",
    "virtual": false,
    "lon": "38.998474",
    "uuid": "30801624bcddc28daee6",
    "iconUrl": "https://images.tuyaeu.com/smart/icon/15264583415nnlzwfs1qd2wqz6i937op3nmi_0.png",
    "lat": "44.915752",
    "runtimeEnv": "prod",
    "devId": "30801624bcddc28daee6",
    "dpMaxTime": 1552589120538,
    "productId": "modify",
    "activeTime": 1552588137,
    "moduleMap": {
      "wifi": {
        "upgradeStatus": 0,
        "bv": "5.28",
        "cdv": "1.0.0",
        "pv": "2.1",
        "verSw": "2.2.6",
        "isOnline": true,
        "id": 6559391,
        "cadv": ""
      },
      "mcu": {
        "upgradeStatus": 0,
        "cdv": "",
        "verSw": "1.0.0",
        "isOnline": true,
        "id": 6559392,
        "cadv": ""
      }
    },
    "devAttribute": 0,
    "name": "Kuhnya",
    "timezoneId": "Europe/Moscow"
  },
  "from": "system.adapter.tuya.0",
  "user": "system.user.admin",
  "ts": 1552906932446,
  "_id": "tuya.0.30801624bcddc28daee6",
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}
3) - attached
[iobroker.2019-03-18.log](https://github.com/Apollon77/ioBroker.tuya/files/2978325/iobroker.2019-03-18.log)

**Comment by Apollon77** [comment]
Hi to 1.) As you can see in the definiton therei is set min/max based on the schema definition from tuya. SO the limit is not originally coming from the adapter!
This is validated by the schema contained in 2. ...

```
{
"mode": "rw",
"code": "TempSet",
"name": "ç›®æ ‡æ¸©åº¦",
"property": {
"unit": "â„ƒ",
"min": 10,
"max": 70,
"scale": 1,
"step": 5,
"type": "value"
},
```
In fact this is defintion by schema and it is set here, so mainly respected by UI elements from iobroker. The adapter will not check min/max values!

In 3. I can not find any try to update the value ... I can only see some changes with "ack=true" which a NO control changes.  Please enable debug again, try to set the value using Admin "Objects" by simply enter a new number ... then an "ack=false" entry for stateChange shgould be logged and sended.
Or how do you do it now?

**Comment by Anzic23** [comment]
two files, js-changes using the script, Admin - from the admin panel. when I enter a value from admin value is accepted. When using the script values are not accepted and returned 10
[JS.log](https://github.com/Apollon77/ioBroker.tuya/files/2981787/JS.log)
[Admin.log](https://github.com/Apollon77/ioBroker.tuya/files/2981788/Admin.log)

. More precisely, they are accepted if greater than 10.

**Comment by Apollon77** [comment]
Also im Rahmen der aktuellen Updates habe ich hier nochmal geschaut. Der Definierte Scale Wert hier ist 1 bedeutet werte sind um Faktor 10 "erhöht" und der Adapter rechnet das entsprechend um.

Wenn also vom Gerät eine 59 kommt, landet im State eine 5,9 , wenn Du eine 10 rein schreibst wird eine 100 weitergegeben.

Die min/max-Werte die im Schema stehen passen aber mit 10..70 nicht dazu und das ist das Problem hier.

Du kannst Im Objektschema des Devices bei Dir das scale auf 0 setzen, dann wird diese Übersetzung nicht mehr gemacht. Dann finde raus (oder mach das vorher) welche Werte das Gerät in Wirklichkeit akzeptiert. weil ggf ist der Scale korrekt, man müsste aber die min/max und die Nutzung auf 0,1..0,7 (also Prozentsicht) anpassen.

**Comment by snookerap** [comment]
Hat das jemand hinbekommen?
Hab immer noch das Problem, dass der falsche Wert angezeigt wird.

**Comment by Apollon77** [comment]
Hast du mal das Schema im Objekt manuell angepasst?

**Comment by snookerap** [comment]
Welchen Wert muss ich da ändern?

**Comment by Anzic23** [comment]
`Work around invalid data that are returned by some devices` in 3.3.8
maybe this is my case? Ready to help with testing. I still have a temperature of 5.6 instead of 28
![image](https://user-images.githubusercontent.com/37106885/87126605-2717ac80-c295-11ea-89b5-d9207c736fee.png)

**Comment by Apollon77** [comment]
no the "Invalid dat" are really invalid data ... not data that might be mis-interpreted. Sorry
