### ISSUE TITLE
Gerät temporär ignorieren

### ISSUE THREAD

**Issue by RP70DP** [Apollon77/ioBroker.tuya#330]
Ich habe immer mal wieder Geräte, die für eine bestimmte Zeit stromlos sind. Dann versucht der Adapter natürlich ständig sich wiederzuverbinden. Es wäre schön, wenn ich einen Datenpunkt pro Gerät erstellen könnte, der den Adapter veranlasst, keinen Reconnect zu machen. Den State braucht der Adapter nicht selbst erstellen, nur auswerten. Den muss der User selbst anlegen.

Sehr aufwendig?

**Comment by Apollon77** [comment]
Selber anlegen ist blöd, wenn dann muss der adapter das anbieten ... Frage ist weniger der Aufwand, eher die Zeit wann ich dazu komme

**Comment by RP70DP** [comment]
Das ist mir völlig klar. Außerdem ist mir bewußt, dass mein Anliegen total unwichtig ist. Deshalb meine Idee, dass es sich dabei eben um eine Art "Experten"-Einstellung handelt. Somit müsste im Adapter nur eine simple Abfrage eingebaut werden. Aber selbsverständlich kann ich auch das als Ahnungsloser nicht wirklich beurteilen. Mein Anliegen ist deshalb auch tatsächlich Prio niedrig.

**Comment by RP70DP** [comment]
Wird nicht mehr benötigt.

**Comment by Apollon77** [comment]
Feature request makes sense, so I keep it open

**Comment by RP70DP** [comment]
Das respektiere ich selbstverständlich, aber ich kann nichts mehr dazu beitragen.

**Comment by Apollon77** [comment]
Check out GitHub version. noLocalConnection state added to define that no local connection is tried to establish (also prevents errors from trying that)

**Comment by Apollon77** [comment]
3.9.1 released
