### ISSUE TITLE
Three new devices - Please send next line from logfile on disk to developer!

### ISSUE THREAD

**Issue by smartcuc** [Apollon77/ioBroker.tuya#344]
Please send next line from logfile on disk to developer!
{"schemaExt":"[]","schema":"[{\"mode\":\"rw\",\"code\":\"switch_led\",\"name\":\"开关\",\"property\":{\"type\":\"bool\"},\"iconname\":\"icon-dp_power\",\"id\":20,\"type\":\"obj\"},{\"mode\":\"rw\",\"code\":\"work_mode\",\"name\":\"模式\",\"property\":{\"range\":[\"white\",\"colour\",\"scene\",\"music\"],\"type\":\"enum\"},\"iconname\":\"icon-dp_mode\",\"id\":21,\"type\":\"obj\"},{\"mode\":\"rw\",\"code\":\"bright_value\",\"name\":\"亮度值\",\"property\":{\"min\":10,\"max\":1000,\"scale\":0,\"step\":1,\"type\":\"value\"},\"iconname\":\"icon-liangdu1\",\"id\":22,\"type\":\"obj\"},{\"mode\":\"rw\",\"code\":\"temp_value\",\"name\":\"冷暖值\",\"property\":{\"min\":0,\"max\":1000,\"scale\":0,\"step\":1,\"type\":\"value\"},\"iconname\":\"icon-dp_half\",\"id\":23,\"type\":\"obj\"},{\"mode\":\"rw\",\"code\":\"colour_data\",\"name\":\"彩光\",\"property\":{\"type\":\"string\",\"maxlen\":255},\"iconname\":\"icon-yanse\",\"id\":24,\"type\":\"obj\"},{\"mode\":\"rw\",\"code\":\"scene_data\",\"name\":\"场景\",\"property\":{\"type\":\"string\",\"maxlen\":255},\"iconname\":\"icon-shoucang\",\"id\":25,\"type\":\"obj\"},{\"mode\":\"rw\",\"code\":\"countdown\",\"name\":\"倒计时剩余时间\",\"property\":{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1,\"type\":\"value\"},\"iconname\":\"icon-a_nav_timer\",\"id\":26,\"type\":\"obj\"},{\"mode\":\"wr\",\"code\":\"control_data\",\"name\":\"调节\",\"property\":{\"type\":\"string\",\"maxlen\":255},\"iconname\":\"icon-dp_box2\",\"id\":28,\"type\":\"obj\"},{\"mode\":\"rw\",\"code\":\"rhythm_mode\",\"name\":\"生物节律\",\"property\":{\"type\":\"raw\",\"maxlen\":128},\"iconname\":\"icon-dp_time3\",\"id\":30,\"type\":\"raw\"},{\"mode\":\"rw\",\"code\":\"sleep_mode\",\"name\":\"灯光助眠\",\"iconname\":\"icon-dp_sleep\",\"id\":31,\"type\":\"raw\"},{\"mode\":\"rw\",\"code\":\"wakeup_mode\",\"name\":\"灯光唤醒\",\"iconname\":\"icon-dp_sun\",\"id\":32,\"type\":\"raw\"},{\"mode\":\"rw\",\"code\":\"power_memory\",\"name\":\"断电记忆\",\"iconname\":\"icon-dp_lightning\",\"id\":33,\"type\":\"raw\"},{\"mode\":\"rw\",\"code\":\"do_not_disturb\",\"name\":\"停电勿扰\",\"property\":{\"type\":\"bool\"},\"iconname\":\"icon-dp_sleep\",\"id\":34,\"type\":\"obj\"}]"}

Please send next line from logfile on disk to developer!
{"schemaExt":"[]","schema":"[{\"mode\":\"rw\",\"code\":\"control\",\"name\":\"窗帘开关\",\"property\":{\"range\":[\"open\",\"stop\",\"close\",\"continue\"],\"type\":\"enum\"},\"iconname\":\"icon-a_power\",\"id\":1,\"type\":\"obj\"},{\"mode\":\"rw\",\"code\":\"percent_control\",\"name\":\"百分比控制\",\"property\":{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":10,\"type\":\"value\"},\"iconname\":\"icon-icon-percent\",\"id\":2,\"type\":\"obj\"},{\"mode\":\"rw\",\"code\":\"cur_calibration\",\"name\":\"精准校准\",\"property\":{\"range\":[\"start\",\"end\"],\"type\":\"enum\"},\"iconname\":\"icon-dp_loop\",\"id\":3,\"type\":\"obj\"},{\"mode\":\"rw\",\"code\":\"control_back\",\"name\":\"电机转向切换\",\"property\":{\"range\":[\"forward\",\"back\"],\"type\":\"enum\"},\"iconname\":\"icon-dp_loop\",\"id\":8,\"type\":\"obj\"},{\"mode\":\"rw\",\"code\":\"tr_timecon\",\"name\":\"快捷校准\",\"property\":{\"unit\":\"s\",\"min\":1,\"max\":60,\"scale\":0,\"step\":1,\"type\":\"value\"},\"iconname\":\"icon-dp_time2\",\"id\":10,\"type\":\"obj\"}]"}

Please send next line from logfile on disk to developer!
{"schemaExt":"[]","schema":"[{\"mode\":\"rw\",\"code\":\"switch_led\",\"name\":\"开关\",\"property\":{\"type\":\"bool\"},\"iconname\":\"icon-dp_power\",\"id\":20,\"type\":\"obj\"},{\"mode\":\"rw\",\"code\":\"work_mode\",\"name\":\"模式\",\"property\":{\"range\":[\"white\",\"colour\",\"scene\",\"music\"],\"type\":\"enum\"},\"iconname\":\"icon-dp_mode\",\"id\":21,\"type\":\"obj\"},{\"mode\":\"rw\",\"code\":\"bright_value\",\"name\":\"亮度值\",\"property\":{\"min\":10,\"max\":1000,\"scale\":0,\"step\":1,\"type\":\"value\"},\"iconname\":\"icon-liangdu1\",\"id\":22,\"type\":\"obj\"},{\"mode\":\"rw\",\"code\":\"scene_data\",\"name\":\"场景\",\"property\":{\"type\":\"string\",\"maxlen\":255},\"iconname\":\"icon-shoucang\",\"id\":25,\"type\":\"obj\"},{\"mode\":\"rw\",\"code\":\"countdown\",\"name\":\"倒计时\",\"property\":{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1,\"type\":\"value\"},\"iconname\":\"icon-a_nav_timer\",\"id\":26,\"type\":\"obj\"}]"}

**Comment by Apollon77** [comment]
Hi, es fehlt bei jeden noch eine Logzeiole mit der ID des Gerätetyps ... kannst bitte noch ergänzen?

**Comment by smartcuc** [comment]
Sorry, hatte ich glöscht. Jetzt mit ID:

new Schema added for product type iudrbqc3r7fzhxaf. Please send next line from logfile on disk to developer!
{"schemaExt":"[]","schema":"[{\"mode\":\"rw\",\"code\":\"switch_led\",\"name\":\"开关\",\"property\":{\"type\":\"bool\"},\"iconname\":\"icon-dp_power\",\"id\":20,\"type\":\"obj\"},{\"mode\":\"rw\",\"code\":\"work_mode\",\"name\":\"模式\",\"property\":{\"range\":[\"white\",\"colour\",\"scene\",\"music\"],\"type\":\"enum\"},\"iconname\":\"icon-dp_mode\",\"id\":21,\"type\":\"obj\"},{\"mode\":\"rw\",\"code\":\"bright_value\",\"name\":\"亮度值\",\"property\":{\"min\":10,\"max\":1000,\"scale\":0,\"step\":1,\"type\":\"value\"},\"iconname\":\"icon-liangdu1\",\"id\":22,\"type\":\"obj\"},{\"mode\":\"rw\",\"code\":\"scene_data\",\"name\":\"场景\",\"property\":{\"type\":\"string\",\"maxlen\":255},\"iconname\":\"icon-shoucang\",\"id\":25,\"type\":\"obj\"},{\"mode\":\"rw\",\"code\":\"countdown\",\"name\":\"倒计时\",\"property\":{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1,\"type\":\"value\"},\"iconname\":\"icon-a_nav_timer\",\"id\":26,\"type\":\"obj\"}]"}


new Schema added for product type bxwoqogfpqywqiku. Please send next line from logfile on disk to developer!
{"schemaExt":"[]","schema":"[{\"mode\":\"rw\",\"code\":\"control\",\"name\":\"窗帘开关\",\"property\":{\"range\":[\"open\",\"stop\",\"close\",\"continue\"],\"type\":\"enum\"},\"iconname\":\"icon-a_power\",\"id\":1,\"type\":\"obj\"},{\"mode\":\"rw\",\"code\":\"percent_control\",\"name\":\"百分比控制\",\"property\":{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":10,\"type\":\"value\"},\"iconname\":\"icon-icon-percent\",\"id\":2,\"type\":\"obj\"},{\"mode\":\"rw\",\"code\":\"cur_calibration\",\"name\":\"精准校准\",\"property\":{\"range\":[\"start\",\"end\"],\"type\":\"enum\"},\"iconname\":\"icon-dp_loop\",\"id\":3,\"type\":\"obj\"},{\"mode\":\"rw\",\"code\":\"control_back\",\"name\":\"电机转向切换\",\"property\":{\"range\":[\"forward\",\"back\"],\"type\":\"enum\"},\"iconname\":\"icon-dp_loop\",\"id\":8,\"type\":\"obj\"},{\"mode\":\"rw\",\"code\":\"tr_timecon\",\"name\":\"快捷校准\",\"property\":{\"unit\":\"s\",\"min\":1,\"max\":60,\"scale\":0,\"step\":1,\"type\":\"value\"},\"iconname\":\"icon-dp_time2\",\"id\":10,\"type\":\"obj\"}]"}


new Schema added for product type jd1zgsl4focjtd8d. Please send next line from logfile on disk to developer!
{"schemaExt":"[]","schema":"[{\"mode\":\"rw\",\"code\":\"switch_led\",\"name\":\"开关\",\"property\":{\"type\":\"bool\"},\"iconname\":\"icon-dp_power\",\"id\":20,\"type\":\"obj\"},{\"mode\":\"rw\",\"code\":\"work_mode\",\"name\":\"模式\",\"property\":{\"range\":[\"white\",\"colour\",\"scene\",\"music\"],\"type\":\"enum\"},\"iconname\":\"icon-dp_mode\",\"id\":21,\"type\":\"obj\"},{\"mode\":\"rw\",\"code\":\"bright_value\",\"name\":\"亮度值\",\"property\":{\"min\":10,\"max\":1000,\"scale\":0,\"step\":1,\"type\":\"value\"},\"iconname\":\"icon-liangdu1\",\"id\":22,\"type\":\"obj\"},{\"mode\":\"rw\",\"code\":\"temp_value\",\"name\":\"冷暖值\",\"property\":{\"min\":0,\"max\":1000,\"scale\":0,\"step\":1,\"type\":\"value\"},\"iconname\":\"icon-dp_half\",\"id\":23,\"type\":\"obj\"},{\"mode\":\"rw\",\"code\":\"colour_data\",\"name\":\"彩光\",\"property\":{\"type\":\"string\",\"maxlen\":255},\"iconname\":\"icon-yanse\",\"id\":24,\"type\":\"obj\"},{\"mode\":\"rw\",\"code\":\"scene_data\",\"name\":\"场景\",\"property\":{\"type\":\"string\",\"maxlen\":255},\"iconname\":\"icon-shoucang\",\"id\":25,\"type\":\"obj\"},{\"mode\":\"rw\",\"code\":\"countdown\",\"name\":\"倒计时剩余时间\",\"property\":{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1,\"type\":\"value\"},\"iconname\":\"icon-a_nav_timer\",\"id\":26,\"type\":\"obj\"},{\"mode\":\"wr\",\"code\":\"control_data\",\"name\":\"调节\",\"property\":{\"type\":\"string\",\"maxlen\":255},\"iconname\":\"icon-dp_box2\",\"id\":28,\"type\":\"obj\"},{\"mode\":\"rw\",\"code\":\"rhythm_mode\",\"name\":\"生物节律\",\"property\":{\"type\":\"raw\",\"maxlen\":128},\"iconname\":\"icon-dp_time3\",\"id\":30,\"type\":\"raw\"},{\"mode\":\"rw\",\"code\":\"sleep_mode\",\"name\":\"灯光助眠\",\"iconname\":\"icon-dp_sleep\",\"id\":31,\"type\":\"raw\"},{\"mode\":\"rw\",\"code\":\"wakeup_mode\",\"name\":\"灯光唤醒\",\"iconname\":\"icon-dp_sun\",\"id\":32,\"type\":\"raw\"},{\"mode\":\"rw\",\"code\":\"power_memory\",\"name\":\"断电记忆\",\"iconname\":\"icon-dp_lightning\",\"id\":33,\"type\":\"raw\"},{\"mode\":\"rw\",\"code\":\"do_not_disturb\",\"name\":\"停电勿扰\",\"property\":{\"type\":\"bool\"},\"iconname\":\"icon-dp_sleep\",\"id\":34,\"type\":\"obj\"}]"}

**Comment by Apollon77** [comment]
Next update
