### ISSUE TITLE
Zertifikatfehler | Error 50500 SmartLife App | SSL alert number 46 ioBroker -> Instanz Tuya.0

### ISSUE THREAD

**Issue by dodo-dk** [Apollon77/ioBroker.tuya#351]
Wenn man trotz korrektes befolgen der Anleitung den Netzwerkfehler 50500 in der SmartLife App bekommt und zudem im ioBroker Log irgendetwas in der Art `routines:ssl3_read_bytes:sslv3 alert certificate unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert number 46` steht könnte es helfen die Zertifikatdateien/Ordner im ioBroker zu löschen.

Dazu den Adapter anhalten und folgenden Ordner inklusive Inhalt löschen:
`/opt/iobroker/iobroker-data/tuya_0`

Anschließend den Adapter starten, den Proxy starten und wieder nach Anleitung vorgehen.

Viele Grüße

Dodo

**Comment by Apollon77** [comment]
The next version will recreate certs as soon as 3 months old

**Comment by Apollon77** [comment]
3.7.0

**Comment by Apollon77** [comment]
3.8.1
