### ISSUE TITLE
Fehlermeldungen bei Heizungssteuerung

### ISSUE THREAD

**Issue by trovanaffm** [Apollon77/ioBroker.tuya#363]
Hallo Apollon
ich habe ein Problem mit dem Schema 7qx0q329p61h1ace
Ich habe 2 Heizungssteuerungen verbaut und bekomme regelmäßig Fehler bei den IDs 16,26 und 102. 
Hier ist ein Scale Wert von 1 eingetragen (also multiplizierung * 10). 
Dadurch werden gerade bei ID16  "TEMP-SET" fehlerhafte Werte an die Geräte geschrieben. Dies äussert sich darin, das der Min wert auf 50 steht. Wenn nun ein Wert in dieses Objekt geschrieben wird, so wird der Min Wert mit 50 Grad Celsius an das Gerät geschrieben woraufhin die Temperatur hoch gefahren wird. 
Deshalb wären folgende Änderungen an der mapper.js sinnvoll in meinen Augen:

` "7qx0q329p61h1ace": {
        "schemaExt": "[]",
        "schema": "[{\"mode\":\"rw\",\"code\":\"switch\",\"name\":\"开关\",\"property\":{\"type\":\"bool\"},\"iconname\":\"icon-dp_power3\",\"id\":1,\"type\":\"obj\"},{\"mode\":\"rw\",\"code\":\"mode\",\"name\":\"工作模式\",\"property\":{\"range\":[\"auto\",\"manual\"],\"type\":\"enum\"},\"id\":2,\"type\":\"obj\"},{\"mode\":\"rw\",\"code\":\"frost\",\"name\":\"防霜冻功能\",\"property\":{\"type\":\"bool\"},\"iconname\":\"icon-chushuang\",\"id\":10,\"type\":\"obj\"},{\"mode\":\"rw\",\"code\":\"temp_set\",\"name\":\"设温\",\"property\":{\"unit\":\"℃\",\"min\":0.5,\"max\":1000,\"scale\":0.1,\"step\":0.5,\"type\":\"value\"},\"iconname\":\"icon-dp_temp\",\"id\":16,\"type\":\"obj\"},{\"mode\":\"rw\",\"code\":\"upper_temp\",\"name\":\"设置温度上限\",\"property\":{\"unit\":\"\",\"min\":50,\"max\":10000,\"scale\":1,\"step\":10,\"type\":\"value\"},\"iconname\":\"icon-dp_c\",\"id\":19,\"type\":\"obj\"},{\"mode\":\"rw\",\"code\":\"temp_unit_convert\",\"name\":\"温标切换\",\"property\":{\"range\":[\"c\",\"f\"],\"type\":\"enum\"},\"iconname\":\"icon-dp_loop\",\"id\":23,\"type\":\"obj\"},{\"mode\":\"ro\",\"code\":\"temp_current\",\"name\":\"当前温度\",\"property\":{\"unit\":\"℃\",\"min\":-300,\"max\":10000,\"scale\":1,\"step\":1,\"type\":\"value\"},\"iconname\":\"icon-wendu\",\"id\":24,\"type\":\"obj\"},{\"mode\":\"rw\",\"code\":\"lower_temp\",\"name\":\"设置温度下限\",\"property\":{\"unit\":\"\",\"min\":0.5,\"max\":1000,\"scale\":0.1,\"step\":1,\"type\":\"value\"},\"iconname\":\"icon-dp_c\",\"id\":26,\"type\":\"obj\"},{\"mode\":\"rw\",\"code\":\"week_program3\",\"name\":\"周程序（工作日）\",\"iconname\":\"icon-zhouchengxu\",\"id\":30,\"type\":\"raw\"},{\"mode\":\"rw\",\"code\":\"work_days\",\"name\":\"工作日设置\",\"property\":{\"range\":[\"5_2\",\"6_1\",\"7\"],\"type\":\"enum\"},\"iconname\":\"icon-zhouchengxu\",\"id\":31,\"type\":\"obj\"},{\"mode\":\"ro\",\"code\":\"valve_state\",\"name\":\"阀门状态\",\"property\":{\"range\":[\"close\",\"open\"],\"type\":\"enum\"},\"iconname\":\"icon-tcl_function_vs2\",\"id\":36,\"type\":\"obj\"},{\"mode\":\"rw\",\"code\":\"child_lock\",\"name\":\"童锁\",\"property\":{\"type\":\"bool\"},\"iconname\":\"icon-dp_lock\",\"id\":40,\"type\":\"obj\"},{\"mode\":\"ro\",\"code\":\"fault\",\"scope\":\"fault\",\"name\":\"故障告警\",\"property\":{\"label\":[\"e1\",\"e2\",\"e3\"],\"type\":\"bitmap\",\"maxlen\":3},\"iconname\":\"icon-dp_notice\",\"id\":45,\"type\":\"obj\"},{\"mode\":\"ro\",\"code\":\"support_features\",\"name\":\"支持的特性\",\"property\":{\"unit\":\"\",\"min\":0,\"max\":2147483647,\"scale\":1,\"step\":1,\"type\":\"value\"},\"id\":101,\"type\":\"obj\"},{\"mode\":\"ro\",\"code\":\"temp_adjust_step\",\"name\":\"温度调节步进\",\"property\":{\"unit\":\"\",\"min\":0.1,\"max\":5,\"scale\":0.1,\"step\":0.5,\"type\":\"value\"},\"id\":102,\"type\":\"obj\"},{\"mode\":\"ro\",\"code\":\"mfg_model\",\"name\":\"机型\",\"property\":{\"type\":\"string\",\"maxlen\":255},\"id\":105,\"type\":\"obj\"}]"
    },`

Ich habe diese Werte bei mir getestet und damit funktionieren die Heizungssteuerungen wie erwartet.

Getestet mit 2 BEOK WIFI Heizhermostaten:
https://www.amazon.de/dp/B09FJVRPK3/ref=cm_sw_em_r_mt_dp_WHHAM7Q5TXZFPAD97SAK?_encoding=UTF8&psc=1 
und 
https://www.amazon.de/dp/B09FJTF6N9/ref=cm_sw_em_r_mt_dp_TYJMX8XD9W0P46CPEATK?_encoding=UTF8&psc=1 

VG Harald

**Comment by Apollon77** [comment]
Hi,

if the schema contains this value and scale then it comes that way from tuya - and adjusting the schema defintion in "mapper" is not helping (just for "new users" ... but as soon as a user ready ourt his devices the schema from tuya is used and not the one in mapper.js ... 

SO which errors exactly you get?

please set adapter to debug loglevel and show a log from "receiving" and also setting values. In worst caser you "just" need to map the value yourself by writeing "correct" values in it, but I would like to see data from log, maybe I get an idea or it is a bug

**Comment by Apollon77** [comment]
PS: a "fix" for you is to edit the device object definition... but lets please check logs with original settings first

**Comment by trovanaffm** [comment]
Hi Ingo, 
so the Log File show me the following warning:

`2022-01-17 08:58:46.461 - warn: tuya.0 (10589) State value to set for "tuya.0.bf9b98df9332d02ec0hq3d.16" has value "20" less than min "50"
--
2022-01-17 08:58:46.462 - warn: tuya.0 (10589) State value to set for "tuya.0.bf9b98df9332d02ec0hq3d.26" has value "5" less than min "50"
2022-01-17 08:58:46.464 - warn: tuya.0 (10589) State value to set for "tuya.0.bf9b98df9332d02ec0hq3d.102" has value "0.5" less than min "1"
`
Perhaps you have an Idea how I can fix the problem especially with Objekt 16.

**Comment by Apollon77** [comment]
I need a debug loglevel log please: Go Admin - Instances - enable Expertmode - expand the instance - change loglevel from info to debug ...

**Comment by trovanaffm** [comment]
Attached the log file
[iobroker.2022-01-17.log](https://github.com/Apollon77/ioBroker.tuya/files/7880127/iobroker.2022-01-17.log)

**Comment by trovanaffm** [comment]
[iobroker.2022-01-17.log](https://github.com/Apollon77/ioBroker.tuya/files/7880131/iobroker.2022-01-17.log)
now with the correct log file

**Comment by Apollon77** [comment]
Ok, thats strange:
* The schema has the correct min/max values (0.5 and such)
* There is no code in the adapter that also uses the "scale" value on the provided min/max ... so why in your objects are these "wrong" values in?

Ha ... and I found it ... it seems that there was an error in the schema once it was first discovered because in the adapter the schema is different. :-(

The next version will contain the correct schema.

So your options are:
Option A
* try Github version (restart adapter manually after install) or wait for next version soon
* Delete the affected objects from iobroker
* Do a new Proxy sync

Option B
* manually fix the objects to contain the correct scale and min/max

**Comment by trovanaffm** [comment]
Hi Ingo, 
thanks for your reply. 
I'm happy that the fault was found in the schema and it is corrected. 
Thanks for your support.
