### ISSUE TITLE
Schema 7qx0q329p61h1ace

### ISSUE THREAD

**Issue by trovanaffm** [Apollon77/ioBroker.tuya#368]
Hi Ingo, 
there is another bug accured in Version 15, I updatet to this version and every time I tried to change datapoint 16 (TEMP_SET)
with 18 °C it overrides this value with 154.89 °C. 

Could it be that there is an issue with the scale value on htis Datapoint ? 
I changed it manually to scale 1 and after a restart everything works normaly
Attached you will find a log file.

[log file.txt](https://github.com/Apollon77/ioBroker.tuya/files/7964861/log.file.txt)

Thanks for your information about this issue. 

Harald

**Comment by Apollon77** [comment]
in next update
