### ISSUE TITLE
Please add support for Better Life Infrared Heater (pmxdTX2JLrSuJM39)

### ISSUE THREAD

**Issue by maxbragado** [Apollon77/ioBroker.tuya#38]
{"schema":"[{\"mode\":\"rw\",\"code\":\"Power\",\"name\":\"开关\",\"property\":{\"type\":\"bool\"},\"iconname\":\"icon-dp_power2\",\"id\":1,\"type\":\"obj\",\"desc\":\"\"},{\"mode\":\"rw\",\"code\":\"TempSet\",\"name\":\"目标温度\",\"property\":{\"unit\":\"℃\",\"min\":15,\"max\":30,\"scale\":0,\"step\":1,\"type\":\"value\"},\"iconname\":\"icon-dp_temp\",\"id\":2,\"type\":\"obj\",\"desc\":\"\"},{\"mode\":\"rw\",\"code\":\"Mode\",\"name\":\"模式\",\"property\":{\"range\":[\"0\",\"1\",\"2\"],\"type\":\"enum\"},\"iconname\":\"icon-dp_mode\",\"id\":4,\"type\":\"obj\",\"desc\":\"低档\\\\高档、ECO、\"},{\"mode\":\"rw\",\"code\":\"ChildLock\",\"name\":\"童锁\",\"property\":{\"type\":\"bool\"},\"iconname\":\"icon-dp_lock\",\"id\":6,\"type\":\"obj\",\"desc\":\"\"},{\"mode\":\"ro\",\"code\":\"Countdown\",\"name\":\"倒计时剩余时间\",\"property\":{\"unit\":\"H\",\"min\":0,\"max\":12,\"scale\":0,\"step\":1,\"type\":\"value\"},\"iconname\":\"icon-dp_time\",\"id\":11,\"type\":\"obj\",\"desc\":\"\"},{\"mode\":\"rw\",\"code\":\"TimeSet\",\"name\":\"定时功能\",\"property\":{\"unit\":\"H\",\"min\":0,\"max\":12,\"scale\":0,\"step\":1,\"type\":\"value\"},\"id\":101,\"type\":\"obj\",\"desc\":\"\"}]","schemaExt":"[]"}

**Comment by Apollon77** [comment]
thank you
