### ISSUE TITLE
LED Controller Smart Life 3.13 no connection

### ISSUE THREAD

**Issue by maxpd1** [Apollon77/ioBroker.tuya#384]
**Describe the bug**  
I tried to add this item https://futurehousestore.co.uk/smart-controllers/tuya-smart-wi-fi-controller-dc-5-24v.html via Smart Life App into iobroker.

Version 3.12.6 says it isn't compatible and I should upgrade. With 3.13 I see the controller in the app. But it seems that I don't get connected to adapter.

I downloaded certificate via QA code, gave it a name. Are there further steps to take to activate the certificate? 

I restarted the app and I am in my home WLAN.

Product doesn't seem to have an ESP but a wb3s chip.

**Expected behavior**  
I like to see the device under objects in iobroker.
At the moment also 0 > connection is set to false

**Versions:**  
 - Adapter version: latest
 - JS-Controller version: 3.3.22
 - Node version: 4.18.2

**Comment by Apollon77** [comment]
Oh hm .. seems they now phased out the app 3.12.6 for good ... I work on an alternative way to sync it ... but will need some days ... You can try the other apps maybe and reconnect the device via them? in the meantime

**Comment by maxpd1** [comment]
or I wait on you and am able to test your fix with you ;)

**Comment by LM-ku** [comment]
> Oh hm .. seems they now phased out the app 3.12.6 for good ... I work on an alternative way to sync it ... but will need some days ... You can try the other apps maybe and reconnect the device via them? in the meantime

The Wi-Fi plugs and thermostat are controlled by a Tuya 3.12.6 and Smart Life 3.12.1, but it is not possible to add these devices to the driver Tuya. I've tried Android simulator and an old phone with Android 4.4 - everything's inconclusive.

**Comment by Apollon77** [comment]
You can add the devices in 3.13 and then downgrade the app for the sync? Maybe

**Comment by Apollon77** [comment]
Please use 3.8.1 or try --> https://forum.iobroker.net/topic/59899/test-adapter-tuya-3-9-x-alpha-github
