### ISSUE TITLE
New Shema for wiINnkE8ASfAJSX6

### ISSUE THREAD

**Issue by maximaljan** [Apollon77/ioBroker.tuya#39]
Would be beautifull to have this avaiable.

tuya.0 {"schema":"[{\"mode\":\"rw\",\"code\":\"switch\",\"name\":\"开关\",\"property\":{\"type\":\"bool\"},\"id\":1,\"type\":\"obj\",\"desc\":\"\"},{\"mode\":\"rw\",\"code\":\"temperature_c\",\"name\":\"温度\",\"property\":{\"unit\":\"°C\",\"min\":0,\"max\":37,\"scale\":0,\"step\":1,\"type\":\"value\"},\"id\":2,\"type\":\"obj\",\"desc\":\"\"},{\"mode\":\"rw\",\"code\":\"temperature_f\",\"name\":\"华氏温度\",\"property\":{\"unit\":\"°F\",\"min\":32,\"max\":99,\"step\":1,\"type\":\"value\"},\"id\":3,\"type\":\"obj\",\"desc\":\"\"},{\"mode\":\"rw\",\"code\":\"exchange\",\"name\":\"华氏摄氏度切换\",\"property\":{\"type\":\"bool\"},\"id\":4,\"type\":\"obj\",\"desc\":\"\"},{\"mode\":\"ro\",\"code\":\"c_temperature\",\"name\":\"实际摄氏温度\",\"property\":{\"unit\":\"°C\",\"min\":0,\"max\":50,\"step\":1,\"type\":\"value\"},\"id\":5,\"type\":\"obj\",\"desc\":\"\"},{\"mode\":\"ro\",\"code\":\"f_temperature\",\"name\":\"实际华氏温度\",\"property\":{\"unit\":\"°F\",\"min\":32,\"max\":122,\"step\":1,\"type\":\"value\"},\"id\":6,\"type\":\"obj\",\"desc\":\"\"},{\"mode\":\"rw\",\"code\":\"appoint\",\"name\":\"预约\",\"property\":{\"unit\":\"m\",\"min\":0,\"max\":1440,\"range\":[0,60,120,180,240,300,360,420,480,540,600,660,720,780,840,900,960,1020,1080,1140,1200,1260,1320,1380,1440],\"step\":1,\"type\":\"value\"},\"id\":7,\"type\":\"obj\",\"passive\":true,\"desc\":\"\"},{\"mode\":\"rw\",\"code\":\"appoint_flag\",\"name\":\"预约标志位\",\"property\":{\"type\":\"bool\"},\"id\":8,\"type\":\"obj\",\"desc\":\"\"},{\"mode\":\"rw\",\"code\":\"TimerData\",\"name\":\"周程序\",\"id\":9,\"type\":\"raw\",\"desc\":\"\"},{\"mode\":\"rw\",\"code\":\"smartTimer\",\"name\":\"定时\",\"property\":{\"range\":[\"holiday\",\"program\"],\"type\":\"enum\"},\"id\":10,\"type\":\"obj\",\"desc\":\"\"}]","schemaExt":"[]"}

**Comment by Apollon77** [comment]
Thank you
