### ISSUE TITLE
Please add new schema for product type 5tnccdqna35enim9

### ISSUE THREAD

**Issue by RP70DP** [Apollon77/ioBroker.tuya#393]
``
{"schemaExt":"[{\"complexType\":\"\",\"id\":22,\"inputStyle\":\"\",\"inputType\":\"percent1\"},{\"complexType\":\"\",\"id\":23,\"inputStyle\":\"\",\"inputType\":\"percent\"},{\"complexType\":\"\",\"id\":26,\"inputStyle\":\"\",\"inputType\":\"countdown1\"}]","schema":"[{\"mode\":\"rw\",\"code\":\"switch_led\",\"name\":\"开关\",\"property\":{\"type\":\"bool\"},\"iconname\":\"icon-dp_power\",\"id\":20,\"type\":\"obj\"},{\"mode\":\"rw\",\"code\":\"work_mode\",\"name\":\"模式\",\"property\":{\"range\":[\"white\",\"colour\",\"scene\",\"music\"],\"type\":\"enum\"},\"iconname\":\"icon-dp_mode\",\"id\":21,\"type\":\"obj\"},{\"mode\":\"rw\",\"code\":\"colour_data\",\"name\":\"彩光\",\"property\":{\"type\":\"string\",\"maxlen\":255},\"iconname\":\"icon-yanse\",\"id\":24,\"type\":\"obj\"},{\"mode\":\"rw\",\"code\":\"scene_data\",\"name\":\"场景\",\"property\":{\"type\":\"string\",\"maxlen\":255},\"iconname\":\"icon-shoucang\",\"id\":25,\"type\":\"obj\"},{\"mode\":\"rw\",\"code\":\"countdown\",\"name\":\"倒计时\",\"property\":{\"min\":0,\"max\":86400,\"scale\":0,\"step\":1,\"type\":\"value\"},\"iconname\":\"icon-a_nav_timer\",\"id\":26,\"type\":\"obj\"},{\"mode\":\"wr\",\"code\":\"music_data\",\"name\":\"音乐律动\",\"property\":{\"type\":\"string\",\"maxlen\":255},\"iconname\":\"icon-dp_mic\",\"id\":27,\"type\":\"obj\"},{\"mode\":\"rw\",\"code\":\"mic_music_data\",\"name\":\"麦克风音乐律动\",\"property\":{\"type\":\"string\",\"maxlen\":255},\"iconname\":\"icon-dp_mode\",\"id\":42,\"type\":\"obj\"},{\"mode\":\"rw\",\"code\":\"dreamlightmic_music_data\",\"name\":\"炫彩本地音乐律动\",\"property\":{\"type\":\"raw\",\"maxlen\":\"255\"},\"iconname\":\"icon-dp_mode\",\"id\":52,\"type\":\"raw\"}]"} 
``

**Comment by RP70DP** [comment]
Please add new schema.

**Comment by Apollon77** [comment]
will be in next version
