### ISSUE TITLE
New shema for YWK0ZiumXZGkb8nj roller shutter wall switch

### ISSUE THREAD

**Issue by BigDi** [Apollon77/ioBroker.tuya#40]
I bought a roller shutter wall swich from aliexpress. I tried to integrade it in io.broker. But it seems that that sheme is missing. I can't control the switch.
Here are the lines from the log file:
info: tuya.0 new Shema added for product type YWK0ZiumXZGkb8nj. Please send next line from logfile on disk to developer!
--
2019-04-21 17:36:31.772  - info:  tuya.0  {"schema":"[{\"mode\":\"rw\",\"code\":\"status\",\"name\":\"窗帘状态\",\"property\":{\"range\":[\"0\",\"1\",\"2\",\"3\"],\"type\":\"enum\"},\"id\":1,\"type\":\"obj\",\"desc\":\"开  关 暂停\"}]","schemaExt":"[]"}

**Comment by BigDi** [comment]
Woran liegt es, dass "mein" ausgelesenes Schema nur so kurz ist? Über die App lässt sich viel mehr steuern

**Comment by Apollon77** [comment]
Keine Ahnung. An sich sollte die App das gleiche Schema nutzen as I know. ggf nochmal mit Proxy syncen und schauen ob mehr kommt?

**Comment by BigDi** [comment]
Oder die haben es sich wirklich einfach gemacht und steuern den Schalter über den Status. Der Timer wird dann über die Cloud abgewickelt.

**Comment by BigDi** [comment]
Ich muss da noch einmal nachfragen. Ich hatte den Schalter zwar in iobroker hinterlegt, aber nicht benutzt, da ich der Meinung war, dass ich ein Update des Adapter brauche, um ihn zu benutzen. Da lag ich schonmal falsch. 
Ich habe den Schalter entfernt und über den Proxy erneut hinzugefügt. Soweit so gut. Aber es passiert nichts, wenn ich den Status per Hand nun ändere. Zwischendurch wird die Zahl grün. Heißt dies, der Wert wurde aktualisiert?
In der Instanz  steht "Status: 1 Geräte im Netzwerk gefunden, 0 Geräte verbunden, 1 mit bekanntem Schema, 1 initialisiert für Echtzeit-Updates und zur Steuerung". Der Schalter ist über den Alexa Skill verbunden. Die App ist entladen, aber das Profil ist angemeldet.
Muss ich mich überall abmelden, damit es mit iobroker funktioniert?

**Comment by Apollon77** [comment]
Ne das Schema wird nur gemeldet das ich es einbauen kann das es bei anderen Usersn gleich automatisch erkannt werden kann. Nach einmal proxy sync ist es bei dir vorhanden.
Also wenn grün wird dann heisst das an sich das das gerät den wert bestätigt hat. bzw er meldet dann den neuen aktuellen wert zurück.
Für mehr müsste ich Debug log sehen

**Comment by Apollon77** [comment]
..und am besten weiter im Forum

**Comment by Apollon77** [comment]
thank you
