### ISSUE TITLE
Can't import new lamp into tuya driver via proxy

### ISSUE THREAD

**Issue by paveltsytovich** [Apollon77/ioBroker.tuya#405]
I use instruction for import new lamp into tyua driver and I can't import my new device. When I run proxy and them open smartlife 3.12 app on my android emulator - proxy not see new lamp and don't stop automatically. In iobroker log I see many errors in SSL : 

![image](https://user-images.githubusercontent.com/1669930/161376760-2e68e274-b47c-4572-93c1-ad7bb5c7ff74.png)

I instelled ca.pem and setup wi-fi proxy in my android emulator

**Versions:**  
 - Adapter version: 3.6.15
 - JS-Controller version: 4.0.21
 - Node version: 14.19.1
 - Operating system: rapsberrian 32bit

**Comment by Apollon77** [comment]
If you see these ssl errors then most likely the ssl cert is not added correctly to the android

**Comment by paveltsytovich** [comment]
> If you see these ssl errors then most likely the ssl cert is not added correctly to the android

I following instruction for this driver and install certificate from tuya`s driver for Wi-FI and VPN-app

**Comment by paveltsytovich** [comment]
If you have little bit time I could show  my problem via zoom.  I ask into iobroker telegram channel and give answers that some people has same issue too

**Comment by Apollon77** [comment]
Which Android version do you used? please use older one line Android 8 ...

I know that this whole proxy sync is not ideal anymore (and hinestly I never tried it at Android myself - Android manual was provided by community). So I only know the common pitfalls.

In worst case you need to wait until the alternative sync method is ready, sorry

**Comment by paveltsytovich** [comment]
I used Android 7.1 in EMemu Android emulator.  I think about following approach::

1. Take exits Lamp`s object and export to json file
2.  Change property with id, mac and etc (id and mac we can get from smart lifer app)
3. Import into tuya object tree

I try apply this approach but driver not see new object. Could you advice, what should I change in properties which your driver can see my object  or this approach not impossible? 

How soon do you plan to implement an alternative method? Is there anything I can do to help you?

**Comment by Apollon77** [comment]
post the pbject you tried? In fact the object ID mus match to what the device reports ... but then this should work WITH a restart of the adapter!!

**Comment by Apollon77** [comment]
And you need to put in the IP!

**Comment by paveltsytovich** [comment]
I changed identifier, ip and id (from smartlife app), but can't work. Could you please advice me, what property of lamp I should change?

{
  "tuya.0.bfa1a303d373c38fb314hq": {
    "type": "device",
    "common": {
      "name": "Lamp # 4",
      "read": true
    },
    "native": {
      "virtual": false,
      "dpName": {},
      "lon": "30.3643525",
      "uuid": "07524102286dcd74510d",
      "mac": "286dcd74510d",
      "iconUrl": "https://images.tuyaeu.com/smart/icon/001460162698766TR4v1/55b5daf5cdd9fb30c7c045f457770fbe.png",
      "runtimeEnv": "prod",
      "lat": "59.8103293",
      "devId": "bfa1a303d373c38fb314hq",
      "dpMaxTime": 1623998060378,
      "productId": "qoqolwtqzfuhgghq",
      "activeTime": 1623996832,
      "categoryCode": "wf_dj",
      "moduleMap": {
        "wifi": {
          "upgradeStatus": 0,
          "cdv": "1.0.0",
          "bv": "30.01",
          "pv": "2.2",
          "verSw": "1.4.2",
          "isOnline": false,
          "id": 24793776,
          "cadv": "1.0.1"
        },
        "mcu": {
          "upgradeStatus": 0,
          "cdv": "",
          "verSw": "1.4.2",
          "isOnline": false,
          "id": 24793775,
          "cadv": ""
        }
      },
      "devAttribute": 0,
      "name": "Лампа # 4",
      "timezoneId": "Europe/Warsaw",
      "category": "dj",
      "localKey": "0e5fe371e5324637",
      "schema": [
        {
          "mode": "rw",
          "code": "switch_led",
          "name": "开关",
          "property": {
            "type": "bool"
          },
          "iconname": "icon-dp_powe",
          "id": 20,
          "type": "obj"
        },
        {
          "mode": "rw",
          "code": "work_mode",
          "name": "模式",
          "property": {
            "range": [
              "white",
              "colour",
              "scene",
              "music"
            ],
            "type": "enum"
          },
          "iconname": "icon-dp_mode",
          "id": 21,
          "type": "obj"
        },
        {
          "mode": "rw",
          "code": "bright_value",
          "name": "亮度值",
          "property": {
            "min": 10,
            "max": 1000,
            "scale": 0,
            "step": 1,
            "type": "value"
          },
          "iconname": "icon-liangdu1",
          "id": 22,
          "type": "obj"
        },
        {
          "mode": "rw",
          "code": "temp_value",
          "name": "冷暖值",
          "property": {
            "min": 0,
            "max": 1000,
            "scale": 0,
            "step": 1,
            "type": "value"
          },
          "iconname": "icon-dp_half",
          "id": 23,
          "type": "obj"
        },
        {
          "mode": "rw",
          "code": "colour_data",
          "name": "彩光",
          "property": {
            "type": "string",
            "maxlen": 255
          },
          "iconname": "icon-yanse",
          "id": 24,
          "type": "obj"
        },
        {
          "mode": "rw",
          "code": "scene_data",
          "name": "场景",
          "property": {
            "type": "string",
            "maxlen": 255
          },
          "iconname": "icon-shoucang",
          "id": 25,
          "type": "obj"
        },
        {
          "mode": "rw",
          "code": "countdown",
          "name": "倒计时",
          "property": {
            "min": 0,
            "max": 86400,
            "scale": 0,
            "step": 1,
            "type": "value"
          },
          "iconname": "icon-a_nav_timer",
          "id": 26,
          "type": "obj"
        },
        {
          "mode": "rw",
          "code": "music_data",
          "name": "音乐灯",
          "property": {
            "type": "string",
            "maxlen": 255
          },
          "iconname": "icon-dp_mic",
          "id": 27,
          "type": "obj"
        },
        {
          "mode": "rw",
          "code": "control_data",
          "name": "调节",
          "property": {
            "type": "string",
            "maxlen": 255
          },
          "iconname": "icon-dp_box2",
          "id": 28,
          "type": "obj"
        }
      ],
      "productKey": "qoqolwtqzfuhgghq",
      "schemaExt": [
        {
          "complexType": "",
          "id": 20,
          "inputStyle": "",
          "inputType": " "
        },
        {
          "complexType": "",
          "id": 21,
          "inputStyle": "",
          "inputType": " "
        },
        {
          "complexType": "",
          "id": 22,
          "inputStyle": "",
          "inputType": " "
        },
        {
          "complexType": "",
          "id": 23,
          "inputStyle": "",
          "inputType": " "
        },
        {
          "complexType": "",
          "id": 26,
          "inputStyle": "",
          "inputType": " "
        }
      ],
      "version": "3.3",
      "ip": "192.168.88.20",
      "gwId": "bfa1a303d373c38fb314hq",
      "active": 2,
      "ablilty": 0,
      "encrypt": true
    },
    "from": "system.adapter.tuya.0",
    "user": "system.user.admin",
    "ts": 1648890076902,
    "_id": "tuya.0.bfa1a303d373c38fb314hq",
    "acl": {
      "object": 1636,
      "owner": "system.user.admin",
      "ownerGroup": "system.group.administrator"
    }
  },
  "tuya.0.bfa1a303d373c38fb314hq.20": {
    "type": "state",
    "common": {
      "type": "boolean",
      "read": true,
      "write": true,
      "name": "switch_led",
      "role": "switch"
    },
    "native": {},
    "from": "system.adapter.tuya.0",
    "user": "system.user.admin",
    "ts": 1648890076929,
    "_id": "tuya.0.bfa1a303d373c38fb314hq.20",
    "acl": {
      "object": 1636,
      "state": 1636,
      "owner": "system.user.admin",
      "ownerGroup": "system.group.administrator"
    }
  },
  "tuya.0.bfa1a303d373c38fb314hq.21": {
    "type": "state",
    "common": {
      "type": "number",
      "states": {
        "0": "white",
        "1": "colour",
        "2": "scene",
        "3": "music"
      },
      "read": true,
      "write": true,
      "name": "work_mode",
      "role": "level"
    },
    "native": {},
    "from": "system.adapter.tuya.0",
    "user": "system.user.admin",
    "ts": 1648890076931,
    "_id": "tuya.0.bfa1a303d373c38fb314hq.21",
    "acl": {
      "object": 1636,
      "state": 1636,
      "owner": "system.user.admin",
      "ownerGroup": "system.group.administrator"
    }
  },
  "tuya.0.bfa1a303d373c38fb314hq.22": {
    "type": "state",
    "common": {
      "type": "number",
      "min": 10,
      "max": 1000,
      "read": true,
      "write": true,
      "name": "bright_value",
      "role": "level"
    },
    "native": {},
    "from": "system.adapter.tuya.0",
    "user": "system.user.admin",
    "ts": 1648890076931,
    "_id": "tuya.0.bfa1a303d373c38fb314hq.22",
    "acl": {
      "object": 1636,
      "state": 1636,
      "owner": "system.user.admin",
      "ownerGroup": "system.group.administrator"
    }
  },
  "tuya.0.bfa1a303d373c38fb314hq.23": {
    "type": "state",
    "common": {
      "type": "number",
      "max": 1000,
      "read": true,
      "write": true,
      "name": "temp_value",
      "role": "level"
    },
    "native": {},
    "from": "system.adapter.tuya.0",
    "user": "system.user.admin",
    "ts": 1648890076937,
    "_id": "tuya.0.bfa1a303d373c38fb314hq.23",
    "acl": {
      "object": 1636,
      "state": 1636,
      "owner": "system.user.admin",
      "ownerGroup": "system.group.administrator"
    }
  },
  "tuya.0.bfa1a303d373c38fb314hq.24": {
    "type": "state",
    "common": {
      "type": "string",
      "read": true,
      "write": true,
      "name": "colour_data",
      "role": "text"
    },
    "native": {},
    "from": "system.adapter.tuya.0",
    "user": "system.user.admin",
    "ts": 1648890076946,
    "_id": "tuya.0.bfa1a303d373c38fb314hq.24",
    "acl": {
      "object": 1636,
      "state": 1636,
      "owner": "system.user.admin",
      "ownerGroup": "system.group.administrator"
    }
  },
  "tuya.0.bfa1a303d373c38fb314hq.25": {
    "type": "state",
    "common": {
      "type": "string",
      "read": true,
      "write": true,
      "name": "scene_data",
      "role": "text"
    },
    "native": {},
    "from": "system.adapter.tuya.0",
    "user": "system.user.admin",
    "ts": 1648890076951,
    "_id": "tuya.0.bfa1a303d373c38fb314hq.25",
    "acl": {
      "object": 1636,
      "state": 1636,
      "owner": "system.user.admin",
      "ownerGroup": "system.group.administrator"
    }
  },
  "tuya.0.bfa1a303d373c38fb314hq.26": {
    "type": "state",
    "common": {
      "type": "number",
      "max": 86400,
      "read": true,
      "write": true,
      "name": "countdown",
      "role": "level"
    },
    "native": {},
    "from": "system.adapter.tuya.0",
    "user": "system.user.admin",
    "ts": 1648890076953,
    "_id": "tuya.0.bfa1a303d373c38fb314hq.26",
    "acl": {
      "object": 1636,
      "state": 1636,
      "owner": "system.user.admin",
      "ownerGroup": "system.group.administrator"
    }
  },
  "tuya.0.bfa1a303d373c38fb314hq.27": {
    "type": "state",
    "common": {
      "type": "string",
      "read": true,
      "write": true,
      "name": "music_data",
      "role": "text"
    },
    "native": {},
    "from": "system.adapter.tuya.0",
    "user": "system.user.admin",
    "ts": 1648890076957,
    "_id": "tuya.0.bfa1a303d373c38fb314hq.27",
    "acl": {
      "object": 1636,
      "state": 1636,
      "owner": "system.user.admin",
      "ownerGroup": "system.group.administrator"
    }
  },
  "tuya.0.bfa1a303d373c38fb314hq.28": {
    "type": "state",
    "common": {
      "type": "string",
      "read": true,
      "write": true,
      "name": "control_data",
      "role": "text"
    },
    "native": {},
    "from": "system.adapter.tuya.0",
    "user": "system.user.admin",
    "ts": 1648890076959,
    "_id": "tuya.0.bfa1a303d373c38fb314hq.28",
    "acl": {
      "object": 1636,
      "state": 1636,
      "owner": "system.user.admin",
      "ownerGroup": "system.group.administrator"
    }
  },
  "tuya.0.bfa1a303d373c38fb314hq.ip": {
    "type": "state",
    "common": {
      "name": "Device IP",
      "type": "string",
      "role": "info.ip",
      "read": true,
      "write": false
    },
    "native": {},
    "from": "system.adapter.tuya.0",
    "user": "system.user.admin",
    "ts": 1648890076908,
    "_id": "tuya.0.bfa1a303d373c38fb314hq.ip",
    "acl": {
      "object": 1636,
      "state": 1636,
      "owner": "system.user.admin",
      "ownerGroup": "system.group.administrator"
    }
  },
  "tuya.0.bfa1a303d373c38fb314hq.online": {
    "type": "state",
    "common": {
      "name": "Device online status",
      "type": "boolean",
      "role": "indicator.reachable",
      "read": true,
      "write": false
    },
    "native": {},
    "from": "system.adapter.tuya.0",
    "user": "system.user.admin",
    "ts": 1648890076902,
    "_id": "tuya.0.bfa1a303d373c38fb314hq.online",
    "acl": {
      "object": 1636,
      "state": 1636,
      "owner": "system.user.admin",
      "ownerGroup": "system.group.administrator"
    }
  }
}

**Comment by Apollon77** [comment]
Is the device an encrypted one or not? Becase ifg encrypted then you would also need to know the encryption key to decreypt the communication ... so without this it will not work that way

**Comment by paveltsytovich** [comment]
I think my device is encrypted.  How I can know this decryption key and what property of decrypt key? May be I use proxy? but in my case proxy get error with SSL :-( . How you installed you devices without android app? iphone or other approach?

I hope that I can use proxy, but I can't resolve issue with SSL :(

**Comment by Apollon77** [comment]
I used iOS but thats long time ago as app versions were working ... Or be patient till I have finished the alternative method

**Comment by paveltsytovich** [comment]
My method with export exists object->change property->import into iob work correctly. I got local_key from iot.tuya.com and all work fine. Perhaps this information will be useful to you to modify the driver

**Comment by Apollon77** [comment]
3.8.1 do not need proxy anymore
