### ISSUE TITLE
AC's wrong temperature range (product key hw50w7qvxluhslkk and 2si3Y6O3K2rK9XBr)

### ISSUE THREAD

**Issue by Percy2Live** [Apollon77/ioBroker.tuya#407]
Hi,

for my AC's I can see that the datapoint range for the temperature set is not correct.
This is what the log file states:

```
2022-04-22 00:00:35.216 - warn: tuya.0 (764) State value to set for "tuya.0.88430000500291be7eed.2" has value "26" less than min "160"
2022-04-22 00:01:35.376 - warn: tuya.0 (764) State value to set for "tuya.0.88430000500291be7eed.2" has value "26" less than min "160"
2022-04-22 00:02:38.007 - warn: tuya.0 (764) State value to set for "tuya.0.88430000500291be7eed.2" has value "26" less than min "160"
```

This is what the datapoint states: 
```
{
  "type": "state",
  "common": {
    "type": "number",
    "unit": "℃",
    "min": 160,
    "max": 880,
    "scale": 1,
    "read": true,
    "write": true,
    "name": "temp_set",
    "role": "level"
  },
  "native": {},
  "_id": "tuya.0.50081216bcddc26f503a.2",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  },
  "from": "system.adapter.tuya.0",
  "user": "system.user.admin",
  "ts": 1650482239496
}

```

This might be related to #368 

It happens for the products with the product keys hw50w7qvxluhslkk and 2si3Y6O3K2rK9XBr

**Versions:**  
 - Adapter version: v3.6.15
 - JS-Controller version: 3.3.22
 - Node version: 14.18.3
 - Operating system: Docker Container

**Comment by Apollon77** [comment]
Please show the JSON from the device object ... there the Schema defintion from Tuya is in where all this bases on. Seems like a wrong factor was provided by Tuya for min/max ...

**Comment by Apollon77** [comment]
interesting that noone else sumbled over that so far ... min/max values are not converted based on the scale ... iiiinteresting.

For now please manually adjist the ".2" object and sset im/max correctly (divide by 10) ... Next version will do that for new devices

**Comment by Ilovegym66** [comment]
Since my sd-card in the LSC Videodoorbell is broken, I got this warning from the tuya-Adapter, looks like a simular problem?:

Log:
`2022-04-24 10:21:46.622  - warn: tuya.0 (3144282) State value to set for "tuya.0.bf2281494e0b9e1ed74rmh.110" has value "0.2" less than min "1"
2022-04-24 10:21:46.622  - warn: tuya.0 (3144282) State value to set for "tuya.0.bf2281494e0b9e1ed74rmh.110" has value "0.2" less than min "1"
2022-04-24 10:21:47.292  - warn: tuya.0 (3144282) State value to set for "tuya.0.bf2281494e0b9e1ed74rmh.110" has value "0.5" less than min "1"
2022-04-24 10:21:47.292  - warn: tuya.0 (3144282) State value to set for "tuya.0.bf2281494e0b9e1ed74rmh.110" has value "0.5" less than min "1"
`

Object:
`{
  "type": "state",
  "common": {
    "type": "number",
    "min": 1,
    "max": 5,
    "scale": 1,
    "read": true,
    "write": false,
    "name": "sd_status",
    "role": "value",
    "custom": {
      "influxdb.0": {
        "enabled": true,
        "storageType": "",
        "aliasId": "",
        "changesOnly": true,
        "debounce": 1000,
        "changesRelogInterval": "3600",
        "changesMinDelta": 1
      }
    }
  },
  "native": {},
  "_id": "tuya.0.bf2281494e0b9e1ed74rmh.110",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  },
  "from": "system.adapter.tuya.0",
  "user": "system.user.admin",
  "ts": 1650639492448
}`

**Comment by Apollon77** [comment]
Please post the device object then we see if on "id 2" also a scale is set

**Comment by Apollon77** [comment]
@Ilovegym66 ?

**Comment by Ilovegym66** [comment]
ah, sorry, forgot to provide.. 
here the object, Adapter version is actual from github, stopped, uploaded, started, you found a min and max define between there.. :
`
{
  "type": "state",
  "common": {
    "type": "number",
    "scale": 1,
    "read": true,
    "write": false,
    "name": "sd_status",
    "role": "value",
    "custom": {
      "influxdb.0": {
        "enabled": true,
        "storageType": "",
        "aliasId": "",
        "changesOnly": true,
        "debounce": 1000,
        "changesRelogInterval": 3600,
        "changesMinDelta": 1,
        "enableDebugLogs": false,
        "debounceTime": 1000,
        "retention": 63072000,
        "maxLength": 10,
        "ignoreZero": false,
        "blockTime": 0,
        "ignoreBelowNumber": "",
        "disableSkippedValueLogging": false
      },
      "influxdb.1": {
        "enabled": true,
        "storageType": "",
        "aliasId": "",
        "debounceTime": 1000,
        "blockTime": 0,
        "changesOnly": true,
        "changesRelogInterval": 3600,
        "changesMinDelta": 1,
        "ignoreBelowNumber": "",
        "disableSkippedValueLogging": false,
        "enableDebugLogs": false,
        "debounce": 1000,
        "maxLength": 10
      }
    },
    "min": 1,
    "max": 5
  },
  "native": {},
  "_id": "tuya.0.bf2281494e0b9e1ed74rmh.110",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  },
  "from": "system.adapter.tuya.0",
  "user": "system.user.admin",
  "ts": 1659262041499
}
`

current warnings in the log:

`
tuya.0 | 2022-07-31 12:09:20.340 | warn | State value to set for "tuya.0.bf2281494e0b9e1ed74rmh.110" has value "0.5" less than min "1"
-- | -- | -- | --
tuya.0 | 2022-07-31 12:09:19.667 | warn | State value to set for "tuya.0.bf2281494e0b9e1ed74rmh.110" has value "0.2" less than min "1"

`

**Comment by Apollon77** [comment]
should be fixed in next version
