### ISSUE TITLE
WiFi Alexa Light Switch 

### ISSUE THREAD

**Issue by BrummF** [Apollon77/ioBroker.tuya#408]
I installed the TUYA adapter in my IoBroker installation running in a docker container.
I forwarded the ports 8888/8889 and the UDP ports 6666/6667 to the container.
After that i used the android emulator and the smart life app V3.12.6. Everything worked as expected.

After that the data points of the light switch were created but the adapter showed no connection to the device
![image](https://user-images.githubusercontent.com/35379524/164913927-f08f3356-3636-40d1-8888-6128858debc8.png)

In the log file a saw that the adapter tries to connect the device via port 6668. so I forwarded this port also, but without a positive result.
![image](https://user-images.githubusercontent.com/35379524/164913940-78188b36-5063-4716-a8e1-cb1ee828cb5c.png)

**Versions:**  
 - Adapter version: Tuya 3.6.15
 - JS-Controller version: 4.0.21
 - Node version: v14.19.1
 - Operating system:  ubuntu 20 LTS

**Comment by Apollon77** [comment]
EHOSTUNREACH means that the debice is not reachable in your network ... most likely WLAN is bad or such?  check the device, try power off/on. pot try if you can conect to the given port
