### ISSUE TITLE
"Network error" when trying to sync via proxy

### ISSUE THREAD

**Issue by stuermera** [Apollon77/ioBroker.tuya#42]
I synced my devices a week ago without problems.

Today I added another switch and wanted to re-sync - same procedure as before - pressed the "Start proxy" button, connected to WiFi and manual proxy with my hosts IP and port 8888.
Switching sockets works fine in Tuya app, but after a few seconds I get an error "network connection error" in the Tuya app.

Any idea?

**Comment by Apollon77** [comment]
Then it seems that the proxy is not set up correctly. Is the Certificate enabled? Is the proxy set up correctly for the WLAN connection? Please also check images and infos on GitHub README and subpage.

On port 8889 yu can see a webinterface of the proxy in the adapter. If you only see CONNECT there then SSL cert is incorrect. Or else what you see there?

**Comment by Reuli61** [comment]
Ich habe das gleiche Problem. Es funktioniert nicht. Es startet kein Proxy.

**Comment by schreda** [comment]
Same for me.. Proxy doesn't start.
Anyway i have to wait for a fix for fw2.0...

**Comment by Apollon77** [comment]
Was sagt das Log? Was heisst "Proxy startet nicht"?

**Comment by ChristianHoefer** [comment]
War bei mir anfangs auch so. Nach einigem mal drauf klicken und Adapter neu starten ging es dann dauerhaft und Problemlos. 

@Apollon77 "Proxy startet nicht" heißt (in meinem Fall) dass das Modal mit dem QR-Code nicht aufgeht und damit das Zertifikat nicht heruntergeladen werden kann.

**Comment by Reuli61** [comment]
Richtig. So ist es. Das Modul geht nicht auf.

**Comment by Reuli61** [comment]
tuya.1 | 2019-05-04 18:56:20.521 | error | at Module.require (module.js:597:17)
-- | -- | -- | --
tuya.1 | 2019-05-04 18:56:20.521 | error | at Function.Module._load (module.js:498:3)
tuya.1 | 2019-05-04 18:56:20.521 | error | at tryModuleLoad (module.js:506:12)
tuya.1 | 2019-05-04 18:56:20.521 | error | at Module.load (module.js:566:32)
tuya.1 | 2019-05-04 18:56:20.521 | error | at Object.Module._extensions..js (module.js:664:10)
tuya.1 | 2019-05-04 18:56:20.521 | error | at Module._compile (module.js:653:30)
tuya.1 | 2019-05-04 18:56:20.521 | error | at Object.<anonymous> (/opt/iobroker/node_modules/brotli/compress.js:1:76)
tuya.1 | 2019-05-04 18:56:20.521 | error | at require (internal/module.js:11:18)
tuya.1 | 2019-05-04 18:56:20.521 | error | at Module.require (module.js:597:17)
tuya.1 | 2019-05-04 18:56:20.521 | error | at Function.Module._load (module.js:498:3)
tuya.1 | 2019-05-04 18:56:20.521 | error | at tryModuleLoad (module.js:506:12)
tuya.1 | 2019-05-04 18:56:20.521 | error | at Module.load (module.js:566:32)
tuya.1 | 2019-05-04 18:56:20.521 | error | at Object.Module._extensions..js (module.js:664:10)
tuya.1 | 2019-05-04 18:56:20.521 | error | at Module._compile (module.js:653:30)
tuya.1 | 2019-05-04 18:56:20.521 | error | at Object.<anonymous> (/opt/iobroker/node_modules/brotli/build/encode.js:21:207)
tuya.1 | 2019-05-04 18:56:20.521 | error | at new ArrayBuffer (<anonymous>)
tuya.1 | 2019-05-04 18:56:20.521 | error | RangeError: Array buffer allocation failed
tuya.1 | 2019-05-04 18:56:20.520 | error | message messagebox.system.adapter.tuya.1 [object Object] Array buffer allocation failed

**Comment by Reuli61** [comment]
tuya.1 | 2019-05-04 18:58:59.839 | error | RangeError: Array buffer allocation failed at new ArrayBuffer (<anonymous>) at Object.<anonymous> (/opt/iobroker/node_modules/brotli/build/encode.js:21:207) at Module._compile (module.js:6
-- | -- | -- | --
tuya.1 | 2019-05-04 18:58:59.838 | error | message messagebox.system.adapter.tuya.1 [object Object] Array buffer allocation failed
tuya.1 | 2019-05-04 18:58:59.670 | error | RangeError: Array buffer allocation failed at new ArrayBuffer (<anonymous>) at Object.<anonymous> (/opt/iobroker/node_modules/brotli/build/encode.js:21:207) at Module._compile (module.js:6
tuya.1 | 2019-05-04 18:58:59.669 | error | message messagebox.system.adapter.tuya.1 [object Object] Array buffer allocation failed

**Comment by Reuli61** [comment]
Ich habe es. Zu wenig Speicher. Einige beendet. Dann lief es.

**Comment by ChristianHoefer** [comment]
Ich habe gerade nochmal eine neue iobroker Instanz aufgesetzt und nur diesen Adapter installiert. Das Modal mit dem QR Code ging erst auf nachdem der Adapter neugestartet wurde.

**Comment by Reuli61** [comment]
Jetzt hat das Proxy Modul gestartet. Alles synchronisiert. Aber Geräte im Netzwerk gefunden aber mit keinen verbunden.
Status: 10 Geräte im Netzwerk gefunden, 0 Geräte verbunden, 10 mit bekanntem Schema, 10 initialisiert für Echtzeit-Updates und zur Steuerung
Ich verstehe es nicht.

**Comment by Reuli61** [comment]
Noch mal den Adapter beenden und starten. Das wars.
Manchmal sieht man den Wald vor lauter Bäumen nicht.

**Comment by stuermera** [comment]
Sorry, what I meant was...
AnyProxy installed on iPhone, Certificate granted.
I enter the ioBroker IP and 8888 as port on my iPhone WiFI connection.
I start the proxy on ioBroker/Tuya plugin.
I start TUYA app... it does nothing except an error after a few seconds that no internet connection can established - browser is working.

It seems TUYA has "fixed" the issue that AnyProxy can be used?

**Comment by Apollon77** [comment]
Hm, das muss man mal prüfen.

**Comment by stuermera** [comment]
Es hatte vor ner Woche auch noch funktioniert.
Aktuell dürften alle Zugriffe auf die Tuya Server blockiert werden - ich kann mit aktiviertem Proxy im WLAN am iPhone jede Seite ansurfen, nur www.tuya.com nicht. Ohne Proxy gehts.

**Comment by ChristianHoefer** [comment]
Ich habe das eben noch Probiert und da hat es auf anhieb funktioniert:
<img width="1669" alt="Bildschirmfoto 2019-05-09 um 00 31 31" src="https://user-images.githubusercontent.com/6047702/57412741-103d7c00-71f2-11e9-9001-57d8373143a8.png">

**Comment by stuermera** [comment]
Eigenartig. Ist immer eine 1/100 Chance bei mir.

**Comment by 9steff2** [comment]
also ich bekomme es ebenfalls nicht hin, Proxy gestartet und das Zertifikat runtergeladen, installiert und aktiviert, aber sobald den Proxy manuell auf dem iPhone eingebe, habe ich einen Netzwerkfehler in der App.

Es wird somit nichts syncronisiert.....

**Comment by Apollon77** [comment]
Bei mir geht es aktuell auch nicht. Bin am experimentieren ... mit dem Charles Proxy geht es noch problemlos. Bin weiter am probieren.

**Comment by Apollon77** [comment]
welche App OS und version und App versionen jutzt Ihr? Wir sammeln in #56 ...

**Comment by Apollon77** [comment]
closing this as dpicate to #56
