### ISSUE TITLE
Error: 3069195552:error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert number 46

### ISSUE THREAD

**Issue by kBrausew** [Apollon77/ioBroker.tuya#420]
**Add device does not work as expected**  
Device does not work as expected. DP status is not changed or data points are missing.

**To Reproduce**  
1.Start Proxy
2. Start App with use proxy
3. Devices added to iob
4. No Action an the DP's
5. Log Error: SSL-Proxy ERROR: Error: 3069195552:error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert number 46
6. Error: 3069195552:error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert number 46
7. Log: new Schema added for product type dfbljzjm. Please send next line from logfile on disk to developer!
8. Test the "Unlock methods" with the device: no action in IOB

here you are:

{"schemaExt":"[{\"complexType\":\"\",\"id\":25,\"inputStyle\":\"\",\"inputType\":\"plain\"},{\"complexType\":\"\",\"id\":26,\"inputStyle\":\"\",\"inputType\":\" \"},{\"complexType\":\"\",\"id\":33,\"inputStyle\":\"\",\"inputType\":\" \"},{\"complexType\":\"\",\"id\":36,\"inputStyle\":\"\",\"inputType\":\" \"},{\"complexType\":\"\",\"id\":46,\"inputStyle\":\"\",\"inputType\":\" \"},{\"complexType\":\"\",\"id\":49,\"inputStyle\":\"\",\"inputType\":\" \"},{\"complexType\":\"\",\"id\":50,\"inputStyle\":\"\",\"inputType\":\" \"},{\"complexType\":\"\",\"id\":58,\"inputStyle\":\"\",\"inputType\":\" \"}]","schema":"[{\"mode\":\"rw\",\"code\":\"unlock_method_create\",\"name\":\"添加开门方式\",\"id\":1,\"type\":\"raw\"},{\"mode\":\"rw\",\"code\":\"unlock_method_delete\",\"name\":\"删除开门方式\",\"id\":2,\"type\":\"raw\"},{\"mode\":\"rw\",\"code\":\"unlock_method_modify\",\"name\":\"修改开门方式\",\"id\":3,\"type\":\"raw\"},{\"mode\":\"rw\",\"code\":\"bluetooth_unlock\",\"name\":\"蓝牙解锁\",\"id\":6,\"type\":\"raw\"},{\"mode\":\"ro\",\"code\":\"unlock_fingerprint\",\"name\":\"指纹解锁\",\"property\":{\"min\":0,\"max\":999,\"scale\":0,\"step\":1,\"type\":\"value\"},\"id\":12,\"trigger\":\"direct\",\"type\":\"obj\",\"extContent\":\"{\\\"trigger\\\":\\\"direct\\\"}\"},{\"mode\":\"ro\",\"code\":\"unlock_password\",\"name\":\"密码解锁\",\"property\":{\"min\":0,\"max\":999,\"scale\":0,\"step\":1,\"type\":\"value\"},\"id\":13,\"trigger\":\"direct\",\"type\":\"obj\",\"extContent\":\"{\\\"trigger\\\":\\\"direct\\\"}\"},{\"mode\":\"ro\",\"code\":\"unlock_dynamic\",\"name\":\"动态密码解锁\",\"property\":{\"min\":0,\"max\":999,\"scale\":0,\"step\":1,\"type\":\"value\"},\"id\":14,\"trigger\":\"direct\",\"type\":\"obj\",\"extContent\":\"{\\\"trigger\\\":\\\"direct\\\"}\"},{\"mode\":\"ro\",\"code\":\"unlock_card\",\"name\":\"卡片解锁\",\"property\":{\"min\":0,\"max\":999,\"scale\":0,\"step\":1,\"type\":\"value\"},\"id\":15,\"trigger\":\"direct\",\"type\":\"obj\",\"extContent\":\"{\\\"trigger\\\":\\\"direct\\\"}\"},{\"mode\":\"ro\",\"code\":\"open_inside\",\"name\":\"门从内侧打开\",\"property\":{\"type\":\"bool\"},\"id\":18,\"trigger\":\"direct\",\"type\":\"obj\",\"extContent\":\"{\\\"trigger\\\":\\\"direct\\\"}\"},{\"mode\":\"ro\",\"code\":\"unlock_ble\",\"name\":\"蓝牙解锁记录\",\"property\":{\"min\":0,\"max\":999,\"scale\":0,\"step\":1,\"type\":\"value\"},\"id\":19,\"trigger\":\"direct\",\"type\":\"obj\",\"extContent\":\"{\\\"trigger\\\":\\\"direct\\\"}\"},{\"mode\":\"ro\",\"code\":\"alarm_lock\",\"name\":\"门锁告警\",\"property\":{\"range\":[\"wrong_finger\",\"wrong_password\",\"wrong_card\",\"wrong_face\",\"tongue_bad\",\"too_hot\",\"unclosed_time\",\"tongue_not_out\",\"pry\",\"key_in\",\"low_battery\",\"power_off\",\"shock\",\"defense\"],\"type\":\"enum\"},\"id\":21,\"trigger\":\"direct\",\"type\":\"obj\",\"extContent\":\"{\\\"trigger\\\":\\\"direct\\\"}\"},{\"mode\":\"ro\",\"code\":\"hijack\",\"name\":\"劫持告警\",\"property\":{\"type\":\"bool\"},\"id\":22,\"trigger\":\"direct\",\"type\":\"obj\",\"extContent\":\"{\\\"trigger\\\":\\\"direct\\\"}\"},{\"mode\":\"rw\",\"code\":\"doorbell_song\",\"name\":\"报警时间(min)\",\"property\":{\"range\":[\"0\",\"1\",\"2\",\"3\"],\"type\":\"enum\"},\"iconname\":\"icon-dp_time\",\"id\":26,\"trigger\":\"direct\",\"type\":\"obj\",\"extContent\":\"{\\\"trigger\\\":\\\"direct\\\"}\"},{\"mode\":\"rw\",\"code\":\"automatic_lock\",\"name\":\"自动落锁\",\"property\":{\"type\":\"bool\"},\"id\":33,\"trigger\":\"direct\",\"type\":\"obj\",\"extContent\":\"{\\\"trigger\\\":\\\"direct\\\"}\"},{\"mode\":\"rw\",\"code\":\"synch_member\",\"name\":\"同步成员开门方式\",\"id\":35,\"type\":\"raw\"},{\"mode\":\"rw\",\"code\":\"auto_lock_time\",\"name\":\"开门时间\",\"property\":{\"unit\":\"\",\"min\":1,\"max\":120,\"scale\":0,\"step\":1,\"type\":\"value\"},\"iconname\":\"icon-dp_time3\",\"id\":36,\"trigger\":\"direct\",\"type\":\"obj\",\"extContent\":\"{\\\"trigger\\\":\\\"direct\\\"}\"},{\"mode\":\"ro\",\"code\":\"closed_opened\",\"name\":\"门开合状态\",\"property\":{\"range\":[\"unknown\",\"open\",\"closed\"],\"type\":\"enum\"},\"id\":40,\"trigger\":\"direct\",\"type\":\"obj\",\"extContent\":\"{\\\"trigger\\\":\\\"direct\\\"}\"},{\"mode\":\"rw\",\"code\":\"manual_lock\",\"name\":\"手动落锁\",\"property\":{\"type\":\"bool\"},\"id\":46,\"trigger\":\"direct\",\"type\":\"obj\",\"extContent\":\"{\\\"trigger\\\":\\\"direct\\\"}\"},{\"mode\":\"ro\",\"code\":\"lock_motor_state\",\"name\":\"落锁状态\",\"property\":{\"type\":\"bool\"},\"id\":47,\"trigger\":\"direct\",\"type\":\"obj\",\"extContent\":\"{\\\"trigger\\\":\\\"direct\\\"}\"},{\"mode\":\"rw\",\"code\":\"lock_user_enable\",\"name\":\"解冻用户\",\"property\":{\"min\":0,\"max\":999,\"scale\":0,\"step\":1,\"type\":\"value\"},\"id\":49,\"trigger\":\"direct\",\"type\":\"obj\",\"extContent\":\"{\\\"trigger\\\":\\\"direct\\\"}\"},{\"mode\":\"rw\",\"code\":\"lock_user_disable\",\"name\":\"冻结用户\",\"property\":{\"min\":0,\"max\":999,\"scale\":0,\"step\":1,\"type\":\"value\"},\"id\":50,\"trigger\":\"direct\",\"type\":\"obj\",\"extContent\":\"{\\\"trigger\\\":\\\"direct\\\"}\"},{\"mode\":\"rw\",\"code\":\"synch_method\",\"name\":\"同步解锁方式\",\"id\":54,\"type\":\"raw\"},{\"mode\":\"rw\",\"code\":\"arming_mode\",\"name\":\"门磁报警\",\"property\":{\"type\":\"bool\"},\"id\":58,\"trigger\":\"direct\",\"type\":\"obj\",\"extContent\":\"{\\\"trigger\\\":\\\"direct\\\"}\"}]"}

**Comment by kBrausew** [comment]
[tuya.log](https://github.com/Apollon77/ioBroker.tuya/files/8694018/tuya.log)

**Comment by kBrausew** [comment]
[tuya.log](https://github.com/Apollon77/ioBroker.tuya/files/8694020/tuya.log)

**Comment by Apollon77** [comment]
So for me to summarize, you did the proxy process and in the end it worked, right?

But you still can not control the device? Then please switch loglevel for the instance to debug and post that log from adapterstart and also from such an try to control something

**Comment by kBrausew** [comment]
F..k... I now always get network error 5050 in the EMU
Have to reinstall everything (EMU + Tuya)

**Comment by kBrausew** [comment]
[iobroker.2022-06-06-1.log.zip](https://github.com/Apollon77/ioBroker.tuya/files/8844749/iobroker.2022-06-06-1.log.zip)

here are the logs... after the detection has ended, no more activities are recorded in the log, even after a restart of the Tuya adapter

**Comment by Apollon77** [comment]
That basicallylooks good ... whats the issue?

It basically looks that way that he knows the IP of one devcie and not of the secind and he also do not get anby UDP messagefrom the other one (but from a third?) Make sure the UDP messagesreach the iobroker host!

**Comment by kBrausew** [comment]
Problem: I'm not getting any events from the device and I can't control it.

Topology: There is a Bluetooth mesh bridge (WLAN) to which a Bluetooth fingerprint device is connected.
Fingerprint is not battery operated. (As far as I know, Bluetooth has not assigned an IP in the WLAN).
There is no third device.
I exposed Dockers UDP and TCP to ports 6666, 6667, 6668, 8888, 8889 on the network. The unnecessary TCP shouldn't cause any problems.
I also exposed 6668 because it is described in the tuyAPI documentation.
At the moment I'm trying to test the connection examples directly with the tuyAPI (unfortunately a little lack of time and therefore moderate progress ;-) )

**Comment by Apollon77** [comment]
Alternative could be to add the IP manually to the objects if the devcie was discovered correctly ... then it could work

**Comment by Apollon77** [comment]
also see https://github.com/Apollon77/ioBroker.tuya#important-note

**Comment by kBrausew** [comment]
> ... bridge ... as sub devices ...

Can I configure it somehow or is it already working after the initial configuration (usually)

Or may I enter the IP of the bridge on the sub device

**Comment by Apollon77** [comment]
The proxy sync shopuld have added the bridget and sub devices as I remember ... and rest is then done when discovered via UDP ...

**Comment by kBrausew** [comment]
When I look at the log, I only see that he discovered the bridge (bf94d448b9679109b9bcfx) ...
... Fingerprint but not [bff053avzo2zygyr: None of the discovered devices matches :-( ]

is he now receiving UDP or not (bridge discovered, fingerprint not ...)
what should I look for now?

**Comment by Apollon77** [comment]
Please try with version 3.7.0 and install the certificste anew after update!
