### ISSUE TITLE
Proxy iPhone oder Mac... bitte um Hilfe

### ISSUE THREAD

**Issue by MotschaM** [Apollon77/ioBroker.tuya#421]
Ich finde den Adapter so toll, aber jetzt läuft er nicht mehr und ich weis nicht warum. Habe keine Verbindung mehr zu meiner App. 
Hatte es in Benutzung mit einer Wärmepumpe und die App Smarter Pool. 

Habe iOS und osX und es klappt mit keiner Anleitung, da entweder Android oder Emulator der wiederum aber nur auf einem Windows läuft... 

Hat jemand ein Mac oder iPhone bei dem er es aktuell hinbekommt das mit dem Proxy zu machen?

**Comment by Apollon77** [comment]
proxy mit ios geht nicht ... geht nur Android aktuell. Ich arbeite an einer alternativen Sync methode ..... dauert noch bissl
