### ISSUE TITLE
Firmware 1.0.10

### ISSUE THREAD

**Issue by ChristianHoefer** [Apollon77/ioBroker.tuya#43]
Ich habe aktuelle Teckin steckdosen bekommen mit der Firmware 1.0.10. Diese scheinen das UDP Paket nicht auf 6666 sondern auf 6667 auszusenden.

<img width="791" alt="Bildschirmfoto 2019-05-05 um 13 01 42" src="https://user-images.githubusercontent.com/6047702/57192901-f6701080-6f35-11e9-91e4-4981d080db57.png">

**Comment by ChristianHoefer** [comment]
Wobei die alleinige Änderung des Ports das Problem nicht beseitigt. Anbei der Log aus iobroker:

2019-05-05 11:09:45.818 - debug: tuya.0 Discovered device: 10.1.5.49:49154 - U��/��@0��ź�Ēm�8�z�ò�;�w){���&3]��az��q��U�e�_AlLQlr}鴝�&�a�yp�i&�h�M��-���	��Z0�P|���3�f9����W@�m��)

**Comment by schreda** [comment]
Liegt anscheinend am TLS protokoll
https://github.com/codetheweb/tuyapi/issues/175#issuecomment-485203453

**Comment by ChristianHoefer** [comment]
Danke, das bedeutet zum aktuellen stand sind diese nicht direkt einzubinden?

**Comment by schreda** [comment]
Leider.. Ich warte auch auf einen fix. Ist aber von tuyapi abhängig..

**Comment by Apollon77** [comment]
Correct, duplicate to #32

**Comment by Apollon77** [comment]
It seems that the tuyapi projext is close to decode the new protocol. To prepare to adopt the adapter I would need such a new device here with me or at least links that I could purchase one ... can someone provide me details or such a device? Such a plug from here would be more appreciated then a lamp ;-)

**Comment by ChristianHoefer** [comment]
I Used https://www.amazon.de/dp/B07D5V139R/ref=sspa_dk_detail_1?psc=1&pd_rd_i=B07D5V139R&pd_rd_w=65p7C&pf_rd_p=00903874-3af0-47e0-8622-ee58087f71cf&pd_rd_wg=xmzh9&pf_rd_r=MSFEPP1EDY9Y0MRKQKRY&pd_rd_r=ba98eb13-6fdd-11e9-9a96-d95f0a414c28
