### ISSUE TITLE
Klimaanlage über WiFi-IR-Fernbedienung

### ISSUE THREAD

**Issue by franks06347** [Apollon77/ioBroker.tuya#443]
Hallo,
ich nutze eine WiFi-IR-Fernbedienung. Diese sendet IR-Signale mit denen ich Geräte steuern kann, z.B. eine Klimaanlage.
Beide Geräte werden in den ioBroker übertragen. Die WiFi-IR-Fernbedienung und die Klimaanlage.

![grafik](https://user-images.githubusercontent.com/95623262/184478592-11289f87-8f00-4d08-b89d-833190f8b3b0.png)

Die Objekte der WiFi-IR-Fernbedienung werden im ioBroker aktualisiert.
Die Objekte der Klimaanlage aktualisieren sich im ioBroker leider nicht und eine Steuerung über den ioBroker ist nicht möglich.
In der Tuya-APP funktioniert alles tadellos.
Gibt es dafür eine Lösung?
Viele Grüße
Frank

**Comment by Apollon77** [comment]
Ehrlich ... keine Ahnung ... Ich habe so ein gerät nicht und wenn ein sub gerät tut wüsste ich nicht warum ein anderes nicht ... Ggf mal Adapter loglevel auf Debug stellen und  vergleichen was da so ankommt. Die Frage ist auch was genau was tut ...

**Comment by franks06347** [comment]
Hallo Apollon77,
ich kann dir so ein Teil sponsern. Die 9 EUR gebe ich gern aus.
https://www.amazon.de/gp/product/B09DKN2ZJL/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1
Damit kann ich jedes Gerät mit IR-Fernbedienung smart machen.
Schickst du mir deine Adresse per PN.
Ich schicke dir so ein Teil zu.
Ist das OK?
Viele Grüße
Frank

**Comment by Apollon77** [comment]
Schick mir gern eine email an iobroker@fischer-ka.de, dann regen wir das so. Wann ich aber dazu komme kann ich aktuell mit allen Baustellen nicht versprechen!

**Comment by Apollon77** [comment]
Bin gerade am Thema dran ... Bereithalten :-)

**Comment by Apollon77** [comment]
--> https://forum.iobroker.net/topic/59899/test-adapter-tuya-3-9-x-alpha-github

**Comment by Apollon77** [comment]
3.9.1 released
