### ISSUE TITLE
Power Socket values not updating (works with another socket)

### ISSUE THREAD

**Issue by Bobmorton-TX** [Apollon77/ioBroker.tuya#444]
Thanks for your great tool!
I have successfully paired a power socket and get the data updates in iobroker
now i have added another power socket of a different brand. It is also correctly paired and shows the data in the object tree. But the values like cur_voltage cur_power only get updated once after pairing. 
If i turn off the power socket off (via iobroker) it reports a cur_power of 0 and if I turn it on it reports a correct value for cur_power but his does not update ever again (unless turned on/off)

[tuya log from iobroker.txt](https://github.com/Apollon77/ioBroker.tuya/files/9460396/tuya.log.from.iobroker.txt)

**Comment by Apollon77** [comment]
Ywes there are such devices that do not report power locally sometimes ... therefor the polling interval can be used to actively reasd values from devices. Does it work when it is polling?

**Comment by Bobmorton-TX** [comment]
I tried different polling times (5,10,20,60) it does not update values. 

I have installed a VM: Home Assisitant with HACS and the local tuya plugin and set the polling for the device there to 10 seconds. It updates the power and voltage values in HACS
Iobroker running at the same time now gets these values as well and updates correctly.

**Comment by Apollon77** [comment]
It would be great to see a tuya adapter debug log (without running hass in parallel!) with a polling in it because first do not have this.And in general please include full debug log since beginning and tell menthe affected device Id.

**Comment by Apollon77** [comment]
PS:And if hass provides a debug log would be great to see what thy maybe do different

**Comment by Bobmorton-TX** [comment]
Morning.

I restarted Iobroker today and now the polling from seems to work now.
i see  this line now in the log:
**<html><body>


tuya.0 | 2022-09-01 10:08:51.371 | debug | bfd3892ea2f066641brpkk request data via get ...
-- | -- | -- | --



</body>
</html>**

and the values are updating like they should. 

thanks

**Comment by Apollon77** [comment]
great to hear
