### ISSUE TITLE
QR Code to download root-certificate not clickable

### ISSUE THREAD

**Issue by reutli** [Apollon77/ioBroker.tuya#448]
In case of using an android emulator it's not possible to scan the QR-Code to get the root certificate.
You have to use the link http://ip_of_iobroker:8889/ca.pem to download the certificate.

QR code should be clickable to get the root-certificate directly for download - as discussed in [https://forum.iobroker.net/topic/58050/tuya-adapter-problem-ios-und-genymotion-mac](url)

**Comment by Apollon77** [comment]
Next version allows to also click it

**Comment by Apollon77** [comment]
Fixed in 3.7.0
