### ISSUE TITLE
Proxy Error: Hinzufügen von Geräten nicht möglich! Keine Verbindung zur App!

### ISSUE THREAD

**Issue by Domi920** [Apollon77/ioBroker.tuya#449]
Hallo,
wenn ich den Proxy in der Instanz Starte bekomme ich sofort folgende Fehlermeldung in Dauerschleife:
<html>
<body>

tuya.0 | 2022-09-22 16:29:33.331 | error | Error: 3069295104:error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1546:SSL alert number 46
-- | -- | -- | --
tuya.0 | 2022-09-22 16:29:33.329 | error | SSL-Proxy ERROR: Error: 3069295104:error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1546:SSL alert number 46

</body>
</html>

Kann demzufolge auch keine Verbindung zur App über den Proxy herstellen. 

Woran liegt das?

Gruß Dominik

**Comment by Domi920** [comment]
Tatsächlich kommt diese Meldung nur wenn z. B. mein Android Emulator (Memu) mit den Proxy verbunden ist.
Die SmartLife App ist V 3.12.6
Android Version 7.1.2

Leider gibt es keine Lösung.

Habe es mit einen Samsung Galaxy S5 getestet, aber ebenfalls kein Erfolg.


Bei genaueren Betrachtung des Zertifikats ist mir aufgefallen dass dies seit 20.06.2022 abgelaufen zu sein scheint:
![2022 06 20](https://user-images.githubusercontent.com/68474558/191858424-9ba50dd7-92de-4a34-b0b7-73eed3dfcf8c.jpg)

Die Gültigkeitsdaten werden beim Samsung Galaxy S5 genau gleich angezeigt.


Möglicherweise klappt es deshalb nicht.
Funktioniert es bei dir? Falls ja, wie?

**Comment by Apollon77** [comment]
Welche Version vom Adapter wird genutzt? An sich prüft dieses ob das erzeugte Zertifikat ausgelaufen ist und generiert ein neues ... dann muss es ggf neu runtergeladen werden. ist an sich in der 3.6.15 drin https://github.com/Apollon77/ioBroker.tuya#3615-2022-01-24

**Comment by Domi920** [comment]
Nutze bereits die 3.6.15 Version vom Tuya Adapter.
Habe gestern auf beiden Android Geräten das Zertifikat gelöscht und neu heruntergeladen.
Aber das Datum war immer veraltet, wie man im Bild oben sieht. Das ausgegebene Datum zeigt auch 19.06.2020 an.

Bei mir funktioniert das nicht.

Habs auch gestern auf dem Galaxy S5 das erste mal installiert, also kann sicher davor nichts drauf gewesen sein.

Möglicherweise liegts aber auch an den neuen Updates von npm, Node.js, ...
Hatte vor kurzem auch schon Probleme mit Adapterupdates...konnte aber Deinen fix erfolgreich anwenden:
https://forum.iobroker.net/topic/57337/fehler-25-bei-adapter-install-update-mit-npm8
Musste dies aber nach jeden neuen Update wieder ausführen lassen um keinen Fehler zu haben. Funktioniert hat es aber immer wieder.

Hier meine System Details:
Systeminformationen
raspberrypi
Plattform
linux
Betriebssystem
linux
Architektur
arm
CPUs
4
Geschwindigkeit
1500 MHz
Modell
ARMv7 Processor rev 3 (v7l)
RAM
7.71 GB
System-Betriebszeit
2 T. 09:11:57
Node.js
v16.17.0
time
1663919931341
timeOffset
-120
Anzahl der Adapter
435
NPM
8.15.0
Datenträgergröße
180.16 GB
freier Festplattenspeicher
164.1 GB
Betriebszeit
2 T. 08:56:58
Aktive Instanzen
33
Weg
/opt/iobroker/

**Comment by Apollon77** [comment]
Dann bitte mal in /opt/iobroker/iobroker-data/tuya.X/... schauen bzw da löschen.. Da liegen die Zertifikate und dort schaut er an sich nach dem Erzeugungsdatum und löcht ggf

**Comment by Domi920** [comment]
Da befand sich die ca.pem Datei tatsächlich noch veraltet.
Hab diese nun entfernt und es wurde auch eine neue ca.pem Datei heruntergeladen.

Alle installieren Zertifikate sind deinstalliert und das neu heruntergeladene installiert.
Das Datum der Gültigkeit stimmt auch und wurde auf 2024 verlängert.

Allerdings gibt es wieder die gleichen Fehlermeldungen und es funktioniert nicht.

Habe alles Neugestartet, aber funktioniert nicht.
Das Datum beim Android Emulator ist aktuell auf den heutigen Tag.

Was läuft nun jetzt schief?

**Comment by Ilovegym66** [comment]
das hab ich auch, auch so durchgefuehrt, altes Zertifikat geloscht, neues wurde heruntergeladen.. aber geht nicht mehr...
evtl was mit Admin 6 ? der letzte Sync war noch unter Admin5..bei mir.. hmm wirft n haufen Socket errors raus..
siehe mein Issue.. :-)

**Comment by Apollon77** [comment]
Und die App ist <3.14 ???!!

**Comment by Apollon77** [comment]
Socket error heisst das irgendwas verbindungen beendet

**Comment by Apollon77** [comment]
WTF ... nothing changed since ages on how the certs are generated :-(

Ooooooooohhhhhhhhh ... One idea that I could have that newer self signed certs are not allowed to be 2 years aymore ... Apple did such a change ... and it seems Google too https://thehackernews.com/2020/09/ssl-tls-certificate-validity-398.html
(meeh yes seems so https://github.com/joeferner/node-http-mitm-proxy/pull/246)

Do you want to try something?

check if you have a /opt/iobroker/node_modules/iobroker.tuya/node_modules/http-mitm-proxy or a /opt/iobroker/node_modules/http-mitm-proxy ... there open lib/ca.js

And adjust one line: https://github.com/joeferner/node-http-mitm-proxy/blob/1ba10061bc9a8b866bbeaf30f695813d293add28/lib/ca.js#L205 change that to "+ 1" instead of "+ 2" ... then delete the certificate and restar the adapter.

Does it work then ?????

**Comment by Domi920** [comment]
Habs soeben gleich getestet. Leider ohne Erfolg :-(

In diesem Pfad war die Datei:
/opt/iobroker/node_modules/http-mitm-proxy/lib/ca.js

Komisch ist aber, dass das Zertifikat das Datum von gestern hat, obwohl ich es gelöscht habe in diesen Pfad:
/opt/iobroker/iobroker-data/tuya_0/certs/ca.pem

![Neuer Test 2022 09 27_1800](https://user-images.githubusercontent.com/68474558/192577528-19604454-40d0-4c9d-800c-b6f186b81744.jpg)

Gruß Dominik

**Comment by Apollon77** [comment]
Du hast nur die CA gelöscht und nicht das zertifikat. Löch mal das ganze directory ... siehe screenshot - ist immer noch 2 Jahre... darf nch dem Updaste nur 1 Jahr sein

**Comment by Domi920** [comment]
Habe nun alles aus folgenden Verzeichnis gelöscht:
/opt/iobroker/iobroker-data/tuya_0

Glücklicherweise funktioniert es wieder. 
Allerdings steht beim Zertifikat immer noch 2 Jahre Gültigkeit.

Die Datei hatte ich zuvor aber wie hier beschrieben umgeschrieben:
![Unbenannt](https://user-images.githubusercontent.com/68474558/192638742-1f8ccff6-a9c2-4582-97df-e75efadb58ce.jpg)

Was habe ich dann falsch gemacht?

**Comment by Apollon77** [comment]
Also es geht jetzt wieder? Jetzt kapiere ich nix mehr ... auch warum es immer noch 2 Jahre sind ... :-(

**Comment by Domi920** [comment]
Wahrscheinlich hatte es vorher nicht geklappt weil ich nur die "ca.pem" Datei gelöscht habe & das Zertifikat aus den Sicherheitseinstellungen im Android Emulator.
Auf deine Nachricht erst habe ich beide Ordner im Pfad /opt/iobroker/iobroker-data/tuya_0 gelöscht.
Deshalb wurde ein neues Zertifikat mit ab heutigen Datum erstellt.

Habe die Datei im Texteditor vom Raspberry Pi System (TeamViewer Fernwartung) umgeschrieben auf +1.
Möglicherweise ist da was schief gelaufen, weil man einen anderen Editor bräuchte.
Wenn ich die Datei gespeichert hatte & wieder geöffnet hatte, war aber die Änderung noch vorhanden.


Jedenfalls war es notwendig beide Ordner im Pfad zu löschen & dann alles neu anlegen lassen & installieren.

**Comment by Apollon77** [comment]
"beide ordner"?Also alles in tuya_0, korrekt? ok, dann baue ich das in den adapter mit ein

**Comment by Domi920** [comment]
Ja beide Ordner im Pfad:
/opt/iobroker/iobroker-data/tuya_0

Die Änderung mit +1 hat irgendwie nicht funktioniert, weiß nicht worans lag.


Kommt die Änderung auch in den Adpater dass alles selbst löscht nach Ablauf?

**Comment by Apollon77** [comment]
Ich dneke ich lösche es wenn älter als 3 monate oder wie jetzt schon das Zertifikalsfile ... aber scheinbar kam es dadurch zu issues

**Comment by Domi920** [comment]
Die Lösung klingt sehr gut.
Vielen Dank für Deine großartige Arbeit!

Gruß Dominik

**Comment by Apollon77** [comment]
Version 3.7.0 hat es implementiert ... bitte checken

**Comment by Domi920** [comment]
@Apollon77 Habe es getestet. Sieht aus als würde alles funktionieren. V3.7.2
Vielen Dank für deine großartige Arbeit!

**Comment by Apollon77** [comment]
Danke für die Rückmeldung
