### ISSUE TITLE
LSC Doorbell doesn't work any more - none of known devices matches?

### ISSUE THREAD

**Issue by Ilovegym66** [Apollon77/ioBroker.tuya#450]
since some weeks/months? the LSC Doorbell doesn't work any more correctly, it's always offline in the Adapter, but with the App it works fine. I resetet the device with powerrecycle, same again. I deleted the device from Tuya and assigned it new again, same again. 
Every other device works fine, this is the only one with this issue. The mysterios thing is, that the objects are created and some (not all) fields are filled with correct data in iobroker, but the device is only in iobroker tuya adapter everytime offline. 
There was no Firmware Update on the device, I've switched this option off on every device. 
It can only be, that Tuya changed the Schema... 

Here the logfile with debug:
[tuya.log](https://github.com/Apollon77/ioBroker.tuya/files/9632731/tuya.log)

**Comment by Apollon77** [comment]
Log tells: 2022-09-23 11:59:26.610  - debug: tuya.0 (662682) bfeeaa29ccb41608a6wp8h: Try to initialize encrypted device with received UDP messages (#IPs: 1): version=undefined, key=122b899d48bb637f
2022-09-23 11:59:26.610  - info: tuya.0 (662682) bfeeaa29ccb41608a6wp8h: None of the discovered devices matches :-(

It has no IP (most likely because you removed the device from tuya and receonnected it and then it got a noew localkey ... so you need to redo the procxy sync!

**Comment by Ilovegym66** [comment]
Yes, already done ..

**Comment by Apollon77** [comment]
Then try agin please and delete the "device object" of that devcie in iobroker first ... else I need a debug log from such a sync. In jedem Fall sagt er das die geräte daten zu keinem encrpytion key passen

**Comment by Ilovegym66** [comment]
Ah vielleicht hab ich auch n Problem mit dem Zertifikat.. ich schau mal!

**Comment by Apollon77** [comment]
Das Zertifikat vom Proxy Sync ist hier egal ...

**Comment by Ilovegym66** [comment]
naja funktioniert nicht mehr so... schau:

[tuyaproxyerror.log](https://github.com/Apollon77/ioBroker.tuya/files/9633168/tuyaproxyerror.log)

**Comment by Apollon77** [comment]
hast du das zertifikat neu installiert nicht das das abgelaufen ist. SOnst mal adapter stoppen /opt/iobroker/iobroker-data/tuya.0 verzeichnis löschen und adapterneu starten. dann gibts in jedem Fall ein neues Zertifikat. Dann das neu im handy installieren

**Comment by Ilovegym66** [comment]
ja, hab sogar die Instanz auf n anderen Host gezogen, mir die Installation lief ohne Probleme, da neues Zertifikat gezogen, vorher die Objekte in tuya.0. geloescht, dann proxy gestartet und es wurden auf Anhieb alle 29 devices gefunden, Verbunden sind dann 28, alle, nur die Doorbell nicht.. :-(

**Comment by Ilovegym66** [comment]
was mich wundert, ich kann ja andere Devices hinzufuegen, das geht, nur die f(*&(*ing Doorbell setzt er nicht um.. soll ich vielleicht dort ma Onvif ausschalten und das Device auf Werkseinstellungen setzen? hmp...

**Comment by Apollon77** [comment]
Und du hast die Device Objkete von der Doorbell VOR dem Sync mal gelöscht????

**Comment by Ilovegym66** [comment]
Yes.. hab's.. es lag an der Firewall, udp war geblockt.. 🙈🙈

**Comment by Apollon77** [comment]
hihi, manchmal kanns soooooo einfach sein
