### ISSUE TITLE
Tuya SSL Cert error

### ISSUE THREAD

**Issue by benziman88** [Apollon77/ioBroker.tuya#458]
Hi,

I just setup a new fresh iobroker instance and wanted to pair my devices via Tuya proxy.
I already isntalled the tuya proxy cert but can only install it as Wifi cert on my two samsung androids.
Followed all other steps as I did this plenty times already (Wifi with custom proxy set). and installed smart life app 3.12.6

Tuya proxy is on, when I start the smart life app with proxy set I receive network erro 50505

Log shows the following

2022-10-07 11:59:21.606  - error:  tuya.0 (1682) Error: 1995406016:error:14094416:SSL  routines:ssl3_read_bytes:sslv3 alert certificate  unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1546:SSL alert  number 46
2022-10-07 11:59:21.609  - error:  tuya.0 (1682) SSL-Proxy ERROR: Error: 1995406016:error:14094416:SSL  routines:ssl3_read_bytes:sslv3 alert certificate  unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1546:SSL alert  number 46
2022-10-07 11:59:21.611  - error:  tuya.0 (1682) Error: 1995406016:error:14094416:SSL  routines:ssl3_read_bytes:sslv3 alert certificate  unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1546:SSL alert  number 46

Thing is these exact steps worked on my old iobroker instance with the same android device, now I only have a Fritzbox with one network (no more vlans etc) I can controll everything within the latest smart life app. 

any ideas?

thank you in advance

**Comment by Apollon77** [comment]
Was this your first ever try with the proxy or a secodn try?

see https://github.com/Apollon77/ioBroker.tuya/issues/449

Please try to stop adapter, delete /opt/iobroker/tuya.0 completely, restart adapter, Try again (incl. certificate import).

**Comment by Apollon77** [comment]
PS: Which Android version?

**Comment by benziman88** [comment]
> Was this your first ever try with the proxy or a secodn try?
> 
> see #449
> 
> Please try to stop adapter, delete /opt/iobroker/tuya.0 completely, restart adapter, Try again (incl. certificate import).

I already successfully did this process more than 110 times without any isseus in the last 2 years.

**Comment by benziman88** [comment]
> PS: Which Android version?

Android 13 and Android 11 (the tablet with android 11 worked on my old iobroker instance with tuya proxy)

**Comment by Apollon77** [comment]
Then most likely the certificate is outdated . Plesase delete the folder as told above and reimport certificate after restart of adapter. Does it work then again?

**Comment by Apollon77** [comment]
And PS: ANdroid versions MIGHT also be an issue because Goodle change like apple that certs are only allowed to be 375 days long and not 2 years ... but maybe it still works

**Comment by benziman88** [comment]
> > Was this your first ever try with the proxy or a secodn try?
> > see #449
> > Please try to stop adapter, delete /opt/iobroker/tuya.0 completely, restart adapter, Try again (incl. certificate import).
> 
> I already successfully did this process more than 110 times without any isseus in the last 2 years.

removed /opt/iobroker/iobroker-data/tuya_0

didn't work with the tablet but worked instantly with my phone and android 13!
thanks a lot!

**Comment by Apollon77** [comment]
version 3.7.0 should solve the issues. Please report back and pot use new gnerated certificate!
