### ISSUE TITLE
Strange values and unit for temperature

### ISSUE THREAD

**Issue by morskipas** [Apollon77/ioBroker.tuya#459]
Hello all,

I have problems with the values and the unit of temperature of my heating thermosta brand Moes type BHT-002-GBLW(Wifi). I think this is pretty much the same as #378 and #456.
The temperature is too low by a factor of 5 and the unit is displayed as â "ƒ My set 23 degrees Celsius is displayed in the adapter as 4.6 â "ƒ

Thanks for your support

**Expected behavior**  
Show the 4.6 â "ƒ as  23 °C

**Versions:**  
 - Adapter version: <3.6.15>
 - JS-Controller version: <4.0.23>
 - Node version: <v16.17.0>
 - Operating system: <Raspberry Pi 4 - Raspberry Pi OS - Debian Linux 11>

<img width="1535" alt="iobroker" src="https://user-images.githubusercontent.com/6042276/194725884-04ec613b-7642-48d3-a7ae-96c3be9fd7bb.png">

**Comment by Apollon77** [comment]
duplicate #456 ... same as solution/workaround for now ...
