### ISSUE TITLE
Log Warning greater than max "null"

### ISSUE THREAD

**Issue by Bernd9000** [Apollon77/ioBroker.tuya#465]
Tuya Version `3.7.1`
Nach wie vor werden `NULL` Werte bei min und max eingetragen seit Version 3.70.
Wenn man die Werte selbst korrigiert werden Sie nach Adapter neustart wieder auf "NULL" gesetzt.

Log Meldung:
 State value to set for "tuya.0.bf23ebb4f4e5b868b4rx3e.22" has value "130" greater than max "null"

Siehe auch [#464](https://github.com/Apollon77/ioBroker.tuya/issues/464)

**Comment by Apollon77** [comment]
3.7.2 fixt das, kommt gleich
