### ISSUE TITLE
State value to set for "tuya.0.08708068500291bdb880.4" has value "1" greater than max "null"

### ISSUE THREAD

**Issue by mpl1337** [Apollon77/ioBroker.tuya#466]
Bekomme nach wie vor den Fehler,

`Instanzeinstellungen: tuya.0v3.7.2`

`<html>
<body>

tuya.0 | 2022-10-27 20:29:50.495 | warn | State value to set for "tuya.0.08708068500291bdb880.4" has value "1" greater than max "null"
-- | -- | -- | --

</body>
</html>`

**Comment by Apollon77** [comment]
Bitte mal das betroffene Objekt (nur das!=) löschen und adapter neu starten. Dann immer noch?

Falls ja bitte Adapter mit Debug Log starten und mit log posten oder an iobroker@fischer-ka.de mit Referenz auf dieses Issue zusenden
