### ISSUE TITLE
Neues Schema Blitzwoif Stekdosen BW-SHP2

### ISSUE THREAD

**Issue by philipplindner-media-network** [Apollon77/ioBroker.tuya#47]
```
tuya.0	2019-05-24 17:49:00.246	info	{"schema":"[{\"mode\":\"rw\",\"code\":\"switch_1\",\"name\":\"开关1\",\"property\":{\"type\":\"bool\"},\"iconname\":\"icon-dp_power2\",\"id\":1,\"type\":\"obj\",\"desc\":\"\"},{\"mode\":\"rw\",\"code\":
tuya.0	2019-05-24 17:49:00.246	info	new Shema added for product type VdDGAJHYWVj62FGM. Please send next line from logfile on disk to developer!
```
Dies sien die Loginräge von Meine IoBroker.

**Comment by philipplindner-media-network** [comment]
meine Eingabe war leider nicht komplet:
```
tuya.0 new Shema added for product type VdDGAJHYWVj62FGM. Please send next line from logfile on disk to developer!

 {"schema":"[{\"mode\":\"rw\",\"code\":\"switch_1\",\"name\":\"开关1\",\"property\":{\"type\":\"bool\"},\"iconname\":\"icon-dp_power2\",\"id\":1,\"type\":\"obj\",\"desc\":\"\"},{\"mode\":\"rw\",\"code\":\"countdown_1\",\"name\":\"开关1倒计时\",\"property\":{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1,\"type\":\"value\"},\"iconname\":\"icon-dp_time2\",\"id\":9,\"type\":\"obj\",\"desc\":\"\"},{\"mode\":\"rw\",\"code\":\"add_ele\",\"name\":\"增加电量\",\"property\":{\"unit\":\"\",\"min\":0,\"max\":50000,\"scale\":3,\"step\":100,\"type\":\"value\"},\"iconname\":\"icon-battery\",\"id\":17,\"type\":\"obj\",\"desc\":\"\"},{\"mode\":\"ro\",\"code\":\"cur_current\",\"name\":\"当前电流\",\"property\":{\"unit\":\"mA\",\"min\":0,\"max\":30000,\"scale\":0,\"step\":1,\"type\":\"value\"},\"iconname\":\"icon-Ele\",\"id\":18,\"type\":\"obj\",\"desc\":\"\"},{\"mode\":\"ro\",\"code\":\"cur_power\",\"name\":\"当前功率\",\"property\":{\"unit\":\"W\",\"min\":0,\"max\":50000,\"scale\":1,\"step\":1,\"type\":\"value\"},\"iconname\":\"icon-dp_tool\",\"id\":19,\"type\":\"obj\",\"desc\":\"\"},{\"mode\":\"ro\",\"code\":\"cur_voltage\",\"name\":\"当前电压\",\"property\":{\"unit\":\"V\",\"min\":0,\"max\":5000,\"scale\":1,\"step\":1,\"type\":\"value\"},\"iconname\":\"icon-a_function_turbo\",\"id\":20,\"type\":\"obj\",\"desc\":\"\"},{\"mode\":\"ro\",\"code\":\"test_bit\",\"name\":\"产测结果位\",\"property\":{\"unit\":\"\",\"min\":0,\"max\":5,\"scale\":0,\"step\":1,\"type\":\"value\"},\"iconname\":\"icon-dp_direction\",\"id\":21,\"type\":\"obj\",\"desc\":\"\"},{\"mode\":\"ro\",\"code\":\"voltage_coe\",\"name\":\"电压校准系数\",\"property\":{\"unit\":\"\",\"min\":0,\"max\":1000000,\"scale\":0,\"step\":1,\"type\":\"value\"},\"iconname\":\"icon-gaodiyin\",\"id\":22,\"type\":\"obj\",\"desc\":\"\"},{\"mode\":\"ro\",\"code\":\"electric_coe\",\"name\":\"电流校准系数\",\"property\":{\"unit\":\"\",\"min\":0,\"max\":1000000,\"scale\":0,\"step\":1,\"type\":\"value\"},\"iconname\":\"icon-gaodiyin\",\"id\":23,\"type\":\"obj\",\"desc\":\"\"},{\"mode\":\"ro\",\"code\":\"power_coe\",\"name\":\"功率校准系数\",\"property\":{\"unit\":\"\",\"min\":0,\"max\":1000000,\"scale\":0,\"step\":1,\"type\":\"value\"},\"iconname\":\"icon-gaodiyin\",\"id\":24,\"type\":\"obj\",\"desc\":\"\"},{\"mode\":\"ro\",\"code\":\"electricity_coe\",\"name\":\"电量校准系数\",\"property\":{\"unit\":\"\",\"min\":0,\"max\":1000000,\"scale\":0,\"step\":1,\"type\":\"value\"},\"iconname\":\"icon-gaodiyin\",\"id\":25,\"type\":\"obj\",\"desc\":\"\"},{\"mode\":\"ro\",\"code\":\"fault\",\"scope\":\"fault\",\"name\":\"故障告警\",\"property\":{\"label\":[\"ov_cr\"],\"type\":\"bitmap\",\"maxlen\":1},\"id\":26,\"type\":\"obj\",\"desc\":\"ov_cr：过流保护\"}]","schemaExt":"[{\"id\":1,\"inputType\":\" \"},{\"id\":9,\"inputType\":\" \"},{\"id\":17,\"inputType\":\" \"}]"}
```
muss dies in die date: lib/mapper.js?

**Comment by Apollon77** [comment]
Ja, dort baue ich es ein. Ist aber am Ende nur relevant wenn man weitere Geräte des Typs hinzufügt weil dann das Shema direkt genutzt werden kann um die States sinnvoller anzulegen. Der Sync mit dem Proxy ist dennoch nötig. Ist also am Ende nur "Conveniece" :-)

**Comment by philipplindner-media-network** [comment]
als muss der Prixy Dauernt laufen?

**Comment by Apollon77** [comment]
Nein. Einmalig. Oder nachdem du neue Geräte hinzugefügt hast. Auch dann einmalig. Der Proxy „klaut“ den lokalen encryption key und speichert ihn. Und holt das Schema. Das reicht einmalig.

**Comment by philipplindner-media-network** [comment]
ok. kann man mit den offenen port das Gerätes selber locan kommunizieren?

**Comment by Apollon77** [comment]
Der Adapter kann nur lokal kommunizieren. Also ja. Und um den einen key zu bekommen braucht es einmalig den Proxy

**Comment by philipplindner-media-network** [comment]
als irgend wie will er nicht so richtig folgende Meldung Kommt:
`

tuya.0 | 2019-05-26 22:24:52.711 | info | 81353660600194d116aa: Can not start because IP unknown
-- | -- | -- | --
tuya.0 | 2019-05-26 22:24:46.211 | info | 81353660600194d116aa: Can not start because IP unknown
tuya.0 | 2019-05-26 22:24:45.961 | info | 81353660600194d116aa: Can not start because IP unknown
tuya.0 | 2019-05-26 22:24:45.708 | info | 81353660600194d116aa: Can not start because IP unknown

`
mach ich da irgend was falsch?

**Comment by Apollon77** [comment]
Kommt darauf an (siehe auch im Forum).
IPs kommen an sich über lokale UDP Pakete die die Geräte senden. Also entweder irgendetwas blockt diese UDP Pakete oder die Geräte haben eine neue verschlüsselte Firmware dann ist das noch nicht unterstützt und wir warten etwas bis das alles entschlüsselt ist. Wie ist denn die FW versionsnummer?

**Comment by philipplindner-media-network** [comment]
Als das Miet den IP Blockade kann ich noch nachziehen. FW: wifi-modul 1.0.6 MCU-Versio 1.0.6, bei den UDP Paketen gehen die über den gesendet port 6668?

**Comment by philipplindner-media-network** [comment]
Keiner nachtrag habe Prot Ggeöffenet und adabier neugestarte folgende meldung kam
`

tuya.0 | 2019-05-27 11:14:23.864 | info | Discover for local Tuya devices on port 6666
-- | -- | -- | --
tuya.0 | 2019-05-27 11:14:23.864 | info | Existing devices initialized
tuya.0 | 2019-05-27 11:14:23.863 | info | 81353660600194d116aa: Can not start because IP unknown
tuya.0 | 2019-05-27 11:14:23.795 | info | starting. Version 1.0.7 in /opt/iobroker/node_modules/iobroker.tuya, node: v8.16.0

`

**Comment by Apollon77** [comment]
UDP multicasts are send to port 6666

**Comment by Apollon77** [comment]
Um Herauszufinden ob 1.0.6 die "neue" oder die "alte" Firmware ist versuch mal ein Telnet auf das gerät auf Port 6668 ... wenn das klappt ist es die alte Firmware und es sollte dann nur an den UDP liegen. Wenn Port 6668 zu ist (und glaube 6669 offen) dann ist es de neue verschlüsselte Firmware und es heisst warten

**Comment by philipplindner-media-network** [comment]
ok mit telnet komm ich dreuf

**Comment by philipplindner-media-network** [comment]
brucht das überhaut eine Protfreigabe nach ausen?

**Comment by Apollon77** [comment]
Ausser wenn man die Proxy Nummer macht theoretisch nicht. Praktisch gab es berichte das einige Geräte sehr instabil wurden wenn Sie nicht "nach Hause telefonieren" konnten und öfter abgestürzt/rebootet sind ...

**Comment by philipplindner-media-network** [comment]
weißt du wie die UDP beflehe laufen? Ich habe mal angefangen deine Form beitrage zu lesen. Bringe es was 
 wenn  mann man in Objekte die IP einschreibt weil der Datenfunk ist bei mir lehr,

**Comment by Apollon77** [comment]
Falls es Probleme mit den UDP Paketen gibt kannst DU die IP manuell eintragen, dann nutzt er das nach einem Neustart

**Comment by philipplindner-media-network** [comment]
wo muss ich die IP Eintragen? will igen wie will es immer noch nicht. [bild1](https://puu.sh/Dy7e2/91c2065332.png)
`{
  "type": "device",
  "common": {
    "name": "Waschmaschine",
    "read": true,
    "write": false
  },
  "native": {
    "ip": 192.168.178.XXX <-- ist das die reichtige stelle
    "virtual": false,
    "lon": "12.4577374",
    "uuid": "81353660600194d116aa",
    "iconUrl": "https://images.tuyaeu.com/smart/icon/1536752669ijospdb3eoq_0.png",
    "lat": "51.35646",
    "runtimeEnv": "prod",
    "devId": "81353660600194d116aa",
    "dpMaxTime": 1558898891980,
    "productId": "VdDGAJHYWVj62FGM",
    "activeTime": 1558708153,
    "moduleMap": {
      "wifi": {
        "upgradeStatus": 0,
        "bv": "5.42",
        "cdv": "1.0.0",
        "pv": "2.2",
        "verSw": "1.0.6",
        "isOnline": true,
        "id": 9080299,
        "cadv": ""
      },
      "mcu": {
        "upgradeStatus": 0,
        "cdv": "",
        "verSw": "1.0.6",
        "isOnline": true,
        "id": 9080300,
        "cadv": ""
      }
    },
    "devAttribute": 3,
    "name": "Waschmaschine",
    "timezoneId": "Europe/Amsterdam",
    "category": "cz",
    "localKey": "b198e0396ae29d6e",
    "schema": [
      {
        "mode": "rw",
        "code": "switch_1",
        "name": "开关1",
        "property": {
          "type": "bool"
        },
        "iconname": "icon-dp_power2",
        "id": 1,
        "type": "obj",
        "desc": ""
      },
      {
        "mode": "rw",
        "code": "countdown_1",
        "name": "开关1倒计时",
        "property": {
          "unit": "s",
          "min": 0,
          "max": 86400,
          "scale": 0,
          "step": 1,
          "type": "value"
        },
        "iconname": "icon-dp_time2",
        "id": 9,
        "type": "obj",
        "desc": ""
      },
      {
        "mode": "rw",
        "code": "add_ele",
        "name": "增加电量",
        "property": {
          "unit": "",
          "min": 0,
          "max": 50000,
          "scale": 3,
          "step": 100,
          "type": "value"
        },
        "iconname": "icon-battery",
        "id": 17,
        "type": "obj",
        "desc": ""
      },
      {
        "mode": "ro",
        "code": "cur_current",
        "name": "当前电流",
        "property": {
          "unit": "mA",
          "min": 0,
          "max": 30000,
          "scale": 0,
          "step": 1,
          "type": "value"
        },
        "iconname": "icon-Ele",
        "id": 18,
        "type": "obj",
        "desc": ""
      },
      {
        "mode": "ro",
        "code": "cur_power",
        "name": "当前功率",
        "property": {
          "unit": "W",
          "min": 0,
          "max": 50000,
          "scale": 1,
          "step": 1,
          "type": "value"
        },
        "iconname": "icon-dp_tool",
        "id": 19,
        "type": "obj",
        "desc": ""
      },
      {
        "mode": "ro",
        "code": "cur_voltage",
        "name": "当前电压",
        "property": {
          "unit": "V",
          "min": 0,
          "max": 5000,
          "scale": 1,
          "step": 1,
          "type": "value"
        },
        "iconname": "icon-a_function_turbo",
        "id": 20,
        "type": "obj",
        "desc": ""
      },
      {
        "mode": "ro",
        "code": "test_bit",
        "name": "产测结果位",
        "property": {
          "unit": "",
          "min": 0,
          "max": 5,
          "scale": 0,
          "step": 1,
          "type": "value"
        },
        "iconname": "icon-dp_direction",
        "id": 21,
        "type": "obj",
        "desc": ""
      },
      {
        "mode": "ro",
        "code": "voltage_coe",
        "name": "电压校准系数",
        "property": {
          "unit": "",
          "min": 0,
          "max": 1000000,
          "scale": 0,
          "step": 1,
          "type": "value"
        },
        "iconname": "icon-gaodiyin",
        "id": 22,
        "type": "obj",
        "desc": ""
      },
      {
        "mode": "ro",
        "code": "electric_coe",
        "name": "电流校准系数",
        "property": {
          "unit": "",
          "min": 0,
          "max": 1000000,
          "scale": 0,
          "step": 1,
          "type": "value"
        },
        "iconname": "icon-gaodiyin",
        "id": 23,
        "type": "obj",
        "desc": ""
      },
      {
        "mode": "ro",
        "code": "power_coe",
        "name": "功率校准系数",
        "property": {
          "unit": "",
          "min": 0,
          "max": 1000000,
          "scale": 0,
          "step": 1,
          "type": "value"
        },
        "iconname": "icon-gaodiyin",
        "id": 24,
        "type": "obj",
        "desc": ""
      },
      {
        "mode": "ro",
        "code": "electricity_coe",
        "name": "电量校准系数",
        "property": {
          "unit": "",
          "min": 0,
          "max": 1000000,
          "scale": 0,
          "step": 1,
          "type": "value"
        },
        "iconname": "icon-gaodiyin",
        "id": 25,
        "type": "obj",
        "desc": ""
      },
      {
        "mode": "ro",
        "code": "fault",
        "scope": "fault",
        "name": "故障告警",
        "property": {
          "label": [
            "ov_cr"
          ],
          "type": "bitmap",
          "maxlen": 1
        },
        "id": 26,
        "type": "obj",
        "desc": "ov_cr：过流保护"
      }
    ],
    "productKey": "VdDGAJHYWVj62FGM",
    "schemaExt": [
      {
        "id": 1,
        "inputType": " "
      },
      {
        "id": 9,
        "inputType": " "
      },
      {
        "id": 17,
        "inputType": " "
      }
    ]
  },
  "from": "system.adapter.tuya.0",
  "ts": 1558965664876,
  "_id": "tuya.0.81353660600194d116aa",
  "acl": {
    "object": 1638
  }
}`

**Comment by philipplindner-media-network** [comment]
weil es auch so nicht geht. Ich kann die nur anbieten über eine Konferenzschaltung mahl zu scheuen was los ist. wenn es für dich ok ist schreib mir eine e-Mail an post@philipp-lindner,de und wir besprechen alles weitere.

**Comment by Apollon77** [comment]
Ja das wäre die richtige Stelle generell. Wie siehst denn das Log aus?

**Comment by philipplindner-media-network** [comment]
als staus ist grün er spukt mir jetzt volgende Logs aus:

tuya.0 | 2019-05-27 23:10:49.593 | error | 81353660600194d116aa.1: Error: Timeout waiting for response
-- | -- | -- | --
tuya.0 | 2019-05-27 23:10:46.498 | error | 81353660600194d116aa.1: Error: Timeout waiting for response
tuya.0 | 2019-05-27 23:10:41.641 | error | 81353660600194d116aa.1: Error: Timeout waiting for response
tuya.0 | 2019-05-27 23:08:27.902 | info | Discover for local Tuya devices on port 6666
tuya.0 | 2019-05-27 23:08:27.898 | info | Existing devices initialized
tuya.0 | 2019-05-27 23:08:27.893 | info | 81353660600194d116aa Init with IP=192.168.178.235, Key=b198e0396ae29d6e
tuya.0 | 2019-05-27 23:08:27.827 | info | starting. Version 1.0.7 in /opt/iobroker/node_modules/iobroker.tuya, node: v8.16.0
tuya.0 | 2019-05-27 23:01:47.026 | error | 81353660600194d116aa.1: Error: Timeout waiting for response
tuya.0 | 2019-05-27 23:00:30.127 | error | 81353660600194d116aa.1: Error: Timeout waiting for response
tuya.0 | 2019-05-27 22:58:47.425 | error | 81353660600194d116aa.1: Error: Returned command byte did not match expected byte.
tuya.0 | 2019-05-27 22:57:41.826 | info | Discover for local Tuya devices on port 6666
tuya.0 | 2019-05-27 22:57:41.823 | info | Existing devices initialized
tuya.0 | 2019-05-27 22:57:41.820 | info | 81353660600194d116aa Init with IP=192.168.178.235, Key=b198e0396ae29d6e
tuya.0 | 2019-05-27 22:57:41.740 | info | starting. Version 1.0.7 in /opt/iobroker/node_modules/iobroker.tuya, node: v8.16.0

**Comment by Apollon77** [comment]
Die App auf dem handy ist beendet/gekillt? und andere Verbindungen zu Port 6668 gibts auch nicht? Die Geräte können nur eine Verbindung aufbauen. ALso wenn jemand anders verbunden ist (Handy per App oder sowas) und Adapter kann nicht verbinden

**Comment by philipplindner-media-network** [comment]
so alle beendet und es geht trozdem nicht und spukt folgende medlung aus : 

tuya.0 | 2019-05-27 23:58:06.812 | error | 81353660600194d116aa.1: Error: Timeout waiting for response
-- | -- | -- | --
tuya.0 | 2019-05-27 23:57:54.283 | error | 81353660600194d116aa.1: Error: Timeout waiting for response
tuya.0 | 2019-05-27 23:56:41.600 | info | Discover for local Tuya devices on port 6666
tuya.0 | 2019-05-27 23:56:41.600 | info | Existing devices initialized
tuya.0 | 2019-05-27 23:56:41.599 | info | 81353660600194d116aa Init with IP=192.168.178.235, Key=b198e0396ae29d6e
tuya.0 | 2019-05-27 23:56:41.523 | info | starting. Version 1.0.7 in /opt/iobroker/node_modules/iobroker.tuya, node: v8.16.0
tuya.0 | 2019-05-27 23:54:20.210 | info | Discover for local Tuya devices on port 6666
tuya.0 | 2019-05-27 23:54:20.209 | info | Existing devices initialized
tuya.0 | 2019-05-27 23:54:20.209 | info | 81353660600194d116aa Init with IP=192.168.178.235, Key=b198e0396ae29d6e
tuya.0 | 2019-05-27 23:54:20.113 | info | starting. Version 1.0.7 in /opt/iobroker/node_modules/iobroker.tuya, node: v8.16.0
tuya.0 | 2019-05-27 23:51:18.290 | error | 81353660600194d116aa.1: Error: Timeout waiting for response

**Comment by Apollon77** [comment]
Aber Du kannst dich lokal vom gleichen Host aus auf Port 6668 verbinden per Telnet und bekommst Da auch was zu sehen wenn Du das gerät manuell schaltest??

**Comment by philipplindner-media-network** [comment]
Verbinden ja aber ich sehe keine Informationen als keine Aufforderung was einzugeben. Ich habe meine HomeServer Neugestartet, wo IoBroker leuft.

[onjete](https://puu.sh/Dyjxv/f9189c5d59.png)
[Instansen](https://puu.sh/Dyjy3/e5fd4763cb.png)
[logs](https://puu.sh/Dyjz2/5ead210ea4.png)

**Comment by Apollon77** [comment]
Heisst .. er kann sich erfolgreich verbinden? Oder auch das nicht?
Sieht damit eher für mich nach den neuen Geräten aus mit der anderen Firmware

**Comment by philipplindner-media-network** [comment]
ja es verbindet sich liefert bost keine daten. Als Heist es der adabter kann nichts weiter machen. kann man die daten die über die Ablaufen via Proxy abreifen und das irgen wie in den ioBroker bingen?

**Comment by Apollon77** [comment]
Ne die Mqtt Verbindung der App hab ich nicht abgreifen können und auch sonst wäre es über den proxy nicht sinnvoll. Haben die Geräte bei dir auch port 6669 geöffnet?

**Comment by philipplindner-media-network** [comment]
nach meiner Erkenntnis nicht das ist doch so eine sch***ß nur über eine beschissen App, Ich wollte es Eigenreich für meine Waschmaschine verwenden um zu Prüfen ob sie noch läuft. Die war schön kompakt und preiswert. Ich Habe noch Dekt FritzBox Stkdosen im einsetz, leider ewas Teuer. Da gebt es eine gute Einbiegung in IOBoker, und eine gute App's selbst über Java und PHP Scripts kann man sie steuern. 
Ich dachte mir die die Befelen die von der App kommen zur stekdose Abfangen kann.
Bild Reiche ich noch nach

PS: in der APP Werd auch meine Externe IP Angezeigt hat das was zu bedauten?

**Comment by philipplindner-media-network** [comment]
[PortScan](https://puu.sh/DyRVO/7a3cd44dad.png)
[App](https://puu.sh/DyRYJ/a1cf468923.png)

**Comment by philipplindner-media-network** [comment]
Sie mache aber drossendem eine Tolle Arbeite mit diesen Adapter. Mich rege es nur auf das Ich wahrscheinlich nur über die App alles steuern kann. Wenn meine Löt kühnste nicht so schlecht sind hätte ich schon Tasmota auf den Chip Geflecht.

**Comment by Apollon77** [comment]
Die App läuft über die Tuya Cloud und daher natürlich die externe IP ....

Also an sich sieht der Portscan und so korrekt aus für den "alten Firmwaretyp" der tun sollte. Ich würde ja die Geräte einfach zurückschicken und andere kaufen die auch Tuya/SmartLife sind und damit neu versuchen. Im Worst case kommt da ein Gerät mit neuer Firmware was hoffentlich bald geht

**Comment by Apollon77** [comment]
Aber ich kann hier gerade nur zu machen weil scheinbar das Gerät am Port 6668 nicht reagiert wie es eigentlich sollte. Vllt haben die da noch was mehr limitiert.

**Comment by philipplindner-media-network** [comment]
Vielen Dank für deine Mühe ich werde sie trotzdem behalten und wo anders einsetzen. Wo Ich Nicht so Drauf angewiesen bin.
