### ISSUE TITLE
externe Geräte lassen sich nicht steuern

### ISSUE THREAD

**Issue by MrBaltimore** [Apollon77/ioBroker.tuya#471]
Nabend,

erstmal ein Lob für die tolle Arbeit. Deinen Namen les ich irgendwie ziemlich oft bei den Adaptern ;-).

Nun zum Problem:
- Tuya Adapter installiert und mit SmartLife App verbunden
- Geräte werden alle erkannt und eingelesen

Geräte die im lokalem Netzwerk liegen können auch problemlos gesteuert werden. Alle externen Geräte (2 Steckdosen im Ferienhäuschen) werden zwar angezeigt, sind aber nicht ansprechbar über den Adapter. Über die App sind beide steuerbar.

Keine Ahung, ob das speziell nur bei mir nicht funktioniert oder ob das so gewollt ist. Wäre auf jeden Fall genial, wenn es funktionieren würde.

**Versions:**  
 - Adapter version: 3.7.2
 - JS-Controller version: 4.0.23
 - Node version: 16.5.1
 - Operating system: Docker Container auf QNAP NAS

**Comment by Apollon77** [comment]
Naja, der Adapter arbeitet aktuell ausschliesslich lokal. Wenn er also lokal nicht zu den geräten verbinden kann - was bei deinem Ferienhaus gegeben sein sollte, geht nichts.

Ich nehme es mal als Feature Request mit das Cloud-basierte Steuerung gewünscht wird

**Comment by MrBaltimore** [comment]
Ok, das der Adapter rein lokal arbeitet war mir nicht bewusst. Habe ich anscheinend überlesen.

Wäre echt klasse, wenn die Cloud-basierte Steuerung umgesetzt würde.

**Comment by Apollon77** [comment]
Wenn Du testen willst: https://forum.iobroker.net/topic/59663/test-adapter-tuya-3-8-0

**Comment by MrBaltimore** [comment]
Uii, das hört sich sehr interessant an. Bin leider grad im besagten Ferienhaus 😉. Morgen warten 60m Hecke auf mich und wollen in Form gebracht werden. Ich könnt 🤮.
Komme erst Sonntag dazu und mach dann Meldung.

**Comment by Apollon77** [comment]
Na dann "Vile Spass" ...

**Comment by MrBaltimore** [comment]
So, hab jetzt alles installiert. tuya IoT Account erstellt und Access ID und Secret eingetragen.
Verbindung kommt zustande und Geräte werden angelegt.
Schalten klappt auch wunderbar, aber genau das war es auch. Die Datenpunkte für V, W, mA, IP und Device online Status werden zwar angelegt, werden aber nicht aktualisiert. Haken bei Geräte über Cloud abfragen... ist gesetzt.

Interessant ist, dass bei 2 Steckdosen, die schon lange registriert sind (immer lokal), mehr Datenpunkte angelegt werden, als bei den beiden (1 x lokal, 1x extern) die ich erst letzte Woche hinzugefügt habe. Alle Wichtigen sind aber, bei den Neuen, da.

Das Log zeigt einiges an, aber nur Info und Warning - kein Error. Wills nicht unbedingt posten, keine Ahnung was man mit den Device IDs so alles anfangen kann. Falls du es haben willst, schicke ich es dir lieber direkt zu.

**Comment by Apollon77** [comment]
Am Ende bitte Instanz auf Debug loglevel setzen, dann bissl mitlaufen lassen und dann Log aus /opt/iobroker/log/... nehmen und mit an iobroker@fischer-ka.de sendenund dagen welche Geräte ggf nicht passen, dann schau ich mal was ich dem Log entnehmen kann.

Was die iot Platform angeht: Du hast aber deinen App Accuont auch dort verknüpft wie es in der Anleitung steht?

**Comment by MrBaltimore** [comment]
Klar, es werden mir auch alle devices angezeigt und unter Account steht auch der richtige. Schalten geht ja auch, was vorher nicht möglich war. 

Den Rest mach ich heute Abend

**Comment by Apollon77** [comment]
3.9.1 released

**Comment by kuch3n** [comment]
Gefunden, tatsächlich kam keine Version aus der Cloud. Objekt editiert und Version auf `3.3` gesetzt.
