### ISSUE TITLE
None of the discovered devices matches :-(

### ISSUE THREAD

**Issue by Domi920** [Apollon77/ioBroker.tuya#474]
.Hallo,
habe ein paar neue Rolloschalter verbaut, leider kann ich diese über den Adapter nicht ansteuern.
In den Objekten fehlt auch die IP Adresse.

Was kann man machen? 

@Apollon77 gibt es eine einfache Lösung?

Habe die Version 3.8.0 installiert (auf der "alten" funktionierte es auch nicht)

Gruß Dominik

**Comment by Apollon77** [comment]
Dann bitte Debug Log posten. ggf 3.4er oder 3.2er device ... dann ggf duplicate #457

**Comment by Domi920** [comment]
Danke für die schnelle Antwort!

Wenn ich in den Objektdaten folgendes hinzufüge:

(Zeile 144)
dann funktioniert die Ansteuerung, aber leider kommen keine Daten zurück.
![2022-11-04](https://user-images.githubusercontent.com/68474558/200047834-836a930b-e7cc-472d-a828-740641c1c209.png)

in den Objekten fehlt die IP-Adresse. Diese konnte ich aber über die Smartlife App nicht herausfinden.
Gibt es einen Trick?


Es geht umd as Gerät:
bf8aeda8b58d7d8d86rsmg


Hier der Debug Log im Anhang
[iobroker.2022-11-04.log.zip](https://github.com/Apollon77/ioBroker.tuya/files/9941093/iobroker.2022-11-04.log.zip)

**Comment by Apollon77** [comment]
wie vermutet 

> 2022-11-04 19:16:51.644 - debug: tuya.0 (11146) bf8aeda8b58d7d8d86rsmg: No relevant Data for default decrypt try: {"payload":{"ip":"192.162.2.248","gwId":"bf8aeda8b58d7d8d86rsmg","active":2,"ablilty":0,"encrypt":true,"productKey":"peuxry657kkycsar","version":"3.4","token":true,"wf_cfg":true},"leftover":false,"commandByte":35,"sequenceN":0}

ein 3.4er Gerät.

Sollte mit der 3.8.0 vom Adapter erstmal über cloud gehen?

Ansonsten duplicate #457 

... suche immer noch so ein gerät für die Tests :-)

**Comment by Domi920** [comment]
Die Ansteuerung des Gerätes funktioniert, ja.
Allerdings werden die Daten nicht zurück synchronisiert.

Wie kann ich helfen?
Bzw. wie sollen wir weiterverfahren?

**Comment by Domi920** [comment]
Weiß nicht ob es hilft, aber diese Rollo Schalter habe ich, die 3.4 verwenden.
https://www.amazon.de/dp/B0B64X3QX9/ref=twister_B0B64VC2CW?_encoding=UTF8&psc=1

**Comment by Apollon77** [comment]
>  Allerdings werden die Daten nicht zurück synchronisiert.

Hast Du die Cloud Daten gespeichert? Wenn ja dann läuft die steuerung über die cloud ... also im Admin noch "polle daten von der cloud" anhaken und er sollte aus der cloud die daten auch lesen - aber halt nicht realtime ... es sei den ... ach lies einfach den ersten Post  unter https://forum.iobroker.net/topic/59663/test-adapter-tuya-3-8-0/ . das teht alles was die 3.8.0 anbelangt

**Comment by Apollon77** [comment]
Sobald die 3.8.0 released ist wollte ich mir das 3.4 Thema ansehen und ja mit einem Testgerät wäre das viel einfacher ... Wenn du das tun würdest wäre das cool (muss ich dann wohl mal wieder mein "230V Hoffe-keiner kriegt-nen-Schlag Sonderkabel" aus dem Schrank holen ;-))

Melde dich bitte mal bei iobroker@fischer-ka.de wenn du magst

**Comment by Domi920** [comment]
Hab ich gemacht :-)

**Comment by Apollon77** [comment]
Try  --> https://forum.iobroker.net/topic/59899/test-adapter-tuya-3-9-x-alpha-github
