### ISSUE TITLE
renaming of device in App: sync after adapter start appreciated 

### ISSUE THREAD

**Issue by latzi0710** [Apollon77/ioBroker.tuya#476]
When a device is renamed in the app and the adapter-sync is performed it would be great if the device name under tuya.x.device-xy is renamed automatically.

Many thanks for the great work in version 3.8 - a real big milestone 👏 !!!

**Comment by Apollon77** [comment]
@latzi0710 Please try GitHub version ... This should only preseve the sub states and not the devcie name anymore

**Comment by latzi0710** [comment]
No, unfortunately name of device keeps unchanged. Do you need a debug-log?

**Comment by Apollon77** [comment]
pleas retry 3.8.1 again. FOr me all this works

**Comment by latzi0710** [comment]
works great 👏 👍 !!!
Thanks a lot
