### ISSUE TITLE
New Version 3.8.1 disconnects from devices every 30min

### ISSUE THREAD

**Issue by mk176** [Apollon77/ioBroker.tuya#478]
First of all, i want to say thanks for the great work on all the adapters you provide and the good support you provide.
I found a bug/issue after installin the new version of the tuya adapter

**Describe the bug**  
After installing the new version 3.8.1 the power plug is disconnected every 30 min and automatically reconnected after 6min
with the older version 3.7.2 it is continously connected

**To Reproduce**  
1. Upgrade to 3.8.1
2. See error

**Expected behavior**  
Continously connected to the device

**Screenshots & Logfiles**  
2022-11-09 16:20:06.745  - warn: tuya.0 (8508) bf299798a35bbaeacdvntu: Error on Reconnect: connection timed out
...
2022-11-09 16:21:56.745 - info: tuya.0 (8508) bf299798a35bbaeacdvntu Init with IP=192.168.0.148, Key=xxxxxxxxxxxxxxxx, Version=3.3

**Versions:**  
 - Adapter version: 3.8.1
 - JS-Controller version: 4.0.23
 - Node version: 16.18.0
 - Operating system: Windows 10

**Comment by mk176** [comment]
Closed it since i do have the same problems with the version 3.7.2
But only since 1 week. So i was assuming it is the new version.
But after downgrading it happend also after 4 hour.
I need to investigate the issue further more to find the root cause

**Comment by Apollon77** [comment]
Maybe reboot the device

**Comment by Apollon77** [comment]
PS: But in the end ... whats the issue with a reconnect?
