### ISSUE TITLE
Incorrect local timer, please correct it. 50502

### ISSUE THREAD

**Issue by m0rph3u** [Apollon77/ioBroker.tuya#479]
Hi,

ich habe den Tuya Adapter -Proxy schon lange nicht mehr benutzt. Aber nach meinem letzten Kenntnisstand klappte die Synchronisierung das letzte mal, mit der Smart Life App Version 3.12.6 Android noch ohne Probleme.

Jetzt wollte ich mal wieder neue Geräte hinzufügen und erhalte nun jedesmal den Fehler "Incorrect local timer, please correct it. 50502". Nach anfänglicher Ratlosigkeit. Überprüfung der Zeitzone etc konnte ich das Problem nach mehreren Stunden endlich lokalisieren.

Bei meinem Setup liefert der Tuya Adapter anscheinend eine abgelaufene Version des Zertifikates NodeMITMProxyCA aus. (Screenshot Anbei). Das Zertifikat ist seit 16.02.2022 abgelaufen. Heute ist der 12.11.2022. Ich weis nicht ob das ein generelles Problem ist. Oder ob es nur an meinem Setup liegt.

Ich konnte das Problem jedenfalls dahingehend lösen, indem ich auf dem Android Gerät das Datum auf 12.01.2022 umgestellt habe. Danach klappte die Synchronisierung ohne Probleme.

Gibt es eine Möglichkeit die Laufzeit des Zertifikates wieder zu verlängern?

Viele Grüße
![Screenshot_2022-11-12-22-38-22](https://user-images.githubusercontent.com/73857179/201496501-7fa192e0-b86c-4216-8108-fabcc1f0f029.png)

**Comment by Apollon77** [comment]
Ehrlich ... Updaten auf 3.8.1 und freuen das Proxy nicht mehr nötig ist :-)
