### ISSUE TITLE
'None of the discovered devices matches :-(' messages in log

### ISSUE THREAD

**Issue by dadolphs** [Apollon77/ioBroker.tuya#480]
I see on a regular base a lot of _None of the discovered devices matches :-(_ messages in the log and every messages is preceeded with a unique ID. Sometimes (!!) I see also the message _Error on Reconnect: connection timed out_ in between these messages.

**Comment by Apollon77** [comment]
See Forum.
* "None of the discovered devices matches"  means that there is an UDP package that could not be decrypted
* "Error on Reconnect: connection timed out" means that a device disconnected the adapter and the adapter got a timout when trying to reconnect.
Can happen :)
