### ISSUE TITLE
new Schema added for product type xpaqxtzoftcxrpuu. Please send next line from logfile on disk to developer!

### ISSUE THREAD

**Issue by MarcProe** [Apollon77/ioBroker.tuya#481]
Hi! I hope this is the correct way reporting this.

LSC A60-PA-WIFILIC-TY-CCT (An E27 light Bulb)

tuya.0 | 2022-11-15 08:16:06.261 | info | {"schemaExt":"[{\"complexType\":\"\",\"id\":22,\"inputStyle\":\"\",\"inputType\":\"percent1\"},{\"complexType\":\"\",\"id\":23,\"inputStyle\":\"\",\"inputType\":\"percent\"},{\"complexType\":\"\",\"id\":26,\"inputStyle\":\"\",\"inputType\":\"countdown1\"}]","schema":"[{\"code\":\"switch_led\",\"defaultValue\":\"\",\"canTrigger\":true,\"iconname\":\"icon-dp_power\",\"type\":\"obj\",\"executable\":true,\"mode\":\"rw\",\"defaultRecommend\":true,\"name\":\"开关\",\"property\":{\"type\":\"bool\"},\"id\":20,\"editPermission\":false},{\"code\":\"work_mode\",\"defaultValue\":\"\",\"canTrigger\":true,\"iconname\":\"icon-dp_mode\",\"type\":\"obj\",\"executable\":true,\"mode\":\"rw\",\"defaultRecommend\":true,\"name\":\"模式\",\"property\":{\"range\":[\"white\",\"colour\",\"scene\",\"music\"],\"type\":\"enum\"},\"id\":21,\"editPermission\":false},{\"code\":\"bright_value\",\"defaultValue\":\"\",\"canTrigger\":true,\"iconname\":\"icon-liangdu1\",\"type\":\"obj\",\"executable\":true,\"mode\":\"rw\",\"defaultRecommend\":true,\"name\":\"白光亮度\",\"property\":{\"min\":10,\"max\":1000,\"scale\":0,\"step\":1,\"type\":\"value\"},\"id\":22,\"editPermission\":false},{\"code\":\"temp_value\",\"defaultValue\":\"\",\"canTrigger\":true,\"iconname\":\"icon-dp_half\",\"type\":\"obj\",\"executable\":true,\"mode\":\"rw\",\"defaultRecommend\":true,\"name\":\"冷暖值\",\"property\":{\"min\":0,\"max\":1000,\"scale\":0,\"step\":1,\"type\":\"value\"},\"id\":23,\"editPermission\":false},{\"code\":\"scene_data\",\"defaultValue\":\"\",\"canTrigger\":true,\"iconname\":\"icon-shoucang\",\"type\":\"obj\",\"executable\":true,\"mode\":\"rw\",\"defaultRecommend\":true,\"name\":\"场景\",\"property\":{\"type\":\"string\",\"maxlen\":255},\"id\":25,\"editPermission\":false},{\"code\":\"countdown\",\"defaultValue\":\"\",\"canTrigger\":true,\"iconname\":\"icon-a_nav_timer\",\"type\":\"obj\",\"executable\":true,\"mode\":\"rw\",\"defaultRecommend\":true,\"name\":\"倒计时\",\"property\":{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1,\"type\":\"value\"},\"id\":26,\"editPermission\":false},{\"code\":\"control_data\",\"defaultValue\":\"\",\"canTrigger\":true,\"iconname\":\"icon-dp_box2\",\"type\":\"obj\",\"executable\":true,\"mode\":\"wr\",\"defaultRecommend\":true,\"name\":\"实时调节\",\"property\":{\"type\":\"string\",\"maxlen\":255},\"id\":28,\"editPermission\":false},{\"code\":\"rhythm_mode\",\"defaultValue\":\"\",\"canTrigger\":true,\"iconname\":\"icon-dp_time3\",\"type\":\"raw\",\"executable\":true,\"mode\":\"rw\",\"defaultRecommend\":true,\"name\":\"生物节律\",\"property\":{\"type\":\"raw\",\"maxlen\":128},\"id\":30,\"editPermission\":false},{\"code\":\"sleep_mode\",\"defaultValue\":\"\",\"canTrigger\":true,\"iconname\":\"icon-dp_sleep\",\"type\":\"raw\",\"executable\":true,\"mode\":\"rw\",\"defaultRecommend\":true,\"name\":\"灯光助眠\",\"id\":31,\"editPermission\":false},{\"code\":\"wakeup_mode\",\"defaultValue\":\"\",\"canTrigger\":true,\"iconname\":\"icon-dp_sun\",\"type\":\"raw\",\"executable\":true,\"mode\":\"rw\",\"defaultRecommend\":true,\"name\":\"灯光唤醒\",\"id\":32,\"editPermission\":false},{\"code\":\"remote_switch\",\"defaultValue\":\"\",\"canTrigger\":true,\"iconname\":\"icon-dp_power\",\"type\":\"obj\",\"executable\":true,\"mode\":\"rw\",\"defaultRecommend\":false,\"name\":\"遥控器开关\",\"property\":{\"type\":\"bool\"},\"id\":41,\"editPermission\":false}]"}
-- | -- | -- | --
tuya.0 | 2022-11-15 08:16:06.261 | info | new Schema added for product type xpaqxtzoftcxrpuu. Please send next line from logfile on disk to developer!

**Comment by Apollon77** [comment]
thank you, will be in next version
