### ISSUE TITLE
Add support for groups

### ISSUE THREAD

**Issue by padrino-x** [Apollon77/ioBroker.tuya#484]
Would be nice if the adapter handled groups, too. =)
Thanks.

**Comment by Apollon77** [comment]
@padrino-x Please try GitHub version. I was only able to test it with a simple "two sockets" group because I have not more devices ... so please try if that works out also for lamps and such - also test the new rgb states and such

**Comment by Ilovegym66** [comment]
works fine, with 5 Groups, thank you!

**Comment by Apollon77** [comment]
Please retest GitHub version. Groups needs to be controlled via cloud for their status to be correct

**Comment by Ilovegym66** [comment]
test successful. Tested with 4 groups, different lamps (one group with 2x up/downlights, other group 6x spotlights, next group with 2x ceiling lights, next with 3x bulbs e27). 
Tested functions: on/off, color, brightness.  
Testprocedure: change status in iobroker, and change status in app. Both are sync after some seconds.

**Comment by Apollon77** [comment]
cool ... Did you also tested the special RGB states that they work correctly?

**Comment by Ilovegym66** [comment]
not tested, now tested, not working. 
Set rgb in object 24-colordata rgb , no reactions. object are not filled from adapter if I change it from the app.

**Comment by Apollon77** [comment]
Could I get a debug log from such a change pelase?

**Comment by Ilovegym66** [comment]
ok, done, I send it with reference to this issue to your email. :)

**Comment by Apollon77** [comment]
Wow ... why the heck groups have again other data formats ...I hate them ;-)

Can you please provide me the JSON of the "groups.8356529" device object?

**Comment by Ilovegym66** [comment]
`{
  "type": "device",
  "common": {
    "name": "Büro-OGB-Gruppe",
    "read": true
  },
  "native": {
    "standard": false,
    "groupType": 0,
    "dpName": {
      "20": "",
      "21": "",
      "22": "",
      "23": "",
      "24": "",
      "25": "",
      "26": "",
      "28": "",
      "29": "",
      "30": "",
      "31": "",
      "32": ""
    },
    "pv": "2.2",
    "type": 0,
    "groupKey": "",
    "deviceNum": 2,
    "id": 8356529,
    "iconUrl": "https://images.tuyaeu.com/smart/icon/bay1582107078862SB6a/16048840777eef662f2f9.png",
    "devId": "",
    "productId": "qgtabvdolwnyncad",
    "dps": {
      "20": false,
      "21": 1,
      "22": 68.1,
      "23": 796,
      "24": "015901dc036c",
      "25": "",
      "26": 0,
      "28": "1006f01dc036c00000000",
      "29": "",
      "30": "",
      "31": "",
      "32": ""
    },
    "name": "Büro-OGB-Gruppe",
    "localKey": "3502e1dd7417878a",
    "gid": 8962714,
    "children": [
      "bfca0ac8444651ebeeqcqy",
      "bff755bafd2a4ec063efix"
    ],
    "groupSchema": {
      "schema": [
        {
          "code": "switch_led",
          "defaultValue": "",
          "canTrigger": true,
          "iconname": "icon-dp_power",
          "type": "obj",
          "executable": true,
          "mode": "rw",
          "defaultRecommend": true,
          "name": "开关",
          "property": {
            "type": "bool"
          },
          "id": 20,
          "editPermission": false
        },
        {
          "code": "work_mode",
          "defaultValue": "",
          "canTrigger": true,
          "iconname": "icon-dp_mode",
          "type": "obj",
          "executable": true,
          "mode": "rw",
          "defaultRecommend": true,
          "name": "模式",
          "property": {
            "range": [
              "white",
              "colour",
              "scene",
              "music"
            ],
            "type": "enum"
          },
          "id": 21,
          "editPermission": false
        },
        {
          "code": "bright_value",
          "defaultValue": "",
          "canTrigger": true,
          "iconname": "icon-liangdu1",
          "type": "obj",
          "executable": true,
          "mode": "rw",
          "defaultRecommend": true,
          "name": "亮度值",
          "property": {
            "min": 10,
            "max": 1000,
            "scale": 0,
            "step": 1,
            "type": "value"
          },
          "id": 22,
          "editPermission": false
        },
        {
          "code": "temp_value",
          "defaultValue": "",
          "canTrigger": true,
          "iconname": "icon-dp_half",
          "type": "obj",
          "executable": true,
          "mode": "rw",
          "defaultRecommend": true,
          "name": "冷暖值",
          "property": {
            "min": 0,
            "max": 1000,
            "scale": 0,
            "step": 1,
            "type": "value"
          },
          "id": 23,
          "editPermission": false
        },
        {
          "code": "colour_data",
          "defaultValue": "",
          "canTrigger": true,
          "iconname": "icon-yanse",
          "type": "obj",
          "executable": true,
          "mode": "rw",
          "defaultRecommend": true,
          "name": "彩光",
          "property": {
            "type": "string",
            "maxlen": 255
          },
          "id": 24,
          "editPermission": false
        },
        {
          "code": "scene_data",
          "defaultValue": "",
          "canTrigger": true,
          "iconname": "icon-shoucang",
          "type": "obj",
          "executable": true,
          "mode": "rw",
          "defaultRecommend": true,
          "name": "场景",
          "property": {
            "type": "string",
            "maxlen": 255
          },
          "id": 25,
          "editPermission": false
        },
        {
          "code": "countdown",
          "defaultValue": "",
          "canTrigger": true,
          "iconname": "icon-a_nav_timer",
          "type": "obj",
          "executable": true,
          "mode": "rw",
          "defaultRecommend": true,
          "name": "倒计时",
          "property": {
            "min": 0,
            "max": 86400,
            "scale": 0,
            "step": 1,
            "type": "value"
          },
          "id": 26,
          "editPermission": false
        },
        {
          "code": "control_data",
          "defaultValue": "",
          "canTrigger": true,
          "iconname": "icon-dp_box2",
          "type": "obj",
          "executable": true,
          "mode": "wr",
          "defaultRecommend": true,
          "name": "调节",
          "property": {
            "type": "string",
            "maxlen": 255
          },
          "id": 28,
          "editPermission": false
        },
        {
          "code": "debug_data",
          "defaultValue": "",
          "canTrigger": true,
          "iconname": "icon-dp_tool",
          "type": "obj",
          "executable": true,
          "mode": "wr",
          "defaultRecommend": false,
          "name": "调试",
          "property": {
            "type": "string",
            "maxlen": 255
          },
          "id": 29,
          "editPermission": false
        },
        {
          "code": "rhythm_mode",
          "defaultValue": "",
          "canTrigger": true,
          "iconname": "icon-dp_time3",
          "type": "raw",
          "executable": true,
          "mode": "rw",
          "defaultRecommend": false,
          "name": "生物节律",
          "property": {
            "type": "raw",
            "maxlen": 128
          },
          "id": 30,
          "editPermission": false
        },
        {
          "code": "sleep_mode",
          "defaultValue": "",
          "canTrigger": true,
          "iconname": "icon-dp_sleep",
          "type": "raw",
          "executable": true,
          "mode": "rw",
          "defaultRecommend": false,
          "name": "入睡计划",
          "property": {
            "type": "raw",
            "maxlen": "255"
          },
          "id": 31,
          "editPermission": false
        },
        {
          "code": "wakeup_mode",
          "defaultValue": "",
          "canTrigger": true,
          "iconname": "icon-dp_sun",
          "type": "raw",
          "executable": true,
          "mode": "rw",
          "defaultRecommend": false,
          "name": "唤醒计划",
          "property": {
            "type": "raw",
            "maxlen": "255"
          },
          "id": 32,
          "editPermission": false
        }
      ],
      "schemaExt": [
        {
          "complexType": "plain",
          "id": 20,
          "inputStyle": "",
          "inputType": ""
        },
        {
          "complexType": "",
          "id": 22,
          "inputStyle": "bright",
          "inputType": "percent1"
        },
        {
          "complexType": "",
          "id": 23,
          "inputStyle": "temp",
          "inputType": "percent"
        },
        {
          "complexType": "",
          "id": 26,
          "inputStyle": "plain",
          "inputType": "countdown1"
        }
      ]
    },
    "dpIdList": [
      20,
      21,
      22,
      23,
      24,
      25,
      26,
      28,
      29,
      30,
      31,
      32
    ]
  },
  "from": "system.adapter.tuya.0",
  "user": "system.user.admin",
  "ts": 1669727622696,
  "_id": "tuya.0.groups.8356529",
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}`

**Comment by Apollon77** [comment]
Ok, another check can be dine with GitHub version

**Comment by Apollon77** [comment]
released in 3.10.0
