### ISSUE TITLE
Tuya Smart Meter not updating values

### ISSUE THREAD

**Issue by ManuelBu96** [Apollon77/ioBroker.tuya#488]
I have installed two new smart meter at home and they only sync the correct values if the app on my mobile phone is open. The sync intervall is every 30 seconds. The connection is direct over the lan and not over the cloud.

`tuya.0 | 2022-11-26 14:18:59.719 | debug | stateChange tuya.0.bfdeeab851deb54bc8qayu.19 |  {"val":424,"ack":true,"ts":1669468739710,"q":0,"from":"system.adapter.tuya.0","user":"system.user.admin","lc":1669468438530}
tuya.0 | 2022-11-26 14:19:29.823 | debug | stateChange tuya.0.bfdeeab851deb54bc8qayu.19 | {"val":424,"ack":true,"ts":1669468769816,"q":0,"from":"system.adapter.tuya.0","user":"system.user.admin","lc":1669468438530}`

**Expected behavior**  
Syncing the correct value without open the app on the mobile phone

**Versions:**  
 - Adapter version: v3.9.4
 - JS-Controller version: v5.7.0
 - Node version:  v12.22.12
 - Operating system: debian 10

If you need more logs or information feel free to contact me.

**Comment by Apollon77** [comment]
Yes there are Tuya devices that do not push values out by themself but with the polling interval it should update the values in this interval also without the open app. if this is NOT working please provide a debug log

**Comment by Apollon77** [comment]
PS: If you like real time updates of these devices you might have a chance by using the Cloud credentials and also signup for that iot platform and then values could come in via MQTT from tuya cloud servers - but as said ... should work in poll interval

**Comment by ManuelBu96** [comment]
> Yes there are Tuya devices that do not push values out by themself but with the polling interval it should update the values in this interval also without the open app. if this is NOT working please provide a debug log

Ok the poll of these devices is working but the value is every time the same as you see in the log.
![grafik](https://user-images.githubusercontent.com/24299595/204102821-eb3cb910-bb7c-4d8c-a2ca-9ac80909b1de.png)
![grafik](https://user-images.githubusercontent.com/24299595/204102890-1ab142d9-f34c-45c6-ae30-8b0f2f499d0e.png)


[log.txt](https://github.com/Apollon77/ioBroker.tuya/files/10096789/log.txt)

**Comment by Apollon77** [comment]
Ok, also was ich sehe ich das das Gerät leider auf die Anfrage immer die gleichen "alten" Werte zurückgibt.

Bitte mal folgendes machen:
* Adapter stoppen
* per SSH einloggen
* `DEBUG=Tuya* iob debug tuya` ausführen
* Dann ohne offene app laufen lassen kurz bis er ein paarmal daten geholt hat
* Ausgabe der Shell in Textfile und hier anhängen

Mit dem erweiterten Log sehe ich was genau auf der Kommunikationsebene abgeht

**Comment by ManuelBu96** [comment]
Hier der benötigte Log.
Die beiden Smart Meter haben die folgenden IDs
- bfdeeab851deb54bc8qayu
- bf98912a880aa0dea9o4tl

[log.txt](https://github.com/Apollon77/ioBroker.tuya/files/10116248/log.txt)

**Comment by Apollon77** [comment]
meeehh  .... ich hatte nen Copy/Pase error drin. kannst bitte nochmal machen:

`DEBUG=TuyAPI* iob debug tuya`

**Comment by Apollon77** [comment]
Hm ... all the relevant infos I miss still in the log ... 


When I start a process that way I get something like this ....


![Bildschirm­foto 2022-11-30 um 22 02 18](https://user-images.githubusercontent.com/11976694/204907311-63718fda-0459-4b37-a0ea-228ff746859a.png)

it is clear that the "colors" are not in the textfile but Ineed these infos ... it this not the same when you run this?

**Comment by ManuelBu96** [comment]
Nein es sieht nicht genauso aus wie bei dir. Ich habe das gleiche aussehen wie bei dem vorherigen Test.
DEBUG=Tuya* iob debug tuya
DEBUG=TuyAPI* iob debug tuya
Bringen genau die gleichen Ausgaben.
================================================================
No, it doesn't look the same as yours. I have the same look as the previous test.
DEBUG=Tuya* iob debug tuya
DEBUG=TuyAPI* iob debug tuya
Bring exactly the same outputs.

**Comment by ManuelBu96** [comment]
Ja jetzt sind die erweiterten Logs da.

[log.txt](https://github.com/Apollon77/ioBroker.tuya/files/10131188/log.txt)

**Comment by Apollon77** [comment]
Ok, das Gerät gibt die Daten genau so zurück wie dsie ankommen. Dann bleibt nur eine Idee.

1.) Bitte von GitHub updaten
2.) Adapter stoppen
3.) Unter Admin - Objekte das Device Objekt der betroffenen geräte editieren: 
* in der Zeile mit dem Objekt vom Typ "device" hinten rechts auf den Stift drücken
* Dann kommt ein JSON von dem Objekt (ggf auf den Raw object/Json tab gehen)
* dort im Bereich "native", auf der gleichen ebene wo auch "ip" bzw "localKey" ist noch eine Zeile mit 
`"useRefreshToGet": true,` hinzufügen.
(vllt zur sicherheit das ganze JSON vorher sichern falls was kaputt geht)
4.) Adapter mal bitte wieder so starten wie beim letzten log und dann schauen ob jetzt aktuelle werte beim polling ankommen. Log nehme ich gern zum veriofizierne auch wenns klappt

**Comment by ManuelBu96** [comment]
Also ich habe beide Gerät nach deiner Anleitung angepasst. Leider keine Veränderung. Die Werte werden immer noch nicht aktualisiert. Hier nochmal der Log

[log.txt](https://github.com/Apollon77/ioBroker.tuya/files/10132893/log.txt)

Ich habe vorher auch nochmal die App deinstalliert und über GitHub installiert. Alle Geräte neu verbunden.

**Comment by Apollon77** [comment]
Ok, there was an issue in another part of the adapter ... getting complex ... please try github again and provide same log again. thank you (und ja keine ahnung watrum ich englisch geschrieben hab)
