### ISSUE TITLE
Erste Inbetriebnahme und Neues Gerät

### ISSUE THREAD

**Issue by Matdos** [Apollon77/ioBroker.tuya#49]
Nach der Installation hat sich bei mir das Pop Up Fenster mit dem Qr Code nicht geöffnet, das lag daran das mein Raspberry zu wenig Ram übrig hatte, nachdem ich für die Syncronisation ein paar Adapter abgeschaltet habe (500Mb freier Ram) hat dann alles funktioniert (auf Youtube gibt es eine super Anleitung).

Jetzt habe ich die App Syncronisiert nur habe ich jetzt im Log eine Meldung über ein neues Gerät bekommen das ich an den Entwickler weiterleiten soll.

![1](https://user-images.githubusercontent.com/51334337/58819801-4a533f80-8631-11e9-8a88-fa30248fc84f.png)
![2](https://user-images.githubusercontent.com/51334337/58819807-4f17f380-8631-11e9-8c76-7eeaf3771344.png)
![3](https://user-images.githubusercontent.com/51334337/58819816-517a4d80-8631-11e9-96fb-7d540c7ab92a.png)

**Comment by Apollon77** [comment]
Hast Du es bitte als Text - am besten direkt aus dem Log auf der Platte unter /opt/iobroker/log/... ?! Danke

**Comment by Matdos** [comment]
wenn ich cd opt/iobroker/log/ eingebe kommt Verzeichnis nicht gefunden, wie kommeich da hin?

**Comment by Matdos** [comment]
Das hier?

XCEjLKZzUQNuA. Please send next line from logfile on disk to developer!
2019-06-03 14:00:02.577  - info: tuya.0 {"schema":"[{\"mode\":\"rw\",\"code\
":\"led_switch\",\"name\":\"开关\",\"property\":{\"type\":\"bool\"},\"iconname\":\"i
con-dp_power2\",\"id\":1,\"type\":\"obj\",\"desc\":\"\"},{\"mode\":\"rw\",\"code\":\
"work_mode\",\"name\":\"模式\",\"property\":{\"range\":[\"white\",\"colour\",\"scene
\",\"scene_1\",\"scene_2\",\"scene_3\",\"scene_4\"],\"type\":\"enum\"},\"iconname\":
\"icon-dp_mode\",\"id\":2,\"type\":\"obj\",\"desc\":\"\"},{\"mode\":\"rw\",\"code\":
\"bright_value\",\"name\":\"亮度\",\"property\":{\"unit\":\"\",\"min\":25,\"max\":25
5,\"scale\":0,\"step\":1,\"type\":\"value\"},\"iconname\":\"icon-dp_sun\",\"id\":3,\
"type\":\"obj\",\"desc\":\"\"},{\"mode\":\"rw\",\"code\":\"temp_value\",\"name\":\"
冷暖\",\"property\":{\"unit\":\"\",\"min\":0,\"max\":255,\"scale\":0,\"step\":1,\"ty
pe\":\"value\"},\"iconname\":\"icon-dp_light\",\"id\":4,\"type\":\"obj\",\"desc\":\"
\"},{\"mode\":\"rw\",\"code\":\"colour_data\",\"name\":\"彩光模式数\",\"property\":{
\"type\":\"string\",\"maxlen\":14},\"id\":5,\"type\":\"obj\",\"desc\":\"rgbhsv\"},{\
"mode\":\"rw\",\"code\":\"scene_data\",\"name\":\"情景模式数\",\"property\":{\"type\
":\"string\",\"maxlen\":14},\"id\":6,\"type\":\"obj\",\"desc\":\"rgbhsv\"},{\"mode\"
:\"rw\",\"code\":\"flash_scene_1\",\"name\":\"柔光模式\",\"property\":{\"type\":\"st
ring\",\"maxlen\":14},\"id\":7,\"type\":\"obj\",\"desc\":\"\"},{\"mode\":\"rw\",\"co
de\":\"flash_scene_2\",\"name\":\"缤纷模式\",\"property\":{\"type\":\"string\",\"max
len\":44},\"id\":8,\"type\":\"obj\",\"desc\":\"\"},{\"mode\":\"rw\",\"code\":\"flash
_scene_3\",\"name\":\"炫彩模式\",\"property\":{\"type\":\"string\",\"maxlen\":14},\"
id\":9,\"type\":\"obj\",\"desc\":\"\"},{\"mode\":\"rw\",\"code\":\"flash_scene_4\",\
"name\":\"斑斓模式\",\"property\":{\"type\":\"string\",\"maxlen\":44},\"id\":10,\"ty
pe\":\"obj\",\"desc\":\"\"}]","schemaExt":"[{\"id\":3,\"inputType\":\"percent1\"},{\
"id\":4,\"inputType\":\"percent1\"}]"}
2019-06-03 14:00:02.804  - info: tuya.0 60010752bcddc29067e2 Init with IP=19

**Comment by Apollon77** [comment]
Danke!

**Comment by Matdos** [comment]
Bin froh das es passt ;-) Ich danke für die Unterstützung und für den Adapter!!

**Comment by Apollon77** [comment]
thank you
