### ISSUE TITLE
Change of IP

### ISSUE THREAD

**Issue by OberfragGER** [Apollon77/ioBroker.tuya#494]
**Is your feature request related to a problem? Please describe.**
When the IP og a device changes after connecting to the adapter, the old IP is still stored an the adapter is not turning green

**Describe the solution you'd like**
Make the IP writable.

**Describe alternatives you've considered**
Maybe a "new discover"?

**Additional context**
At the moment the Workaroun is to delet the instance an objects ans create the instance new.

**Comment by Apollon77** [comment]
Already implemented since 3.9.2

**Comment by Apollon77** [comment]
At "Objects" in Admin under the "device" there is an IP state ... just enter the correct IP there ad set the new one as value (ack=false) and it shgould update it

**Comment by Apollon77** [comment]
Hm, you areright ... fix will come in 3.10.1
