### ISSUE TITLE
Adapter won't connect + when connected doesn't switch in some cases

### ISSUE THREAD

**Issue by andiweli** [Apollon77/ioBroker.tuya#496]
**Describe the bug**  
Adapter shows "not connected" but seems to be connected + switching devices with Home app and/or Tuya app doesn't switch the device itself in some cases.

**To Reproduce**  
I've set the 3 state-switches of my 6-port-outlet to be switchable with Yahka:

![yahka](https://user-images.githubusercontent.com/11447150/205887252-73d4cc46-7b49-474d-9358-48a565ea5766.PNG)

![tuya](https://user-images.githubusercontent.com/11447150/205887340-6fa7123a-f472-4afc-9ac4-329197d36a03.PNG)

**Expected behavior**  
When switching with Home app or Tuya app, the values under "objects" in ioBroker should change from true to false (and the other way round).

**Screenshots & Logfiles**  
See above.

**Versions:**  
 - Adapter version: 3.9.4
 - JS-Controller version: 4.0.23
 - Node version: 16.18.1
 - Operating system: Raspi OS Lite

**Comment by Apollon77** [comment]
If "online" state is set to "false" then this means that the adapter do not have a local connection to the device. This means that live state updates will also not work unless aoxu also have configured the app-Cloudcredentials AND setup the iot platform from Tuya to get live updates via MQTT. So please provide a logand make sure that the Tuya App on your mobile device is CLOSED (and ENDED!) when using the adpater, else the App blocks the local connection and so the adapter can not connect.

When you have provided app cloud credentials then the data are polled in the defined interval.

In general: Please look in the log - and pot enable debuig log to see exactly whats going on.

For support please open/join thread in Forum
