### ISSUE TITLE
Akktuelle anleitung Tuya Adapter In Iobroker

### ISSUE THREAD

**Issue by wolfsbruder22** [Apollon77/ioBroker.tuya#497]
Hallo, gibt es Irgentwo eine "Aktuelle" Anleitung zum Einbinden von Z.B: LSC Wlan cam über Tuya Adapter in den Iobroker?
Alles was ich bisher im Web Gefunden habe ist mindestens 2 Jahre alt.
Habe bereits einige anleitungen befolgt bekomme aber kein Ergebniss, der Tuya Adapter bleibt Gelb.

**Comment by Apollon77** [comment]
Hm ... Mal die Readme gelesen bzw die Infos die der Tuya Adapter im Admin hat? Ist deit der 3.8 alles mega einfach ... Die App Zugangsdaten im Admin eintragen, Knopf drüclken, fertig
