### ISSUE TITLE
Anleitung funktioniert unter ANDROID 13 nicht.

### ISSUE THREAD

**Issue by sreevo** [Apollon77/ioBroker.tuya#498]
wie im titel schon beschrieben funktioniert die anleitung mit dem QR Code und Zertifikate aufm handy speichern. Proxy eintragen und app öffnen nicht. wenn ich genau so vorgehe kommt in der SmartLife oder Tuya App dass ich keine Internet Verbindung habe...

keine ahnung wo der fehler liegt,

**Comment by Apollon77** [comment]
Können viele Gründe sein, aber die beste lösung ist viel einfacherm... Ab v3.8 ist der ganze Proxy kram nicht mehr nötig ... Updaten und freuen. Siehe Readme und Admin
