### ISSUE TITLE
Geräte Namen werden Guids wieder überschrieben

### ISSUE THREAD

**Issue by PerfectAnswer** [Apollon77/ioBroker.tuya#5]
Es geht um diese Steckdosen von Gosund: https://www.amazon.de/gp/product/B07B911Y6V/ref=oh_aui_detailpage_o03_s00?ie=UTF8&psc=1

Aktuelle Values die ausgegeben werden sind mA, mW, mV, IP, Online?, ein- oder ausgeschaltet. Kumulierte Werte wie in der App gibt es nicht, muss ich auch nicht zwingend haben.

Da als Werte aktuell nur Guids ausgelesen werden, hatte ich die Guid Bezeichner mit normalen Namen überschrieben (z.B. Trockner oder WaMa) und die einzelnen Values mit (mA),(mW) etc. bezeichnet. blöderweise werden diese Werte dann aber regelmäßig wieder überschrieben (Siehe Screenshot).

![tuya](https://user-images.githubusercontent.com/834752/47985940-80e8cc00-e0db-11e8-8591-cfa6f147b5e7.JPG)

**Comment by Apollon77** [comment]
Bitte 1.1.3 vom GitHub testen und Feedback geben.

**Comment by PerfectAnswer** [comment]
Was die Vergesslichkeit des Adapters betrifft, das sieht jetzt gut aus.
Adapter aktualisiert, Adapter gestoppt und neu gestartet, die manuell überschriebenen Werte bleiben erhalten. Sehr schön ;)

Muss ich mir gedanken machen wegen dem nicht vorhandenen lokalen encryption key?
Mein Logfile sieht übrigens so aus:

`tuya.0 | 2018-11-06 20:52:22.285 | info | 0420034268c63ac1fb00: No schema exists, init basic states ...
-- | -- | -- | --
tuya.0 | 2018-11-06 20:52:22.219 | info | Discover for local Tuya devices on port 6666
tuya.0 | 2018-11-06 20:52:22.201 | info | Existing devices initialized
tuya.0 | 2018-11-06 20:52:22.200 | info | 0420034268c63ac1fb00: No local encryption key available, get data using polling, controlling of device NOT possibe. Please sync with App!
tuya.0 | 2018-11-06 20:52:22.198 | info | 0420034268c63ac1fb00 Init with IP=192.168.178.88, Key=undefined
tuya.0 | 2018-11-06 20:52:22.092 | info | 05200314ecfabc18939d: No schema exists, init basic states ...
tuya.0 | 2018-11-06 20:52:21.991 | info | 04200342b4e62d16dcc9: No schema exists, init basic states ...
tuya.0 | 2018-11-06 20:52:21.981 | info | 05200314ecfabc18939d: No local encryption key available, get data using polling, controlling of device NOT possibe. Please sync with App!
tuya.0 | 2018-11-06 20:52:21.977 | info | 05200314ecfabc18939d Init with IP=192.168.178.87, Key=undefined
tuya.0 | 2018-11-06 20:52:21.904 | info | 04200342b4e62d16dcc9: No local encryption key available, get data using polling, controlling of device NOT possibe. Please sync with App!
tuya.0 | 2018-11-06 20:52:21.879 | info | 04200342b4e62d16dcc9 Init with IP=192.168.178.86, Key=undefined
tuya.0 | 2018-11-06 20:52:21.465 | info | starting. Version 0.1.3 in /opt/iobroker/node_modules/iobroker.tuya, node: v6.14.4

`

**Comment by Apollon77** [comment]
Naja wenn Du die Geräte auch steuern willst dann solltest DU dir gednken machen und per Admin mit der App syncen ... danach sollten die keys da sein

**Comment by ToTXR4Y** [comment]
Also ich finde nur die 1.0.7 (auch im ioBroker so installiert) und keine 1.1.3. Wie kann ich die denn zum ioBroker hinzufügen? Installieren aus URL und dem Master-Branch hier brachte mir auch nur die 1.0.7. Ich habe nämlich ein paar Steckdosen mit 4 Ports die sich auch umbenennen wenn ich neue Gosund Steckdosen oder andere Geräte in der Smartlife App hinzufüge und dann im ioBroker abgleiche.
