### ISSUE TITLE
eMylo 1-Phasen - WLAN 

### ISSUE THREAD

**Issue by smartcuc** [Apollon77/ioBroker.tuya#501]
**Is your feature request related to a problem? Please describe.**
Adapter does not get A, V & W or convert them into single mesurements. 
[Device type: ](https://www.amazon.de/1-phasiger-DIN-Schienen-Stromz%C3%A4hler-Energiemessger%C3%A4t-Stromz%C3%A4hler-LCD-Anzeige/dp/B083BFGHPQ/ref=sr_1_21?keywords=Smart+Meter&qid=1672156438&sr=8-21) eMylo Smart 1-Phasen-Digitalenergiezähler - WLAN

**Describe the solution you'd like**
Would like to get single values for A, V & W to write them into a database.

**Describe alternatives you've considered**
Not having at this time any alternative solutions. Lost in space.

**Additional context**
IOB-Forum: https://forum.iobroker.net/topic/61423/emylo-smart-1-phasen-wlan

![grafik](https://user-images.githubusercontent.com/21308626/209705588-b791cb55-9074-4f2e-b4eb-e098ac7178d6.png)

HA-Online Adapter:
![grafik](https://user-images.githubusercontent.com/21308626/209705633-07fb69e7-f208-4d11-86df-8ca00d5f9a17.png)

**Comment by smartcuc** [comment]
ioBroker - Debug:
[iobroker.2022-12-28.log](https://github.com/Apollon77/ioBroker.tuya/files/10316184/iobroker.2022-12-28.log)

HA - Debug:
[tuya-70c62286b295c3942b517e50069d8414-Dach BKW-a71b0116096fcf6353b9c74e680810d7.json.txt](https://github.com/Apollon77/ioBroker.tuya/files/10316191/tuya-70c62286b295c3942b517e50069d8414-Dach.BKW-a71b0116096fcf6353b9c74e680810d7.json.txt)

Looks like that phase_a and alarm_set_2 needs to be encrypted.

**Comment by Apollon77** [comment]
see https://forum.iobroker.net/post/917164

**Comment by Apollon77** [comment]
see https://github.com/Koenkk/zigbee2mqtt/discussions/13663#discussioncomment-3757100

**Comment by Apollon77** [comment]
@smartcuc Ok, then lets try it ... Install GitHub version please ... it should add:
* 3 more states unter .6 /phase _a) wuth the correct values. test it please
* a JSON state unter .17 with the alarm settings. Theoretically also "changeing shgould work (simply set the json after change)
* 13 more states unter .10 that contains boolean states of the "bitmap" 

Please try to test as much as possible from it

**Comment by smartcuc** [comment]
When I did it right, no changes with the github version.

[iobroker.2022-12-28.log](https://github.com/Apollon77/ioBroker.tuya/files/10316716/iobroker.2022-12-28.log)

![grafik](https://user-images.githubusercontent.com/21308626/209880807-77f65ff8-77dd-4c42-8d6a-bf87f00f2258.png)

**Comment by smartcuc** [comment]
Ups, looks like the npm version. Trying github now.

**Comment by smartcuc** [comment]
$ iobroker url Apollon77/ioBroker.tuya --host kn-ums01 --debug

install Apollon77/ioBroker.tuya

Installing Apollon77/ioBroker.tuya... (System call)

npm WARN crc@4.1.1 requires a peer of buffer@>=6.0.3 but none is installed. You must install peer dependencies yourself.

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):

npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: osx-temperature-sensor@1.0.7 (node_modules/osx-temperature-sensor):npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for osx-temperature-sensor@1.0.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ iobroker.tuya@3.11.4updated 1 package in 807.383s

87 packages are looking for funding run `npm fund` for details

upload [3] tuya.admin /opt/iobroker/node_modules/iobroker.tuya/admin/index_m.html index_m.html text/html

upload [1] tuya.admin /opt/iobroker/node_modules/iobroker.tuya/admin/warning.png warning.png image/png

upload [0] tuya.admin /opt/iobroker/node_modules/iobroker.tuya/admin/words.js words.js application/javascript

Process exited with code 0

**Comment by smartcuc** [comment]
![grafik](https://user-images.githubusercontent.com/21308626/209883120-ac859b55-43dd-429d-acc9-b4997e1b8990.png)

**Comment by smartcuc** [comment]
[iobroker.2022-12-28.log](https://github.com/Apollon77/ioBroker.tuya/files/10316840/iobroker.2022-12-28.log)

**Comment by smartcuc** [comment]
Leider werden die Werte nicht aktualisiert. Kann dies nur an der Spannung sehen.

**Comment by Apollon77** [comment]
Ok, next round :-) Werte kommen scheinbar nur per polling rein

**Comment by smartcuc** [comment]
Adapter is crashing.

[iobroker.2022-12-29.log](https://github.com/Apollon77/ioBroker.tuya/files/10317100/iobroker.2022-12-29.log)

$ iobroker url Apollon77/ioBroker.tuya --host kn-ums01 --debug

install Apollon77/ioBroker.tuya

NPM version: 6.14.17

Installing Apollon77/ioBroker.tuya... (System call)

npm WARN crc@4.1.1 requires a peer of buffer@>=6.0.3 but none is installed. You must install peer dependencies yourself.

npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: osx-temperature-sensor@1.0.7 (node_modules/osx-temperature-sensor):npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for osx-temperature-sensor@1.0.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ iobroker.tuya@3.11.4updated 1 package in 814.712s

87 packages are looking for funding run `npm fund` for details

upload [3] tuya.admin /opt/iobroker/node_modules/iobroker.tuya/admin/index_m.html index_m.html text/html

upload [2] tuya.admin /opt/iobroker/node_modules/iobroker.tuya/admin/tuya.png tuya.png image/png

upload [0] tuya.admin /opt/iobroker/node_modules/iobroker.tuya/admin/words.js words.js application/javascript

Process exited with code 0

**Comment by Apollon77** [comment]
Retry .... fixed on GitHub

**Comment by smartcuc** [comment]
Still crashing.

![grafik](https://user-images.githubusercontent.com/21308626/209891394-45049d7c-49a2-4eca-ad0f-c10055248d9e.png)

[iobroker.2022-12-29.log](https://github.com/Apollon77/ioBroker.tuya/files/10317165/iobroker.2022-12-29.log)


$ iobroker url Apollon77/ioBroker.tuya --host kn-ums01 --debug

install Apollon77/ioBroker.tuya

Installing Apollon77/ioBroker.tuya... (System call)

npm WARN crc@4.1.1 requires a peer of buffer@>=6.0.3 but none is installed. You must install peer dependencies yourself.

npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

updated 2 packages in 811.07s

87 packages are looking for funding run `npm fund` for details

upload [3] tuya.admin /opt/iobroker/node_modules/iobroker.tuya/admin/index_m.html index_m.html text/html

upload [2] tuya.admin /opt/iobroker/node_modules/iobroker.tuya/admin/tuya.png tuya.png image/png

upload [1] tuya.admin /opt/iobroker/node_modules/iobroker.tuya/admin/warning.png warning.png image/png

upload [0] tuya.admin /opt/iobroker/node_modules/iobroker.tuya/admin/words.js words.js application/javascript

Update "system.adapter.tuya.0"

Process exited with code 0

**Comment by Apollon77** [comment]
2 mins

**Comment by Apollon77** [comment]
Try again ... (but I go to bed now :-)) )

**Comment by smartcuc** [comment]
No problem. Take a break and rest. ;-)

**Comment by Apollon77** [comment]
But try ... maybe we are lucky ;-) (this is the thing with "blind coding")

**Comment by smartcuc** [comment]
So far it is working fine. A & W will be available to test as soon the is shining...

[iobroker.2022-12-29.log](https://github.com/Apollon77/ioBroker.tuya/files/10317237/iobroker.2022-12-29.log)

$ iobroker url Apollon77/ioBroker.tuya --host kn-ums01 --debug

install Apollon77/ioBroker.tuya

Installing Apollon77/ioBroker.tuya... (System call)

npm WARN crc@4.1.1 requires a peer of buffer@>=6.0.3 but none is installed. You must install peer dependencies yourself.

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: osx-temperature-sensor@1.0.7 (node_modules/osx-temperature-sensor):npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for osx-temperature-sensor@1.0.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ iobroker.tuya@3.11.4updated 1 package in 815.341s

87 packages are looking for funding run `npm fund` for details

upload [3] tuya.admin /opt/iobroker/node_modules/iobroker.tuya/admin/index_m.html index_m.html text/html

upload [1] tuya.admin /opt/iobroker/node_modules/iobroker.tuya/admin/warning.png warning.png image/png

upload [0] tuya.admin /opt/iobroker/node_modules/iobroker.tuya/admin/words.js words.js application/javascript

Process exited with code 0

**Comment by Apollon77** [comment]
Id the 17-decoded and 10-* are also there now and have values? But will check log tomorrow. Good n8

**Comment by smartcuc** [comment]
Many thanks. Will have a look later on.

**Comment by smartcuc** [comment]
![grafik](https://user-images.githubusercontent.com/21308626/209894850-17aa9df7-c2a3-4580-be63-e6fc3594415c.png)

**Comment by Apollon77** [comment]
Good morning :-)

Kannst du auch versuchen eins der "bits" zu triggern? Wenn nicht auch ok, wäre nur interessant :-)

Und bitte das 17-decoded checken und natürlich die power/current werte

**Comment by smartcuc** [comment]
Good Morning. 

Objects 12 - 17: - ok
Object 17-decoded: no value
Object 20 - 6-current: ok
Object 6-power: wrong. Should be 0,35 ( *1000 instead of /1000?)
Object 6-voltage: ok

![grafik](https://user-images.githubusercontent.com/21308626/209942635-6581c2a1-cd33-477c-9018-fd445c2ed5fa.png)

**Comment by Apollon77** [comment]
Near to done :-) Try again

**Comment by smartcuc** [comment]
Sorry, it takes some time when installing via github.

6-power is looking fine.
17-decoded is having issues.

![grafik](https://user-images.githubusercontent.com/21308626/209951776-235f32ff-1f19-46ca-8dbb-0589bd9bae6d.png)

**Comment by smartcuc** [comment]
[iobroker.2022-12-29.log](https://github.com/Apollon77/ioBroker.tuya/files/10319488/iobroker.2022-12-29.log)

**Comment by Apollon77** [comment]
> 17-decoded is having issues.

which isues? It should be a JSON and it is one ...

**Comment by smartcuc** [comment]
Ah, ok. Was thinking each alarm would be its own object. However, threshold and doAction are working in both directions. 

overcurrent: On/Off toogle and value in A
overvoltage: On/Off toogle and value in V
undervoltage: On/Off toogle and value in V
sufficient credit balance: On/Off toogle and value in kWh

[{"alarmCode":"three_phase_current_imbalance","doAction":true,"threshold":10},{"alarmCode":"under_voltage","doAction":true,"threshold":245},{"alarmCode":"three_phase_current_loss","doAction":true,"threshold":180},
{"alarmCode":"arrears","doAction":false,"threshold":30}]

**Comment by smartcuc** [comment]
Would be great, when object 14 would be a button. Pushing true; Release false.

**Comment by smartcuc** [comment]
10-2 & 10-3 are working, but even when monitoring is switched off.

**Comment by Apollon77** [comment]
> Was thinking each alarm would be its own object.

I decided against this because it is more configuration topic and I have not idea how it reacts when I just set one thing ... so it is a bigger effort to compile the full thing when in different states ... so yes maybe someone uses it to control it but it is nothing to trigger on. And the contained "sub ids" are dynamic in general (spec wise there are 13 thresholds that it could be), so even more effort to handle all this.
If there is later a use case to have it in states we can talk ;-) For now I would leave that way.

> 10-2 & 10-3 are working, but even when monitoring is switched off.

You mean they go to "true" when triggered? Cool :-) Thank you for verifying

> Would be great, when object 14 would be a button

The adapter converts the types completely generic and in this case it is a read/write boolean ... this can only be a switch (a button would be a read-only boolean), so I can not differentiate. So yes you need to do a true/false (or maybe it resets to false automatically)


So in the end all fine and done? :-)

Please use latest GitHub version and do a last final check ( did some smaller optimizations)

**Comment by smartcuc** [comment]
So far it is working fine. A & W will be available to test as soon the is shining...

Was thinking each alarm would be its own object. However, is working in both directions.

Well, from my end, all needs are covered. A, V, & W are available, I know that I have to change the JSON when I want to adjust alarming. So, at the end I’m happy. The rest is up to you. Maybe there should be something in the docu regarding the JSON to set these for alarms.

Many thanks!!

R. K.

**Comment by Apollon77** [comment]
Docs added https://github.com/Apollon77/ioBroker.tuya#convertedenhanced-datapoints
