### ISSUE TITLE
Wifi LED-Bulb RGB Lamp can be switched on/off, but the work_mode cannot be changed

### ISSUE THREAD

**Issue by guc206** [Apollon77/ioBroker.tuya#507]
**Describe the bug**  
The lamp was recognized by the adapter and objects 20 to 32 were created. The lamp can be switched on/off with the switch_state object. Some other objects can be changed manually, but are not sent to the lamp. After renewed polling, the old values are again in the objects.

**Expected behavior**  
scene(2) is in work-mode and can be changed to white(0), but a short time later the default value is restored

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version:  "tuya"         : 3.12.0 
 - JS-Controller version: "js-controller": 4.0.24
 - Node version: v16.16.0
 - Operating system: linux11 bullseye

**Comment by Apollon77** [comment]
Sorry, but this is waaayyy to unspecific with the thousands of devices out there.

Please switch loglevel to debug and provide a FULL debaug log from start till start end and then your tries to control the values via ioBroker (incl. note down the time and tell me when happened what). Take logfile from logfile on disk at /opt/iobroker/log/...

**Comment by guc206** [comment]
I switched the loglevel to debug und i changed the value of object 21 from scene to color.
The Timestamp was 10:16:25.184 
in 10:17:02.734 started a new refresh from all object and the object 21 has the old value scene. 
I have sent the log file to the address given

**Comment by Apollon77** [comment]
Where did you sent it? I received nothing. try iobroker@fischer-ka.de

**Comment by guc206** [comment]
I sent it again to iobroker@fischer-ka.de

**Comment by Apollon77** [comment]
Now I received it

**Comment by Apollon77** [comment]
Wie setzt DU die Werte denn? sieht mir aus als wenn du "bestätigt" auf true setzt ... (ack) ... das ist FALSCH! Ack muss false sein wenn Du es was kontrollieren willst

**Comment by Apollon77** [comment]
Ich finde in beiden Logs keinen versuch etwas zu kontollieren ... statt dessen aber ack=true Werte von Admin.
