### ISSUE TITLE
Add support for WLAN Gateways

### ISSUE THREAD

**Issue by SKB-CGN** [Apollon77/ioBroker.tuya#508]
Hi,
i have installed the new Tuya Version and did a device sync with the cloud. All 3 devices were found, but every minute this line appears in the log:

`bf1c7901c7bf47e603evkv: Received data for node DA1 for unexpected device. Please resync devices`

**Comment by Apollon77** [comment]
Which exact version is "the new version"?

Please provide a full debug log from start until such messages appear. Please send to iobroker@fischer-ka.de with reference to this issue

**Comment by SKB-CGN** [comment]
You got a mail :)

**Comment by Apollon77** [comment]
You too ... was no debug log

**Comment by Apollon77** [comment]
Oookk ... you have a WLAN-Gateway

**Comment by Apollon77** [comment]
Please try GitHub

**Comment by Apollon77** [comment]
@SKB-CGN Any feedback?

**Comment by SKB-CGN** [comment]
Currently, it is working and the message does not appear anymore. Thanks!

**Comment by Apollon77** [comment]
Ok, release will come. Thank you
