### ISSUE TITLE
Device wird im Off Status des Tuya Adapters gefunden und im On Status nicht.

### ISSUE THREAD

**Issue by Menne01** [Apollon77/ioBroker.tuya#511]
Hallo,
ich habe hier ein Wlan Steckdosen Adapter mit Energiemessung.
Das Gerät wird mit dem Workarround MEmu gefunden und lässt sich auch bedienen.
Das Schalten wird sofort ausgelöst und auch true/false kommen sofort zurück, aber die Energiewerte werden erst nach 30 Sek. angezeigt. Sobald ich ausgeschaltet habe, werden die Werte nach 5 Sek. zurückgesetzt. Kurios ist, solbald ich die App öffne und gehe in den derzeitigen Energieverbrauch, werden die Werte nach 5 Sek wie in der App aktualisiert.  
Also hab ich dann Tuya-Mqtt installiert. Dort wird das Device erkannt, nachdem ich den Tuya Adapter ausgeschaltet habe.

` pi@iobroker:/opt/tuya-mqtt $ DEBUG=tuya-mqtt:* node tuya-mqtt.js
  tuya-mqtt:info Connection established to MQTT server +0ms
  tuya-mqtt:tuyapi Search for device id bf5c926XXXXX055ja2r +0ms
  tuya-mqtt:info Home Assistant state topic homeassistant/status received message:  +227ms
  tuya-mqtt:info Home Assistant state topic hass/status received message:  +1ms
  tuya-mqtt:info Home Assistant state topic homeassistant/status received message:  +3s
  tuya-mqtt:info Home Assistant state topic hass/status received message:  +11ms
  tuya-mqtt:tuyapi Found device id bf5c9265XXXXXXX5ja2r +4s
  tuya-mqtt:tuyapi Disconnected from device Workzone Smart Wifi Socket (bf5c92651aXXXXXXXa2r, 43bafXXXX8fa496c) +203ms
  tuya-mqtt:error Error connecting to device id bf5c92651XXXXXX5ja2r...retry in 10 seconds. +0ms
  tuya-mqtt:tuyapi Search for device id bf5cXXXXXX055ja2r +15s
  tuya-mqtt:tuyapi Found device id bf5c926XXXXX055ja2r +1ms
  tuya-mqtt:tuyapi Disconnected from device Workzone Smart Wifi Socket (bf5c926XXXXX5ja2r, 43baf2XXXXX496c) +90ms
  tuya-mqtt:error Error connecting to device id bf5c9265XXXXf4055ja2r...retry in 10 seconds. +15s`
Leider wird das Gerät als offline bzw. disconnect gemeldet.

Schalte ich den Adapter wieder an kommt folgende Ausgabe in der Konsole:

`pi@iobroker:/opt/tuya-mqtt $ DEBUG=tuya-mqtt:* node tuya-mqtt.js
  tuya-mqtt:info Connection established to MQTT server +0ms
  tuya-mqtt:tuyapi Search for device id bf5cXXXX085XX55ja2r +0ms
  tuya-mqtt:error bind EADDRINUSE 0.0.0.0:6666 +0ms
  tuya-mqtt:error Will attempt to find device again in 60 seconds +1ms
  tuya-mqtt:info Home Assistant state topic homeassistant/status received message:  +251ms
  tuya-mqtt:info Home Assistant state topic hass/status received message:  +0ms
  tuya-mqtt:info Home Assistant state topic homeassistant/status received message:  +3s
  tuya-mqtt:info Home Assistant state topic hass/status received message:  +11ms`

Übrigens musste ich die Ports  für das Zertifikat auf 6666 und 6667 stellen. Denn dort spuckt das Device seine Daten aus:

`tuya.0 | 2023-01-31 11:01:28.563 | info | Listen for encrypted local Tuya devices on port 6667
tuya.0 | 2023-01-31 11:01:28.562 | info | Listen for local Tuya devices on port 6666
tuya.0 | 2023-01-31 11:01:28.549 | info | Existing devices initialized`

Habe sie danach wieder auf die ürsprünglichen Ports zurück gesetzt.

Die Access-ID und die Access-Secret sind gesetzt

Der Adapter meldet alles ok:

![grafik](https://user-images.githubusercontent.com/89869516/215734170-e806ba84-7ef7-4237-afc7-097213259222.png)

Mqtt meldet:

![grafik](https://user-images.githubusercontent.com/89869516/215737397-f92488f3-259e-47a8-8ac3-ab3cd63f24c7.png)

**Comment by Apollon77** [comment]
Bitte Zusatzprogramme ausschalten. Tuya Adapter mit Debug Log starten und das og vom Adapterstart bis zu den problemen senden.

**Comment by Apollon77** [comment]
Please also check Readme and maybe try https://github.com/Apollon77/ioBroker.tuya#devices-that-do-not-deliver-up-to-date-data

**Comment by Menne01** [comment]
Anmerkung, 
habe dir das reinen Debug Log geschickt.
Was meinst du mit Zusatzprogrammen? Hier läuft keins. Tuya-Mqtt läuft doch garnicht. Siehe Fotos oben.
Dein letzter Link bring nichts.

**Comment by Menne01** [comment]
Habe dir  das Log geschickt.
Was meinst du mit Zusatzprogrammen? Wüsste nicht was hier noch laufen sollte. 
TuyaMqtt startet erst gar nicht, siehe Fotos oben.

Der Link unten bringt nichts. Alles schon durch.

Gruß Dirk

**Comment by Menne01** [comment]
Ingo, das hatten wir in einem anderen Thread schon erledigt. Es läuft alles.

Grüße

Ich schliesse das Issue
