### ISSUE TITLE
Fehlermeldung seit Version 3.14 - ... Value greater than max

### ISSUE THREAD

**Issue by morskipas** [Apollon77/ioBroker.tuya#516]
Hallo zusammen, seit der Version 3.14 

(Apollon77) Added special handling for needed multiplier for TempSet(2), TempCurrent(3) and floorTemp(102) objects

bekomme ich folgende Meldungen. Der Faktor wurde automatisch korrekt gewählt, die Temp-Werte haben bei meinem Thermostat  aber wohl einen max. Wert, der nun überschritten wird.

<img width="807" alt="image" src="https://user-images.githubusercontent.com/6042276/216337425-80ddfc88-b953-4e50-b240-1569d7b24a4e.png">

Das meine FloorTemp etwas utopisch ist, liegt an einem nicht angeschlossenen ext. Temp-Sensor.

Was kann ich hier tun?
Zuvor hatte ich die Multiplikatoren über Alias Objekte  eingepflegt.

Danke für die Unterstützung
Frank

**Comment by Apollon77** [comment]
Ja dann muss ich wohl min/max noch umrechnen.

**Comment by morskipas** [comment]
> Ja dann muss ich wohl min/max noch umrechnen.

Vielen Dank für die schnelle Antwort :-) das wäre echt super.
Schönen Sonntag noch.
Beste Grüße
Frank

**Comment by Apollon77** [comment]
Please try GitHub version - better there?

**Comment by morskipas** [comment]
> Please try GitHub version - better there?

Hallo, sieht super aus. Temperaturen werden korrekt angezeigt und das Log ist sauber, keine Fehler mehr.
Vielen Dank für die schnelle Änderung
Beste Grüße
Frank
