### ISSUE TITLE
Fehlermeldung

### ISSUE THREAD

**Issue by Krodon1** [Apollon77/ioBroker.tuya#52]
Hallo,

ich habe diese Fehlermeldung beim Einbinden eines Rolladenschalters bekommen:
{"schema":"[{\"mode\":\"rw\",\"code\":\"status\",\"name\":\"窗帘状态\",\"property\":{\"range\":[\"1\",\"2\",\"3\"],\"type\":\"enum\"},\"id\":1,\"type\":\"obj\",\"desc\":\"开 关 暂停\"}]","schemaExt":"[]"}

VG

Krodon

**Comment by Apollon77** [comment]
Danke. Das ist keine Fehlermeldung sondern eine Information. Da müsste noch eine Zeile davor sein mit den Device Typ. Hast du die bitte noch?!

**Comment by Krodon1** [comment]
Hallo Ingo;

dies ist die komplette Fehlermeldung:

tuya.0	2019-06-07 17:41:08.491	info	328214383c71bf311f48: Can not start because IP unknown
tuya.0	2019-06-07 17:41:08.441	info	{"schema":"[{\"mode\":\"rw\",\"code\":\"status\",\"name\":\"窗帘状态\",\"property\":{\"range\":[\"1\",\"2\",\"3\"],\"type\":\"enum\"},\"id\":1,\"type\":\"obj\",\"desc\":\"开 关 暂停\"}]","schemaExt":"[]"}
tuya.0	2019-06-07 17:41:08.440	info	new Shema added for product type MA6aYCAx1vYF4pH7. Please send next line from logfile on disk to developer!

**Comment by Apollon77** [comment]
thank you
