### ISSUE TITLE
smartlive app daten auf tuya übertragen

### ISSUE THREAD

**Issue by mcbirne** [Apollon77/ioBroker.tuya#520]
Es ist mir nicht mehr möglich neue Geräte an den tuya adapter zu übertragen. Ich habe das Zertifikat installiert und den Proxy eingerichtet. Als App verwende ich smartlife 3.12.6. Mit der Version hat es bis zum letzten mal (ca. 6 Monate her) immer funktioniert. 
Als fehler erhalte ich immer "Netzwerkfehler, Bitte versuchen Sie es nochmal".  Ich verwende dafür ein altes Handy mit Android 8.

Hat jemand einen Tipp?

**Comment by mcbirne** [comment]
Super, wusste gar nicht, dass es jetzt so geht. 
Vielen Dank!

**Comment by Apollon77** [comment]
Changelogs are your friend :-)
