### ISSUE TITLE
Adapter kann nach einigen Tagen keine Werte mehr setzten

### ISSUE THREAD

**Issue by FamBae** [Apollon77/ioBroker.tuya#521]
**Describe the bug**  
Zunächst vielen Dank für die Arbeit, ein toller Adapter! Leider bin ich bez. IOBroker und Tuya ein Anfänger, habe aber nun einen Beok Wifi Thermostat (für eine elektrische Fußbodenheizung) im Einsatz. Anfangs hat alles - nach manuellem Setzten der IP - wie gewünscht funktioniert. Insbesondere konnten Werte über den IOBroker gesetzt werden.

Nach 3 Tagen nun geht dies nun nicht mehr. Es werden im IOBroker in "Objekte" zwar die Werte, die am Thermostat oder in der App (Tuya Smart Life) eingestellt werden, richtig angezeigt, es können aber keine Werte mehr gesetzt werden.

Der Debug-Output dazu sieht wie folgt aus:

tuya.0 2023-02-17 21:01:27.679	debug	bfe4bb28e0b51c6db1ykcd.2: set value 47 via bfe4bb28e0b51c6db1ykcd (Local): res=undefined
tuya.0 2023-02-17 21:01:27.679	debug	bfe4bb28e0b51c6db1ykcd: Error from device (0): App still open on your mobile phone? Timeout waiting for status response from device id: bfe4bb28e0b51c6db1ykcd
tuya.0 2023-02-17 21:01:22.678	debug	bfe4bb28e0b51c6db1ykcd onChange triggered for 2 and value 23.5
tuya.0 2023-02-17 21:01:22.678	debug	stateChange tuya.0.bfe4bb28e0b51c6db1ykcd.2 {"val":23.5,"ack":false,"ts":1676667682676,"q":0,"from":"system.adapter.admin.0","user":"system.user.admin","lc":1676667682676}

Dabei ist es unerheblich, ob die Smart Life App offen, geschlossen oder der Benutzer gar abgemeldet ist. Hardware und Netzwerk usw. sind unverändert geblieben. Es kommt offensichtlich immer zum Timeout. Ist dazu schon etwas bekannt? 

Bez. Timeout: mir ist da noch ein etwas merkwürdiges Verhalten des Adapters bez. Zeit aufgefallen, wie die beiden folgenden, benachbarten Debug-Einträge zeigen, die etwa gleichzeitig abgesetzt wurden:

tuya.0 2023-02-17 **22**:30:58.535	debug	bfe4bb28e0b51c6db1ykcd request data via get ...
tuya.0 2023-02-17 **21**:30:58.535	debug	bfe4bb28e0b51c6db1ykcd request data via get ...

Also, vielen Dank schon mal.

**Versions:**  
Plattform: linux
Tyua-Adapter 3.14.1 (von hier installiert wg. Temperatur)
JS-Controller: 4.0.24
Node.js: v16.19.0
NPM: v8.19.3

**Comment by Apollon77** [comment]
Bitte mehr log zeigen ... und übrigens ... 22 Uhr und 21 Uhr ist nicht unbedingt gleichzeitig, oder?! ;-)
Mal das Gerät neu gestartet?

**Comment by tholighaus** [comment]
Hallo,

bei mir ist in der aktuellen Version auf einmal das gleiche Problem. Zustände in den Objekten werden angezeigt und ändern sich, aber setzen kann ich keine mehr.

Gibt es schon eine Lösung?

**Comment by Apollon77** [comment]
Naja dann wiederhole ich die obige Frage: Mehr log bitte

**Comment by tholighaus** [comment]
das würde ich Dir gerne geben, aber da steht leider selbst im DEBUG Modus nicht mehr drin. Was ich herausgefunden habe, wenn man eine manuelle Sync mit den App Daten macht, funktioniert es danach nicht mehr. Lösche ich dann nur die Instanz und lege sie wieder neu an mit den Zugangsdaten, geht es wieder. Der Status der Knoten wird allerdings immer korrekt angezeigt, nur eine Änderung der Werte ist nicht möglich.

**Comment by Apollon77** [comment]
Ehrlich ... Bei Debug steht nicht mehr drin? Machst Du das auch richtig?

Admin - Expertenmodus - Instanzen - Aufklappen - Loglevel ändern. Dann Debug aus dem Logfile auf Platte unter /opt/iobroker/log/... holen.

Im zweifel mitlaufen lassen bis es aufhört zu gehen und dann ein bissl davor und halt danach posten.
