### ISSUE TITLE
Verbunden mit Gerät oder Dienst mit Warnung - funktioniert aber

### ISSUE THREAD

**Issue by andiweli** [Apollon77/ioBroker.tuya#526]
**Describe the bug**  
"Verbunden mit Gerät oder Dienst" hat immer rotes X, Gerät funktioniert aber problemlos über Yahka

**Expected behavior**  
Grünes Häckchen

**Screenshots & Logfiles**  
![Bildschirm­foto 2023-03-20 um 19 13 59](https://user-images.githubusercontent.com/11447150/226430181-4aeec337-0f4b-424e-b9f5-cce4c604c7ac.png)

**Versions:**  
 - Adapter version: 3.14.1
 - JS-Controller version: 16.19.1
 - Node version: 16.19.1
 - Operating system: Raspberry OS Lite

**Comment by Apollon77** [comment]
Yahka? das heisst?

Wenn kein Gerät verbunden ist dann kann wohl keine lokale verbidnung hergestellt werden. Achtung: Bei Tuya kann immer nur EINER lokal verbinden ... also wenn da noch ein homebridge plugin oder die Tuya App offen ist dann kann das schn die ursache sein. Das ist im Log alles ersichtlich.

Also bitte mehr Details und ggf Log zeigen

**Comment by andiweli** [comment]
Es ist nur eine ioBroker Instanz am Laufen.
Yahka = Homekit Adapter, dort schalte ich das Objekt das mir der Tuya Adapter anbietet.

Der Adapter zeigt mir folgendes an:
Status: 1 Geräte im Netzwerk gefunden, 1 Geräte lokal verbunden, 1 mit bekanntem Schema, 1 für lokale Echtzeitaktualisierungen und Steuerung initialisiert.

Somit sollte alles - es ist nur eine 6-fach Leiste - gefunden worden sein.
Die Steckdose lässt sich auch problemlos schalten, nur zeigt der Adapter o.a. Fehler an.

**Comment by Apollon77** [comment]
Debug log bitte, meine Glaskugel ist leider gestern runtergefallen ;-)

**Comment by andiweli** [comment]
<html>
<body>


tuya.0 | 2023-04-02 20:04:24.702 | warn | Error fetching device list for group 1233503: TypeError: Cannot read properties of undefined (reading 'forEach')
-- | -- | -- | --
tuya.0 | 2023-04-02 20:01:42.886 | info | 52110031c44f33f76ad9: Error on Reconnect (7): connection timed out
tuya.0 | 2023-04-02 20:00:37.881 | info | 52110031c44f33f76ad9: Error on Reconnect (5): connect ECONNREFUSED 10.1.0.114:6668
tuya.0 | 2023-04-02 19:59:57.610 | info | 52110031c44f33f76ad9: Error on Reconnect (3): connection timed out
tuya.0 | 2023-04-02 19:59:54.233 | info | 52110031c44f33f76ad9: Error on Reconnect (1): connection timed out
tuya.0 | 2023-04-02 19:59:52.604 | info | 52110031c44f33f76ad9 Init with IP=10.1.0.114, Key=b91843b0ca2b9bae, Version=3.3
tuya.0 | 2023-04-02 19:59:52.603 | info | 52110031c44f33f76ad9: Connect locally to device
tuya.0 | 2023-04-02 19:59:51.224 | info | IOT Cloud ID/Secret not configured, disabling real time State updates from Cloud MQTT
tuya.0 | 2023-04-02 19:59:50.195 | info | Listen for encrypted local Tuya devices on port 6667
tuya.0 | 2023-04-02 19:59:50.194 | info | Listen for local Tuya devices on port 6666
tuya.0 | 2023-04-02 19:59:49.232 | info | Try to sync devices from Cloud using stored cloud credentials
tuya.0 | 2023-04-02 19:59:49.224 | info | Existing devices initialized
tuya.0 | 2023-04-02 19:59:49.214 | info | 52110031c44f33f76ad9 Init with IP=10.1.0.114, Key=b91843b0ca2b9bae, Version=3.3
tuya.0 | 2023-04-02 19:59:49.210 | info | 52110031c44f33f76ad9: Connect locally to device
tuya.0 | 2023-04-02 19:59:48.227 | info | starting. Version 3.14.2 (non-npm: Apollon77/ioBroker.tuya#e27cb6b012036fffab8313acdf3e87085fe92898) in /opt/iobroker/node_modules/iobroker.tuya, node: v16.19.1, js-controller: 4.0.24


</body>
</html>

**Comment by andiweli** [comment]
Kleines Update...

Das Löschen des Objektes für die 6-fach Steckerleiste (inkl ganzem Objektbaum) und nachfolgendes erneutes Starten des Tuya-Adapters lässt wieder alles grün werden.

An der Steckerleiste wurde aber nichts verändert.

**Comment by Apollon77** [comment]
Ja, oben ist leiderkein Debug log sondern nur Info log ... aber wenns wieder geht alles gut
