### ISSUE TITLE
js-controller 5 / Error fetching device list for group 31012170: TypeError: Cannot read properties of undefined (reading 'forEach')

### ISSUE THREAD

**Issue by Grothesk242** [Apollon77/ioBroker.tuya#529]
Log shows: 
```
Error fetching device list for group 31012170: TypeError: Cannot read properties of undefined (reading 'forEach')
```

**Versions:**  
 - Adapter version: v3.14.2
 - JS-Controller version: 5.0.1-alpha.0-20230406-4552d569
 - Node version: v19.8.1
 - Operating system: Debian 12 / Bookworm

**Comment by Apollon77** [comment]
this happens when the coud connection is not initialized ... please post debug log ... (and no should not be controller 5 dependent)
