### ISSUE TITLE
Error and info for Tuya 

### ISSUE THREAD

**Issue by larryxxl2** [Apollon77/ioBroker.tuya#532]
permanent error and infos from tuya adapter
![image](https://user-images.githubusercontent.com/96195330/231605480-c552aa8f-c854-415a-b0c3-19c5e7bf6072.png)
v3.13.1

devices 
![image](https://user-images.githubusercontent.com/96195330/231605720-d03d1f30-c7e1-491b-b067-b9cf95149640.png)

**Comment by Apollon77** [comment]
Which adapter verison is used? Please instakll the latest beta version (3.14.2). Plesse restart the adapter and report if it happens again, if yes then I need a debug log to see what happeed as that first happened. it seems that there was a request but the device was not responding and so something hangs

**Comment by larryxxl2** [comment]
oldVersion of Tuya Adapter v3.13.1
With beta version 3.14.2 the problem of the constant messages of the Tuya adapter no longer occurs.
Thanks.
