### ISSUE TITLE
MQTT Echtzeit-Updates pausieren wenn ein lokal verbundenes Gerät offline ist (während Verbindungsversuche)

### ISSUE THREAD

**Issue by Domi920** [Apollon77/ioBroker.tuya#533]
Nutze das Entwicklerkonto von Tuya um Echtzeit-Updates zu erhalten.
Mir ist aufgefallen, dass diese Echtzeitdaten nicht abgeholt werden, wenn ein anderes Gerät, dass lokal verbunden ist, offline ist.
Wenn also z. B. so eine Meldung im Log erscheint:
`Error on Reconnect (5): connect EHOSTUNREACH`
Dann ist der Adapter mit dem Neuverbinden beschäftigt & pausiert dem Anschein nach die Echtzeit Updates über MQTT.

Macht es Sinn dieses Verhalten zu ändern, oder ist es beabsichtigt?

Gruß Dominik

Adapter Version: v3.13.1
PC: Rasperry Pi 4B
Betriebssystem: linux
Architektur: arm64
CPUs: 4
Geschwindigkeit: 1800 MHz
Modell: Cortex-A72
RAM: 7.63 GB
Node.js: v16.19.1
NPM: 8.19.3

**Comment by Apollon77** [comment]
An sich sollten MQTT Updates ignoriert werden wenn das gerät lokal verbunden ist. Bitte von solch einer konstellation mal ein Debug log posten.

**Comment by Domi920** [comment]
Ich meinte, wenn ein lokal verbundenes Gerät offline ist und Verbindungsaufbau-Versuche statt finden, dass währenddessen die MQTT Updates von den anderen Geräten nicht funktionieren.

Sozusagen wird MQTT von cloud Geräten "ausgebremst" wenn der Adapter mit den automatischen Reconnect von lokalen Geräten beschäftigt ist.

**Comment by Apollon77** [comment]
> Sozusagen wird MQTT von cloud Geräten "ausgebremst" wenn der Adapter mit den automatischen Reconnect von lokalen Geräten beschäftigt ist.

ääähhmm ...nein.

> Bitte von solch einer konstellation mal ein Debug log posten.

**Comment by Domi920** [comment]
Vorerst hatte ich das "Problem" nicht mehr.
Sobald ich es merke, schreibe ich hier.

Danke für deine Unterstützung!
