### ISSUE TITLE
[Feature] add support for app "Elesion" used by pearl tuya devices (low prior)

### ISSUE THREAD

**Issue by mcm1957** [Apollon77/ioBroker.tuya#536]
**Is your feature request related to a problem? Please describe.**
not really as workaround seems to exist

**Describe the solution you'd like**
Currently the tuya adapter supports "SmartLife" and "Tuya_Smart". Devices sold by pearl.de should be used with their own app "Elesion" which seems to be a otherwise labeled version of "Tuya Smart". The adapter cannot connect to devices configured with "Elesion". Elesion and Tuya Samrt seem to have different userbase / account databases.

Anyway - the pearl devices (watering system) could be connected to Tuya Smart app. And using this account the adapter seems to work without issues. After connecting the devices to the Tuya app they vanish at the Elesion app. This indicates "seperated" databases at tuya.

I would assume, that by changing connect data in some way it should be able to use devices connected via Elesion app too.

**Describe alternatives you've considered**
Existing alternative is to use Tuya Smart app. It's not ckear if this solution will cause any issues like unsupported features now.

**Additional context**
If I can provide some data (or you can provide Info how you retrieved the current connect data sets) I would be glad to help / and or provide a PR. (Eventually to be discuees at telegram)

**Comment by Apollon77** [comment]
I assume that this then needs to be found out on an API level which means sniffing app traffic ... Honestly ... if the solution is to just pair with the other apps please use this solution. i can leave open if someone finds time for sniffing which that app, but with the knowledge that the normal tuya apps all communicate encrypted the chance is low to find out the neeed parms without insider knowledge. @TA2k any idea?

**Comment by mcm1957** [comment]
At completly OK to NOT spent any reasonable effort here. Currently I do not see any disadvanteges using the original tuya app, I'll report if I detect some differences.

Reason for isse was:
-) source looked like addin a set of "keys" would be sufficient for adaptio. But I do not know how you determined the existing keys so I do not know whether this is some "look at xyz" or 40h investigations ...
-) I was first disappointed the the tuya compatible pearl devices (accorsing to google und aother forum posts) did not work with the adapter until I tried using the original app and determined that this was the problem.

**Comment by Apollon77** [comment]
In theory if someone decompiles the app and gets the client id and secret we can ad it. Or simply use the smartlife app or siuch .. they should also work
