### ISSUE TITLE
[Question] "Connect locally to device" although no connect is possible due to WLAN configuration

### ISSUE THREAD

**Issue by mcm1957** [Apollon77/ioBroker.tuya#537]
What does the message:

```info | bf0fc837d67786xxxxxxxx: Connect locally to device```

indicate? If it should read "trying to connect..." I would suggest to add "trying" to the text.

Otherwise I'm a little bit surprised, as all three tuya devices are connected to a guest wlan which (until now) did not allow any data exchange between main wlan ( where ioBroker is connected to) and guest wlan. (Feature provided by Fritz Box). As I never entred the main WLAN password into any tuya app, the devices should not be able to connect to the main wlan (at least I hope so :-)). Network view of FritzBox confiorms that the Tuya devices are at seperated wlan.

**Comment by mcm1957** [comment]
OK, according to states the local connectio n is inactive:

![image](https://user-images.githubusercontent.com/28575778/236539810-adfb1c26-2312-4040-933f-68dbc2827174.png)

So looks like some non 100% optimal texting only.

**Comment by Apollon77** [comment]
The message shows the setting if a local connection will be done or not (aka cloud only). so it is a "status info".
In your case online is false so it is l´not connected locally at the end because then it will use ckoud - according to confog

**Comment by mcm1957** [comment]
Still suggesting to adapt the text.

**Comment by Apollon77** [comment]
changed in next version
