### ISSUE TITLE
[Questiion?] How to interpret values for NX-6477 irrigation valves

### ISSUE THREAD

**Issue by mcm1957** [Apollon77/ioBroker.tuya#541]
I installed NX-6477 irrigation valves and integrated them into ioBroker via Tuya Adapter.
The coupling works. But there are a few states that I can't interpret with the best will in the world:

How to interpret those states for time plans?

![image](https://github.com/Apollon77/ioBroker.tuya/assets/28575778/28b3d5a5-3ff1-44f2-a402-f99e5c3b7462)

And how should I interpret next_time !?
![image](https://github.com/Apollon77/ioBroker.tuya/assets/28575778/52854258-ea8b-455e-8209-8b05d576a99c)

I'll ask here if I just don't understand that or if something doesn't fit here.

**Comment by Apollon77** [comment]
They all look like base64 encoded binary data, content unknown in a first place. So the only thing you can do is to decode them to binary data (Buffer.from("...", "base64") ) and then maybe do changes in the app and try to find out how to interpret them. Usually such dsta are multiple bytes with different meaning (Timer like maybe the day and time or such or length).

Maybe check also Google if someone did such an decoding already.

If you find out details open a issue or PR with infos and I can try to implement it, but for now I close the issue.

**Comment by mcm1957** [comment]
OkI ll checkEspecially the next time value should be guessable.
-------- Ursprüngliche Nachricht --------Von: Ingo Fischer ***@***.***> Datum: 18.06.23  23:50  (GMT+02:00) An: "Apollon77/ioBroker.tuya" ***@***.***> Cc: "Martin M." ***@***.***>, Author ***@***.***> Betreff: Re: [Apollon77/ioBroker.tuya] [Questiion?] How to interpret values for NX-6477 irrigation valves (Issue #541) 
They all look like base64 encoded binary data, content unknown in a first place. So the only thing you can do is to decode them to binary data (Buffer.from("...", "base64") ) and then maybe do changes in the app and try to find out how to interpret them. Usually such dsta are multiple bytes with different meaning (Timer like maybe the day and time or such or length).
Maybe check also Google if someone did such an decoding already.
If you find out details open a issue or PR with infos and I can try to implement it, but for now I close the issue.
