### ISSUE TITLE
Littlelf Smart App

### ISSUE THREAD

**Issue by tobiasw83** [Apollon77/ioBroker.tuya#543]
Hallo,

wäre eine Einbindung der App "littlelf Smart" möglich?

Danke
Tobias

**Comment by Apollon77** [comment]
Eher nicht weil man erst rausfinden müsste welche IDS und alles hier verwndet werden gegenüber der Tuya platform. EInfach die Geräte drt ablernen und an der normalken Tuya Smart lifeapp anmelden. SOllte tun wenn es tuya ist
