### ISSUE TITLE
local connection

### ISSUE THREAD

**Issue by 150d** [Apollon77/ioBroker.tuya#551]
I'm not sure I fully understand how the local connection works:

I have a Tuya Smart device in a different network segment than my ioBroker instance. This of course means that the adapter will never be able to "sniff" UDP-packets not addressed to the ioBroker node and auto-discovery can not work.

So after setting up the adapter by using cloud sync as described, I entered the device IP in the (previously empty) datapoint. According to the log, the connection was established locally and the adapter status also turned from yellow to green.

But some time after this, the datapoints are no longer updated, nor does the adapter seem to even know there might be a problem (no log entries about timeouts or similar). The datapoints are just no longer updated and modified values do not appear to reach the device.

As an alternative, I have set "local connection" to FALSE for the device and enabled "poll cloud" in adapter settings. This apparently works better, so far I've not seen a lost connection between adapter and device.

Question: Is this how it is supposed to work? Is it not possible to maintain a direct connection if the device is in a different network? How does the local connection work: Is the adapter activly polling the device, or is it just sniffing packets the device sends to the cloud?

**Comment by Apollon77** [comment]
if it works and then sudenly stops ... please provide a deblug log that shows this and we know more, but yes if you set the IP and evce protocol version (these both details are taken normally from UDP packages) then it should work because normal local connection is just TCP
