### ISSUE TITLE
Datenpunkte Aktualisierung bei Reconnect/Adapterstart

### ISSUE THREAD

**Issue by chrvidal** [Apollon77/ioBroker.tuya#558]
Ich nutze ein SBoard mit dem Wiegand-Protokoll um damit ein Tedee Schloss über ein NFC Reader zu öffnen.
An sich funktioniert das ganze sehr zuverlässig, leider wird der Trigger über den DP "unlock_card_kit" auch ausgelöst wenn der Adapter neu Startet oder sich neu mit dem SBoard verbindet weil der DP "unlock_card_kit" dabei Aktualisiert wird. 

Dh. die Tür wird geöffnet bei Adapter Neustart, gibt es hierfür eventuell schon eine Lösung?

**Comment by Apollon77** [comment]
> gibt es hierfür eventuell schon eine Lösung?

naja da ich kein problem kenne ist die Frage welche Lösung Du erwartest. Am Ende ist es aber normal das der Adapter Datenpunkte aktualisiert. Am Ende müsste jetzt deine Logik in JavaScript sicherstellen nur dann eine Aktion auszuführen wenn auch etwas passiert. Wie man das bei dem gerät erkennt weiss ich nicht. Am Ende kann es viele Gründe geben das die Daten aktualisiert werden, zb auch wenn das Gerät neu gestartet wird oder die Netzwerkverbindung mal abgebrochen ist oder oder oder ... Der Adapter kann da nichts tun. Das muss deine Logik machen. Sorry
