### ISSUE TITLE
getting the Keys via the Proxy doesnt work anymore (App update)

### ISSUE THREAD

**Issue by DerNick** [Apollon77/ioBroker.tuya#56]
There was an update for the smartlife app that said "bugs fixed", now getting the Device Keys via the proxy doesnt work anymore :(. I dont know if it is fixable or not but i think they somehow changed the transmission method or something like that. I am using IOS and all Settings are right, because it fine worked for the last times. Pleas fix it if its possible :).

**Comment by Apollon77** [comment]
What exactly the proxy web Uiis showing? You are sure that certificate is used and activated correctly and such?

**Comment by DerNick** [comment]
Where do i find that? I can start the Proxy in the settings but if I add it to my phone and configure it and if i then launch the app and do the refresh nothing happens. Sometimes it also shows "Network error" in the app. I am pretty sure it is all right configured because it worked perfectly for the last times. Does it work for you? If yes what Smart life version and IOS or Android? Thx :)

**Comment by Apollon77** [comment]
I will check it the next days. Need to focus on an other topic at the moment.

**Comment by DerNick** [comment]
thank you

**Comment by Apollon77** [comment]
verified :-(

**Comment by DerNick** [comment]
Lets hope you can fix it 😕👍

**Comment by Apollon77** [comment]
collecting infos ... so also https://github.com/TuyaAPI/cli/issues/19

**Comment by 9steff2** [comment]
Habe es mit den App´s Smart Life 3.10.1 und der TuyaSmart 3.10.0 versucht, leider kein Erfolg

**Comment by DerNick** [comment]
Bei Android kriegt man vielleicht noch eine alte version als Apk. Hoffe ich zumindest. Werd mal suchen nachher.

**Comment by BigDi** [comment]
Ältere Versionen sind verfügbar. Z.B. unter
[https://apkpure.com/de/smart-life-smart-living/com.tuya.smartlife/versions](url)

**Comment by Apollon77** [comment]
Kannst du mal testen ob es unter Android noch geht bzw mir älteren Versionen besser geht? Ich hab leider kein android :-(

**Comment by DerNick** [comment]
Werds gleich mal testen falls es sich installieren läst. Hab auch nicht mehr die neuesten android Geräte.

**Comment by DerNick** [comment]
Hab gerade die v3.9.5 auf meinem android Tablet getestet und siehe da, es hat sofort funktioniert. Ich hoffe das bleibt so und die ändern das nicht wieder. find die Tuya Birnen eigentlich echt cool.

**Comment by Apollon77** [comment]
heisst App 3.9.5 auf Android tut und 3.10 nicht?

**Comment by Apollon77** [comment]
Kann jemand hier Android Apps decomilen um die Änderungen zu analysieren?

**Comment by DerNick** [comment]
Hab gerade alle neueren Versionen für android getestet und es scheint mit allen zu funktionieren (auch mit der neuesten). Also bezieht sich das Problem offensichtlich nur auf IOS Geräte.

**Comment by Apollon77** [comment]
Dann versuche ch heute abend mal einen Android Emulator :-)

Also grob ala https://community.home-assistant.io/t/alternative-tuya-smart-outlet-setup/51830

**Comment by 9steff2** [comment]
also ich habe es mittels Android nun auch hinbekommen

das Gerät wird angezeigt, aber der Adapter wird nicht grün....es besteht keine Verbindung zu tuya

**Comment by Apollon77** [comment]
Es besteht keine Verbindung zu tuya? Das sagt das log bestimmt nicht ;-)

Bitte im Forum Thread oder als extra issue debug log Posten. Danke.

**Comment by Apollon77** [comment]
Also Encryptiod Geräte geht nun mit 2.0.1 auf GitHub. Bitte testen. Wir lassen diesen Thread um das iOS Proxy Problem weiter zu bearbeiten

**Comment by BigDi** [comment]
Wenn ich über die URL versuche zu installieren kommt bei der Installation folgende LOG
npm ERR! code E404
npm ERR! 404 Not Found: https://github.com/Apollon77/ioBroker.tuya/blob/master/README.md/tarball/master
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-06-27T05_33_03_524Z-debug.log

**Comment by BigDi** [comment]
COOOL! Es geht. Vielen Dank! Hier noch zur Vollständigkeit der Log

tuya.0 | 2019-06-27 07:54:36.569 | debug | system.adapter.admin.0: logging true
-- | -- | -- | --
tuya.0 | 2019-06-27 07:53:51.893 | debug | system.adapter.admin.0: logging false
tuya.0 | 2019-06-27 07:53:27.187 | debug | stateChange tuya.0.11670434ecfabc9b416e.1  {"val":"3","ack":true,"ts":1561614807184,"q":0,"from":"system.adapter.tuya.0","lc":1561614807184}
tuya.0 | 2019-06-27 07:53:27.181 | debug | 11670434ecfabc9b416e: Received data: {"1":"3"}
tuya.0 | 2019-06-27 07:53:27.168 | debug | stateChange tuya.0.info.connection  {"val":true,"ack":true,"ts":1561614807163,"q":0,"from":"system.adapter.tuya.0","lc":1561614807163}
tuya.0 | 2019-06-27 07:53:27.167 | debug | stateChange tuya.0.11670434ecfabc9b416e.online  {"val":true,"ack":true,"ts":1561614807161,"q":0,"from":"system.adapter.tuya.0","lc":1561614807161}
tuya.0 | 2019-06-27 07:53:27.167 | debug | connected set to true
tuya.0 | 2019-06-27 07:53:27.150 | debug | 11670434ecfabc9b416e: Connected to device
tuya.0 | 2019-06-27 07:53:27.135 | info | 11670434ecfabc9b416e Init with IP=192.168.178.59, Key=78bb3cf6c8832bdf, Version=3.3
tuya.0 | 2019-06-27 07:53:27.101 | debug | stateChange tuya.0.11670434ecfabc9b416e.ip  {"val":"192.168.178.59","ack":true,"ts":1561614807089,"q":0,"from":"system.adapter.tuya.0","lc":1561614807089}
tuya.0 | 2019-06-27 07:53:27.097 | debug | stateChange tuya.0.11670434ecfabc9b416e.online  {"val":false,"ack":true,"ts":1561614807085,"q":0,"from":"system.adapter.tuya.0","lc":1559668317452}
tuya.0 | 2019-06-27 07:53:27.083 | debug | 11670434ecfabc9b416e: Create device objects if not exist
tuya.0 | 2019-06-27 07:53:27.081 | debug | 11670434ecfabc9b416e: Schema found for YWK0ZiumXZGkb8nj: [object Object]
tuya.0 | 2019-06-27 07:53:27.073 | debug | 11670434ecfabc9b416e: Try to initialize encrypted device with received UDP messages: version=undefined, key=78bb3cf6c8832bdf
tuya.0 | 2019-06-27 07:53:27.072 | debug | Discovered encrypted device and store for later usage:  192.168.178.59:49154 - U��Зfgo3i����2��*�a��n���'\�B��]�n�N�	 c���ى�ܤ�17��C��W����1\�ue�#�F��x�/ں������JGEa6w7�}h�$V&�
tuya.0 | 2019-06-27 07:53:23.015 | info | Listen for encrypted local Tuya devices on port 6667
tuya.0 | 2019-06-27 07:53:23.014 | info | Listen for local Tuya devices on port 6666
tuya.0 | 2019-06-27 07:53:23.001 | info | Existing devices initialized
tuya.0 | 2019-06-27 07:53:23.001 | info | 11670434ecfabc9b416e: None of the discovered devices matches :-(
tuya.0 | 2019-06-27 07:53:22.999 | debug | 11670434ecfabc9b416e: Try to initialize encrypted device with received UDP messages: version=undefined, key=78bb3cf6c8832bdf
tuya.0 | 2019-06-27 07:53:22.927 | debug | 11670434ecfabc9b416e: Create device objects if not exist
tuya.0 | 2019-06-27 07:53:22.922 | debug | init 1 known devices
tuya.0 | 2019-06-27 07:53:22.910 | debug | connected set to false
tuya.0 | 2019-06-27 07:53:22.778 | info | starting. Version 2.0.1 in /opt/iobroker/node_modules/iobroker.tuya, node: v8.12.0
tuya.0 | 2019-06-27 07:53:22.655 | debug | statesDB connected
tuya.0 | 2019-06-27 07:53:22.585 | debug | objectDB connected
tuya.0 | 2019-06-27 07:52:50.917 | debug | system.adapter.admin.0: logging true

**Comment by drhideg** [comment]
I tried to move my ioBroker setup from virtual to physical machine and run in this bug. In my virtual setup is all good, on live its not. The main difference beetween the packages version is the node. I downgraded the debian's 10.15.2 to 8.16.0 from nodesource and the proxy start working, even with the 3.11 Smart Life app. Before that, i got the network error in the app.

**Comment by Apollon77** [comment]
Interesting finding, thank you

**Comment by vaaarg** [comment]
are there any news on this issue. tried all to get this working on:

pi4
Node.js
v10.16.3
NPM
6.9.0

but failed. proxy receives no data. setting up thius adapter on a pi3 and standard image installation worked without problems.

**Comment by Apollon77** [comment]
The issue is not the adapter but the app. iOS is not working. Did you tried the Android way? Maybe with android simulator?

**Comment by vaaarg** [comment]
tried this on android 8.0 with smart life and tuya app. also tried some time ago with windows android emulation but dont know if this was setup correctly.

**Comment by Apollon77** [comment]
Best get support in forum.

**Comment by Apollon77** [comment]
Please try 3.0.0 from Github. Improtant: Certificate has a different name, so reinstall cert!! Worked for me on iOS!

**Comment by ChristianH99** [comment]
I tried it a few times today but without success. When opening AnyConnect Port 8889 I can only see CONNECT entries from Tuya. When monitoring my traffic with Charles Proxy I can see  the POST entries which (I guess) include the needed information. Is there any way to add these manually to the adapter?

**Comment by Apollon77** [comment]
Please use the GitHub Version
