### ISSUE TITLE
Add support for Cozy Life app

### ISSUE THREAD

**Issue by Sebi2030** [Apollon77/ioBroker.tuya#565]
Hi, ich habe eine WLAN Glühbirne die von Tuya ist sich jedoch nicht über die smartlife App sondern über CozyLife App einbindet. Da das ja auch von tuya ist wäre es schön wenn diese App als Login Möglichkeit hinzugefügt wird damit man auch Geräte dieser App nutzen kann.

**Comment by Apollon77** [comment]
EInfach die Tuya App nutzen ... Es wäre kit neu das es die andere app sein muss.

Da leider für die andere App keiene Secretes bekannt sind bisher geht das leider nciht
