### ISSUE TITLE
Zwei Instanzen bei Nutzung Smartlife und Ledvance

### ISSUE THREAD

**Issue by nizoo83** [Apollon77/ioBroker.tuya#570]
Ich habe mehrere Geräte im Smartlife und Ledvance. In der Instanz kann ich jedoch nur entweder oder auswählen. Gibt es da eine Möglichkeit beides zu aktivieren? Wenn ich eine zweite Instanz mache meckert ioBroker weil der Port belegt ist.

**Comment by Apollon77** [comment]
Das geht nur auf getrennten Hosts. Ansonsten einfach dei Geräte alle in einer der beiden Apps anlernen? Das sollte gehen.
