### ISSUE TITLE
Tuya Adapter bleibt Gelb bei LEDVANCE

### ISSUE THREAD

**Issue by biker1602** [Apollon77/ioBroker.tuya#571]
Hallo
Ich habe den Tuya Adapter 3.15.0  mit einer Zweiten Instanz für LEDVANCE WiFi Glühlampen die über die LEDVANCE Smart+ App laufen auf dem Iobroker insatlliert.
Ich habe dort dann den Benutzernamen und das Passwort eingegeben aber leider bleibt der Adapter gelb obwohl er die Gerätedaten von der App holt.
Beim Adapter ist ein rotes X  bei Verbunden mit Gerät oder Dienst.
Ich kann die Geräte selbst auch unter Objekte schalten aber wenn ich z.B. eine Glühlempe über die App  einschalte, verändert sich der Zustand unter Objekte nicht von false auf true.
Im Adapter selbst zeigt er mir unter Lokale Verbindungen folgendes an.
  
Status: 3 Geräte im Netzwerk gefunden, 0 Geräte lokal verbunden, 3 mit bekanntem Schema, 3 für lokale Echtzeitaktualisierungen und Steuerung initialisiert.

Bei der ersten Instanz des Tuya Adapters die ich mit SmartLife betreibe habe ich diese Probleme nicht und der Adaüter ist auch grün.
Kannst du mir sagen woran das liegt oder was ich verkehrt mache.
Danke

**Comment by Apollon77** [comment]
M besten einfach auf eine App gehen, an sich sollten die apps jeweils auch in der anderen App anlernbar sein.

**Comment by c1328** [comment]
Sorry dass ich nachfrage, ich konnte ein Ledvance device nicht in der Smart Life App anlernen. Daher gehe ich auch über eine zweite Instanz des Tuya Adapters, womit die Steuerung auch einwandfrei geht - an der gelb/roten Anzeige der Instanz habe ich mich bisher nicht gestört.

**Comment by Apollon77** [comment]
Ok, warum die gelb anzeigt weiss ich nicht. Bitte mal debug log anhängen.

**Comment by c1328** [comment]
Noch ohne debug aktiviert zu haben, vermute ich, dass das das Problem ist:
<img width="1045" alt="image" src="https://github.com/Apollon77/ioBroker.tuya/assets/112856305/9f57253e-dad4-4306-8ff8-4bb904b3724a">

**Comment by Apollon77** [comment]
Ja, wie gesagt das liegt daran das zwei instanzen auf dem Host laufen

**Comment by biker1602** [comment]
Vielen Dank ich habe jetzt die zweite Instanz Gelöscht  und bei der Ersten Instanz einfach die Daten vob LEDVANCE eingegebnen und er hat die Daten geholt. Ich hatte gedacht wenn ich das mache das er mir die Geräte von Smartlife raus löscht. Aber so ist alles fein. Danke nochmal

**Comment by c1328** [comment]
Naja, rauslöschen tut er sie vielleicht nicht gleich, aber soweit ich das verstehe, kann nur entweder ein Smartlife Konto, oder ein Ledvance Konto aktiv sein. Aber bitte korrigiert mich, wenn ich irre. Sofern mehrere Konten in einer Instanz hinterlegt werden können, braucht es natürlich keine zweite Instanz.

**Comment by biker1602** [comment]
Ich habe beide Konten bei einer Instanz hinterlegt und ich kann auch beide gleichzeitig steuern. Da gibt es bis jetzt keine Probleme.

**Comment by c1328** [comment]
Ich denke das liegt daran, dass die Verbindungen lokal aufgebaut werden, sobald die Geräte einmal in der Instanz registriert sind. Sobald eine lokale Verbindung nicht möglich ist, muss man nach meinem Verständnis über eine zweite Instanz gehen (und dann tut auch die UDP Meldung nicht weh).
