### ISSUE TITLE
Bluetooth device does not deliver updates - only if app is connected or a datapoint is controlled (solution of #488 does not fix it)

### ISSUE THREAD

**Issue by c1328** [Apollon77/ioBroker.tuya#572]
**Describe the bug**  
A bluetooth device does only deliver updates if tuya app is opened or any datapoint is controlled e.g. by a script. This seems very similar as [#488](https://github.com/Apollon77/ioBroker.tuya/issues/488) but the described method does not help. IoT sync is also configured but it does not change anything.

The bluetooth device is connected via a BT gateway.

**Expected behavior**  
Get updated values (e.g. current temperature) from device within defined poll interval.

**Screenshots & Logfiles**  
I try to deliver a log file soon.

**Versions:**  
 - Adapter version: 3.15.0
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: debian 12

**Additional context**  
The workaround is to control a datapoint with the existing value every 5 minutes to get all other values updated.

**Comment by c1328** [comment]
Yes I noticed that in #488 but as far as I could see it has no effect for me.

**Comment by Apollon77** [comment]
Then please provide a full debug log, but I would assume that the BLE Hub do not expose the sub device data ... is the cloud having then and getting them via MQTT?

**Comment by c1328** [comment]
Hi Apollon77,
since some time I use the workaround to "write/control" some irrelevant datapoint every 5 min to receive updated temperature values. That works so I would not spend more effort here.

Yes, I use both, Tuya Cloud and MQTT sync.

Gracias!
