### ISSUE TITLE
App Notifications

### ISSUE THREAD

**Issue by Ilovegym66** [Apollon77/ioBroker.tuya#573]
It's possible to implement app notifications, like the "battery-empty" or if someone ring the bell, etc..? 

Tuya send an mail to all developer, because they changed their api:

Notice on Google FCM push update
Dear Developer,
According to the requirements of Google Firebase: if your App is using the old version HTTP or XMPP API, it must be migrated to the latest Firebase Cloud Messaging API (HTTP v1) by June 20, 2024, otherwise it will cause the issue on App push notifications. The user maynot be able to recieve the App push notifications.This rule will affect all apps that have been listed on overseas App markets.

Currently, the Tuya OEM App/App SDK has been adapted to Google's latest rules. If your app has been launched App market outside mainland china , please follow this tutorial for operation: [Configure Google FCM](https://developer.tuya.com/en/docs/iot/fcm-push?id=K989rrxsofo5i)

If you have any questions or need further guidance, please feel free to contact our support team. Thank you for your understanding and support.

Tuya IoT Development Platform Team
2024-03-11

**Comment by Apollon77** [comment]
No, we are not the app and can not do push stuff in name f the app. you can implement this in iobroker :-)
