### ISSUE TITLE
Niedrige Werte werden von der WLAN-Tuya Steckdose nicht angezeigt

### ISSUE THREAD

**Issue by Klugschieter** [Apollon77/ioBroker.tuya#578]
Moin,
ist eigentlich keine Frage zum Adapter (der funktioniert super), aber ich weiß gerade nicht wo ich das sonst fragen soll und hoffe jemand hier weiß etwas darüber.
Meine WLAN-Tuya Steckdose mit Power-Messung zeigt keine kleinen Werte für cur_current und cur_power an. Wenn ich das richtig sehe, werden erst Werte >1A angezeigt. Auch in der Smartlife App werden diese Werte erst ab dieser Grenze angezeigt. Ist das irgendwo beschrieben, ab welchen Grenzen erst eine Anzeige erfolgt, bzw. kann man das irgendwo ändern?

**Comment by Apollon77** [comment]
Also bei mir werden kleiner Daten übertragen denke ich ... Aber wenn ich das komplett etuyas Thematik und ggf nnoch geräteabhängig. Sorry. Sicher das es keine kleineren sind in der Tuya App?

**Comment by sonny1985** [comment]
Hi.
Ich hab auch 3 Messstecker , natürlich komplett unterschiedliche, im Einsatz. 2 Messen unter 1A ohne Probleme, eine davon auch erst ab einem höheren Wert.
Ich glaub auch das das Geräteabhängig ist.

**Comment by Klugschieter** [comment]
Moin, erstmal danke für die Antworten!
Bei größeren Verbrauchern ist das wie gesagt kein Thema. Aber wenn ich zB. mein Handy über ein USB Netzteil lade, wird alles über 1A angezeigt, je weiter der Aufladevorgang fortschreitet und die Ladeautomatik vom Handy runterregelt damit langsamer geladen wird, fallen die Werte auf 0, obwohl das Handy schon noch lädt. Ist jetzt nicht weltbewegend, ich nutze die Tuya-Steckdosen eigentlich hauptsächlich mit Geräten die über ein 1A liegen, aber ich dachte ich kann mir damit so eine kleine Anzeige basteln, die mir zeigt wann das Handy voll geladen ist und muss es dafür gar nicht erst mehr in die Hand nehmen. Es scheint dann wohl doch Geräteabhängig zu sein. Auf jeden Fall danke für die Infos!

**Comment by Apollon77** [comment]
jupp, kann ich leider nichts ändern
