### ISSUE TITLE
Es besteht keine Verbindung zu tuya

### ISSUE THREAD

**Issue by 9steff2** [Apollon77/ioBroker.tuya#58]
Nachdem ich mittels eines Android Gerätes die Geräte in den ioBroker bekommen habe, besteht nun laut ioBroker keine Verbindung zu Tuya...

tuya.0	2019-06-26 17:45:25.390	info	Discover for local Tuya devices on port 6666
tuya.0	2019-06-26 17:45:25.385	info	Existing devices initialized
tuya.0	2019-06-26 17:45:25.384	info	36617123807d3a2a16b4: Can not start because IP unknown
tuya.0	2019-06-26 17:45:25.317	info	starting. Version 1.0.7 in /opt/iobroker/node_modules/iobroker.tuya, node: v8.14.0
tuya.0	2019-06-26 17:44:02.705	info	Discover for local Tuya devices on port 6666
tuya.0	2019-06-26 17:44:02.700	info	Existing devices initialized
tuya.0	2019-06-26 17:44:02.699	info	36617123807d3a2a16b4: Can not start because IP unknown
tuya.0	2019-06-26 17:44:02.635	info	starting. Version 1.0.7 in /opt/iobroker/node_modules/iobroker.tuya, node: v8.14.0

passt das so oder meinst du ein anders log?

**Comment by Apollon77** [comment]
Bitte logging auf debug stellen und vorher nochmal neu vom GitHub installieren. 

Debug log unter Instanzen - expertenmodus, dort Spalte Logstufe.

**Comment by 9steff2** [comment]
tuya.0 | 2019-06-26 18:01:42.937 | info | Listen for encrypted local Tuya devices on port 6667
-- | -- | -- | --
tuya.0 | 2019-06-26 18:01:42.937 | info | Listen for local Tuya devices on port 6666
tuya.0 | 2019-06-26 18:01:42.929 | info | Existing devices initialized
tuya.0 | 2019-06-26 18:01:42.929 | info | 36617123807d3a2a16b4: None of the discovered devices matches :-(
tuya.0 | 2019-06-26 18:01:42.929 | debug | 36617123807d3a2a16b4: Try to initialize encrypted device with received UDP messages: version=undefined, key=bb4d4c49ceab5229
tuya.0 | 2019-06-26 18:01:42.896 | debug | 36617123807d3a2a16b4: Create device objects if not exist
tuya.0 | 2019-06-26 18:01:42.894 | debug | init 1 known devices
tuya.0 | 2019-06-26 18:01:42.889 | debug | connected set to false
tuya.0 | 2019-06-26 18:01:42.861 | info | starting. Version 2.0.0 in /opt/iobroker/node_modules/iobroker.tuya, node: v8.14.0
tuya.0 | 2019-06-26 18:01:42.753 | debug | statesDB connected
tuya.0 | 2019-06-26 18:01:42.725 | debug | objectDB connected

**Comment by Apollon77** [comment]
Aahhhhh interessant. Version is leer. Naja ich schaue heute Abend auch mal. Hab mir nen android Emulator besorgt und mit dem teste ich dann mal

**Comment by Apollon77** [comment]
Bitte 2.0.1 vom Github checken!

**Comment by 9steff2** [comment]
habe die version 2.0.1 installiert, selbiges

**Comment by Apollon77** [comment]
Dann bitte nochmal debug log senden. 

Und sicherstellen das UDP Pakete nicht irgendwo blockiert werden!

**Comment by 9steff2** [comment]
tuya.0 | 2019-06-27 19:27:23.434 | info | Listen for encrypted local Tuya devices on port 6667
-- | -- | -- | --
tuya.0 | 2019-06-27 19:27:23.434 | info | Listen for local Tuya devices on port 6666
tuya.0 | 2019-06-27 19:27:23.428 | info | Existing devices initialized
tuya.0 | 2019-06-27 19:27:23.428 | info | 36617123807d3a2a16b4: None of the discovered devices matches :-(
tuya.0 | 2019-06-27 19:27:23.428 | debug | 36617123807d3a2a16b4: Try to initialize encrypted device with received UDP messages: version=undefined, key=bb4d4c49ceab5229
tuya.0 | 2019-06-27 19:27:23.392 | debug | 36617123807d3a2a16b4: Create device objects if not exist
tuya.0 | 2019-06-27 19:27:23.390 | debug | init 1 known devices
tuya.0 | 2019-06-27 19:27:23.387 | debug | connected set to false
tuya.0 | 2019-06-27 19:27:23.361 | info | starting. Version 2.0.2 in /opt/iobroker/node_modules/iobroker.tuya, node: v8.14.0
tuya.0 | 2019-06-27 19:27:23.253 | debug | statesDB connected
tuya.0 | 2019-06-27 19:27:23.224 | debug | objectDB connected

**Comment by Apollon77** [comment]
Und danach? Zu wenig log. Bitte etwas Geduld. Udp messages werden an sich alle paar Sekunden versendet von den Geräten. Aber wichtig: smart Life App auf dem Handy killen. Und auch sonst nirgends offen haben!!

**Comment by 9steff2** [comment]
tuya.0	2019-06-27 21:08:05.598	debug	system.adapter.admin.0: logging true

Das kam jetzt noch, mehr kommt aber nicht

App ist auf keinen gerät aktiv

Bei dem Gerät handelt es sich um den Liminea Türkontakt

Keine Ahnung was ich dir sonst noch für Infos zukommen lassen könnte

**Comment by Apollon77** [comment]
Türkontakt? Batteriebetrieben? Dann ist das der Grund. Die gehen nicht weil die nur bei Änderungen kurz online sind ihre Daten in die tuya Cloud senden und offline gehen. Der Adapter hat da keine Chancen verbinden.

**Comment by 9steff2** [comment]
Ja genau....

ach mist, dann bekomme ich den gar nicht in den ioBroker....

**Comment by Apollon77** [comment]
Nope. So lange bis jemand einen Weg gefunden hat die Daten direkt aus der tuya Cloud rauszuholen leider nicht.
