### ISSUE TITLE
Adapter 3.16.0 wird nicht grün

### ISSUE THREAD

**Issue by zaphod2** [Apollon77/ioBroker.tuya#585]
Adapterversion 3.16.0 wird nicht grün. mit v3.15.0 läuft alles wie gehabt, also Adapter wird grün.

**Comment by Apollon77** [comment]
Bitte debug logging einschalten und mal posten. nicht grün heisst an sich das es keine verbindungen bekommt ... Es hat sich an sich nichts viel geändert .... wäre sehr komisch

**Comment by Ilovegym66** [comment]
Kann ich nicht nachvollziehen, hier laeuft V3.16.0 unter buanet docker V10 latest mit js-controller 6.0.10 und Node 20 ohne Probleme.
@zaphod2  bitte auch mal Angaben zum System machen.

**Comment by zaphod2** [comment]
Läuft jetzt.
