### ISSUE TITLE
Support for Cecotec devices 

### ISSUE THREAD

**Issue by tillsteinbach** [Apollon77/ioBroker.tuya#587]
I own a Cecotec dehumidifier that is using the Cecotec App. Under the hood this is also Tuya.
I would love to get the data from the device in ioBroker and control it from there to use PV-power to run it.

I will try to also pair the device with the Tuya App, this could potentially be a work around.

**Comment by tillsteinbach** [comment]
I just tried to pair the connect to the Smart Life App and used the connector and it works flawlessly. So if someone has a Cecotec BigDry or similar device, this will enable you to connect it with ioBroker.

Thanks to the author!

**Comment by Apollon77** [comment]
Cool, thank you for validating!
