### ISSUE TITLE
Zählweise der Attribute unterschlägt die 3

### ISSUE THREAD

**Issue by PerfectAnswer** [Apollon77/ioBroker.tuya#6]
Bin mir nicht sicher ob es ein issue oder ein Feature ist ;)
Unterhalb der der Objekte (WaMa, Trockner, etc.) werden die einzelnen Attribute numerisch dargestellt.
1,2,4,5,6
Es fehlt die 3.
![tuya](https://user-images.githubusercontent.com/834752/47986294-8c88c280-e0dc-11e8-9c68-de8103abc301.JPG)

**Comment by Ilovegym66** [comment]
die 3 fehlt nicht, sondern du hast nicht die erforderliche Sicherheitsstufe, um diese angezeigt zu bekommen :-) :D :D 
Welche App benutzt du? Bei mir werden die Namen aus der App übernommen, benutze die "Oittm Smart" App (Android) für ein LED Stripe und den Diffusor.

**Comment by PerfectAnswer** [comment]
Den Klassiker: SmartLife
Oitmm Smart gibt es auch für iOS, aber die Screenshots sehen 1:1 identisch zu SmartLife aus.
Bei den Steckdosen wir auch kein Schema erkannt, von daher ist es auch nicht verwunderlich das die Werte nur durchnummeriert werden. Verwunderlich ist nur die fehlende 3.

**Comment by Apollon77** [comment]
Der adapter initialisiert ohne Schema genau das was als werte zurückkommen. Wenn die 3 da fehlt dann fehlt sie. 

Interessant wäre hier der App Sync und was danach für ein Schema da ist und ob die 3 da dann drin ist. 

For now: as designed ;-)
