### ISSUE TITLE
Status never updated

### ISSUE THREAD

**Issue by drhideg** [Apollon77/ioBroker.tuya#61]
I added a tuya device [schema](https://github.com/Apollon77/ioBroker.tuya/issues/60) to my iobroker setup in [mapper.js](https://github.com/Apollon77/ioBroker.tuya/blob/master/lib/mapper.js), but the device dont send its devId in the UDP broadcast message and never update object status with the **'Received data for other deviceId...'** message. If I comment out the [condition](https://github.com/Apollon77/ioBroker.tuya/blob/9e2f7e75640018eab74437707d03d37a2e6099da/main.js#L300) it works well, but i dont know what happened if i have more than 1 tuya device.
I only got **'json obj data unvalid'** on the polling request from the tuya instance, or something like this **'{ dps: { '14': 75 }, t: 1562671026 }'** (dps 14 is the battery value on this device)

**Comment by Apollon77** [comment]
The Shchema in mapper is nearly irrelevant here it only for convenience for other users and to have better names.
Else I do not understand what you want to say. Please provide full debug log for me to understand

In general: Battery devices normally are not supported because they are normally not sending UDP at all and are also not online long enough for the adapter to connect. On event they go online, send their data to the Tuya cloud and go offline again.

**Comment by drhideg** [comment]
Sorry for my incomprehension.
The device is a vacuum cleaner, its always online, and it isnt send the deviceId in the JSON response.
Maybe the example was bad in the starting post, dsp 14 is the battery charge value in percentage.
With untouched source, i got this, and status never updated:

tuya.0 | 2019-07-09 17:20:57.460 | warn | bf38f0acc15a6cbe45rbxr: Received data for other deviceId undefined ... ignoring
-- | -- | -- | --
tuya.0 | 2019-07-09 17:20:57.458 | warn | bf38f0acc15a6cbe45rbxr: Received data for other deviceId undefined ... ignoring
tuya.0 | 2019-07-09 17:20:57.443 | warn | bf38f0acc15a6cbe45rbxr: Received data for other deviceId undefined ... ignoring
tuya.0 | 2019-07-09 17:20:48.290 | warn | bf38f0acc15a6cbe45rbxr: Received data for other deviceId undefined ... ignoring
tuya.0 | 2019-07-09 17:20:46.846 | warn | bf38f0acc15a6cbe45rbxr: Received data for other deviceId undefined ... ignoring
tuya.0 | 2019-07-09 17:20:43.757 | warn | bf38f0acc15a6cbe45rbxr: Received data for other deviceId undefined ... ignoring
tuya.0 | 2019-07-09 17:20:43.753 | warn | bf38f0acc15a6cbe45rbxr: Received data for other deviceId undefined ... ignoring
tuya.0 | 2019-07-09 17:20:41.747 | warn | bf38f0acc15a6cbe45rbxr: Received data for other deviceId undefined ... ignoring
tuya.0 | 2019-07-09 17:20:29.331 | debug | system.adapter.admin.0: logging true
tuya.0 | 2019-07-09 15:18:12.961 | debug | Discovered encrypted device and store for later usage:  192.168.1.12:49153 -  U��Зfgo3i����2��*����gY�~�����b�4��gӵ�J���n�%�ZK�0@�>��<����Y�_�]K�i��ˤ��RH^v����Z�jMg�V��v�)�
tuya.0 | 2019-07-09 15:18:11.472 | debug | stateChange tuya.0.info.connection  {"val":true,"ack":true,"ts":1562685491467,"q":0,"from":"system.adapter.tuya.0","user":"system.user.admin","lc":1562685491467}
tuya.0 | 2019-07-09 15:18:11.471 | debug | stateChange tuya.0.bf38f0acc15a6cbe45rbxr.online  {"val":true,"ack":true,"ts":1562685491462,"q":0,"from":"system.adapter.tuya.0","user":"system.user.admin","lc":1562685491462}
tuya.0 | 2019-07-09 15:18:11.471 | debug | connected set to true
tuya.0 | 2019-07-09 15:18:11.461 | debug | bf38f0acc15a6cbe45rbxr: Connected to device
tuya.0 | 2019-07-09 15:18:11.396 | info | Listen for encrypted local Tuya devices on port 6667
tuya.0 | 2019-07-09 15:18:11.396 | info | Listen for local Tuya devices on port 6666
tuya.0 | 2019-07-09 15:18:11.394 | info | Existing devices initialized
tuya.0 | 2019-07-09 15:18:11.394 | info | bf38f0acc15a6cbe45rbxr Init with IP=192.168.1.12, Key=27c1d0072b4526bc, Version=3.3
tuya.0 | 2019-07-09 15:18:11.332 | debug | bf38f0acc15a6cbe45rbxr: Create device objects if not exist
tuya.0 | 2019-07-09 15:18:11.331 | debug | init 1 known devices
tuya.0 | 2019-07-09 15:18:11.324 | debug | connected set to false
tuya.0 | 2019-07-09 15:18:11.293 | info | starting. Version 2.0.2 in /opt/iobroker/node_modules/iobroker.tuya, node: v8.16.0
tuya.0 | 2019-07-09 15:18:11.177 | debug | statesDB connected
tuya.0 | 2019-07-09 15:18:11.169 | debug | objectDB connected
tuya.0 | 2019-07-09 15:17:40.663 | error | already running
tuya.0 | 2019-07-09 15:17:40.659 | debug | statesDB connected
tuya.0 | 2019-07-09 15:17:40.650 | debug | objectDB connected
tuya.0 | 2019-07-09 15:17:37.983 | debug | stateChange tuya.0.bf38f0acc15a6cbe45rbxr.online  {"val":false,"ack":true,"ts":1562685457982,"q":0,"from":"system.adapter.tuya.0","user":"system.user.admin","lc":1562685457982}
tuya.0 | 2019-07-09 15:17:37.982 | debug | connected set to false
tuya.0 | 2019-07-09 15:17:37.982 | debug | stateChange tuya.0.info.connection  {"val":false,"ack":true,"ts":1562685457981,"q":0,"from":"system.adapter.tuya.0","user":"system.user.admin","lc":1562685457981}
tuya.0 | 2019-07-09 15:17:37.981 | debug | bf38f0acc15a6cbe45rbxr: Disconnected from device


Then i modify main.js around line 300, add debug line and remove condition:

```
            const util = require('util')
            adapter.log.debug(deviceId + ': Received raw: ' + (util.inspect(dat$
            if (typeof data !== 'object' || !data || !data.dps) return;
//            if (data.devId !== deviceId) {
//                adapter.log.warn(deviceId + ': Received data for other device$
//                return;
//            }
```
and got status updates:


tuya.0 | 2019-07-09 17:29:23.058 | debug | stateChange  tuya.0.bf38f0acc15a6cbe45rbxr.25  {"val":false,"ack":true,"ts":1562686163058,"q":0,"from":"system.adapter.tuya.0","user":"system.user.admin","lc":1562686163058}
-- | -- | -- | --
tuya.0 | 2019-07-09 17:29:23.057 | debug | bf38f0acc15a6cbe45rbxr: Received data: {"25":false}
tuya.0 | 2019-07-09 17:29:23.057 | debug | bf38f0acc15a6cbe45rbxr: Received raw: { dps: { '25': false }, t: 1562686162 }
tuya.0 | 2019-07-09 17:29:23.050 | debug | stateChange  tuya.0.bf38f0acc15a6cbe45rbxr.28  {"val":"5","ack":true,"ts":1562686163049,"q":0,"from":"system.adapter.tuya.0","user":"system.user.admin","lc":1562686163049}
tuya.0 | 2019-07-09 17:29:23.049 | debug | bf38f0acc15a6cbe45rbxr: Received data: {"28":"charging"}
tuya.0 | 2019-07-09 17:29:23.049 | debug | bf38f0acc15a6cbe45rbxr: Received raw: { dps: { '28': 'charging' }, t: 1562686162 }
tuya.0 | 2019-07-09 17:29:23.046 | debug | stateChange  tuya.0.bf38f0acc15a6cbe45rbxr.27  {"val":"0","ack":true,"ts":1562686163044,"q":0,"from":"system.adapter.tuya.0","user":"system.user.admin","lc":1562686163044}
tuya.0 | 2019-07-09 17:29:23.044 | debug | bf38f0acc15a6cbe45rbxr: Received data: {"27":"idle"}
tuya.0 | 2019-07-09 17:29:23.044 | debug | bf38f0acc15a6cbe45rbxr: Received raw: { dps: { '27': 'idle' }, t: 1562686162 }
tuya.0 | 2019-07-09 17:29:13.786 | debug | stateChange  tuya.0.bf38f0acc15a6cbe45rbxr.30  {"val":"0","ack":true,"ts":1562686153786,"q":0,"from":"system.adapter.tuya.0","user":"system.user.admin","lc":1562686153786}
tuya.0 | 2019-07-09 17:29:13.786 | debug | bf38f0acc15a6cbe45rbxr: Received data: {"30":"low"}
tuya.0 | 2019-07-09 17:29:13.786 | debug | bf38f0acc15a6cbe45rbxr: Received raw: { dps: { '30': 'low' }, t: 1562686153 }
tuya.0 | 2019-07-09 17:29:11.961 | debug | stateChange  tuya.0.bf38f0acc15a6cbe45rbxr.27  {"val":"5","ack":true,"ts":1562686151959,"q":0,"from":"system.adapter.tuya.0","user":"system.user.admin","lc":1562686151959}
tuya.0 | 2019-07-09 17:29:11.958 | debug | bf38f0acc15a6cbe45rbxr: Received data: {"27":"chargego"}
tuya.0 | 2019-07-09 17:29:11.958 | debug | bf38f0acc15a6cbe45rbxr: Received raw: { dps: { '27': 'chargego' }, t: 1562686151 }
tuya.0 | 2019-07-09 17:29:10.927 | debug | stateChange  tuya.0.bf38f0acc15a6cbe45rbxr.30  {"val":"1","ack":true,"ts":1562686150923,"q":0,"from":"system.adapter.tuya.0","user":"system.user.admin","lc":1562686150923}
tuya.0 | 2019-07-09 17:29:10.920 | debug | bf38f0acc15a6cbe45rbxr: Received data: {"30":"normal"}
tuya.0 | 2019-07-09 17:29:10.919 | debug | bf38f0acc15a6cbe45rbxr: Received raw: { dps: { '30': 'normal' }, t: 1562686150 }
tuya.0 | 2019-07-09 17:29:09.394 | debug | stateChange  tuya.0.bf38f0acc15a6cbe45rbxr.27  {"val":"1","ack":true,"ts":1562686149392,"q":0,"from":"system.adapter.tuya.0","user":"system.user.admin","lc":1562686141321}
tuya.0 | 2019-07-09 17:29:09.392 | debug | bf38f0acc15a6cbe45rbxr: Received data: {"27":"auto"}
tuya.0 | 2019-07-09 17:29:09.392 | debug | bf38f0acc15a6cbe45rbxr: Received raw: { dps: { '27': 'auto' }, t: 1562686148 }
tuya.0 | 2019-07-09 17:29:03.374 | debug | stateChange  tuya.0.bf38f0acc15a6cbe45rbxr.25  {"val":true,"ack":true,"ts":1562686143373,"q":0,"from":"system.adapter.tuya.0","user":"system.user.admin","lc":1562686143373}
tuya.0 | 2019-07-09 17:29:03.373 | debug | bf38f0acc15a6cbe45rbxr: Received data: {"25":true}
tuya.0 | 2019-07-09 17:29:03.373 | debug | bf38f0acc15a6cbe45rbxr: Received raw: { dps: { '25': true }, t: 1562686142 }
tuya.0 | 2019-07-09 17:29:03.370 | debug | stateChange  tuya.0.bf38f0acc15a6cbe45rbxr.28  {"val":"1","ack":true,"ts":1562686143370,"q":0,"from":"system.adapter.tuya.0","user":"system.user.admin","lc":1562686143370}
tuya.0 | 2019-07-09 17:29:03.369 | debug | bf38f0acc15a6cbe45rbxr: Received data: {"28":"working"}
tuya.0 | 2019-07-09 17:29:03.369 | debug | bf38f0acc15a6cbe45rbxr: Received raw: { dps: { '28': 'working' }, t: 1562686142 }
tuya.0 | 2019-07-09 17:29:01.322 | debug | stateChange  tuya.0.bf38f0acc15a6cbe45rbxr.27  {"val":"1","ack":true,"ts":1562686141321,"q":0,"from":"system.adapter.tuya.0","user":"system.user.admin","lc":1562686141321}
tuya.0 | 2019-07-09 17:29:01.321 | debug | bf38f0acc15a6cbe45rbxr: Received data: {"27":"auto"}
tuya.0 | 2019-07-09 17:29:01.320 | debug | bf38f0acc15a6cbe45rbxr: Received raw: { dps: { '27': 'auto' }, t: 1562686140 }
tuya.0 | 2019-07-09 17:28:58.157 | debug | stateChange  tuya.0.bf38f0acc15a6cbe45rbxr.27  {"val":"5","ack":true,"ts":1562686138156,"q":0,"from":"system.adapter.tuya.0","user":"system.user.admin","lc":1562686138156}
tuya.0 | 2019-07-09 17:28:58.156 | debug | bf38f0acc15a6cbe45rbxr: Received data: {"27":"chargego"}
tuya.0 | 2019-07-09 17:28:58.156 | debug | bf38f0acc15a6cbe45rbxr: Received raw: { dps: { '27': 'chargego' }, t: 1562686137 }
tuya.0 | 2019-07-09 15:28:47.944 | debug | Discovered encrypted device and store for later usage:  192.168.1.12:49153 -  U��Зfgo3i����2��*����gY�~�����b�4��gӵ�J���n�%�ZK�0@�>��<����Y�_�]K�i��ˤ��RH^v����Z�jMg�V��v�)�
tuya.0 | 2019-07-09 15:28:43.624 | debug | stateChange tuya.0.info.connection  {"val":true,"ack":true,"ts":1562686123614,"q":0,"from":"system.adapter.tuya.0","user":"system.user.admin","lc":1562686123614}
tuya.0 | 2019-07-09 15:28:43.623 | debug | stateChange tuya.0.bf38f0acc15a6cbe45rbxr.online  {"val":true,"ack":true,"ts":1562686123614,"q":0,"from":"system.adapter.tuya.0","user":"system.user.admin","lc":1562686123614}
tuya.0 | 2019-07-09 15:28:43.620 | debug | bf38f0acc15a6cbe45rbxr: Received data: undefined
tuya.0 | 2019-07-09 15:28:43.620 | debug | bf38f0acc15a6cbe45rbxr: Received raw: 'json obj data unvalid'
tuya.0 | 2019-07-09 15:28:43.617 | debug | connected set to true
tuya.0 | 2019-07-09 15:28:43.611 | debug | bf38f0acc15a6cbe45rbxr: Connected to device
tuya.0 | 2019-07-09 15:28:43.548 | info | Listen for encrypted local Tuya devices on port 6667
tuya.0 | 2019-07-09 15:28:43.548 | info | Listen for local Tuya devices on port 6666
tuya.0 | 2019-07-09 15:28:43.546 | info | Existing devices initialized
tuya.0 | 2019-07-09 15:28:43.545 | info | bf38f0acc15a6cbe45rbxr Init with IP=192.168.1.12, Key=27c1d0072b4526bc, Version=3.3
tuya.0 | 2019-07-09 15:28:43.472 | debug | bf38f0acc15a6cbe45rbxr: Create device objects if not exist
tuya.0 | 2019-07-09 15:28:43.470 | debug | init 1 known devices
tuya.0 | 2019-07-09 15:28:43.465 | debug | connected set to false
tuya.0 | 2019-07-09 15:28:43.454 | info | starting. Version 2.0.2 in /opt/iobroker/node_modules/iobroker.tuya, node: v8.16.0
tuya.0 | 2019-07-09 15:28:43.360 | debug | statesDB connected
tuya.0 | 2019-07-09 15:28:43.348 | debug | objectDB connected
tuya.0 | 2019-07-09 15:28:12.864 | error | already running
tuya.0 | 2019-07-09 15:28:12.860 | debug | statesDB connected
tuya.0 | 2019-07-09 15:28:12.851 | debug | objectDB connected
tuya.0 | 2019-07-09 15:28:10.204 | debug | stateChange tuya.0.bf38f0acc15a6cbe45rbxr.online  {"val":false,"ack":true,"ts":1562686090203,"q":0,"from":"system.adapter.tuya.0","user":"system.user.admin","lc":1562686090203}
tuya.0 | 2019-07-09 15:28:10.204 | debug | connected set to false
tuya.0 | 2019-07-09 15:28:10.203 | debug | stateChange tuya.0.info.connection  {"val":false,"ack":true,"ts":1562686090202,"q":0,"from":"system.adapter.tuya.0","user":"system.user.admin","lc":1562686090202}
tuya.0 | 2019-07-09 15:28:10.201 | debug | bf38f0acc15a6cbe45rbxr: Disconnected from device

**Comment by Apollon77** [comment]
Grrrr ... I hate devices that exist out of the specs :-(

Ok, 2.0.3 has removed the check. Thank you for experimenting
