### ISSUE TITLE
Tuya 3.0

### ISSUE THREAD

**Issue by wolltswurm** [Apollon77/ioBroker.tuya#65]
Nach mehrmaligen versuchen über emulator bringt er den webproxy nicht " cannot get"
user Zertifikat kann nicht geladen werden.

![webproxy](https://user-images.githubusercontent.com/49351305/64347495-5665e900-cff4-11e9-82d3-1c7ce699cff7.JPG)

**Comment by Apollon77** [comment]
Auf 8889 ist nur noch das Zertifikat, keine Web-UI mehr weil ein anderer proxy in Benutzung ist. Bitte QR-Code für Zertifikat nutzen

**Comment by xXBJXx** [comment]
Auf einem emulator kann man kein QR-Code nutzen wie kann man da dann an das Zertifikat kommen ?

**Comment by Apollon77** [comment]
Du kannst jetzt auch iOS wieder nutzen oder ein anderes normales Handy.
Sonst http://<ip>:8889/ca.pem

**Comment by wolltswurm** [comment]
Auch bei ios hat es nicht funktioniert sei es ipad oder iphone x, viel falsch machen geht ja nicht .

**Comment by Apollon77** [comment]
;it der neuen 3.0.0 sollte alles wieder tun!!
