### ISSUE TITLE
QR-Code wird nicht generiert.

### ISSUE THREAD

**Issue by stereodruid** [Apollon77/ioBroker.tuya#66]
Hallo Apollon,

wenn ich auf den Button zum den QR-Code generieren klicke, passiert nichts.
Neustart des Adapters habe ich probiert.
Ich nutze für ioBroker den Port 8088, sollte das einen Unterschied machen?

System ist ein Raspberry pi 3.
Netzwerkanbindung per LAN.

**Auszug des Log's:**

tuya.0 | 2019-09-06 12:16:15.521 | info | terminating
-- | -- | -- | --
tuya.0 | 2019-09-06 12:16:15.317 | info | starting. Version 3.0.0 in /opt/iobroker/node_modules/iobroker.tuya, node: v6.12.3
tuya.0 | 2019-09-06 12:16:15.247 | info | States connected to redis: 0.0.0.0:6379
tuya.0 | 2019-09-06 12:16:15.015 | error | at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.tuya/main.js:30:20)
tuya.0 | 2019-09-06 12:16:15.015 | error | at require (internal/module.js:20:19)
tuya.0 | 2019-09-06 12:16:15.015 | error | at Module.require (module.js:497:17)
tuya.0 | 2019-09-06 12:16:15.015 | error | at Function.Module._load (module.js:438:3)
tuya.0 | 2019-09-06 12:16:15.015 | error | at tryModuleLoad (module.js:446:12)
tuya.0 | 2019-09-06 12:16:15.015 | error | at Module.load (module.js:487:32)
tuya.0 | 2019-09-06 12:16:15.015 | error | at Object.Module._extensions..js (module.js:579:10)
tuya.0 | 2019-09-06 12:16:15.015 | error | at Module._compile (module.js:542:28)
tuya.0 | 2019-09-06 12:16:15.015 | error | at Object.runInThisContext (vm.js:97:10)
tuya.0 | 2019-09-06 12:16:15.015 | error | at createScript (vm.js:56:10)
tuya.0 | 2019-09-06 12:16:15.015 | error | SyntaxError: Unexpected identifier
tuya.0 | 2019-09-06 12:16:15.015 | error | ^^^^^^^^^
tuya.0 | 2019-09-06 12:16:15.015 | error | async _sendPing() {
tuya.0 | 2019-09-06 12:16:15.015 | error | /opt/iobroker/node_modules/tuyapi/index.js:247
tuya.0 | 2019-09-06 12:16:15.000 | error | uncaught exception: Unexpected identifier

**Comment by Apollon77** [comment]
Which nodejs Version is used? You need at least nodejs 8!!

**Comment by stereodruid** [comment]
That was the solution. I was on node version 6.x. Thank you very much. Issue can be closed.
