### ISSUE TITLE
Proxy funktioniert nicht

### ISSUE THREAD

**Issue by hacky98** [Apollon77/ioBroker.tuya#7]
Ich habe das Problem, dass sowohl auf meinem iPhone und Android Handy ich es nicht hinbekomme, die Tuya Codes auszulesen.
Immer wenn ich den Proxy und alles eingerichtet habe und in die App gehe, sagt die App, dass sie keine Verbindung aufbauen kann und dann lädt nicht einmal die Geräte Liste auf dem iPhone.
Und habe alles auf meinem Raspberry Pi 3 installiert.

**Comment by Apollon77** [comment]
Scheint mir eher ein benutzerfehler zu sein weil der Proxy nicht erreicht werden kann. Bitte im iobroker Forum Posten in den tuya Threads.
