### ISSUE TITLE
SSL des Proxys schlägt fehl

### ISSUE THREAD

**Issue by Bluetexon** [Apollon77/ioBroker.tuya#71]
Hallo,

ich habe heute bereits (über die Smart Life App) eine Steckdose erfolgreich in ioBroker hinzugefügt. Nun wollte ich die nächste Steckdose hinzufügen und in ioBroker importieren, doch leider funktioniert der Proxy jetzt nicht mehr korrekt.
Ich habe den tuya-Adapter 3.0.2 direkt hier von GitHub installiert, da es mit der 2.0.4 ebenfalls nicht ging.

Im ioBroker Fehlerlog werden folgende zwei Meldungen mehrmals geloggt, wenn eine Request von meinem Handy gesendet wird:

tuya.0 | 2019-10-01 22:12:18.049 | error | Error: 4144439296:error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1536:SSL alert number 46
-- | -- | -- | --
tuya.0 | 2019-10-01 22:12:18.049 | error | SSL-Proxy ERROR: Error: 4144439296:error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1536:SSL alert number 46

In der Smart Life App steht, wenn der Proxy aktiv ist, immer "Incorrect local timer 50502". Ohne Proxy funktioniert die App problemlos.
Eine korrekte Internetverbindung besteht ebenfalls, da ich mit Proxy normal im Intertet surfen kann.

Ich danke dir für deine tolle Arbeit an diesem Adapter und hoffe, dass wir den Fehler beheben können :)

Gruß,
Bluetexon

**Comment by Apollon77** [comment]
"mit proxy normal im web surfen" ... auch auf https seiten?

versuch mal 

apt-get install ca-certificates

**Comment by Bluetexon** [comment]
HTTPS geht so halb. In Chrome auf dem Handy kommt dann der Fehler `NET::ERR_CERT_AUTHORITY_INVALID`. 

Wenn ich versuche ca-certificates zu installieren erscheint lediglich diese Meldung:
`ca-certificates is already the newest version (20161130+nmu1+deb9u1).`

Meine Android-WiFi Einstellungen sehen wie folgt aus:
![photo_2019-10-02_16-00-04](https://user-images.githubusercontent.com/22718113/66050597-ca30de00-e52d-11e9-923e-831dc7a0b008.jpg)

**Comment by Apollon77** [comment]
Und das Zertifikat ist korrekt für alle möglichen Fälle (siehe Github infos) hinterlegt?

**Comment by ioJoe1** [comment]
Hallo,
nach 3 Tagen Dauerrecherche gebe ich jetzt auf und kommentiere einfach mal in der Hoffnung hier vielleicht eine Lösung zu finden. Ich habe vermutlich alle kursierenden Anleitungen und Ansätze probiert, um den Tuya Adapter ans Laufen zu bringen, jedoch bekomme ich folgende Fehlermeldung nicht weg: 


020-01-10 00:47:01.601 - error: tuya.0 (6260) SSL-Proxy ERROR: Error: 3070118352:error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert number 46
--
2020-01-10 00:47:01.601 - error: tuya.0 (6260) Error: 3070118352:error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert number 46


In der Tuya bzw. SmartLife App erscheint der Fehler: 
Incorrect local timer, please correct it. 50502

Das Zertifikat habe ich sowohl für "WLAN" als auch für "VPN und Apps" installiert. 

Die Seite https://auth.tuya.com kann ich ohne Probleme aufrufen. Surfen im www ist kein Problem.

Ich habe auch schon versucht, die App zu deinstallieren/installieren und bei der Anmeldung "China" als Land ausgewählt. Das hatte zuletzt bei meinem Xiaomi GatewayV3 Probleme gemacht.

Ich komme hier partou nicht weiter und würde mich über den ein oder anderen Tipp freuen. 

Handy ist Samsung Galaxy A3 mit allen Updates
Tuya Adapter ist 3.1.16 (zuvor habe ich es mit 3.1.15 probiert) 
IObroker läuft auf einem Pi4
Router ist eine FritzBox 7362 SL

Vorab danke für jede Unterstützung!

LG

**Comment by Apollon77** [comment]
Welche Version ist die tuya App? Alles ab 3.14 geht aktuell nicht mehr wegen Änderungen. Da gibt es aktuell einen Forum thread zu. Hier also bitte eine ältere Version nehmen (3.12 tut wohl)

Ansonsten bedeutet der timer Fehler aber das das Zertifikat irgendwie nicht voll eingetragen oder aktiviert ist - wenn Surfen (auf https Seiten) tut sollte aber der Timer Fehler nicht auftreten.

**Comment by ioJoe1** [comment]
es war die 3.15. Den Thread habe ich wohl überlesen. Mit der 3.12 hat alles super geklappt :) 
Tausend Dank für den Hinweis!

Ohne meckern zu wollen; Könnte man vielleicht in der Readme immer die zuletzt funktionierende App-Version mit auflisten?

**Comment by Apollon77** [comment]
Gute Idee: War bisher nie ein Problem bis sie in der 3.1.4 es kaputt gemacht haben :-(

**Comment by ioJoe1** [comment]
Nervt bestimmt wenn man da als Entwickler immer nacharbeiten muss... Meinen Respekt für den tollen Adapter den du immer wieder neu schusterst, dass er läuft :)

**Comment by kunator** [comment]
Der Hinweis auf die funktionierende App-Version sollte wirklich ganz nach oben in die Readme-Datei eingefügt werden, das hätte mir doch erheblich Zeit gespart. Ich habe es heute mit mehreren Telefonen, einem Tablet und MEmu probiert, aber erst als ich die Version der Smart Life App auf 3.12 downgegraded habe, klappte die Installation (völlig problemlos). Bitte nicht als Gemecker verstehen. Ich danke für die tolle Arbeit, aber ein solcher Hinweis könnte vielleicht auch für den einen oder anderen interessant sein und unnötigen Frust vermeiden.

**Comment by akurria** [comment]
Leider habe ich die gleichen Fehler wie die über mir. 
Surfen im Internet geht mit dem Handy. Auch Https.
Wenn ich Tuya starte kommt der bekannte Netzwerkfehler.


hm-rpc.0 | 2020-01-30 15:13:38.166 | error | (14195) init error: Error: socket hang up
-- | -- | -- | --
tuya.0 | 2020-01-30 15:13:34.663 | error | (14640) Error: 3069331920:error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert number 46
tuya.0 | 2020-01-30 15:13:34.661 | error | (14640) SSL-Proxy ERROR: Error: 3069331920:error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert number 46
tuya.0 | 2020-01-30 15:13:34.637 | error | (14640) Error: 3069331920:error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert number 46
tuya.0 | 2020-01-30 15:13:34.636 | error | (14640) SSL-Proxy ERROR: Error: 3069331920:error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert number 46
tuya.0 | 2020-01-30 15:13:31.832 | error | (14640) Error: 3069331920:error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert number 46
tuya.0 | 2020-01-30 15:13:31.831 | error | (14640) SSL-Proxy ERROR: Error: 3069331920:error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert number 46

Habe beides schon probiert, VPN, WLAN, hat alles nicht geklappt.
Version auf 3.1.13 runter gegangen, alles bringt nichts.

**Comment by Apollon77** [comment]
3.12.x sollte tun... bitte nutzen und das Zertifikat ist bei dr Meldung ggf falsch aktiviert.

**Comment by akurria** [comment]
> 3.12.x sollte tun... bitte nutzen und das Zertifikat ist bei dr Meldung ggf falsch aktiviert.

Habe ich gemacht, sieht auch besser aus, er läd im Tuya, aber dann kommt Laden fehlgeschlagen. 
Ich bin ratlos. Zertifikat mache ich über WLAN, weil ich kein VPN nutze.

**Comment by Apollon77** [comment]
Zu Videos kann ich nichts sagen. Die stammen nicht von mir und ich kenne die meisten bestimmt nicht mal. Offiziell wäre: https://github.com/Apollon77/ioBroker.tuya/blob/master/PROXY.md#android

**Comment by nobtuk** [comment]
Hallo, ich hatte das gleiche Problem seit Gestern, auf Grund dieser Seite habe ich dann mal die Tuya App kontrolliert, und siehe da die hat sich gestern heimlich aktualisiert. Gelöscht und ältere Version neu installiert und siehe es geht wieder. 
Jetzt habe ich aber eine andere Frage: Im iobroker lassen sich die Lichtschalter (ohne N-Leiter) schalten aber wenn ich manuell am Lichtschalter schalte wird die Änderung nicht immer im iobroker erfasst. Egal ob im iobroker online mit true oder false angezeigt wird. Es wird dort nicht immer online = true angezeigt obwohl im ping Adapter online angezeigt wird. Ich möchte einen Lichtschalter eines 3er Lichtschalters (Tuya) z.B. nur nutzen um eine WLAN Steckdose zu schalten. Also keine Last an diesem einen Schalter von dem 3er Schalter.Außerdem würde ich gerne wissen ob ich jetzt immer noch über China schalte oder nicht.

**Comment by Apollon77** [comment]
Debug Log aktivieren und renschauen. Wenn online nicht true dann hat der Adapter  keine Verbindung - ist dann ggf die App offen und "klaut" sich die Verbindung?
