### ISSUE TITLE
State wird nicht übermittelt

### ISSUE THREAD

**Issue by Saesh123** [Apollon77/ioBroker.tuya#72]
Hi, ich habe neue Luminea Wifi Kontaktsensoren hinzugefügt. Leider wird der Status geöffnet/geschlossen nicht übertragen. Der Batteriestatus wird richtig übermittelt. Über die Smart Life App wird jeder Status korrekt weitergehen. Die übrigen Steckdosen werden korrekt übermittelt. Habt ihr dafür eine Erklärung und eventuell eine Lösung?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Apollon77** [comment]
Ist der Adapter zu dem Gerät verbunden? Steht connected state da auf true?

**Comment by Saesh123** [comment]
>Ist der Adapter zu dem Gerät verbunden? Steht connected state da auf true?

@Apollon77 nein, stehen jeweils auf false und das seit Anfang an. Die Batteryangaben werden aber aktualisiert. Per Smart Life wird jeder Status aktualisiert.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Apollon77** [comment]
Dann habe ich keine Ahnung wo die Batterieinfos herkommen in ioBroker. Wenn nicht verbunden fehlen die UDP Pakete - bei Bateriebasierten geräten ist es eigentlich so das die mit dem Adapter nicht funktionieren weil die nie lang genug online sind und nur online gehen, was in die Tuya Cloud melden und wieder offline gehen ... Batterie schonen!
Also von daher sage ich mal : Diese Sensotren gehen nicht
