### ISSUE TITLE
v3.0.2: SSL-Proxy ERROR: Error: socket hang up

### ISSUE THREAD

**Issue by ESEEG** [Apollon77/ioBroker.tuya#73]
Hi,
während der Proxy läuft und ich die Smart-Life-App starte erhalte ich folgende Fehle im Log:

Error: socket hang up at TLSSocket.onSocketClose (_tls_wrap.js:764:23) at TLSSocket.emit (events.js:203:15) at _handle.close (net.js:606:12) at Socket.done (_tls_wrap.js:388:7) at 

SSL-Proxy ERROR: Error: socket hang up

Die App meldet dabei "Das Netzwerk hat Verbindungsfehler Bitte überprüfen Sie das Netzwerk".
Zertifikat "NodeMITMProxyCA" ist installiert und Proxyeinstellungen (ioBroker-IP + Port 8888) in der WLAN-Verbindung sind gesetzt. Ich erhalte die Meldung sowohl auf ipad als auch iphone (jeweils v13.1.2)

Alles was ich dazu finden konnte ist, dass exakt dieses Problem mit Aufspielen von v.3.0.2 gelöst werden konnte und die meisten Android nutzen. Mehrfache Neuinstallation des Tuya-Adapters brachte keine Besserung. 

Node.js: v10.16.3
NPM: 6.9.0
Auf Raspberry Pi 3b+

**Comment by Apollon77** [comment]
hast Du das Zertifikat auch aktiviert??

**Comment by ESEEG** [comment]
Das ist jetzt peinlich...das war's. Bei dem ständigen neuinstallieren und einrichten ist das offenbar untergegangen.Sollte jemand dasselbe Problem haben:
Einstellungen->Allgemein->Info->Zertifikatsvertrauenseinstellungen->NodeMITMProxyCA  aktivieren.
