### ISSUE TITLE
Add PIR Sensor

### ISSUE THREAD

**Issue by w0nk1** [Apollon77/ioBroker.tuya#74]
It would be great to add PIR sensors:

nfo: tuya.0 {"schema":"[{\"mode\":\"ro\",\"code\":\"PIR\",\"name\":\"PIR\",\"property\":{\"range\":[\"pir\"],\"type\":\"enum\"},\"id\":101,\"type\":\"obj\",\"desc\":\"pir 检测\"},{\"mode\":\"ro\",\"code\":\"battery\",\"name\":\"电池电量\",\"property\":{\"unit\":\"\",\"min\":0,\"max\":10000,\"scale\":0,\"step\":1,\"type\":\"value\"},\"id\":103,\"type\":\"obj\",\"desc\":\"mcu 上报电池电量\"}]","schemaExt":"[]"}

would be great.

**Comment by Apollon77** [comment]
The line above is missing with the device-type id :-(
