### ISSUE TITLE
No updates of adapter objects

### ISSUE THREAD

**Issue by eljarno** [Apollon77/ioBroker.tuya#75]
Like I commented already in the no sync issue, finally I could manage to get the adapter running. But unfortunately no objects (the smart home devices) are updated once the the states of them have been changed, like switching the light on. Either I'm not able to control the devices by changing the state values, as it possible for example in the Alexa adapter.

**Comment by eljarno** [comment]
Okay now it worked for the must stuff suddenly without changing anything, but however the door sensors are still now working

**Comment by Apollon77** [comment]
Not working means? Cause not updated? Are those battery powered devices?

**Comment by eljarno** [comment]
Yes they are battery powered devices for sure. But they are completely new. Not working means the status update are not synced to ioBroker. Whereas Alexa recognize it every time with some seconds of latency.

**Comment by Apollon77** [comment]
Tuya battery Powered devices go online when sometjing happens, report tehir status into the Tuya cloud and then go offline.
The adapter is working with a local connection to the device, but the device is way too short available locally (if) ... The adapter can not connect to the Tuya cloud.

Amyzon Skill from Tuya is connection to their cloud system, so they have the status
