### ISSUE TITLE
Possibility to implement groups ?

### ISSUE THREAD

**Issue by DutchmanNL** [Apollon77/ioBroker.tuya#77]
In the SmartLife app its possible to group device into 1 channel, this would be very useful also for the tuya adapter to adopt this principle.

If the data cannot be receive from tuya itself, I would suggest to have an equal implementation path as the Zigbee and Tradfri adapter were ups create groups and manage the group memberships within the adapter config.

This will also be handy/important for ioT integration. Example : My son has 3 Led-Spots (tuya) in his room now these are 3 devices.
I can now make a lot of effort and handle it by scripting, or configure a routine in Alexa.
using the last one is easier, will will cause unneeded overloads 

![IMG_6933](https://user-images.githubusercontent.com/7318445/67158072-cfff2f80-f333-11e9-807d-f7da9bf73489.PNG)

**Comment by Apollon77** [comment]
Zigbee and zwave protocols habe group support directly. Tuya not. 
You can use scenes for this.

**Comment by DutchmanNL** [comment]
> You can use scenes for this.

you mean the adapter scenes ?
Yes possible but for new users almost not understandable and all states ( 8 for 1 lamp) must be configured manually.

I mean something more user friendly I think a nice add-on.
You create a group, the adapter ensures synchronization of the values of alle States by the main group.

**Comment by Apollon77** [comment]
Yes I mean scenes ... Mixing together protocol/communication adapters with such "local" functionalities is not the wanted behaviour. If (like zigbee or zwave) the protocol itself allows grouping then this belongs to the adapter ... but tuya does not have this

**Comment by DutchmanNL** [comment]
stupid tuya does it only by its cloud grr

**Comment by Apollon77** [comment]
Yes and even then all devices are controlled separately in the background

**Comment by Apollon77** [comment]
I would close here, I see no real way to hold that up to date because it si only in their cloud

**Comment by DutchmanNL** [comment]
Maybe we should consider to have something similar for devices?

Fully understand the zigbee & zwave part (done by protocol) still I think combining actions on states simultaneously like for tuya, but also other, woul be a nice disability addition
