### ISSUE TITLE
Adapter is not stopped correctly while updating

### ISSUE THREAD

**Issue by ToTXR4Y** [Apollon77/ioBroker.tuya#79]
It seems that the adapter is not stopped correctly while updating through the admin-panel of iobroker.

host.iobroker | 2019-12-01 17:32:54.434 | warn | instance system.adapter.tuya.0 already running with pid 10224

After updating the adapter turns yellow or red in some cases, pausing and restarting the adapter it will turn green.

**Comment by Apollon77** [comment]
Which js-Controller?

**Comment by ToTXR4Y** [comment]
2.1.1, the newest at the moment i guess.

**Comment by Apollon77** [comment]
is nug in controller. will be fixed in next controller version
