### ISSUE TITLE
new Shema added for product type ScIEYTTGvXy1uuWt

### ISSUE THREAD

**Issue by ChrSch84** [Apollon77/ioBroker.tuya#8]
Hope this helps :)

tuya.0 | 2018-11-19 18:33:43.657 | info | {"schema":"[{\"mode\":\"rw\",\"code\":\"switch_1\",\"name\":\"开关1\",\"property\":{\"type\":\"bool\"},\"iconname\":\"icon-dp_power2\",\"id\":1,\"type\":\"obj\",\"desc\":\"\"},{\"mode\":\"rw\",\"code\"
-- | -- | -- | --
tuya.0 | 2018-11-19 18:33:43.657 | info | new Shema added for product type ScIEYTTGvXy1uuWt. Please send next line from logfile on disk to developer!

**Comment by Apollon77** [comment]
thank you, will be in next version

**Comment by ChrSch84** [comment]
Thank you.
