### ISSUE TITLE
problem with Proxy

### ISSUE THREAD

**Issue by Dome2075** [Apollon77/ioBroker.tuya#88]
Hi,,
i want to add new Devices to tuya but i always get an error:

![image](https://user-images.githubusercontent.com/37158961/71514608-bb916300-289f-11ea-8432-5d8a159b7062.png)

What i'm doing Wrong? 
Is there a problen in Software?

I use:

Adapter:3.1.15
Node.js: v8.15.0 
NPM: 6.4.1
Typ: js-controller: 2.1.1

**Comment by spitfire4all** [comment]
Hi,
same Problem here.
Try to add new device from tuya to iobroker.



> tuya.0 | 2019-12-27 20:02:41.324 | error | at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
> -- | -- | -- | --
> tuya.0 | 2019-12-27 20:02:41.324 | error | (24145) Error: connect ECONNREFUSED 192.168.168.148:8888
> tuya.0 | 2019-12-27 20:02:41.323 | error | (24145) SSL-Proxy ERROR: Error: connect ECONNREFUSED 192.168.168.148:8888
> tuya.0 | 2019-12-27 20:02:39.855 | error | (24145) Error: 3070118352:error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1536:SSL alert number 46
> tuya.0 | 2019-12-27 20:02:39.854 | error | (24145) SSL-Proxy ERROR: Error: 3070118352:error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1536:SSL alert number 46
> tuya.0 | 2019-12-27 20:02:35.776 | error | (24145) Error: 3070118352:error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1536:SSL alert number 46
> tuya.0 | 2019-12-27 20:02:35.776 | error | (24145) SSL-Proxy ERROR: Error: 3070118352:error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1536:SSL alert number 46
> tuya.0 | 2019-12-27 20:02:32.833 | error | (24145) Error: 3070118352:error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1536:SSL alert number 46
> tuya.0 | 2019-12-27 20:02:32.833 | error | (24145) SSL-Proxy ERROR: Error: 3070118352:error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1536:SSL alert number 46
> tuya.0 | 2019-12-27 20:02:32.832 | error | (24145) Error: 3070118352:error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1536:SSL alert number 46
> tuya.0 | 2019-12-27 20:02:32.831 | error | (24145) SSL-Proxy ERROR: Error: 3070118352:error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1536:SSL alert number 46
> tuya.0 | 2019-12-27 20:02:29.844 | error | (24145) Error: 3070118352:error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1536:SSL alert number 46
> tuya.0 | 2019-12-27 20:02:29.843 | error | (24145) SSL-Proxy ERROR: Error: 3070118352:error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1536:SSL alert number 46
> tuya.0 | 2019-12-27 20:02:29.606 | error | (24145) Error: 3070118352:error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1536:SSL alert number 46
> tuya.0 | 2019-12-27 20:02:29.605 | error | (24145) SSL-Proxy ERROR: Error: 3070118352:error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1536:SSL aler
> 



I use:

Adapter:3.1.15
Node.js v10.16.3
NPM 6.9.0

**Comment by Apollon77** [comment]
Yes. The smartlife app was changed and so communication works different :-(

The tuya app still works (3.13.x) and older android versions like 3.12.6 also works. It is broken starting 3.14.

Please also see https://forum.iobroker.net/post/345945 or https://github.com/codetheweb/tuyapi/issues/280
