### ISSUE TITLE
 Fehler incorrect local timer, please correct it 50502

### ISSUE THREAD

**Issue by wowik2018** [Apollon77/ioBroker.tuya#9]
Hallo bei mir zeigt es Fehler incorrect local timer, please correct it 50502

**Comment by Apollon77** [comment]
Kannst Du normale HTTP-Webseiten aufrufen wenn Du mit dem Proxy verbunden bist? Wenn nein dann stimmt da was nicht.

**Comment by Apollon77** [comment]
ich mache hier zu, bitte diskussion hier mit führen: https://forum.iobroker.net/viewtopic.php?f=36&t=18029&p=195263#p195263

**Comment by lunadelfin17** [comment]
aber da ist keine Lösung zu finden

**Comment by Apollon77** [comment]
Ein Kommentar auf ein seit einem Jahr geschlossenen issue? I 

Der Fehler kommt mit dem aktuellsten Adapter nur wenn Proxy oder Zertifikat nicht korrekt ein ggf richtet wurden.  Für neue Probleme bitte im iobroker Forum schauen. Oder neue issues anlegen.

**Comment by lunadelfin17** [comment]
Ein frohes neues Jahr 2020 und weiterhin viel Erfolg und vor allem Gesundheit wünsche ich.

 

Entschuldigung!

 

Als Anfänger war ich so froh, dass ich immerhin schon den PI 4 und ioBroker eingerichtet habe.

 

Und nun – mit den aktuellsten Versionen – öffne ich die Visualisierung (der Tuya hat grünes Licht) und will mal eben testen … und da bekomme ich die Fehlermeldung  

„Keine gültige Lizenz gefunden“

 

und das, obwohl ich mir sicher bin, dass ich mit Einrichtung des iobroker auf „Einverstanden“ geklickt habe und meine, damit eine Lizenz bekommen zu haben.

 

…. Und weiterhin reagierte die probeweise eingerichtete Wohnzimmerlampe nicht L …. Die Farbe der Lampe auf der Visualisierung wechselte zwar auf gelb – aber nichts tat sich.

 

… als ich dann als Schalter den Alexa.2 ausgewählt habe, funktionierte Licht an / aus immerhin, zwar mit Verzögerung.

 

…. Aber die Meldung „keine Lizenz….“ Führte schließlich dazu, dass ich nichts editieren oder probieren kann.

 

Ich habe leider weiterhin keine Lösung gefunden J

 

Sorry, wenn ich damit belästigt habe L

 

Gruß

 

Bernd

 

Von: Ingo Fischer [mailto:notifications@github.com] 
Gesendet: Mittwoch, 1. Januar 2020 02:05
An: Apollon77/ioBroker.tuya
Cc: lunadelfin17; Comment
Betreff: Re: [Apollon77/ioBroker.tuya] Fehler incorrect local timer, please correct it 50502 (#9)

 

Ein Kommentar auf ein seit einem Jahr geschlossenen issue? I

Der Fehler kommt mit dem aktuellsten Adapter nur wenn Proxy oder Zertifikat nicht korrekt ein ggf richtet wurden. Für neue Probleme bitte im iobroker Forum schauen. Oder neue issues anlegen.

**Comment by Apollon77** [comment]
Bei der Lizenz geht es um die freie Vis Lizenz. Die musst du selbst holen. Free cloud anmeldrn. Dort gibts die. Dann im Vis Adapter eintragen. Steht alles bei Vis Konfigurationsseite. 

Support am besten im forum
