### ISSUE TITLE
Objekt in Tuya verbindet sich nicht 

### ISSUE THREAD

**Issue by DennisH1978** [Apollon77/ioBroker.tuya#94]
Moin, ich habe nun endlich meinen Eachen IR Remote per Tuya in den Iobroker bekommen. Er zeigt mir auch ein paar Datenpunkte an. Aber nun weiß ich nicht weiter. Ich habe ihm schon ein paar Befehle per App beigebracht, aber wo sind diese nun? Und er sagt auch nicht, dass das Device online ist. Habe ich was übersehen?
![FB_IMG_1578091593076](https://user-images.githubusercontent.com/42620955/71753630-6ea32300-2e83-11ea-97dd-94a619a9ad19.jpg)

**Comment by Apollon77** [comment]
Da ich dieses Gerät selbst nicht habe und auch nicht kenne werde ich dir da nur wenig helfen können. Da musst du sehr viel durch selbst experimentieren und versuchen herauszufinden.

Zuerst einmal hast du vollkommen recht: das Gerät scheint nicht verbunden zu sein. Das musst du zuerst einmal herausfinden warum das so ist. Was steht denn im Log File? Am besten den Adapter neu starten und dann einmal reinschauen was er genau zu diesem Gerät sagt. Kann es sein das die UDP Pakete nicht ankommen beim Rechner wo ioBroker drauf läuft? Dann kann er das nämlich auch nicht finden und kennt die IP nicht.

Wenn es dann einmal verbunden ist dann hilft es meistens einmal über die App etwas zu machen und zu schauen was die Daten. In ioBroker so sagen. Effektiv ist das Schema statisch. Dies bedeutet: irgendwelche angelegten Geräte werden dort denke ich nicht wirklich auftauchen… D.h. du wirst dort mit zahlen IDs oder den IR Zeichenketten arbeiten müssen ist meine Vermutung

**Comment by Apollon77** [comment]
Closed because inactivity

**Comment by nobtuk** [comment]
Hallo DennisH1978,
ich habe gerade deinen Post gelesen. Ich habe auch eine Tuya S-6 IR Fernbedienung. Im Adapter sieht es bei mir so aus wie bei dir auf dem Bild. Bist Du da schon weiter gekommen? Ich stehe nämlich noch vor dem Berg und weiß noch nicht wie ich da drüber kommen soll. Für Tips bzw. Lösungsvorschläge wäre ich dir sehr dankbar. 
LG Norbert
