### ISSUE TITLE
1.Findet meine gärte nicht......2.Bekomme immer Fehler meldung 50502

### ISSUE THREAD

**Issue by cecengazi** [Apollon77/ioBroker.tuya#95]
Hallo, wünsche erst mal jeden hier ein Frohes neues Jahr.

Ich habe  genau die Beschreibung von Elzershark befolgt bei der Installation, 

Ich packe mal einfach ein paar Bilder rein......
![device](https://user-images.githubusercontent.com/52876366/71761276-62da4f80-2ec9-11ea-913d-ae9f33ef23bd.png)
![log](https://user-images.githubusercontent.com/52876366/71761283-67066d00-2ec9-11ea-8a0a-2fa64118550d.png)
![instanzen](https://user-images.githubusercontent.com/52876366/71761285-68d03080-2ec9-11ea-8830-e022e0d7c733.png)
![Screenshot_20200103-180407_Smart Life](https://user-images.githubusercontent.com/52876366/71761335-ee53e080-2ec9-11ea-8589-dad93fd2582b.jpg)

**Comment by Apollon77** [comment]
1.) local timer Fehler deutet darauf hin das der Proxy oder das Zertifikat Nicht korrekt aktiviert ist
2.) generell gibt es aktuell mit smartlife und tuya App 3.14 das Problem das wegen Änderung in der App der Sync nicht mehr tut. Einzige Alternative ist ältere App Version unter android. 

Im Forum gibt es viel Support. Bitte suchen.
