### ISSUE TITLE
Proxy hab ich geschafft.....aber

### ISSUE THREAD

**Issue by cecengazi** [Apollon77/ioBroker.tuya#96]
Hallo,

Es tut mir echt leid das ich hier nochmal schreibe aber ich habe hier nix gefunden der das gleiche Problem hat wie ich......

Ich habe es endlich geschafft mit dem Proxy zu verbinden, vom Handy,aber da klappt es bei mir noch nicht ganz ich habe die gleichen Jalousie schalter wie in diesem Video  https://www.youtube.com/watch?v=DFrnoPjsQPk&t=306s

Habe auch schon Smat Life app V3.3.0 und V3.7.0 probiert (alles immer jeweils abgemeldet auch am echo und wieder angemeldet) mit alexa Funktioniert alles....

Aber bei mir findet es die beiden Schalter nicht und die zwei steckdosen sind auch ohne schema....
Ich binde hier noch zwei Bilder ein.
![Screenshot_20200105-003332_Smart Life](https://user-images.githubusercontent.com/52876366/71772868-54d11100-2f53-11ea-8aff-88bb0e8879b9.jpg)

![Unbenannt](https://user-images.githubusercontent.com/52876366/71772845-deccaa00-2f52-11ea-9721-082496dcfe54.png)

**Comment by cecengazi** [comment]
tuya.0 | 2020-01-05 00:27:44.068 | info | (28034) 20261768600194c4223d: No schema exists, init basic states ...
-- | -- | -- | --
tuya.0 | 2020-01-05 00:27:44.043 | info | (28034) 20261768600194c4223d: No local encryption key available, get data using polling, controlling of device NOT possibe. Please sync with App!
tuya.0 | 2020-01-05 00:27:44.040 | info | (28034) 20261768600194c4223d Init with IP=192.168.1.100, Key=undefined, Version=3.1
tuya.0 | 2020-01-05 00:27:41.589 | info | (28034) 20261768c44f3384a332: No schema exists, init basic states ...
tuya.0 | 2020-01-05 00:27:41.561 | info | (28034) 20261768c44f3384a332: No local encryption key available, get data using polling, controlling of device NOT possibe. Please sync with App!
tuya.0 | 2020-01-05 00:27:41.558 | info | (28034) 20261768c44f3384a332 Init with IP=192.168.1.104, Key=undefined, Version=3.1
tuya.0 | 2020-01-05 00:27:41.306 | info | (28034) Listen for encrypted local Tuya devices on port 6667
tuya.0 | 2020-01-05 00:27:41.305 | info | (28034) Listen for local Tuya devices on port 6666
tuya.0 | 2020-01-05 00:27:41.298 | info | (28034) Existing devices initialized
tuya.0 | 2020-01-05 00:27:41.162 | info | (28034) starting. Version 3.1.15 in /opt/iobroker/node_modules/iobroker.tuya, node: v10.18.0

**Comment by Apollon77** [comment]
Wenn steht 0 mit Schema steht dann hat der Proxy Sync nicht geklappt. Bitte wiederholen. Nach Proxy Start kommt ein populärer mit dem qrcode. Das muss von alleine auch schließen mit einem grünen Haken! Erst dann hat’s geklappt.
