### ISSUE TITLE
Proxy startet nicht???!!!

### ISSUE THREAD

**Issue by Atze12** [Apollon77/ioBroker.tuya#97]
Hallo,
ich habe die video Anleitung genau beachtet,bekomme aber irgendwie keine Verbindung von iobroker zur app.

Wenn ich meine io Broker ip (läuft bei mir auf dem pi ,gleiche ip) und :8889 ,steh da : cannot get/

ist das ein Fehler??? ich verstehe es nicht,.

Grüsse

**Comment by Apollon77** [comment]
Bitte ein qrcode scannen. Da ist d so je url drin.

**Comment by Atze12** [comment]
hallo,ja habe ich gemacht.geht alles nicht.bekomme keine Verbindung mit dem iPhone (app) zu ioBroker

**Comment by Apollon77** [comment]
Bitte beschreibend dein Problem ausführlicher im Forum. Support zur Bedienung machen wir am besten dort.
